Repository nf-core/modules, pull requests merged in 2021-11, with the labels that each got.

#991 Samtools fixmate module
  modules/samtools/fixmate/functions.nf
  modules/samtools/fixmate/main.nf
  modules/samtools/fixmate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/samtools/fixmate/main.nf
  tests/modules/samtools/fixmate/test.yml
Labels: new module, Ready for Review

#1003 gccounter module for hmmcopy
  modules/hmmcopy/gccounter/functions.nf
  modules/hmmcopy/gccounter/main.nf
  modules/hmmcopy/gccounter/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/hmmcopy/gccounter/main.nf
  tests/modules/hmmcopy/gccounter/test.yml
Labels: new module, Ready for Review

#1001 readcounter module for hmmcopy
  modules/hmmcopy/readcounter/functions.nf
  modules/hmmcopy/readcounter/main.nf
  modules/hmmcopy/readcounter/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/hmmcopy/readcounter/main.nf
  tests/modules/hmmcopy/readcounter/test.yml
Labels: new module, Ready for Review

#880 New module: `gunc run` (+ `gunc downloaddb`)
  modules/gunc/downloaddb/functions.nf
  modules/gunc/downloaddb/main.nf
  modules/gunc/downloaddb/meta.yml
  modules/gunc/run/functions.nf
  modules/gunc/run/main.nf
  modules/gunc/run/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gunc/downloaddb/main.nf
  tests/modules/gunc/downloaddb/test.yml
  tests/modules/gunc/run/main.nf
  tests/modules/gunc/run/test.yml
Labels: new module, Ready for Review

#1016 add seqsero2 module
  modules/seqsero2/functions.nf
  modules/seqsero2/main.nf
  modules/seqsero2/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/seqsero2/main.nf
  tests/modules/seqsero2/test.yml
Labels: new module, Ready for Review

#954 New module: Samblaster
  modules/samblaster/functions.nf
  modules/samblaster/main.nf
  modules/samblaster/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/samblaster/main.nf
  tests/modules/samblaster/test.yml
Labels: new module, Ready for Review

#882 Imputeme
  modules/gunzip/test.txt.gz
  modules/imputeme/vcftoprs/functions.nf
  modules/imputeme/vcftoprs/main.nf
  modules/imputeme/vcftoprs/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/imputeme/vcftoprs/main.nf
  tests/modules/imputeme/vcftoprs/test.yml
Labels: help wanted, new module

#1034 add scoary module
  modules/scoary/functions.nf
  modules/scoary/main.nf
  modules/scoary/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/scoary/main.nf
  tests/modules/scoary/test.yml
Labels: new module, Ready for Review

#1022 add meningotype module
  modules/meningotype/functions.nf
  modules/meningotype/main.nf
  modules/meningotype/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/meningotype/main.nf
  tests/modules/meningotype/test.yml
Labels: new module, Ready for Review

#1035 bug fixes: genomicsdbimport
  modules/gatk4/genomicsdbimport/main.nf
  modules/gatk4/genomicsdbimport/meta.yml
  tests/modules/gatk4/genomicsdbimport/main.nf
  tests/modules/gatk4/genomicsdbimport/test.yml
Labels: bug, Ready for Review

#1028 add emmtyper module
  modules/emmtyper/functions.nf
  modules/emmtyper/main.nf
  modules/emmtyper/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/emmtyper/main.nf
  tests/modules/emmtyper/test.yml
Labels: new module, Ready for Review

#1026 add lissero module
  modules/lissero/functions.nf
  modules/lissero/main.nf
  modules/lissero/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/lissero/main.nf
  tests/modules/lissero/test.yml
Labels: new module, Ready for Review

#1045 bugfix: panel of normals subworkflow: remove md5sum on a gzipped file
  tests/subworkflows/nf-core/gatk_create_som_pon/test.yml
Labels: bug

#975 Add new module Mapdamage2
  modules/mapdamage2/functions.nf
  modules/mapdamage2/main.nf
  modules/mapdamage2/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/mapdamage2/main.nf
  tests/modules/mapdamage2/test.yml
Labels: new module, Ready for Review

#901 Implement `plink/extract` module
  modules/plink/extract/functions.nf
  modules/plink/extract/main.nf
  modules/plink/extract/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/plink/extract/main.nf
  tests/modules/plink/extract/test.yml
Labels: Ready for Review

#918 Add new module: cmseq/polymut
  modules/cmseq/polymut/functions.nf
  modules/cmseq/polymut/main.nf
  modules/cmseq/polymut/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/cmseq/polymut/main.nf
  tests/modules/cmseq/polymut/test.yml
Labels: new module, Ready for Review

#927 Picard/collecthsmetrics
  modules/picard/collecthsmetrics/functions.nf
  modules/picard/collecthsmetrics/main.nf
  modules/picard/collecthsmetrics/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/picard/collecthsmetrics/main.nf
  tests/modules/picard/collecthsmetrics/test.yml
Labels: Ready for Review

#1024 add ngmaster module
  modules/ngmaster/functions.nf
  modules/ngmaster/main.nf
  modules/ngmaster/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ngmaster/main.nf
  tests/modules/ngmaster/test.yml
Labels: new module, Ready for Review

#1018 Update module: `pbccs`
  modules/pbccs/main.nf
  modules/pbccs/meta.yml
  tests/__pycache__/test_versions_yml.cpython-39-pytest-6.2.5.pyc
  tests/modules/pbccs/test.yml
Labels: update module, Ready for Review

#963 add new module pmdtools/filter #847
  modules/pmdtools/filter/functions.nf
  modules/pmdtools/filter/main.nf
  modules/pmdtools/filter/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/pmdtools/filter/main.nf
  tests/modules/pmdtools/filter/test.yml
Labels: Ready for Review

#1040 Bwa index
  modules/bwa/index/main.nf
  tests/modules/bwa/index/test.yml
Labels: update module, Ready for Review

#1041 Unicycler with long read input
  modules/unicycler/main.nf
  modules/unicycler/meta.yml
  tests/modules/unicycler/main.nf
  tests/modules/unicycler/test.yml
Labels: update module, Ready for Review

#1039 Change Spades input
  modules/spades/main.nf
  modules/spades/meta.yml
  tests/modules/spades/main.nf
  tests/modules/spades/test.yml
Labels: update module, Ready for Review

#998 Add new module 'ataqv/ataqv'
  modules/ataqv/ataqv/functions.nf
  modules/ataqv/ataqv/main.nf
  modules/ataqv/ataqv/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ataqv/ataqv/main.nf
  tests/modules/ataqv/ataqv/test.yml
Labels: new module, Ready for Review, RIP

#1006 New module: `plink2/vcf`
  modules/plink2/vcf/functions.nf
  modules/plink2/vcf/main.nf
  modules/plink2/vcf/meta.yml
  tests/modules/plink2/vcf/main.nf
  tests/modules/plink2/vcf/test.yml
Labels: new module, Ready for Review, RIP

#1052 Add `leehom` module
  modules/leehom/functions.nf
  modules/leehom/main.nf
  modules/leehom/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/leehom/main.nf
  tests/modules/leehom/test.yml
Labels: new module, Ready for Review, RIP

#947 add module for tbprofiler
  modules/tbprofiler/profile/functions.nf
  modules/tbprofiler/profile/main.nf
  modules/tbprofiler/profile/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/tbprofiler/profile/main.nf
  tests/modules/tbprofiler/profile/test.yml
Labels: new module, Ready for Review, RIP

#935 add module for fastq-scan
  modules/fastqscan/functions.nf
  modules/fastqscan/main.nf
  modules/fastqscan/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/fastqscan/main.nf
  tests/modules/fastqscan/test.yml
Labels: new module, Ready for Review

#938 Update spatyper module (cleanup debug)
  modules/spatyper/main.nf
Labels: update module, Ready for Review

#970 Update agrvate version
  modules/agrvate/main.nf
Labels: update module, Ready for Review, RIP

#515 Cooler merge
  modules/cooler/merge/functions.nf
  modules/cooler/merge/main.nf
  modules/cooler/merge/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/cooler/merge/main.nf
  tests/modules/cooler/merge/test.yml
Labels: new module, Ready for Review, RIP

#884 New modules added: issues #200 and #310
  modules/gatk4/genotypegvcfs/functions.nf
  modules/gatk4/genotypegvcfs/main.nf
  modules/gatk4/genotypegvcfs/meta.yml
  modules/gatk4/indexfeaturefile/functions.nf
  modules/gatk4/indexfeaturefile/main.nf
  modules/gatk4/indexfeaturefile/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/gatk4/genotypegvcfs/main.nf
  tests/modules/gatk4/genotypegvcfs/test.yml
  tests/modules/gatk4/indexfeaturefile/main.nf
  tests/modules/gatk4/indexfeaturefile/test.yml
Labels: new module, Ready for Review, RIP

#940 New module mummer
  modules/mummer/functions.nf
  modules/mummer/main.nf
  modules/mummer/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/mummer/main.nf
  tests/modules/mummer/test.yml
Labels: new module, Ready for Review, RIP

#871 New module: `Ultra`
  modules/ultra/pipeline/functions.nf
  modules/ultra/pipeline/main.nf
  modules/ultra/pipeline/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ultra/pipeline/main.nf
  tests/modules/ultra/pipeline/test.yml
Labels: new module, Ready for Review

#1068 new module fargene
  modules/fargene/functions.nf
  modules/fargene/main.nf
  modules/fargene/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/fargene/main.nf
  tests/modules/fargene/test.yml
Labels: new module, Ready for Review, RIP

#1060 Add `bamutil/trimbam`
  modules/bamutil/trimbam/functions.nf
  modules/bamutil/trimbam/main.nf
  modules/bamutil/trimbam/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/bamutil/trimbam/main.nf
  tests/modules/bamutil/trimbam/test.yml
Labels: new module, Ready for Review, RIP

#1074 Rename all _idx to _tbi
  modules/gatk4/getpileupsummaries/main.nf
  modules/gatk4/getpileupsummaries/meta.yml
  modules/gatk4/mutect2/main.nf
  modules/gatk4/mutect2/meta.yml
  tests/modules/gatk4/getpileupsummaries/main.nf
  tests/modules/gatk4/mutect2/main.nf
Labels: Ready for Review, RIP

#1073 Rename all fastaidx to fai
  modules/gatk4/applybqsr/main.nf
  modules/gatk4/applybqsr/meta.yml
  modules/gatk4/baserecalibrator/main.nf
  modules/gatk4/baserecalibrator/meta.yml
  modules/gatk4/createsomaticpanelofnormals/main.nf
  modules/gatk4/createsomaticpanelofnormals/meta.yml
  modules/gatk4/filtermutectcalls/main.nf
  modules/gatk4/filtermutectcalls/meta.yml
  modules/gatk4/mutect2/main.nf
  modules/gatk4/mutect2/meta.yml
  subworkflows/nf-core/gatk_create_som_pon/main.nf
  subworkflows/nf-core/gatk_create_som_pon/meta.yml
  tests/modules/gatk4/filtermutectcalls/main.nf
  tests/modules/gatk4/mutect2/main.nf
  tests/subworkflows/nf-core/gatk_create_som_pon/main.nf
Labels: Ready for Review, RIP

#1038 Macs2 calllpeak
  modules/macs2/callpeak/main.nf
  modules/macs2/callpeak/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/macs2/callpeak/main.nf
  tests/modules/macs2/callpeak/test.yml
Labels: enhancement, help wanted, Ready for Review, RIP

#992 Add Medaka module
  modules/medaka/functions.nf
  modules/medaka/main.nf
  modules/medaka/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/medaka/main.nf
  tests/modules/medaka/test.yml
Labels: new module, Ready for Review, RIP

#928 add Kronatools KTImportTaxonomy
  modules/kronatools/ktimporttaxonomy/functions.nf
  modules/kronatools/ktimporttaxonomy/main.nf
  modules/kronatools/ktimporttaxonomy/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/kronatools/ktimporttaxonomy/main.nf
  tests/modules/kronatools/ktimporttaxonomy/test.yml
Labels: new module, Ready for Review, RIP

#962 Add Miniasm module
  modules/miniasm/functions.nf
  modules/miniasm/main.nf
  modules/miniasm/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/miniasm/main.nf
  tests/modules/miniasm/test.yml
Labels: new module, Ready for Review, RIP

#933 Fix subworkflows seperate from modules
  .github/workflows/nf-core-linting.yml
  .github/workflows/pytest-workflow.yml
  subworkflows/nf-core/bam_sort_samtools/nextflow.config
  tests/config/pytest_modules.yml
  tests/config/pytest_subworkflows.yml
  tests/modules/sratools/fasterqdump/test.yml
  tests/subworkflows/nf-core/align_bowtie2/test.yml
  tests/subworkflows/nf-core/bam_sort_samtools/test.yml
  tests/subworkflows/nf-core/gatk_create_som_pon/test.yml
Labels: WIP, update subworkflow

#1014 Added new module csvtk/split
  modules/csvtk/split/functions.nf
  modules/csvtk/split/main.nf
  modules/csvtk/split/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/csvtk/split/main.nf
  tests/modules/csvtk/split/test.yml
Labels: new module, Ready for Review, RIP

#980 add ncbi-genome-download module
  modules/ncbigenomedownload/functions.nf
  modules/ncbigenomedownload/main.nf
  modules/ncbigenomedownload/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ncbigenomedownload/main.nf
  tests/modules/ncbigenomedownload/test.yml
Labels: new module, Ready for Review, RIP

#1063 Add module get_chrom_sizes
  modules/custom/getchromsizes/functions.nf
  modules/custom/getchromsizes/main.nf
  modules/custom/getchromsizes/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/custom/getchromsizes/main.nf
  tests/modules/custom/getchromsizes/test.yml
Labels: new module, Ready for Review, RIP

#974 add clonalframeml module
  modules/clonalframeml/functions.nf
  modules/clonalframeml/main.nf
  modules/clonalframeml/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/clonalframeml/main.nf
  tests/modules/clonalframeml/test.yml
Labels: new module, Ready for Review, RIP

#634 Cooler cload
  modules/cooler/cload/functions.nf
  modules/cooler/cload/main.nf
  modules/cooler/cload/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/cooler/cload/main.nf
  tests/modules/cooler/cload/test.yml
Labels: new module, Ready for Review, RIP

#945 add new nucmer module
  modules/nucmer/functions.nf
  modules/nucmer/main.nf
  modules/nucmer/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nucmer/main.nf
  tests/modules/nucmer/test.yml
Labels: new module, Ready for Review, RIP

#937 [fix] hicap module allow optional outputs
  modules/hicap/main.nf
  tests/modules/hicap/main.nf
Labels: update module, Ready for Review, RIP

#1064 Add gatk somatic tumour calling subworkflow
  subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/main.nf
  subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/meta.yml
  subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/nextflow.config
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/main.nf
  tests/subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/test.yml
Labels: Ready for Review, RIP, new subworkflow

#1067 Add gatk somatic paired calling subworkflow
  subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/main.nf
  subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/meta.yml
  subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/nextflow.config
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/main.nf
  tests/subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/test.yml
Labels: Ready for Review, RIP, new subworkflow

#1083 Update in GATK4 variantfiltration: Added vcf_index to vcf tuple; output to vcf.gz format.
  modules/gatk4/variantfiltration/main.nf
  modules/gatk4/variantfiltration/meta.yml
  tests/modules/gatk4/variantfiltration/main.nf
  tests/modules/gatk4/variantfiltration/test.yml
Labels: Ready for Review, RIP

#1084 Fix picard markduplicates
  modules/picard/markduplicates/main.nf
  tests/modules/picard/markduplicates/main.nf
  tests/modules/picard/markduplicates/test.yml
Labels: bug, Ready for Review

#1069 Add thread option to samtools modules
  modules/samtools/ampliconclip/main.nf
  modules/samtools/faidx/main.nf
  modules/samtools/fastq/main.nf
  modules/samtools/fixmate/main.nf
  modules/samtools/flagstat/main.nf
  modules/samtools/idxstats/main.nf
  modules/samtools/index/main.nf
  modules/samtools/merge/main.nf
  modules/samtools/mpileup/main.nf
  modules/samtools/sort/main.nf
  modules/samtools/stats/main.nf
  modules/samtools/view/main.nf
  tests/modules/samtools/ampliconclip/test.yml
  tests/modules/samtools/fixmate/test.yml
  tests/modules/samtools/index/test.yml
  tests/modules/samtools/merge/test.yml
  tests/modules/samtools/sort/test.yml
  tests/modules/samtools/stats/main.nf
  tests/modules/samtools/stats/test.yml
  tests/subworkflows/nf-core/align_bowtie2/test.yml
  tests/subworkflows/nf-core/bam_sort_samtools/test.yml
Labels: Ready for Review, RIP

#1004 Add new module: Das Tool
  modules/dastool/dastool/functions.nf
  modules/dastool/dastool/main.nf
  modules/dastool/dastool/meta.yml
  modules/dastool/scaffolds2bin/functions.nf
  modules/dastool/scaffolds2bin/main.nf
  modules/dastool/scaffolds2bin/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/dastool/dastool/main.nf
  tests/modules/dastool/dastool/test.yml
  tests/modules/dastool/scaffolds2bin/main.nf
  tests/modules/dastool/scaffolds2bin/test.yml
Labels: new module, WIP

#948 add ectyper module
  modules/ectyper/functions.nf
  modules/ectyper/main.nf
  modules/ectyper/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ectyper/main.nf
  tests/modules/ectyper/test.yml
Labels: new module, Ready for Review, RIP

#1085 add bakta module
  modules/bakta/functions.nf
  modules/bakta/main.nf
  modules/bakta/meta.yml
  tests/__pycache__/test_versions_yml.cpython-39-pytest-6.2.5.pyc
  tests/config/pytest_modules.yml
  tests/modules/bakta/main.nf
  tests/modules/bakta/test.yml
Labels: new module, Ready for Review

#1081 Update: `uLTRA`
  modules/ultra/pipeline/main.nf
  modules/ultra/pipeline/meta.yml
  tests/modules/ultra/pipeline/main.nf
  tests/modules/ultra/pipeline/test.yml
Labels: Ready for Review

#786 Add phyloflash module
  modules/phyloflash/functions.nf
  modules/phyloflash/main.nf
  modules/phyloflash/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/phyloflash/main.nf
  tests/modules/phyloflash/test.yml
Labels: new module, Ready for Review, RIP

#1030 CNVkit: Make targets file optional when running in WGS mode
  modules/cnvkit/batch/functions.nf
  modules/cnvkit/batch/main.nf
  modules/cnvkit/batch/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/cnvkit/batch/main.nf
  tests/modules/cnvkit/batch/test.yml
  tests/modules/cnvkit/main.nf
  tests/modules/cnvkit/test.yml
Labels: update module, Ready for Review, RIP

#1048 Peddy nf core2 2dev0
  modules/peddy/functions.nf
  modules/peddy/main.nf
  modules/peddy/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/peddy/main.nf
  tests/modules/peddy/test.yml
Labels: new module, Ready for Review, RIP

#1090 takes gunzip out of fargene main.nf
  modules/fargene/main.nf
  modules/fargene/meta.yml
  tests/modules/fargene/main.nf
  tests/modules/fargene/test.yml
Labels: update module, Ready for Review
