Repository nf-core/modules, pull requests merged in 2021-01, with the labels that each got.

#115 Added testing for Stringtie
  .github/workflows/stringtie.yml
  tests/data/gff/a.gtf
  tests/software/stringtie/main.nf
  tests/software/stringtie/test.yml
Labels: tests

#123 Added cutadapt module
  .github/workflows/cutadapt.yml
  software/cutadapt/functions.nf
  software/cutadapt/main.nf
  software/cutadapt/meta.yml
  tests/software/cutadapt/main.nf
  tests/software/cutadapt/test.yml
Labels: WIP, new module

#124 Added pangolin module
  .github/workflows/pangolin.yml
  software/pangolin/functions.nf
  software/pangolin/main.nf
  software/pangolin/meta.yml
  tests/software/pangolin/main.nf
  tests/software/pangolin/test.yml
Labels: new module
