Repository nf-core/modules, pull requests merged in 2021-03, with the labels that each got.

#267 Adding minia for viralrecon
  software/minia/functions.nf
  software/minia/main.nf
  software/minia/meta.yml
  tests/config/pytest_software.yml
  tests/software/minia/main.nf
  tests/software/minia/test.yml
Labels: Ready for Review, new module

#266 Add kraken2 run module
  software/functions.nf
  software/kraken2/run/functions.nf
  software/kraken2/run/main.nf
  software/kraken2/run/meta.yml
  tests/config/pytest_software.yml
  tests/data/genomics/sarscov2/db/kraken2/hash.k2d
  tests/data/genomics/sarscov2/db/kraken2/opts.k2d
  tests/data/genomics/sarscov2/db/kraken2/taxo.k2d
  tests/software/kraken2/run/main.nf
  tests/software/kraken2/run/test.yml
Labels: new module

#277 Add spades module
  software/spades/functions.nf
  software/spades/main.nf
  software/spades/meta.yml
  tests/config/pytest_software.yml
  tests/software/spades/main.nf
  tests/software/spades/test.yml
Labels: new module

#307 Adding unicycler module
  software/unicycler/functions.nf
  software/unicycler/main.nf
  software/unicycler/meta.yml
  tests/config/pytest_software.yml
  tests/software/unicycler/main.nf
  tests/software/unicycler/test.yml
Labels: Ready for Review, new module

#309 new module: AdapterRemoval
  software/adapterremoval/functions.nf
  software/adapterremoval/main.nf
  software/adapterremoval/meta.yml
  tests/config/pytest_software.yml
  tests/software/adapterremoval/main.nf
  tests/software/adapterremoval/test.yml
Labels: Ready for Review, new module

#311 add gatk4/fastqtosam #198
  software/gatk4/fastqtosam/functions.nf
  software/gatk4/fastqtosam/main.nf
  software/gatk4/fastqtosam/meta.yml
  tests/config/pytest_software.yml
  tests/software/gatk4/fastqtosam/main.nf
  tests/software/gatk4/fastqtosam/test.yml
Labels: Ready for Review, new module

#316 new module: samtools/fastq
  software/samtools/fastq/functions.nf
  software/samtools/fastq/main.nf
  software/samtools/fastq/meta.yml
  tests/config/pytest_software.yml
  tests/software/samtools/fastq/main.nf
  tests/software/samtools/fastq/test.yml
Labels: good first issue, new module

#313 Add alleleCounter module
  software/allelecounter/functions.nf
  software/allelecounter/main.nf
  software/allelecounter/meta.yml
  tests/config/pytest_software.yml
  tests/software/allelecounter/main.nf
  tests/software/allelecounter/test.yml
Labels: new module

#339 modified the samtools/fastq module
  software/samtools/fastq/main.nf
  software/samtools/fastq/meta.yml
  tests/software/samtools/fastq/test.yml
Labels: Ready for Review

#336 Add default output dir for modules that create indices, updated
  README.md
  software/bowtie/build/main.nf
  software/bowtie2/build/main.nf
  software/bwa/index/main.nf
  software/bwamem2/index/main.nf
  software/bwameth/index/main.nf
  software/hisat2/build/main.nf
  software/rsem/preparereference/main.nf
  software/salmon/index/main.nf
  software/star/genomegenerate/main.nf
  tests/software/bowtie/align/test.yml
  tests/software/bowtie/build_test/test.yml
  tests/software/bowtie2/align/test.yml
  tests/software/bowtie2/build_test/test.yml
  tests/software/bwa/index/test.yml
  tests/software/bwamem2/index/test.yml
  tests/software/bwameth/index/test.yml
  tests/software/salmon/index/test.yml
  tests/software/star/genomegenerate/test.yml
Labels: Ready for Review

#337 Update shovill module
  deprecated/shovill/main.nf
  deprecated/shovill/meta.yml
  deprecated/shovill/test/main.nf
  deprecated/shovill/test/nextflow.config
  software/shovill/functions.nf
  software/shovill/main.nf
  software/shovill/meta.yml
  tests/config/pytest_software.yml
  tests/software/shovill/main.nf
  tests/software/shovill/test.yml
Labels: Ready for Review

#353 Add YARA module
  software/yara/index/functions.nf
  software/yara/index/main.nf
  software/yara/index/meta.yml
  software/yara/mapper/functions.nf
  software/yara/mapper/main.nf
  software/yara/mapper/meta.yml
  tests/config/pytest_software.yml
  tests/software/yara/index/main.nf
  tests/software/yara/index/test.yml
  tests/software/yara/mapper/main.nf
  tests/software/yara/mapper/test.yml
Labels: Ready for Review, new module

#386 Fix some module tests after switching to config data
  tests/config/test_data.config
  tests/data/genomics/sarscov2/genome/db/kraken2.tar.gz
  tests/software/cat/fastq/main.nf
  tests/software/kraken2/run/main.nf
  tests/software/kraken2/run/test.yml
  tests/software/untar/main.nf
  tests/software/untar/test.yml
Labels: Ready for Review

#379 Fix some module test after adapting test config approach
  tests/software/bowtie2/align/main.nf
  tests/software/bowtie2/align/test.yml
  tests/software/bowtie2/build_test/main.nf
  tests/software/bowtie2/build_test/test.yml
  tests/software/bwameth/align/main.nf
  tests/software/bwameth/index/main.nf
  tests/software/bwameth/index/test.yml
  tests/software/multiqc/main.nf
Labels: Ready for Review

#382 modify test path - module gatk4 + added new module gatk4/haplotypecaller
  software/gatk4/haplotypecaller/functions.nf
  software/gatk4/haplotypecaller/main.nf
  software/gatk4/haplotypecaller/meta.yml
  tests/config/pytest_software.yml
  tests/software/gatk4/applybqsr/main.nf
  tests/software/gatk4/applybqsr/test.yml
  tests/software/gatk4/baserecalibrator/main.nf
  tests/software/gatk4/baserecalibrator/test.yml
  tests/software/gatk4/bedtointervallist/main.nf
  tests/software/gatk4/bedtointervallist/test.yml
  tests/software/gatk4/createsequencedictionary/main.nf
  tests/software/gatk4/createsequencedictionary/test.yml
  tests/software/gatk4/fastqtosam/main.nf
  tests/software/gatk4/fastqtosam/test.yml
  tests/software/gatk4/haplotypecaller/main.nf
  tests/software/gatk4/haplotypecaller/test.yml
  tests/software/gatk4/mergebamalignment/main.nf
  tests/software/gatk4/mergebamalignment/test.yml
  tests/software/gatk4/mergevcfs/main.nf
  tests/software/gatk4/mergevcfs/test.yml
  tests/software/gatk4/revertsam/main.nf
  tests/software/gatk4/revertsam/test.yml
  tests/software/gatk4/samtofastq/main.nf
  tests/software/gatk4/samtofastq/test.yml
  tests/software/gatk4/splitncigarreads/main.nf
  tests/software/gatk4/splitncigarreads/test.yml
Labels: Ready for Review

#352 New modules: Fgbio callmolecularconsensusreads and sortbam
  software/fgbio/callmolecularconsensusreads/functions.nf
  software/fgbio/callmolecularconsensusreads/main.nf
  software/fgbio/callmolecularconsensusreads/meta.yml
  software/fgbio/sortbam/functions.nf
  software/fgbio/sortbam/main.nf
  software/fgbio/sortbam/meta.yml
  tests/config/pytest_software.yml
  tests/software/fgbio/callmolecularconsensusreads/main.nf
  tests/software/fgbio/callmolecularconsensusreads/test.yml
  tests/software/fgbio/sortbam/main.nf
  tests/software/fgbio/sortbam/test.yml
Labels: new module
