Repository nf-core/modules, pull requests merged in 2021-12, with the labels that each got.

#1108 Dragmap
  modules/dragmap/align/main.nf
  modules/dragmap/align/meta.yml
  modules/dragmap/hashtable/main.nf
  modules/dragmap/hashtable/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/dragmap/align/main.nf
  tests/modules/dragmap/align/nextflow.config
  tests/modules/dragmap/align/test.yml
  tests/modules/dragmap/hashtable/main.nf
  tests/modules/dragmap/hashtable/nextflow.config
  tests/modules/dragmap/hashtable/test.yml
Labels: Ready for Review

#1098 Added UMI sub-workflow
  subworkflows/nf-core/fgbio_create_umi_consensus/main.nf
  subworkflows/nf-core/fgbio_create_umi_consensus/meta.yml
  tests/modules/fgbio/groupreadsbyumi/main.nf
  tests/subworkflows/nf-core/fgbio_create_umi_consensus/main.nf
  tests/subworkflows/nf-core/fgbio_create_umi_consensus/nextflow.config
  tests/subworkflows/nf-core/fgbio_create_umi_consensus/test.yml
Labels: Ready for Review

#1109 Add new module macrel/contigs
  modules/macrel/contigs/main.nf
  modules/macrel/contigs/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/macrel/contigs/main.nf
  tests/modules/macrel/contigs/nextflow.config
  tests/modules/macrel/contigs/test.yml
Labels: new module, Ready for Review

#1111 Update metabat2 output channels and compression
  modules/metabat2/metabat2/main.nf
  modules/metabat2/metabat2/meta.yml
  tests/modules/metabat2/metabat2/test.yml
Labels: Ready for Review

#1144 Update seqwish to version 0.7.2
  modules/seqwish/induce/main.nf
Labels: Ready for Review

#1153 BugFix: add missing tbi output channel to genotypeGVCFs
  modules/gatk4/genotypegvcfs/main.nf
  modules/gatk4/genotypegvcfs/meta.yml
  tests/config/test_data.config
  tests/modules/gatk4/genotypegvcfs/main.nf
  tests/modules/gatk4/genotypegvcfs/test.yml
Labels: bug, Ready for Review

#1168 New subtool: hmmcopy/generatemap
  modules/hmmcopy/gccounter/main.nf
  modules/hmmcopy/generatemap/main.nf
  modules/hmmcopy/generatemap/meta.yml
  modules/hmmcopy/readcounter/main.nf
  tests/config/pytest_modules.yml
  tests/modules/hmmcopy/generatemap/main.nf
  tests/modules/hmmcopy/generatemap/nextflow.config
  tests/modules/hmmcopy/generatemap/test.yml
  tests/modules/hmmcopy/readcounter/test.yml
Labels: new module, Ready for Review

#1101 Add applyvqsr
  modules/gatk4/applyvqsr/main.nf
  modules/gatk4/applyvqsr/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/gatk4/applyvqsr/main.nf
  tests/modules/gatk4/applyvqsr/nextflow.config
  tests/modules/gatk4/applyvqsr/test.yml
Labels: new module, Ready for Review

#1088 add module: Variantrecalibrator
  modules/gatk4/variantrecalibrator/main.nf
  modules/gatk4/variantrecalibrator/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gatk4/variantrecalibrator/main.nf
  tests/modules/gatk4/variantrecalibrator/nextflow.config
  tests/modules/gatk4/variantrecalibrator/test.yml
Labels: new module, Ready for Review

#1031 Added new module snpsift/split
  modules/snpsift/split/main.nf
  modules/snpsift/split/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/snpsift/split/main.nf
  tests/modules/snpsift/split/nextflow.config
  tests/modules/snpsift/split/test.yml
Labels: new module, Ready for Review

#1175 hmmcopy/mapCounter
  modules/hmmcopy/mapcounter/main.nf
  modules/hmmcopy/mapcounter/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/hmmcopy/mapcounter/main.nf
  tests/modules/hmmcopy/mapcounter/nextflow.config
  tests/modules/hmmcopy/mapcounter/test.yml
Labels: new module, Ready for Review

#1172 Fix kleborate inputs
  modules/kleborate/main.nf
  tests/modules/kleborate/test.yml
Labels: Ready for Review

#1188 Uppdate `Lima` module: remove old suffix option
  modules/lima/main.nf
Labels: Ready for Review
