Repository nf-core/modules, pull requests merged in 2021-02, with the labels that each got.

#110 Add SEACR module containing a single CALLPEAK process
  .github/workflows/seacr_callpeak.yml
  .gitignore
  .gitmodules
  software/seacr/callpeak/functions.nf
  software/seacr/callpeak/main.nf
  software/seacr/callpeak/meta.yml
  tests/data/bedgraph/IgG_1_to_chr20.bedgraph
  tests/data/bedgraph/K27me3_1_to_chr20.bedgraph
  tests/software/seacr/main.nf
  tests/software/seacr/test.yml
Labels: new module

#130 Adding a QUAST module
  .github/workflows/quast.yml
  software/quast/functions.nf
  software/quast/main.nf
  software/quast/meta.yml
  tests/software/quast/main.nf
  tests/software/quast/test.yml
Labels: new module

#131 Adding fastp module
  .github/workflows/fastp.yml
  software/fastp/functions.nf
  software/fastp/main.nf
  software/fastp/meta.yml
  tests/software/fastp/main.nf
  tests/software/fastp/test.yml
Labels: new module

#138 Pytest profiles
  .github/filters.yml
  .github/workflows/bowtie2_align.yml
  .github/workflows/bowtie2_build.yml
  .github/workflows/bowtie_build.yml
  .github/workflows/cutadapt.yml
  .github/workflows/dsh_filterbed.yml
  .github/workflows/dsh_splitbed.yml
  .github/workflows/fastp.yml
  .github/workflows/pangolin.yml
  .github/workflows/pytest-workflow.yml
  .github/workflows/quast.yml
  .github/workflows/salmon_index.yml
  .github/workflows/salmon_quant.yml
  .github/workflows/samtools_mpileup.yml
  .github/workflows/samtools_view.yml
  .github/workflows/seacr_callpeak.yml
  .github/workflows/star_align.yml
  .github/workflows/star_genomegenerate.yml
  tests/config/nextflow.config
  tests/software/bowtie/test.yml
  tests/software/bowtie2/test.yml
  tests/software/bwa/test.yml
  tests/software/cutadapt/test.yml
  tests/software/dsh/test.yml
  tests/software/fastp/test.yml
  tests/software/fastqc/test.yml
  tests/software/gffread/test.yml
  tests/software/multiqc/test.yml
  tests/software/pangolin/test.yml
  tests/software/picard/test.yml
  tests/software/preseq/test.yml
  tests/software/quast/test.yml
  tests/software/salmon/test.yml
  tests/software/samtools/test.yml
  tests/software/seacr/test.yml
  tests/software/star/test.yml
  tests/software/stringtie/test.yml
  tests/software/trimgalore/test.yml
  tests/software/ucsc/test.yml
Labels: tests

#143 Get Singularity CI tests working
  .github/filters.yml
  .github/workflows/pytest-workflow.yml
  tests/config/nextflow.config
  tests/software/bowtie/align/test.yml
  tests/software/bowtie/build/test.yml
  tests/software/bowtie2/build/test.yml
Labels: help wanted, tests

#148 ci: Fix artifact path
  .github/workflows/pytest-workflow.yml
Labels: bug, tests

#146 Add bandage image module
  .github/filters.yml
  software/bandage/image/functions.nf
  software/bandage/image/main.nf
  software/bandage/image/meta.yml
  tests/data/gfa/B-3106.gfa
  tests/software/bandage/image/main.nf
  tests/software/bandage/image/test.yml
Labels: new module

#149 Add minimap2 align module
  .github/filters.yml
  software/minimap2/align/functions.nf
  software/minimap2/align/main.nf
  software/minimap2/align/meta.yml
  tests/software/minimap2/align/main.nf
  tests/software/minimap2/align/test.yml
Labels: new module

#79 Bring bedtools up to speed
  .github/filters.yml
  software/bedtools/complement/functions.nf
  software/bedtools/complement/main.nf
  software/bedtools/complement/meta.yml
  software/bedtools/genomecov/functions.nf
  software/bedtools/genomecov/main.nf
  software/bedtools/genomecov/meta.yml
  software/bedtools/intersect/functions.nf
  software/bedtools/intersect/main.nf
  software/bedtools/intersect/meta.yml
  software/bedtools/merge/functions.nf
  software/bedtools/merge/main.nf
  software/bedtools/merge/meta.yml
  software/bedtools/slop/functions.nf
  software/bedtools/slop/main.nf
  software/bedtools/slop/meta.yml
  software/bedtools/sort/functions.nf
  software/bedtools/sort/main.nf
  software/bedtools/sort/meta.yml
  tests/software/bedtools/complement/main.nf
  tests/software/bedtools/complement/test.yml
  tests/software/bedtools/genomecov/main.nf
  tests/software/bedtools/genomecov/test.yml
  tests/software/bedtools/intersect/main.nf
  tests/software/bedtools/intersect/test.yml
  tests/software/bedtools/merge/main.nf
  tests/software/bedtools/merge/test.yml
  tests/software/bedtools/slop/main.nf
  tests/software/bedtools/slop/test.yml
  tests/software/bedtools/sort/main.nf
  tests/software/bedtools/sort/test.yml
Labels: new module

#139 Add documentation for Testing
  README.md
Labels: documentation, tests

#152 Update template module and add more docs for testing and finding containers
  .github/filters.yml
  README.md
  software/TOOL/SUBTOOL/functions.nf
  software/TOOL/SUBTOOL/main.nf
  software/TOOL/SUBTOOL/meta.yml
  tests/software/TOOL/SUBTOOL/main.nf
  tests/software/TOOL/SUBTOOL/test.yml
Labels: documentation

#134 Bcftools viralrecon
  .github/filters.yml
  software/bcftools/bgzip/functions.nf
  software/bcftools/bgzip/main.nf
  software/bcftools/bgzip/meta.yml
  software/bcftools/consensus/functions.nf
  software/bcftools/consensus/main.nf
  software/bcftools/consensus/meta.yml
  software/bcftools/filter/functions.nf
  software/bcftools/filter/main.nf
  software/bcftools/filter/meta.yml
  software/bcftools/isec/functions.nf
  software/bcftools/isec/main.nf
  software/bcftools/isec/meta.yml
  software/bcftools/stats/functions.nf
  software/bcftools/stats/main.nf
  software/bcftools/stats/meta.yml
  software/bcftools/tabix/functions.nf
  software/bcftools/tabix/main.nf
  software/bcftools/tabix/meta.yml
  tests/data/vcf/test.consensus.fa
  tests/data/vcf/test.vcf
  tests/data/vcf/test.vcf.gz
  tests/data/vcf/test.vcf.gz.tbi
  tests/data/vcf/test2.vcf.gz
  tests/data/vcf/test2.vcf.gz.tbi
  tests/data/vcf/test3.vcf.gz
  tests/data/vcf/test3.vcf.gz.tbi
  tests/software/bcftools/bgzip/main.nf
  tests/software/bcftools/bgzip/test.yml
  tests/software/bcftools/consensus/main.nf
  tests/software/bcftools/consensus/test.yml
  tests/software/bcftools/filter/main.nf
  tests/software/bcftools/filter/test.yml
  tests/software/bcftools/isec/main.nf
  tests/software/bcftools/isec/test.yml
  tests/software/bcftools/stats/main.nf
  tests/software/bcftools/stats/test.yml
  tests/software/bcftools/tabix/main.nf
  tests/software/bcftools/tabix/test.yml
Labels: new module

#151 Follow up fixes for bedtools modules added in #79
  .github/workflows/pytest-workflow.yml
  docs/images/nfcore-modules_logo.png
  software/bedtools/complement/main.nf
  software/bedtools/complement/meta.yml
  software/bedtools/genomecov/main.nf
  software/bedtools/genomecov/meta.yml
  software/bedtools/intersect/main.nf
  software/bedtools/intersect/meta.yml
  software/bedtools/merge/main.nf
  software/bedtools/merge/meta.yml
  software/bedtools/slop/main.nf
  software/bedtools/slop/meta.yml
  software/bedtools/sort/main.nf
  software/bedtools/sort/meta.yml
  tests/software/bedtools/complement/main.nf
  tests/software/bedtools/complement/test.yml
  tests/software/bedtools/genomecov/main.nf
  tests/software/bedtools/intersect/main.nf
  tests/software/bedtools/intersect/test.yml
  tests/software/bedtools/merge/main.nf
  tests/software/bedtools/merge/test.yml
  tests/software/bedtools/slop/main.nf
  tests/software/bedtools/slop/test.yml
  tests/software/bedtools/sort/main.nf
  tests/software/bedtools/sort/test.yml
Labels: enhancement

#135 Update indices syntax for BWA index and mem modules
  software/bwa/index/main.nf
  software/bwa/mem/main.nf
  software/bwa/mem/meta.yml
  tests/software/bwa/index/test.yml
  tests/software/bwa/mem/main.nf
  tests/software/bwa/mem/test.yml
Labels: enhancement

#178 Add cpus, memory and time requirements to limit resource consumption
  tests/config/nextflow.config
Labels: enhancement, question, tests

#174 ivar consensus: Add save mpileup as optional in output directive
  software/ivar/consensus/main.nf
Labels: update module

#177 Add gatk/createsequencedictionary
  .github/filters.yml
  deprecated/bwa-mem2/index/main.nf
  deprecated/bwa-mem2/index/meta.yml
  deprecated/bwa-mem2/index/test/main.nf
  deprecated/bwa-mem2/index/test/nextflow.config
  deprecated/gatk/dict/main.nf
  deprecated/gatk/dict/meta.yml
  deprecated/gatk/dict/test/main.nf
  deprecated/gatk/dict/test/nextflow.config
  software/gatk/createsequencedictionary/functions.nf
  software/gatk/createsequencedictionary/main.nf
  software/gatk/createsequencedictionary/meta.yml
  tests/software/gatk/createsequencedictionary/main.nf
  tests/software/gatk/createsequencedictionary/test.yml
Labels: new module

#179 Replace bcftools/tabix by tabix/tabix
  .github/filters.yml
  deprecated/htslib/tabix/main.nf
  deprecated/htslib/tabix/meta.yml
  deprecated/htslib/tabix/test/main.nf
  deprecated/htslib/tabix/test/nextflow.config
  software/bcftools/tabix/meta.yml
  software/tabix/tabix/functions.nf
  software/tabix/tabix/main.nf
  software/tabix/tabix/meta.yml
  tests/data/bed/B.bed.gz
  tests/data/gff/a.gff3.gz
  tests/software/bcftools/tabix/main.nf
  tests/software/bcftools/tabix/test.yml
  tests/software/tabix/tabix/main.nf
  tests/software/tabix/tabix/test.yml
Labels: update module

#180 Replace bcftools/bgzip by tabix/bgzip
  .github/filters.yml
  software/tabix/bgzip/functions.nf
  software/tabix/bgzip/main.nf
  software/tabix/bgzip/meta.yml
  tests/software/bcftools/bgzip/test.yml
  tests/software/tabix/bgzip/main.nf
  tests/software/tabix/bgzip/test.yml
Labels: update module

#175 fix: add guidelines to PRs and issues
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement
