Repository nf-core/modules, pull requests merged in 2021-07, with the labels that each got.

#559 Lofreq filter
  software/lofreq/filter/functions.nf
  software/lofreq/filter/main.nf
  software/lofreq/filter/meta.yml
  tests/config/pytest_software.yml
  tests/software/lofreq/filter/main.nf
  tests/software/lofreq/filter/test.yml
Labels: new module

#562 Pull request for module: lofreq/callparallel
  software/lofreq/callparallel/functions.nf
  software/lofreq/callparallel/main.nf
  software/lofreq/callparallel/meta.yml
  tests/config/pytest_software.yml
  tests/software/lofreq/callparallel/main.nf
  tests/software/lofreq/callparallel/test.yml
Labels: new module

#564 Lofreq call
  software/lofreq/call/functions.nf
  software/lofreq/call/main.nf
  software/lofreq/call/meta.yml
  tests/config/pytest_software.yml
  tests/software/lofreq/call/main.nf
  tests/software/lofreq/call/test.yml
Labels: new module

#565 Delly/call
  software/delly/call/functions.nf
  software/delly/call/main.nf
  software/delly/call/meta.yml
  tests/config/pytest_software.yml
  tests/software/delly/call/main.nf
  tests/software/delly/call/test.yml
Labels: new module

#547 feat: add VEP module
  software/ensemblvep/Dockerfile
  software/ensemblvep/build.sh
  software/ensemblvep/environment.yml
  software/ensemblvep/functions.nf
  software/ensemblvep/main.nf
  software/ensemblvep/meta.yml
  tests/config/pytest_software.yml
  tests/software/ensemblvep/main.nf
  tests/software/ensemblvep/test.yml
Labels: new module

#546 Add snpeff
  software/snpeff/Dockerfile
  software/snpeff/build.sh
  software/snpeff/environment.yml
  software/snpeff/functions.nf
  software/snpeff/main.nf
  software/snpeff/meta.yml
  tests/config/pytest_software.yml
  tests/software/snpeff/main.nf
  tests/software/snpeff/test.yml
Labels: new module

#587 fix: lofreq/call `test.yml` md5sum
  tests/modules/lofreq/call/test.yml
Labels: tests, update module

#586 fix: lofreq/callparallel missing arg (#562)
  modules/lofreq/callparallel/main.nf
  modules/lofreq/callparallel/meta.yml
  tests/modules/lofreq/callparallel/test.yml
Labels: update module

#590 Add samtools ampliconclip
  modules/samtools/ampliconclip/functions.nf
  modules/samtools/ampliconclip/main.nf
  modules/samtools/ampliconclip/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/samtools/ampliconclip/main.nf
  tests/modules/samtools/ampliconclip/test.yml
Labels: new module

#608 Add bcftools reheader (#585)
  modules/bcftools/reheader/functions.nf
  modules/bcftools/reheader/main.nf
  modules/bcftools/reheader/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/bcftools/reheader/main.nf
  tests/modules/bcftools/reheader/test.yml
Labels: new module
