Repository nf-core/modules, pull requests merged in 2021-09, with the labels that each got.

#669 Add bcftools view module
  modules/bcftools/view/functions.nf
  modules/bcftools/view/main.nf
  modules/bcftools/view/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/bcftools/view/main.nf
  tests/modules/bcftools/view/test.yml
Labels: new module, Ready for Review

#689 Getpileupsummaries
  modules/gatk4/getpileupsummaries/functions.nf
  modules/gatk4/getpileupsummaries/main.nf
  modules/gatk4/getpileupsummaries/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gatk4/getpileupsummaries/main.nf
  tests/modules/gatk4/getpileupsummaries/test.yml
Labels: Ready for Review

#682 Mutect2
  modules/gatk4/mutect2/functions.nf
  modules/gatk4/mutect2/main.nf
  modules/gatk4/mutect2/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gatk4/mutect2/main.nf
  tests/modules/gatk4/mutect2/test.yml
Labels: Ready for Review

#656 Adding plink/vcf module using nf-core tool
  modules/plink/vcf/functions.nf
  modules/plink/vcf/main.nf
  modules/plink/vcf/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/plink/vcf/main.nf
  tests/modules/plink/vcf/test.yml
Labels: new module, WIP

#670 Add bcftools/query module
  modules/bcftools/query/functions.nf
  modules/bcftools/query/main.nf
  modules/bcftools/query/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/bcftools/query/main.nf
  tests/modules/bcftools/query/test.yml
Labels: new module, Ready for Review

#697 module: snp-dists
  modules/snpdists/functions.nf
  modules/snpdists/main.nf
  modules/snpdists/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/snpdists/main.nf
  tests/modules/snpdists/test.yml
Labels: new module, Ready for Review

#659 Chromap Module
  modules/chromap/chromap/functions.nf
  modules/chromap/chromap/main.nf
  modules/chromap/chromap/meta.yml
  modules/chromap/index/functions.nf
  modules/chromap/index/main.nf
  modules/chromap/index/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/chromap/chromap/main.nf
  tests/modules/chromap/chromap/test.yml
  tests/modules/chromap/index/main.nf
  tests/modules/chromap/index/test.yml
Labels: Ready for Review

#702 add staphopia-sccmec module
  modules/staphopiasccmec/functions.nf
  modules/staphopiasccmec/main.nf
  modules/staphopiasccmec/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/staphopiasccmec/main.nf
  tests/modules/staphopiasccmec/test.yml
Labels: new module, Ready for Review

#691 Fix kallistobustools version extraction
  modules/kallistobustools/count/main.nf
  modules/kallistobustools/ref/main.nf
Labels: update module, Ready for Review

#686 Fix bug in gffread
  modules/gffread/main.nf
  modules/gffread/meta.yml
  tests/modules/gffread/main.nf
  tests/modules/gffread/test.yml
Labels: update module, Ready for Review

#693 module for `agrvate`
  modules/agrvate/functions.nf
  modules/agrvate/main.nf
  modules/agrvate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/agrvate/main.nf
  tests/modules/agrvate/test.yml
Labels: new module, Ready for Review

#716 Update for mutect2: add output channel for stats file
  modules/gatk4/mutect2/main.nf
  modules/gatk4/mutect2/meta.yml
  tests/modules/gatk4/mutect2/test.yml
Labels: update module, Ready for Review

#720 Module docs transfer - point people to website!
  README.md
Labels: Ready for Review

#723 Refactor cat/cat module
  modules/cat/cat/main.nf
  modules/cat/cat/meta.yml
  tests/modules/cat/cat/main.nf
  tests/modules/cat/cat/test.yml
Labels: Ready for Review

#725 add: MALTEXTRACT
  modules/maltextract/functions.nf
  modules/maltextract/main.nf
  modules/maltextract/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/maltextract/main.nf
  tests/modules/maltextract/test.yml
Labels: Ready for Review

#711 Add module `kleborate`
  modules/kleborate/functions.nf
  modules/kleborate/main.nf
  modules/kleborate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/kleborate/main.nf
  tests/modules/kleborate/test.yml
Labels: new module, Ready for Review

#729 Add glnexus
  modules/glnexus/functions.nf
  modules/glnexus/main.nf
  modules/glnexus/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/glnexus/main.nf
  tests/modules/glnexus/test.yml
Labels: Ready for Review

#710 Diamond
  modules/diamond/blastp/functions.nf
  modules/diamond/blastp/main.nf
  modules/diamond/blastp/meta.yml
  modules/diamond/blastx/functions.nf
  modules/diamond/blastx/main.nf
  modules/diamond/blastx/meta.yml
  modules/diamond/makedb/functions.nf
  modules/diamond/makedb/main.nf
  modules/diamond/makedb/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/diamond/blastp/main.nf
  tests/modules/diamond/blastp/test.yml
  tests/modules/diamond/blastx/main.nf
  tests/modules/diamond/blastx/test.yml
  tests/modules/diamond/makedb/main.nf
  tests/modules/diamond/makedb/test.yml
Labels: Ready for Review

#665 Update fastqc to produce multi-version versions.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pytest-workflow.yml
  .gitignore
  modules/fastqc/functions.nf
  modules/fastqc/main.nf
  modules/fastqc/meta.yml
  modules/multiqc/functions.nf
  modules/multiqc/main.nf
  modules/multiqc/meta.yml
  tests/test_versions_yml.py
Labels: Ready for Review

#719 New module: `LIMA`
  .gitignore
  modules/lima/functions.nf
  modules/lima/main.nf
  modules/lima/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/lima/main.nf
  tests/modules/lima/test.yml
Labels: Ready for Review

#758 few version and test data config fixes
  modules/chromap/chromap/main.nf
  modules/delly/call/main.nf
  modules/ensemblvep/main.nf
  modules/expansionhunter/main.nf
  modules/fgbio/callmolecularconsensusreads/main.nf
  modules/fgbio/sortbam/main.nf
  modules/glnexus/main.nf
  modules/kleborate/main.nf
  modules/minia/main.nf
  tests/config/test_data.config
  tests/modules/delly/call/test.yml
  tests/modules/hifiasm/main.nf
Labels: Ready for Review

#768 add Amps
  modules/amps/functions.nf
  modules/amps/main.nf
  modules/amps/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/amps/main.nf
  tests/modules/amps/test.yml
Labels: Ready for Review

#771 Add bbmap/bbsplit module
  modules/bbmap/bbsplit/functions.nf
  modules/bbmap/bbsplit/main.nf
  modules/bbmap/bbsplit/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/bbmap/bbsplit/main.nf
  tests/modules/bbmap/bbsplit/test.yml
Labels: new module, Ready for Review
