Repository nf-core/modules, pull requests merged in 2021-10, with the labels that each got.

#742 added classic mlst module
  modules/mlst/functions.nf
  modules/mlst/main.nf
  modules/mlst/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/mlst/main.nf
  tests/modules/mlst/test.yml
Labels: new module, Ready for Review

#765 Add gtdbtk/classifywf module
  modules/gtdbtk/classifywf/functions.nf
  modules/gtdbtk/classifywf/main.nf
  modules/gtdbtk/classifywf/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gtdbtk/classifywf/main.nf
  tests/modules/gtdbtk/classifywf/test.yml
Labels: new module, Ready for Review

#773 add ismapper module
  modules/ismapper/functions.nf
  modules/ismapper/main.nf
  modules/ismapper/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ismapper/main.nf
  tests/modules/ismapper/test.yml
Labels: new module, Ready for Review

#784 add spatyper module
  modules/spatyper/functions.nf
  modules/spatyper/main.nf
  modules/spatyper/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/spatyper/main.nf
  tests/modules/spatyper/test.yml
Labels: new module, Ready for Review

#777 add pirate module
  modules/pirate/functions.nf
  modules/pirate/main.nf
  modules/pirate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/pirate/main.nf
  tests/modules/pirate/test.yml
Labels: new module, Ready for Review

#778 new module: gatk4/calculatecontamination
  modules/gatk4/calculatecontamination/functions.nf
  modules/gatk4/calculatecontamination/main.nf
  modules/gatk4/calculatecontamination/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/gatk4/calculatecontamination/main.nf
  tests/modules/gatk4/calculatecontamination/test.yml
Labels: Ready for Review

#752 New module: `pbbam/pbmerge`
  modules/pbbam/pbmerge/functions.nf
  modules/pbbam/pbmerge/main.nf
  modules/pbbam/pbmerge/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/pbbam/pbmerge/main.nf
  tests/modules/pbbam/pbmerge/test.yml
Labels: new module, Ready for Review

#748 New module: `isoseq3/refine`
  modules/isoseq3/refine/functions.nf
  modules/isoseq3/refine/main.nf
  modules/isoseq3/refine/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/isoseq3/refine/main.nf
  tests/modules/isoseq3/refine/test.yml
Labels: new module, Ready for Review

#908 Add IDR module
  modules/idr/functions.nf
  modules/idr/main.nf
  modules/idr/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/idr/main.nf
  tests/modules/idr/test.yml
Labels: new module
