Repository nf-core/modules, pull requests merged in 2021-04, with the labels that each got.

#410 Add plasmidid module
  software/plasmidid/functions.nf
  software/plasmidid/main.nf
  software/plasmidid/meta.yml
  tests/config/pytest_software.yml
  tests/config/test_data.config
  tests/data/README.md
  tests/data/genomics/sarscov2/genome/contigs.fasta
  tests/software/plasmidid/main.nf
  tests/software/plasmidid/test.yml
Labels: new module

#414 Test PR for nf-core modules lint
  .github/workflows/code-linting.yml
  .github/workflows/nf-core-linting.yml
  .github/workflows/pytest-workflow.yml
Labels: Ready for Review, linting, tests

#364 Nanoplot and sequencing_summary.txt for Nanopore test data
  software/nanoplot/functions.nf
  software/nanoplot/main.nf
  software/nanoplot/meta.yml
  tests/config/pytest_software.yml
  tests/config/test_data.config
  tests/data/genomics/sarscov2/nanopore/sequencing_summary/test.sequencing_summary.txt
  tests/software/nanoplot/main.nf
  tests/software/nanoplot/test.yml
Labels: new module

#408 Added kallistobustools/ref
  software/kallistobustools/ref/functions.nf
  software/kallistobustools/ref/main.nf
  software/kallistobustools/ref/meta.yml
  tests/config/pytest_software.yml
  tests/data/delete_me/kallistobustools/GRCm39.chr19_100k.fa.gz
  tests/data/delete_me/kallistobustools/gencode.VM26.chr19_10k.gtf.gz
  tests/software/kallistobustools/ref/main.nf
  tests/software/kallistobustools/ref/test.yml
Labels: new module

#413 new module: rasusa
  software/rasusa/functions.nf
  software/rasusa/main.nf
  software/rasusa/meta.yml
  tests/config/pytest_software.yml
  tests/software/rasusa/main.nf
  tests/software/rasusa/test.yml
Labels: new module

#426 🏋️‍♀️ new submodule mash/sketch🕺
  software/mash/sketch/functions.nf
  software/mash/sketch/main.nf
  software/mash/sketch/meta.yml
  tests/config/pytest_software.yml
  tests/software/mash/sketch/main.nf
  tests/software/mash/sketch/test.yml
Labels: Ready for Review, new module

#424 Add pycoqc module
  software/pycoqc/functions.nf
  software/pycoqc/main.nf
  software/pycoqc/meta.yml
  tests/config/pytest_software.yml
  tests/software/pycoqc/main.nf
  tests/software/pycoqc/test.yml
Labels: Ready for Review, new module

#431 Add abacas module
  software/abacas/functions.nf
  software/abacas/main.nf
  software/abacas/meta.yml
  tests/config/pytest_software.yml
  tests/config/test_data.config
  tests/software/abacas/main.nf
  tests/software/abacas/test.yml
Labels: Ready for Review, new module

#434 Add kraken2 pigz multi-tool container for compressing output fastq files
  software/kraken2/run/main.nf
  tests/config/pytest_software.yml
  tests/software/kraken2/run/main.nf
  tests/software/kraken2/run/test.yml
Labels: Ready for Review

#439 Finish rseqc modules
  software/rseqc/bamstat/meta.yml
  software/rseqc/inferexperiment/meta.yml
  software/rseqc/innerdistance/meta.yml
  software/rseqc/junctionannotation/meta.yml
  software/rseqc/readdistribution/meta.yml
  software/rseqc/readduplication/meta.yml
  tests/config/pytest_software.yml
  tests/software/rseqc/bamstat/main.nf
  tests/software/rseqc/bamstat/test.yml
  tests/software/rseqc/inferexperiment/main.nf
  tests/software/rseqc/inferexperiment/test.yml
  tests/software/rseqc/innerdistance/main.nf
  tests/software/rseqc/innerdistance/test.yml
  tests/software/rseqc/junctionannotation/main.nf
  tests/software/rseqc/readdistribution/main.nf
  tests/software/rseqc/readdistribution/test.yml
  tests/software/rseqc/readduplication/main.nf
  tests/software/rseqc/readduplication/test.yml
Labels: tests

#442 Finish deeptools modules
  software/deeptools/computematrix/meta.yml
  software/deeptools/plotfingerprint/meta.yml
  software/deeptools/plotheatmap/meta.yml
  software/deeptools/plotprofile/meta.yml
  tests/config/pytest_software.yml
  tests/config/test_data.config
  tests/software/deeptools/computematrix/main.nf
  tests/software/deeptools/computematrix/test.yml
  tests/software/deeptools/plotfingerprint/main.nf
  tests/software/deeptools/plotfingerprint/test.yml
  tests/software/deeptools/plotheatmap/main.nf
  tests/software/deeptools/plotheatmap/test.yml
  tests/software/deeptools/plotprofile/main.nf
  tests/software/deeptools/plotprofile/test.yml
Labels: tests

#447 Fixing abacas meta.yml file
  software/abacas/meta.yml
Labels: Ready for Review

#450 Add ucsc/bedclip module
  software/ucsc/bedclip/functions.nf
  software/ucsc/bedclip/main.nf
  software/ucsc/bedclip/meta.yml
  tests/config/pytest_software.yml
  tests/software/ucsc/bedclip/main.nf
  tests/software/ucsc/bedclip/test.yml
Labels: Ready for Review, new module

#449 Update modules required for rnaseq pipeline
  software/hisat2/build/main.nf
  software/preseq/lcextrap/main.nf
  software/preseq/lcextrap/meta.yml
  software/samtools/index/main.nf
  software/samtools/index/meta.yml
  software/star/genomegenerate/main.nf
  tests/software/preseq/lcextrap/test.yml
  tests/software/samtools/index/main.nf
  tests/software/samtools/index/test.yml
  tests/software/star/genomegenerate/main.nf
Labels: Ready for Review, update module

#409 Added kallistobustools/count
  software/kallistobustools/count/functions.nf
  software/kallistobustools/count/main.nf
  software/kallistobustools/count/meta.yml
  tests/config/pytest_software.yml
  tests/data/delete_me/kallistobustools/count/SRR8599150_S1_L001_R1_001.20k_lines.fastq.gz
  tests/data/delete_me/kallistobustools/count/SRR8599150_S1_L001_R2_001.20k_lines.fastq.gz
  tests/data/delete_me/kallistobustools/count/kb_ref.idx
  tests/data/delete_me/kallistobustools/count/mismatch.idx
  tests/data/delete_me/kallistobustools/count/pbmc_1k_protein_v3_antibody_S2_L001_R1_001.100k_sub.fastq.gz
  tests/data/delete_me/kallistobustools/count/pbmc_1k_protein_v3_antibody_S2_L001_R2_001.100k_sub.fastq.gz
  tests/data/delete_me/kallistobustools/count/t2g.kite.txt
  tests/data/delete_me/kallistobustools/count/t2g.txt
  tests/software/kallistobustools/count/main.nf
  tests/software/kallistobustools/count/test.yml
Labels: new module

#415 Update README to include some git best practices
  README.md
Labels: documentation
