Repository nf-core/modules, pull requests merged in 2022-06, with the labels that each got.

#1643 add module for snippy
  modules/snippy/run/main.nf
  modules/snippy/run/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/snippy/run/main.nf
  tests/modules/snippy/run/nextflow.config
  tests/modules/snippy/run/test.yml
Labels: new module, Ready for Review

#1744 new module gatk4/reblockgvcf
  modules/gatk4/reblockgvcf/main.nf
  modules/gatk4/reblockgvcf/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gatk4/reblockgvcf/main.nf
  tests/modules/gatk4/reblockgvcf/nextflow.config
  tests/modules/gatk4/reblockgvcf/test.yml
Labels: WIP

#1750 add module for mcroni
  modules/mcroni/main.nf
  modules/mcroni/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/mcroni/main.nf
  tests/modules/mcroni/nextflow.config
  tests/modules/mcroni/test.yml
Labels: new module, Ready for Review

#1739 FastK/fastK
  modules/fastk/fastk/main.nf
  modules/fastk/fastk/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/fastk/fastk/main.nf
  tests/modules/fastk/fastk/nextflow.config
  tests/modules/fastk/fastk/test.yml
Labels: Ready for Review

#1776 Add FastK/Histex
  modules/fastk/histex/main.nf
  modules/fastk/histex/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/fastk/histex/main.nf
  tests/modules/fastk/histex/nextflow.config
  tests/modules/fastk/histex/test.yml
Labels: Ready for Review

#1778 Add MerquryFK
  modules/merquryfk/merquryfk/main.nf
  modules/merquryfk/merquryfk/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/merquryfk/merquryfk/main.nf
  tests/modules/merquryfk/merquryfk/nextflow.config
  tests/modules/merquryfk/merquryfk/test.yml
Labels: Ready for Review

#1781 Add GeneScopeFK
  modules/genescopefk/main.nf
  modules/genescopefk/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/genescopefk/main.nf
  tests/modules/genescopefk/nextflow.config
  tests/modules/genescopefk/test.yml
Labels: Ready for Review

#1780 Add MerquryFK PloidyPlot
  modules/merquryfk/ploidyplot/main.nf
  modules/merquryfk/ploidyplot/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/merquryfk/ploidyplot/main.nf
  tests/modules/merquryfk/ploidyplot/nextflow.config
  tests/modules/merquryfk/ploidyplot/test.yml
Labels: Ready for Review

#1775 Optional output from the VEP-moduel
  modules/ensemblvep/main.nf
  modules/ensemblvep/meta.yml
  tests/modules/ensemblvep/main.nf
  tests/modules/ensemblvep/nextflow.config
  tests/modules/ensemblvep/test.yml
Labels: Ready for Review

#1569 update bclconvert module, as used in nf-core/demultiplex
  modules/bclconvert/main.nf
  modules/bclconvert/meta.yml
  tests/config/test_data.config
  tests/modules/bclconvert/main.nf
  tests/modules/bclconvert/nextflow.config
  tests/modules/bclconvert/test.yml
Labels: update module, Ready for Review

#1795 new module vcf2db
  modules/vcf2db/main.nf
  modules/vcf2db/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/vcf2db/main.nf
  tests/modules/vcf2db/nextflow.config
  tests/modules/vcf2db/test.yml
Labels: Ready for Review

#1797 Add MerquryFK KatComp
  modules/merquryfk/katcomp/main.nf
  modules/merquryfk/katcomp/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/merquryfk/katcomp/main.nf
  tests/modules/merquryfk/katcomp/nextflow.config
  tests/modules/merquryfk/katcomp/test.yml
Labels: Ready for Review

#1798 Add MerquryFK KatGC
  modules/merquryfk/katgc/main.nf
  modules/merquryfk/katgc/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/merquryfk/katgc/main.nf
  tests/modules/merquryfk/katgc/nextflow.config
  tests/modules/merquryfk/katgc/test.yml
Labels: Ready for Review

#1806 bump bclconvert version
  modules/bclconvert/main.nf
  modules/bclconvert/meta.yml
  tests/modules/bclconvert/test.yml
Labels: Ready for Review

#1819 bclconvert: Update Dockerfile
  modules/bclconvert/Dockerfile
  modules/bclconvert/main.nf
Labels: Ready for Review

#1826 add extra output from snap aligner
  modules/snapaligner/align/main.nf
  modules/snapaligner/align/meta.yml
  tests/modules/snapaligner/align/main.nf
  tests/modules/snapaligner/align/nextflow.config
  tests/modules/snapaligner/align/test.yml
Labels: Ready for Review

#1827 Update Arriba to 2.3.0
  modules/arriba/main.nf
  tests/modules/arriba/test.yml
Labels: Ready for Review

#1835 snapaligner: fix quotes
  modules/snapaligner/align/main.nf
  modules/snapaligner/index/main.nf
Labels: Ready for Review

#1837 Set randomseed for UMI tools if not otherwise set
  modules/umitools/dedup/main.nf
Labels: bug

#1839 NGSCheckMate doesn't generate a pdf for only one sample, made optional output
  modules/ngscheckmate/ncm/main.nf
Labels: update module
