Repository nf-core/modules, pull requests merged in 2022-07, with the labels that each got.

#1842 Add ffq module
  modules/ffq/main.nf
  modules/ffq/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ffq/main.nf
  tests/modules/ffq/nextflow.config
  tests/modules/ffq/test.yml
Labels: Ready for Review

#1840 antismashlite: Support GBK input
  modules/antismash/antismashlite/main.nf
  modules/antismash/antismashlite/meta.yml
Labels: enhancement

#1830 New modules: `ultra/index` and `ultra/align`
  modules/ultra/align/main.nf
  modules/ultra/align/meta.yml
  modules/ultra/index/main.nf
  modules/ultra/index/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ultra/align/main.nf
  tests/modules/ultra/align/nextflow.config
  tests/modules/ultra/align/test.yml
  tests/modules/ultra/index/main.nf
  tests/modules/ultra/index/nextflow.config
  tests/modules/ultra/index/test.yml
Labels: new module, Ready for Review

#1867 Add manual version definition for artic modules
  modules/artic/guppyplex/main.nf
  modules/artic/minion/main.nf
Labels: Ready for Review

#1833 Add ENTREZDIRECT/ESUMMARY
  modules/entrezdirect/esummary/main.nf
  modules/entrezdirect/esummary/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/entrezdirect/esummary/main.nf
  tests/modules/entrezdirect/esummary/nextflow.config
  tests/modules/entrezdirect/esummary/test.yml
Labels: new module, Ready for Review

#1883 Module/bcl2fastq
  modules/bcl2fastq/.gitignore
  modules/bcl2fastq/Dockerfile
  modules/bcl2fastq/LICENSE
  modules/bcl2fastq/README.md
  modules/bcl2fastq/main.nf
  modules/bcl2fastq/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/bcl2fastq/main.nf
  tests/modules/bcl2fastq/nextflow.config
  tests/modules/bcl2fastq/test.yml
Labels: new module, Ready for Review

#1881 Fixed the MD5 checksum
  tests/modules/entrezdirect/esummary/test.yml
Labels: tests, Ready for Review

#1779 Add new module: Pear
  modules/pear/main.nf
  modules/pear/meta.yml
  tests/config/pytest_modules.yml
  tests/config/pytest_modules_test.yml
  tests/modules/pear/main.nf
  tests/modules/pear/nextflow.config
  tests/modules/pear/test.yml
Labels: new module

#1928 renamed output in entrezdirect/esummary: xml
  modules/entrezdirect/esummary/main.nf
  modules/entrezdirect/esummary/meta.yml
  tests/modules/entrezdirect/esummary/main.nf
  tests/modules/entrezdirect/esummary/nextflow.config
  tests/modules/entrezdirect/esummary/test.yml
Labels: update module, Ready for Review

#1926 new (fixed) module: entrezdirect/xtract
  modules/entrezdirect/xtract/main.nf
  modules/entrezdirect/xtract/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/entrezdirect/xtract/main.nf
  tests/modules/entrezdirect/xtract/nextflow.config
  tests/modules/entrezdirect/xtract/test.yml
Labels: new module, Ready for Review

#1927 new (fixed) module: entrezdirect/esearch
  modules/entrezdirect/esearch/main.nf
  modules/entrezdirect/esearch/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/entrezdirect/esearch/main.nf
  tests/modules/entrezdirect/esearch/nextflow.config
  tests/modules/entrezdirect/esearch/test.yml
Labels: new module, Ready for Review

#1919 Added support for ext.args in samtools/faidx
  modules/samtools/faidx/main.nf
Labels: Ready for Review

#1922 Added the samtools/dict module
  modules/samtools/dict/main.nf
  modules/samtools/dict/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/samtools/dict/main.nf
  tests/modules/samtools/dict/nextflow.config
  tests/modules/samtools/dict/test.yml
Labels: Ready for Review
