Repository nf-core/modules, pull requests merged in 2022-08, with the labels that each got.

#1943 add stub for cat/fastq
  modules/cat/fastq/main.nf
  tests/modules/cat/fastq/test.yml
Labels: Ready for Review

#1944 add stub for kallisto/index
  modules/kallisto/index/main.nf
  tests/modules/kallisto/index/test.yml
Labels: Ready for Review

#1945 add stub for picard/collectwgsmtrics
  modules/picard/collectwgsmetrics/main.nf
  tests/modules/picard/collectwgsmetrics/test.yml
Labels: Ready for Review

#1948 Add stub star align genomegenerate
  modules/star/align/main.nf
  modules/star/genomegenerate/main.nf
  tests/modules/star/align/test.yml
  tests/modules/star/genomegenerate/test.yml
Labels: Ready for Review

#1949 add stub for stringtie
  modules/stringtie/merge/main.nf
  modules/stringtie/stringtie/main.nf
  tests/modules/stringtie/merge/test.yml
  tests/modules/stringtie/stringtie/test.yml
Labels: Ready for Review

#1950 Add genmod
  modules/genmod/annotate/main.nf
  modules/genmod/annotate/meta.yml
  modules/genmod/compound/main.nf
  modules/genmod/compound/meta.yml
  modules/genmod/models/main.nf
  modules/genmod/models/meta.yml
  modules/genmod/score/main.nf
  modules/genmod/score/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/genmod/annotate/main.nf
  tests/modules/genmod/annotate/nextflow.config
  tests/modules/genmod/annotate/test.yml
  tests/modules/genmod/compound/main.nf
  tests/modules/genmod/compound/nextflow.config
  tests/modules/genmod/compound/test.yml
  tests/modules/genmod/models/main.nf
  tests/modules/genmod/models/nextflow.config
  tests/modules/genmod/models/test.yml
  tests/modules/genmod/score/main.nf
  tests/modules/genmod/score/nextflow.config
  tests/modules/genmod/score/test.yml
Labels: Ready for Review

#1954 Added support for `task.ext.args`
  modules/ucsc/bedtobigbed/main.nf
  modules/ucsc/bedtobigbed/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ucsc/bed12tobigbed/test.yml
  tests/modules/ucsc/bedtobigbed/main.nf
  tests/modules/ucsc/bedtobigbed/nextflow.config
  tests/modules/ucsc/bedtobigbed/test.yml
Labels: Ready for Review

#1866 Add module: goat/taxonsearch
  modules/goat/taxonsearch/main.nf
  modules/goat/taxonsearch/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/goat/taxonsearch/main.nf
  tests/modules/goat/taxonsearch/nextflow.config
  tests/modules/goat/taxonsearch/test.yml
Labels: new module

#1933 Use a newer container version because the previous one is broken
  modules/ncbigenomedownload/main.nf
Labels: Ready for Review

#1961 Newer container version because the previous one is misconfigured
  modules/ucsc/bedtobigbed/main.nf
Labels: Ready for Review

#1973 Included args option in picard AddOrReplaceReadGroups
  modules/picard/addorreplacereadgroups/main.nf
Labels: update module, Ready for Review

#1932 Set PYTHONHASHSEED for umitools dedup
  modules/umitools/dedup/main.nf
Labels: bug

#1983 feat(pints): Add initial caller module
  modules/pints/caller/main.nf
  modules/pints/caller/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/pints/caller/main.nf
  tests/modules/pints/caller/nextflow.config
  tests/modules/pints/caller/test.yml
Labels: Ready for Review
