Repository nf-core/modules, pull requests merged in 2022-03, with the labels that each got.

#1367 Faqcs patch
  modules/faqcs/main.nf
  modules/faqcs/meta.yml
Labels: update module

#1370 Add picard/sortvcf
  modules/picard/sortvcf/main.nf
  modules/picard/sortvcf/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/picard/sortvcf/main.nf
  tests/modules/picard/sortvcf/nextflow.config
  tests/modules/picard/sortvcf/test.yml
Labels: Ready for Review

#1353 Add samtools index to yara_mapper module
  modules/yara/mapper/main.nf
  modules/yara/mapper/meta.yml
  tests/modules/yara/mapper/test.yml
Labels: Ready for Review

#1384 Decrease indent in seqtk/seq versions.yml output
  modules/seqtk/seq/main.nf
  tests/modules/seqtk/seq/test.yml
Labels: update module

#1382 added module seqkit replace
  modules/seqkit/replace/main.nf
  modules/seqkit/replace/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/seqkit/replace/main.nf
  tests/modules/seqkit/replace/nextflow.config
  tests/modules/seqkit/replace/test.yml
Labels: new module, Ready for Review

#1374 Bump chromap version 0.2.0
  modules/chromap/chromap/main.nf
  modules/chromap/index/main.nf
  tests/modules/chromap/chromap/test.yml
  tests/modules/chromap/index/test.yml
Labels: WIP, update module

#1290 New module: NGSCheckMate
  modules/ngscheckmate/ncm/main.nf
  modules/ngscheckmate/ncm/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ngscheckmate/ncm/main.nf
  tests/modules/ngscheckmate/ncm/nextflow.config
  tests/modules/ngscheckmate/ncm/test.yml
Labels: new module, Ready for Review

#1354 Add core Biscuit tools
  modules/biscuit/align/main.nf
  modules/biscuit/align/meta.yml
  modules/biscuit/biscuitblaster/main.nf
  modules/biscuit/biscuitblaster/meta.yml
  modules/biscuit/bsconv/main.nf
  modules/biscuit/bsconv/meta.yml
  modules/biscuit/epiread/main.nf
  modules/biscuit/epiread/meta.yml
  modules/biscuit/index/main.nf
  modules/biscuit/index/meta.yml
  modules/biscuit/mergecg/main.nf
  modules/biscuit/mergecg/meta.yml
  modules/biscuit/pileup/main.nf
  modules/biscuit/pileup/meta.yml
  modules/biscuit/qc/main.nf
  modules/biscuit/qc/meta.yml
  modules/biscuit/vcf2bed/main.nf
  modules/biscuit/vcf2bed/meta.yml
  tests/config/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/biscuit/align/main.nf
  tests/modules/biscuit/align/nextflow.config
  tests/modules/biscuit/align/test.yml
  tests/modules/biscuit/biscuitblaster/main.nf
  tests/modules/biscuit/biscuitblaster/nextflow.config
  tests/modules/biscuit/biscuitblaster/test.yml
  tests/modules/biscuit/bsconv/main.nf
  tests/modules/biscuit/bsconv/nextflow.config
  tests/modules/biscuit/bsconv/test.yml
  tests/modules/biscuit/epiread/main.nf
  tests/modules/biscuit/epiread/nextflow.config
  tests/modules/biscuit/epiread/test.yml
  tests/modules/biscuit/index/main.nf
  tests/modules/biscuit/index/nextflow.config
  tests/modules/biscuit/index/test.yml
  tests/modules/biscuit/mergecg/main.nf
  tests/modules/biscuit/mergecg/nextflow.config
  tests/modules/biscuit/mergecg/test.yml
  tests/modules/biscuit/pileup/main.nf
  tests/modules/biscuit/pileup/nextflow.config
  tests/modules/biscuit/pileup/test.yml
  tests/modules/biscuit/qc/main.nf
  tests/modules/biscuit/qc/nextflow.config
  tests/modules/biscuit/qc/test.yml
  tests/modules/biscuit/vcf2bed/main.nf
  tests/modules/biscuit/vcf2bed/nextflow.config
  tests/modules/biscuit/vcf2bed/test.yml
Labels: new module, Ready for Review

#1297 Cnvpytor
  modules/cnvpytor/callcnvs/main.nf
  modules/cnvpytor/callcnvs/meta.yml
  modules/cnvpytor/histogram/main.nf
  modules/cnvpytor/histogram/meta.yml
  modules/cnvpytor/importreaddepth/main.nf
  modules/cnvpytor/importreaddepth/meta.yml
  modules/cnvpytor/partition/main.nf
  modules/cnvpytor/partition/meta.yml
  tests/config/test_data.config
  tests/modules/cnvpytor/callcnvs/main.nf
  tests/modules/cnvpytor/callcnvs/nextflow.config
  tests/modules/cnvpytor/callcnvs/test.yml
  tests/modules/cnvpytor/histogram/main.nf
  tests/modules/cnvpytor/histogram/nextflow.config
  tests/modules/cnvpytor/histogram/test.yml
  tests/modules/cnvpytor/importreaddepth/main.nf
  tests/modules/cnvpytor/importreaddepth/nextflow.config
  tests/modules/cnvpytor/partition/main.nf
  tests/modules/cnvpytor/partition/nextflow.config
  tests/modules/cnvpytor/partition/test.yml
Labels: new module, Ready for Review

#1332 ASCAT
  modules/ascat/main.nf
  modules/ascat/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ascat/main.nf
  tests/modules/ascat/nextflow.config
  tests/modules/ascat/test.yml
Labels: Ready for Review

#1388 Add BAM indexes as input for optitype module
  modules/optitype/main.nf
  modules/optitype/meta.yml
  tests/config/test_data.config
  tests/modules/optitype/main.nf
  tests/modules/optitype/test.yml
Labels: Ready for Review

#1423 Add bracken
  modules/bracken/bracken/main.nf
  modules/bracken/bracken/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/bracken/bracken/main.nf
  tests/modules/bracken/bracken/nextflow.config
  tests/modules/bracken/bracken/test.yml
Labels: Ready for Review

#1378 update star/align to include an optional sam output
  modules/star/align/main.nf
Labels: update module, Ready for Review

#1442 Update dragonflye to latest version
  modules/dragonflye/main.nf
Labels: update module

#1441 feat(bbmap): Initialize pileup module
  modules/bbmap/pileup/main.nf
  modules/bbmap/pileup/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/bbmap/pileup/main.nf
  tests/modules/bbmap/pileup/nextflow.config
  tests/modules/bbmap/pileup/test.yml
Labels: new module

#1436 Homer/findpeaks improvements
  modules/homer/findpeaks/main.nf
  modules/homer/findpeaks/meta.yml
  tests/config/pytest_modules.yml
Labels: documentation, update module

#1435 feat(homer): Add pos2bed module
  modules/homer/pos2bed/main.nf
  modules/homer/pos2bed/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/homer/pos2bed/main.nf
  tests/modules/homer/pos2bed/nextflow.config
  tests/modules/homer/pos2bed/test.yml
Labels: new module

#1438 fix(homer): Update output path for bedGraph
  modules/homer/makeucscfile/main.nf
  modules/homer/makeucscfile/meta.yml
  tests/modules/homer/makeucscfile/test.yml
Labels: bug, update module

#1429 Add tests for umitools extract and dedup
  tests/config/pytest_modules.yml
  tests/modules/umitools/dedup/main.nf
  tests/modules/umitools/dedup/nextflow.config
  tests/modules/umitools/dedup/test.yml
  tests/modules/umitools/extract/main.nf
  tests/modules/umitools/extract/nextflow.config
  tests/modules/umitools/extract/test.yml
Labels: Ready for Review

#1437 Add samtools to homer/maketagdirectory to use bam files
  modules/homer/maketagdirectory/main.nf
  modules/homer/maketagdirectory/meta.yml
  tests/modules/homer/maketagdirectory/main.nf
  tests/modules/homer/maketagdirectory/nextflow.config
  tests/modules/homer/maketagdirectory/test.yml
Labels: update module

#1456 Fix homer/maketagdirectory output collision
  modules/homer/maketagdirectory/main.nf
  modules/homer/maketagdirectory/meta.yml
  tests/modules/homer/findpeaks/test.yml
  tests/modules/homer/maketagdirectory/test.yml
  tests/modules/homer/pos2bed/test.yml
Labels: bug

#1206 add stub to modules used in raredisease pipeline
  modules/bcftools/norm/main.nf
  modules/bcftools/view/main.nf
  modules/bwamem2/index/main.nf
  modules/bwamem2/mem/main.nf
  modules/cat/cat/main.nf
  modules/deepvariant/main.nf
  modules/expansionhunter/main.nf
  modules/fastqc/main.nf
  modules/gatk4/bedtointervallist/main.nf
  modules/gatk4/createsequencedictionary/main.nf
  modules/gatk4/intervallisttools/main.nf
  modules/glnexus/main.nf
  modules/multiqc/main.nf
  modules/picard/collecthsmetrics/main.nf
  modules/picard/collectmultiplemetrics/main.nf
  modules/picard/markduplicates/main.nf
  modules/picard/sortvcf/main.nf
  modules/qualimap/bamqc/main.nf
  modules/samtools/faidx/main.nf
  modules/samtools/index/main.nf
  modules/samtools/merge/main.nf
  modules/samtools/sort/main.nf
  modules/samtools/stats/main.nf
  modules/svdb/query/main.nf
  modules/tabix/bgziptabix/main.nf
  modules/tabix/tabix/main.nf
  modules/tiddit/cov/main.nf
  modules/tiddit/sv/main.nf
  modules/ucsc/wigtobigwig/main.nf
  modules/untar/main.nf
  modules/vcfanno/main.nf
  tests/modules/expansionhunter/main.nf
  tests/modules/expansionhunter/test.yml
Labels: Ready for Review

#1465 Update svdb to 2.6.0
  modules/svdb/merge/main.nf
  modules/svdb/query/main.nf
Labels: Ready for Review

#1466 feat: add module for seqkit stats
  modules/seqkit/stats/main.nf
  modules/seqkit/stats/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/seqkit/stats/main.nf
  tests/modules/seqkit/stats/nextflow.config
  tests/modules/seqkit/stats/test.yml
Labels: Ready for Review

#1469 Update cat module
  modules/cat/cat/main.nf
  tests/modules/cat/cat/test.yml
Labels: Ready for Review

#1468 New Module: `gstama/polyacleanup`
  modules/gstama/polyacleanup/main.nf
  modules/gstama/polyacleanup/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gstama/polyacleanup/main.nf
  tests/modules/gstama/polyacleanup/nextflow.config
  tests/modules/gstama/polyacleanup/test.yml
Labels: new module, Ready for Review

#1467 Update PyDamage module
  modules/pydamage/analyze/main.nf
  modules/pydamage/filter/main.nf
Labels: update module

#1474 Add task.ext.args to phantompeakqualtools and finish the module
  modules/phantompeakqualtools/main.nf
  modules/phantompeakqualtools/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/phantompeakqualtools/main.nf
  tests/modules/phantompeakqualtools/nextflow.config
  tests/modules/phantompeakqualtools/test.yml
Labels: Ready for Review
