Repository nf-core/modules, pull requests merged in 2022-02, with the labels that each got.

#1087 Raven assembler
  modules/raven/main.nf
  modules/raven/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/raven/main.nf
  tests/modules/raven/nextflow.config
  tests/modules/raven/test.yml
Labels: new module

#1249 Add svdb/query
  modules/svdb/query/main.nf
  modules/svdb/query/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/svdb/query/main.nf
  tests/modules/svdb/query/nextflow.config
  tests/modules/svdb/query/test.yml
Labels: Ready for Review

#1244 bamcmp
  modules/bamcmp/main.nf
  modules/bamcmp/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/bamcmp/main.nf
  tests/modules/bamcmp/nextflow.config
  tests/modules/bamcmp/test.yml
Labels: new module, Ready for Review

#1233 Add svdb/merge
  modules/svdb/merge/main.nf
  modules/svdb/merge/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/svdb/merge/main.nf
  tests/modules/svdb/merge/nextflow.config
  tests/modules/svdb/merge/test.yml
Labels: Ready for Review

#1256 Update mosdepth
  modules/mosdepth/main.nf
  modules/mosdepth/meta.yml
  tests/modules/mosdepth/main.nf
  tests/modules/mosdepth/test.yml
Labels: Ready for Review

#1218 update manta to enable jointcalling
  modules/manta/germline/main.nf
  modules/manta/germline/meta.yml
  tests/modules/manta/germline/main.nf
  tests/modules/manta/germline/nextflow.config
  tests/modules/manta/germline/test.yml
Labels: Ready for Review

#1182 New module: ichorCNA
  modules/ichorcna/createpon/main.nf
  modules/ichorcna/createpon/meta.yml
  modules/ichorcna/run/main.nf
  modules/ichorcna/run/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ichorcna/createpon/main.nf
  tests/modules/ichorcna/createpon/nextflow.config
  tests/modules/ichorcna/createpon/test.yml
  tests/modules/ichorcna/run/main.nf
  tests/modules/ichorcna/run/nextflow.config
  tests/modules/ichorcna/run/test.yml
Labels: new module, Ready for Review

#1314 add mergemutectstats
  modules/gatk4/mergemutectstats/main.nf
  modules/gatk4/mergemutectstats/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gatk4/mergemutectstats/main.nf
  tests/modules/gatk4/mergemutectstats/nextflow.config
  tests/modules/gatk4/mergemutectstats/test.yml
Labels: Ready for Review

#1323 add module for sistr
  modules/sistr/main.nf
  modules/sistr/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/sistr/main.nf
  tests/modules/sistr/nextflow.config
  tests/modules/sistr/test.yml
Labels: new module, Ready for Review

#1319 add module for legsta
  modules/legsta/main.nf
  modules/legsta/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/legsta/main.nf
  tests/modules/legsta/nextflow.config
  tests/modules/legsta/test.yml
Labels: new module, Ready for Review

#1280 add module for abricate
  modules/abricate/run/main.nf
  modules/abricate/run/meta.yml
  modules/abricate/summary/main.nf
  modules/abricate/summary/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/abricate/run/main.nf
  tests/modules/abricate/run/nextflow.config
  tests/modules/abricate/run/test.yml
  tests/modules/abricate/summary/main.nf
  tests/modules/abricate/summary/nextflow.config
  tests/modules/abricate/summary/test.yml
Labels: new module, Ready for Review

#1315 Picard fixmateinformation
  modules/picard/fixmateinformation/main.nf
  modules/picard/fixmateinformation/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/picard/fixmateinformation/main.nf
  tests/modules/picard/fixmateinformation/nextflow.config
  tests/modules/picard/fixmateinformation/test.yml
Labels: new module, Ready for Review

#1306 Picard cleansam
  modules/picard/cleansam/main.nf
  modules/picard/cleansam/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/picard/cleansam/main.nf
  tests/modules/picard/cleansam/nextflow.config
  tests/modules/picard/cleansam/test.yml
Labels: new module, Ready for Review

#1284 add amrfinderplus module
  modules/amrfinderplus/run/main.nf
  modules/amrfinderplus/run/meta.yml
  modules/amrfinderplus/update/main.nf
  modules/amrfinderplus/update/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/amrfinderplus/run/main.nf
  tests/modules/amrfinderplus/run/nextflow.config
  tests/modules/amrfinderplus/run/test.yml
  tests/modules/amrfinderplus/update/main.nf
  tests/modules/amrfinderplus/update/nextflow.config
  tests/modules/amrfinderplus/update/test.yml
Labels: new module, Ready for Review

#1266 refactored vcfanno
  modules/vcfanno/main.nf
  modules/vcfanno/meta.yml
  tests/config/test_data.config
  tests/modules/vcfanno/main.nf
  tests/modules/vcfanno/nextflow.config
  tests/modules/vcfanno/test.yml
Labels: Ready for Review

#1342 Gatk4 combinegvcfs
  modules/gatk4/combinegvcfs/main.nf
  modules/gatk4/combinegvcfs/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gatk4/combinegvcfs/main.nf
  tests/modules/gatk4/combinegvcfs/nextflow.config
  tests/modules/gatk4/combinegvcfs/test.yml
Labels: new module, Ready for Review

#1339 Faqcs
  modules/faqcs/main.nf
  modules/faqcs/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/faqcs/main.nf
  tests/modules/faqcs/nextflow.config
  tests/modules/faqcs/test.yml
Labels: new module, Ready for Review

#1340 Seqtk seq
  modules/seqtk/seq/main.nf
  modules/seqtk/seq/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/seqtk/seq/main.nf
  tests/modules/seqtk/seq/nextflow.config
  tests/modules/seqtk/seq/test.yml
Labels: new module, Ready for Review

#1346 Gatk4 selectvariants
  modules/gatk4/selectvariants/main.nf
  modules/gatk4/selectvariants/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gatk4/selectvariants/main.nf
  tests/modules/gatk4/selectvariants/nextflow.config
  tests/modules/gatk4/selectvariants/test.yml
Labels: new module, Ready for Review

#1348 Seqkit pair
  modules/seqkit/pair/main.nf
  modules/seqkit/pair/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/seqkit/pair/main.nf
  tests/modules/seqkit/pair/nextflow.config
  tests/modules/seqkit/pair/test.yml
Labels: new module, Ready for Review

#1355 update args & convert to bam
  modules/picard/cleansam/main.nf
  modules/picard/cleansam/meta.yml
  tests/modules/picard/cleansam/test.yml
Labels: update module

#1331 add module for hpsuisero
  modules/hpsuissero/main.nf
  modules/hpsuissero/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/hpsuissero/main.nf
  tests/modules/hpsuissero/nextflow.config
  tests/modules/hpsuissero/test.yml
Labels: new module, Ready for Review

#1329 add module for ssuisero
  modules/ssuissero/main.nf
  modules/ssuissero/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/ssuissero/main.nf
  tests/modules/ssuissero/nextflow.config
  tests/modules/ssuissero/test.yml
Labels: new module, Ready for Review

#1351 Add MAFFT module
  modules/mafft/main.nf
  modules/mafft/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/mafft/main.nf
  tests/modules/mafft/nextflow.config
  tests/modules/mafft/test.yml
Labels: new module, Ready for Review

#1291 bcftools/annotate ready2go
  modules/bcftools/annotate/main.nf
  modules/bcftools/annotate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/bcftools/annotate/main.nf
  tests/modules/bcftools/annotate/nextflow.config
  tests/modules/bcftools/annotate/test.yml
Labels: new module, Ready for Review

#1333 add controlfreec
  modules/controlfreec/main.nf
  modules/controlfreec/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/controlfreec/main.nf
  tests/modules/controlfreec/nextflow.config
  tests/modules/controlfreec/test.yml
Labels: help wanted
