Repository nf-core/modules, pull requests merged in 2022-04, with the labels that each got.

#1472 Fix untar for centrifuge
  modules/centrifuge/main.nf
  modules/centrifuge/meta.yml
  tests/modules/centrifuge/main.nf
Labels: Ready for Review

#1492 feat(homer): Add groseq subworkflow
  subworkflows/nf-core/homer/groseq/main.nf
  subworkflows/nf-core/homer/groseq/meta.yml
  tests/subworkflows/nf-core/homer/groseq/main.nf
  tests/subworkflows/nf-core/homer/groseq/nextflow.config
  tests/subworkflows/nf-core/homer/groseq/test.yml
Labels: new subworkflow

#1491 Refactor adapterremoval
  modules/adapterremoval/main.nf
  modules/adapterremoval/meta.yml
  tests/modules/adapterremoval/test.yml
Labels: Ready for Review

#1493 Update: biobambam/bammarkduplicates2 to v2.0.183
  modules/biobambam/bammarkduplicates2/main.nf
  tests/modules/biobambam/bammarkduplicates2/test.yml
Labels: Ready for Review

#1478 New tool: biobambam/bamsormadup
  modules/biobambam/bamsormadup/main.nf
  modules/biobambam/bamsormadup/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/biobambam/bamsormadup/main.nf
  tests/modules/biobambam/bamsormadup/nextflow.config
  tests/modules/biobambam/bamsormadup/test.yml
Labels: Ready for Review

#1431 Picard liftover vcf
  modules/picard/liftovervcf/main.nf
  modules/picard/liftovervcf/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/picard/liftovervcf/main.nf
  tests/modules/picard/liftovervcf/nextflow.config
  tests/modules/picard/liftovervcf/test.yml
Labels: Ready for Review

#1506 new tool snap-aligner/index
  modules/snapaligner/index/main.nf
  modules/snapaligner/index/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/snapaligner/index/main.nf
  tests/modules/snapaligner/index/nextflow.config
  tests/modules/snapaligner/index/test.yml
Labels: new module, Ready for Review

#1499 new tool: staden_io_lib
  modules/stadeniolib/scramble/main.nf
  modules/stadeniolib/scramble/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/stadeniolib/scramble/main.nf
  tests/modules/stadeniolib/scramble/nextflow.config
  tests/modules/stadeniolib/scramble/test.yml
Labels: new module, Ready for Review

#1505 Tool/crosscheckfingerprints
  modules/picard/crosscheckfingerprints/main.nf
  modules/picard/crosscheckfingerprints/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/picard/crosscheckfingerprints/main.nf
  tests/modules/picard/crosscheckfingerprints/nextflow.config
  tests/modules/picard/crosscheckfingerprints/test.yml
Labels: Ready for Review

#1483 Update dsh-bio to version 2.0.8
  modules/dshbio/exportsegments/main.nf
  modules/dshbio/filterbed/main.nf
  modules/dshbio/filtergff3/main.nf
  modules/dshbio/splitbed/main.nf
  modules/dshbio/splitgff3/main.nf
Labels: Ready for Review

#1513 Add MEGAN/RMA2INFO
  modules/megan/rma2info/main.nf
  modules/megan/rma2info/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/megan/rma2info/main.nf
  tests/modules/megan/rma2info/nextflow.config
  tests/modules/megan/rma2info/test.yml
Labels: Ready for Review

#1509 Tool/snap aligner paired
  modules/snapaligner/paired/main.nf
  modules/snapaligner/paired/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/snapaligner/paired/main.nf
  tests/modules/snapaligner/paired/nextflow.config
  tests/modules/snapaligner/paired/test.yml
Labels: Ready for Review

#1264 fix incorrect yaml formatting.
  modules/allelecounter/meta.yml
Labels: linting

#1498 add module AMPlify
  modules/amplify/predict/main.nf
  modules/amplify/predict/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/amplify/predict/main.nf
  tests/modules/amplify/predict/nextflow.config
  tests/modules/amplify/predict/test.yml
Labels: new module

#1485 Module/bclconvert
  modules/bclconvert/.gitignore
  modules/bclconvert/Dockerfile
  modules/bclconvert/LICENSE
  modules/bclconvert/README.md
  modules/bclconvert/main.nf
  modules/bclconvert/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/bclconvert/main.nf
  tests/modules/bclconvert/nextflow.config
  tests/modules/bclconvert/test.yml
Labels: new module, Ready for Review

#1539 Update samtools view to add input path(index)
  modules/samtools/view/main.nf
  modules/samtools/view/meta.yml
  tests/modules/samtools/view/main.nf
Labels: update module, Ready for Review

#1542 update picard/collecthsmetrics
  modules/picard/collecthsmetrics/main.nf
  modules/picard/collecthsmetrics/meta.yml
  tests/modules/picard/collecthsmetrics/main.nf
  tests/modules/picard/collecthsmetrics/test.yml
Labels: update module, Ready for Review

#1533 Tool/elprep split
  modules/elprep/split/main.nf
  modules/elprep/split/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/elprep/split/main.nf
  tests/modules/elprep/split/nextflow.config
  tests/modules/elprep/split/test.yml
Labels: new module, Ready for Review

#1524 New module: elprep filter
  modules/elprep/filter/main.nf
  modules/elprep/filter/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/elprep/filter/main.nf
  tests/modules/elprep/filter/nextflow.config
  tests/modules/elprep/filter/test.yml
Labels: new module, Ready for Review

#1545 Kaiju2table module
  modules/kaiju/kaiju2table/main.nf
  modules/kaiju/kaiju2table/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/kaiju/kaiju2table/main.nf
  tests/modules/kaiju/kaiju2table/nextflow.config
  tests/modules/kaiju/kaiju2table/test.yml
Labels: new module, Ready for Review

#1551 elprep/split: fix output glob
  modules/elprep/split/main.nf
  tests/modules/elprep/split/test.yml
Labels: bug, update module

#1552 elprep/filter: fix output glob
  modules/elprep/filter/main.nf
  tests/modules/elprep/filter/test.yml
Labels: bug, update module

#1558 Add missing bacteroides_fragilis genome.gbff.gz
  tests/config/test_data.config
Labels: enhancement, Ready for Review

#1532 new module: GAMMA
  modules/gamma/main.nf
  modules/gamma/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gamma/main.nf
  tests/modules/gamma/nextflow.config
  tests/modules/gamma/test.yml
Labels: new module, Ready for Review

#1576 Changed tbi as optional output in GATK4 HaplotypeCaller
  modules/gatk4/haplotypecaller/main.nf
Labels: Ready for Review

#1579 csi output in TABIX
  modules/tabix/tabix/main.nf
  modules/tabix/tabix/meta.yml
  tests/modules/tabix/tabix/main.nf
  tests/modules/tabix/tabix/nextflow.config
  tests/modules/tabix/tabix/test.yml
Labels: Ready for Review

#1578 picard CollectWgsMetrics: update to new cli args
  modules/picard/collectwgsmetrics/main.nf
  tests/modules/picard/collectwgsmetrics/main.nf
Labels: update module, Ready for Review

#1541 New subworkflow: bam_qc_picard
  subworkflows/nf-core/bam_qc_picard/main.nf
  subworkflows/nf-core/bam_qc_picard/meta.yml
  tests/subworkflows/nf-core/bam_qc_picard/main.nf
  tests/subworkflows/nf-core/bam_qc_picard/nextflow.config
  tests/subworkflows/nf-core/bam_qc_picard/test.yml
Labels: Ready for Review, new subworkflow

#1534 Tool/elprep merge
  modules/elprep/merge/main.nf
  modules/elprep/merge/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/elprep/merge/main.nf
  tests/modules/elprep/merge/nextflow.config
  tests/modules/elprep/merge/test.yml
Labels: new module, Ready for Review

#1535 Update bamtools split
  modules/bamtools/split/main.nf
  modules/bamtools/split/meta.yml
  tests/modules/bamtools/split/main.nf
  tests/modules/bamtools/split/test.yml
Labels: enhancement, update module, Ready for Review
