Repository nf-core/modules, pull requests merged in 2022-01, with the labels that each got.

#1191 Fix modules warned or failed with nf-core modules lint
  modules/ataqv/ataqv/main.nf
  modules/bcftools/index/main.nf
  modules/bowtie2/build/main.nf
  modules/cutadapt/main.nf
  modules/fgbio/fastqtobam/main.nf
  modules/gtdbtk/classifywf/main.nf
  modules/idr/main.nf
  modules/jupyternotebook/main.nf
  modules/krona/kronadb/main.nf
  modules/malt/run/main.nf
  modules/paraclu/main.nf
  modules/pirate/main.nf
  modules/porechop/main.nf
  modules/rmarkdownnotebook/main.nf
  modules/spatyper/main.nf
  tests/config/pytest_modules.yml
Labels: Ready for Review

#1193 add module for mash dist
  modules/mash/dist/main.nf
  modules/mash/dist/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/mash/dist/main.nf
  tests/modules/mash/dist/nextflow.config
  tests/modules/mash/dist/test.yml
Labels: new module, Ready for Review

#1169 Bcftools sort new syntax
  modules/bcftools/sort/main.nf
  modules/bcftools/sort/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/bcftools/sort/main.nf
  tests/modules/bcftools/sort/nextflow.config
  tests/modules/bcftools/sort/test.yml
Labels: new module, Ready for Review

#1196 Editing the CAT/CAT module to handle single files
  modules/cat/cat/main.nf
  tests/modules/cat/cat/main.nf
  tests/modules/cat/cat/test.yml
Labels: Ready for Review

#1198 Bump software versions for viralrecon modules
  modules/bcftools/concat/main.nf
  modules/bcftools/consensus/main.nf
  modules/bcftools/filter/main.nf
  modules/bcftools/index/main.nf
  modules/bcftools/isec/main.nf
  modules/bcftools/merge/main.nf
  modules/bcftools/mpileup/main.nf
  modules/bcftools/norm/main.nf
  modules/bcftools/query/main.nf
  modules/bcftools/reheader/main.nf
  modules/bcftools/stats/main.nf
  modules/bcftools/view/main.nf
  modules/bowtie2/align/main.nf
  modules/fastp/main.nf
  modules/minia/main.nf
  modules/nanoplot/main.nf
  modules/pangolin/main.nf
  modules/picard/collecthsmetrics/main.nf
  modules/picard/collectmultiplemetrics/main.nf
  modules/picard/collectwgsmetrics/main.nf
  modules/picard/filtersamreads/main.nf
  modules/picard/markduplicates/main.nf
  modules/picard/mergesamfiles/main.nf
  modules/picard/sortsam/main.nf
  modules/samtools/ampliconclip/main.nf
  modules/samtools/bam2fq/main.nf
  modules/samtools/depth/main.nf
  modules/samtools/faidx/main.nf
  modules/samtools/fastq/main.nf
  modules/samtools/fixmate/main.nf
  modules/samtools/flagstat/main.nf
  modules/samtools/idxstats/main.nf
  modules/samtools/index/main.nf
  modules/samtools/merge/main.nf
  modules/samtools/sort/main.nf
  modules/samtools/stats/main.nf
  modules/samtools/view/main.nf
  tests/modules/bcftools/concat/test.yml
  tests/modules/bcftools/mpileup/test.yml
  tests/modules/bcftools/stats/test.yml
  tests/modules/bowtie2/align/main.nf
  tests/modules/fastp/test.yml
  tests/modules/pangolin/test.yml
  tests/modules/samtools/stats/test.yml
Labels: Ready for Review

#1170 Add pangenome test data set keys
  tests/config/test_data.config
Labels: documentation, enhancement, tests, Ready for Review

#1207 Update dsh-bio to version 2.0.7, add support for compressed GFA 1.0 format
  modules/dshbio/exportsegments/main.nf
  modules/dshbio/exportsegments/meta.yml
  modules/dshbio/filterbed/main.nf
  modules/dshbio/filtergff3/main.nf
  modules/dshbio/splitbed/main.nf
  modules/dshbio/splitgff3/main.nf
  tests/config/test_data.config
  tests/modules/dshbio/exportsegments/main.nf
  tests/modules/dshbio/exportsegments/test.yml
Labels: Ready for Review

#572 module: deepvariant
  modules/deepvariant/main.nf
  modules/deepvariant/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/deepvariant/main.nf
  tests/modules/deepvariant/nextflow.config
  tests/modules/deepvariant/test.yml
Labels: help wanted, new module, WIP

#1216 Bump chromap index version
  modules/chromap/index/main.nf
  tests/modules/chromap/index/test.yml
Labels: update module, Ready for Review

#1204 New module/vcfanno
  modules/vcfanno/main.nf
  modules/vcfanno/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/vcfanno/main.nf
  tests/modules/vcfanno/nextflow.config
  tests/modules/vcfanno/test.yml
Labels: Ready for Review

#1223 Bump version 0.1.5 to chromap/chromap
  modules/chromap/chromap/main.nf
  tests/modules/chromap/chromap/test.yml
  tests/modules/chromap/index/test.yml
Labels: update module, Ready for Review

#1225 ci: Remove second python setup call
  .github/workflows/pytest-workflow.yml
Labels: tests

#1180 Peddy update: delete png and add stub
  modules/peddy/main.nf
Labels: update module, Ready for Review

#1238 Update mergebam syntax and sample specific unmapped channel
  modules/gatk4/mergebamalignment/main.nf
  tests/modules/gatk4/mergebamalignment/main.nf
Labels: update module, Ready for Review

#1200 Allow compressed input for prodigal
  modules/prodigal/main.nf
  modules/prodigal/meta.yml
Labels: Ready for Review

#1242 Fix for version file output check when performing an expected error test
  tests/test_versions_yml.py
Labels: bug

#1219 New module: `bamtools/convert`
  modules/bamtools/convert/main.nf
  modules/bamtools/convert/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/bamtools/convert/main.nf
  tests/modules/bamtools/convert/nextflow.config
  tests/modules/bamtools/convert/test.yml
Labels: new module, Ready for Review
