Repository nf-core/modules, pull requests merged in 2022-09, with the labels that each got.

#1985 Creation of Glimpse Chunk
  modules/glimpse/chunk/main.nf
  modules/glimpse/chunk/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/glimpse/chunk/main.nf
  tests/modules/glimpse/chunk/nextflow.config
  tests/modules/glimpse/chunk/test.yml
Labels: new module, Ready for Review

#2000 [update] bump Bakta to 1.5.0
  modules/bakta/main.nf
Labels: update module, Ready for Review

#2014 new module: deepbgc/pipeline
  modules/deepbgc/download/main.nf
  modules/deepbgc/pipeline/main.nf
  modules/deepbgc/pipeline/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/deepbgc/pipeline/main.nf
  tests/modules/deepbgc/pipeline/nextflow.config
  tests/modules/deepbgc/pipeline/test.yml
Labels: new module

#2003 add module for pasty
  modules/pasty/main.nf
  modules/pasty/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/pasty/main.nf
  tests/modules/pasty/nextflow.config
  tests/modules/pasty/test.yml
Labels: new module, Ready for Review

#2005 add module for pbptyper
  modules/pbptyper/main.nf
  modules/pbptyper/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/pbptyper/main.nf
  tests/modules/pbptyper/nextflow.config
  tests/modules/pbptyper/test.yml
Labels: new module, Ready for Review

#1989 fix(pints): Remove update check
  modules/pints/caller/main.nf
Labels: enhancement

#1855 add snippy/core module
  modules/snippy/core/main.nf
  modules/snippy/core/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/snippy/core/main.nf
  tests/modules/snippy/core/nextflow.config
  tests/modules/snippy/core/test.yml
Labels: new module, Ready for Review

#1934 Added the meta map to minimap2/index
  modules/minimap2/index/main.nf
  modules/minimap2/index/meta.yml
  tests/modules/minimap2/index/main.nf
Labels: Ready for Review

#1935 Added the optional .gzi output of "samtools faidx"
  modules/samtools/faidx/main.nf
  modules/samtools/faidx/meta.yml
  tests/config/test_data.config
  tests/modules/samtools/faidx/main.nf
  tests/modules/samtools/faidx/test.yml
Labels: Ready for Review

#1956 New module: fasta_windows
  modules/fastawindows/main.nf
  modules/fastawindows/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/fastawindows/main.nf
  tests/modules/fastawindows/nextflow.config
  tests/modules/fastawindows/test.yml
Labels: Ready for Review

#2046 Upgraded getchromsizes to support meta and output the gzi index
  modules/custom/getchromsizes/main.nf
  modules/custom/getchromsizes/meta.yml
  tests/modules/custom/getchromsizes/main.nf
  tests/modules/custom/getchromsizes/test.yml
Labels: Ready for Review

#2064 [samtools] add optional csi output
  modules/samtools/merge/main.nf
  modules/samtools/merge/meta.yml
  modules/samtools/sort/main.nf
  modules/samtools/sort/meta.yml
  modules/samtools/view/main.nf
  modules/samtools/view/meta.yml
Labels: Ready for Review

#2078 samtools collate module
  modules/samtools/collate/main.nf
  modules/samtools/collate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/samtools/collate/main.nf
  tests/modules/samtools/collate/nextflow.config
  tests/modules/samtools/collate/test.yml
Labels: new module

#2087 samtools markdup module
  modules/samtools/markdup/main.nf
  modules/samtools/markdup/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/samtools/markdup/main.nf
  tests/modules/samtools/markdup/nextflow.config
  tests/modules/samtools/markdup/test.yml
Labels: new module

#2096 Update samtools view
  modules/samtools/view/main.nf
  modules/samtools/view/meta.yml
  tests/modules/samtools/view/main.nf
  tests/modules/samtools/view/nextflow.config
  tests/modules/samtools/view/test.yml
Labels: enhancement, update module

#2099 2012 bug related to species input in goattaxonsearch module
  modules/goat/taxonsearch/main.nf
  tests/modules/goat/taxonsearch/main.nf
  tests/modules/goat/taxonsearch/test.yml
Labels: bug, Ready for Review

#2049 Make stringtie/merge arguments configurable
  modules/stringtie/merge/main.nf
Labels: enhancement, Ready for Review

#1816 add module for seroba
  modules/seroba/run/main.nf
  modules/seroba/run/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/seroba/run/main.nf
  tests/modules/seroba/run/nextflow.config
  tests/modules/seroba/run/test.yml
Labels: new module, Ready for Review

#2045 Updated dumpsoftwareversions.py to match the pipeline template
  modules/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
  tests/modules/custom/dumpsoftwareversions/main.nf
Labels: Ready for Review

#2036 Added an output channel for the gzi index
  modules/tabix/bgzip/main.nf
  modules/tabix/bgzip/meta.yml
  tests/modules/tabix/bgzip/main.nf
  tests/modules/tabix/bgzip/nextflow.config
  tests/modules/tabix/bgzip/test.yml
Labels: Ready for Review

#2108 Fix broken Quast module and bump MultiQC version in dumpsoftwareversions
  modules/custom/dumpsoftwareversions/main.nf
  modules/qualimap/rnaseq/main.nf
  tests/config/pytest_modules.yml
  tests/config/pytest_modules_test.yml
Labels: Ready for Review

#1307 [bug] pin bioperl version in Prokka module
  modules/prokka/main.nf
Labels: bug, Ready for Review

#1621 Adding stubs to PicardLiftovervcf, GATK4_mergevcfs and filterMutectCalls
  modules/gatk4/filtermutectcalls/main.nf
  modules/gatk4/mergevcfs/main.nf
  modules/picard/liftovervcf/main.nf
  tests/modules/gatk4/filtermutectcalls/main.nf
  tests/modules/gatk4/filtermutectcalls/test.yml
  tests/modules/gatk4/mergevcfs/main.nf
  tests/modules/gatk4/mergevcfs/test.yml
  tests/modules/picard/liftovervcf/main.nf
  tests/modules/picard/liftovervcf/test.yml
Labels: enhancement, Ready for Review

#1149 Adding new module gfaffix
  modules/gfaffix/main.nf
  modules/gfaffix/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gfaffix/main.nf
  tests/modules/gfaffix/nextflow.config
  tests/modules/gfaffix/test.yml
Labels: new module

#1916 New Module: endorspy
  modules/endorspy/main.nf
  modules/endorspy/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/endorspy/main.nf
  tests/modules/endorspy/nextflow.config
  tests/modules/endorspy/test.yml
Labels: new module

#2115 add qname feature to samtools/view
  modules/samtools/view/main.nf
  modules/samtools/view/meta.yml
  tests/modules/samtools/view/main.nf
  tests/modules/samtools/view/nextflow.config
  tests/modules/samtools/view/test.yml
Labels: enhancement, update module, Ready for Review

#2111 add stub and the option to compress output for vep
  modules/ensemblvep/main.nf
  tests/modules/ensemblvep/main.nf
  tests/modules/ensemblvep/nextflow.config
  tests/modules/ensemblvep/test.yml
Labels: update module

#2097 [POC] Get subworkflows working again - bam_stats_samtools
  subworkflows/nf-core/bam_stats_samtools/main.nf
  subworkflows/nf-core/bam_stats_samtools/meta.yml
  subworkflows/nf-core/bam_stats_samtools/nextflow.config
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/bam_stats_samtools/main.nf
  tests/subworkflows/nf-core/bam_stats_samtools/nextflow.config
  tests/subworkflows/nf-core/bam_stats_samtools/test.yml
Labels: update subworkflow

#2128 samtools fasta module
  modules/samtools/fasta/main.nf
  modules/samtools/fasta/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/samtools/fasta/main.nf
  tests/modules/samtools/fasta/nextflow.config
  tests/modules/samtools/fasta/test.yml
Labels: enhancement, new module, Ready for Review

#2136 Explicitly name the output files to avoid the gzi index being flown through the `output` channel
  modules/tabix/bgzip/main.nf
Labels: bug, Ready for Review

#2134 feat added vcflib/vcfbreakmulti module
  modules/vcflib/vcfbreakmulti/main.nf
  modules/vcflib/vcfbreakmulti/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/vcflib/vcfbreakmulti/main.nf
  tests/modules/vcflib/vcfbreakmulti/nextflow.config
  tests/modules/vcflib/vcfbreakmulti/test.yml
Labels: new module, Ready for Review

#2139 Bump HISAT2 version to 2.2.1 in all modules
  modules/hisat2/align/main.nf
  modules/hisat2/build/main.nf
  modules/hisat2/extractsplicesites/main.nf
  tests/modules/hisat2/align/test.yml
  tests/modules/hisat2/build_test/test.yml
  tests/modules/hisat2/extractsplicesites/test.yml
Labels: Ready for Review

#2033 add FCS adaptor
  modules/fcs/fcsadaptor/main.nf
  modules/fcs/fcsadaptor/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/fcs/fcsadaptor/main.nf
  tests/modules/fcs/fcsadaptor/nextflow.config
  tests/modules/fcs/fcsadaptor/test.yml
Labels: new module, Ready for Review
