Repository nf-core/modules, pull requests merged in 2022-05, with the labels that each got.

#1574 new module: srst2/srst2
  modules/srst2/srst2/main.nf
  modules/srst2/srst2/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/srst2/srst2/main.nf
  tests/modules/srst2/srst2/nextflow.config
  tests/modules/srst2/srst2/test.yml
Labels: new module, Ready for Review

#1596 feat added stub to modules gatk4_mergebamalignment_mutect2_revertsam_samtofastq, samtools_view
  modules/gatk4/mergebamalignment/main.nf
  modules/gatk4/mutect2/main.nf
  modules/gatk4/revertsam/main.nf
  modules/gatk4/samtofastq/main.nf
  modules/samtools/view/main.nf
  tests/modules/gatk4/mergebamalignment/main.nf
  tests/modules/gatk4/mergebamalignment/test.yml
  tests/modules/gatk4/mutect2/main.nf
  tests/modules/gatk4/mutect2/test.yml
  tests/modules/gatk4/revertsam/main.nf
  tests/modules/gatk4/revertsam/test.yml
  tests/modules/gatk4/samtofastq/main.nf
  tests/modules/gatk4/samtofastq/test.yml
  tests/modules/samtools/view/main.nf
  tests/modules/samtools/view/test.yml
Labels: update module, Ready for Review

#1604 feat: add module for slimfastq
  modules/slimfastq/main.nf
  modules/slimfastq/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/slimfastq/main.nf
  tests/modules/slimfastq/nextflow.config
  tests/modules/slimfastq/test.yml
Labels: Ready for Review

#1548 add module for shigatyper
  modules/shigatyper/main.nf
  modules/shigatyper/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/shigatyper/main.nf
  tests/modules/shigatyper/nextflow.config
  tests/modules/shigatyper/test.yml
Labels: new module, Ready for Review

#1607 Bowtie2 - Added support for large indexes and improved error reporting
  modules/bowtie2/align/main.nf
  tests/modules/bowtie2/align/main.nf
  tests/modules/bowtie2/align/nextflow.config
  tests/modules/bowtie2/align/test.yml
Labels: enhancement, Ready for Review

#1239 Busco
  modules/busco/main.nf
  modules/busco/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/busco/main.nf
  tests/modules/busco/nextflow.config
  tests/modules/busco/test.yml
Labels: new module, Ready for Review

#1622 Update snapaligner: merge modes into one
  modules/snapaligner/align/main.nf
  modules/snapaligner/align/meta.yml
  modules/snapaligner/single/main.nf
  modules/snapaligner/single/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/snapaligner/align/main.nf
  tests/modules/snapaligner/align/nextflow.config
  tests/modules/snapaligner/align/test.yml
  tests/modules/snapaligner/paired/main.nf
  tests/modules/snapaligner/paired/test.yml
  tests/modules/snapaligner/single/main.nf
  tests/modules/snapaligner/single/nextflow.config
  tests/modules/snapaligner/single/test.yml
Labels: update module, Ready for Review

#1627 Use a template to add retrying to prefetch
  modules/sratools/prefetch/main.nf
  modules/sratools/prefetch/templates/retry_with_backoff.sh
Labels: Ready for Review

#1623 fix added correct entry workflow in test.yml
  tests/modules/gatk4/mergebamalignment/main.nf
  tests/modules/gatk4/mergebamalignment/test.yml
  tests/modules/gatk4/mutect2/main.nf
  tests/modules/gatk4/mutect2/test.yml
  tests/modules/gatk4/revertsam/main.nf
  tests/modules/gatk4/revertsam/test.yml
  tests/modules/gatk4/samtofastq/main.nf
  tests/modules/gatk4/samtofastq/test.yml
  tests/modules/samtools/view/main.nf
  tests/modules/samtools/view/test.yml
Labels: Ready for Review

#1626 Meryl Count
  modules/meryl/count/main.nf
  modules/meryl/count/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/meryl/count/main.nf
  tests/modules/meryl/count/nextflow.config
  tests/modules/meryl/count/test.yml
Labels: Ready for Review

#1636 Add meryl histogram
  modules/meryl/histogram/main.nf
  modules/meryl/histogram/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/meryl/histogram/main.nf
  tests/modules/meryl/histogram/nextflow.config
  tests/modules/meryl/histogram/test.yml
Labels: Ready for Review

#1634 Add meryl unionsum
  modules/meryl/unionsum/main.nf
  modules/meryl/unionsum/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/meryl/unionsum/main.nf
  tests/modules/meryl/unionsum/nextflow.config
  tests/modules/meryl/unionsum/test.yml
Labels: Ready for Review

#1638 Udate arriba
  modules/arriba/main.nf
  modules/arriba/meta.yml
  tests/modules/arriba/main.nf
  tests/modules/arriba/test.yml
Labels: Ready for Review

#1631 Refactor prefetch
  modules/sratools/prefetch/main.nf
  modules/sratools/prefetch/meta.yml
  modules/sratools/prefetch/templates/retry_with_backoff.sh
  tests/config/test_data.config
  tests/modules/sratools/prefetch/main.nf
  tests/modules/sratools/prefetch/test.yml
Labels: Ready for Review

#1632 Refactor fasterq dump
  modules/sratools/fasterqdump/main.nf
  modules/sratools/fasterqdump/meta.yml
  tests/modules/sratools/fasterqdump/main.nf
  tests/modules/sratools/fasterqdump/test.yml
Labels: Ready for Review

#1630 feat: add module that verifies NCBI settings
  modules/custom/sratoolsncbisettings/main.nf
  modules/custom/sratoolsncbisettings/meta.yml
  modules/custom/sratoolsncbisettings/templates/detect_ncbi_settings.sh
  tests/config/pytest_modules.yml
  tests/modules/custom/sratoolsncbisettings/main.nf
  tests/modules/custom/sratoolsncbisettings/nextflow.config
  tests/modules/custom/sratoolsncbisettings/nextflow_mount.config
  tests/modules/custom/sratoolsncbisettings/test.yml
Labels: Ready for Review

#1645 bowtie2: remove code duplication
  modules/bowtie2/align/main.nf
  tests/modules/bowtie2/align/test.yml
Labels: Ready for Review

#1641 Genomescope2 module
  modules/genomescope2/main.nf
  modules/genomescope2/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/genomescope2/main.nf
  tests/modules/genomescope2/nextflow.config
  tests/modules/genomescope2/test.yml
Labels: Ready for Review

#1653 Bowtie2 test fixes
  modules/bowtie2/align/main.nf
  tests/modules/bowtie2/align/main.nf
  tests/modules/bowtie2/align/nextflow.config
  tests/modules/bowtie2/align/test.yml
Labels: Ready for Review

#1660 Bowtie2: add sort option
  modules/bowtie2/align/main.nf
  modules/bowtie2/align/meta.yml
  tests/modules/bowtie2/align/main.nf
  tests/modules/bowtie2/align/test.yml
Labels: Ready for Review

#1602 Add AntiSMASH-lite
  modules/antismash/antismashlite/main.nf
  modules/antismash/antismashlite/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/antismash/antismashlite/main.nf
  tests/modules/antismash/antismashlite/nextflow.config
  tests/modules/antismash/antismashlite/test.yml
Labels: new module

#1682 Add mash screen
  modules/mash/screen/main.nf
  modules/mash/screen/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/mash/screen/main.nf
  tests/modules/mash/screen/nextflow.config
  tests/modules/mash/screen/test.yml
Labels: Ready for Review

#1683 picard: make reference sequence optional
  modules/picard/collecthsmetrics/main.nf
  modules/picard/collectmultiplemetrics/main.nf
  modules/picard/collectwgsmetrics/main.nf
  tests/modules/picard/collecthsmetrics/main.nf
  tests/modules/picard/collecthsmetrics/test.yml
  tests/modules/picard/collectmultiplemetrics/main.nf
  tests/modules/picard/collectmultiplemetrics/test.yml
  tests/modules/picard/collectwgsmetrics/test.yml
Labels: Ready for Review

#1689 Update umitools/dedup module to make --output-stats optional
  modules/umitools/dedup/main.nf
  modules/umitools/dedup/meta.yml
  tests/modules/umitools/dedup/main.nf
  tests/modules/umitools/dedup/nextflow.config
  tests/modules/umitools/dedup/test.yml
Labels: Ready for Review

#1693 mosdepth: cram compatiblility
  modules/mosdepth/main.nf
  modules/mosdepth/meta.yml
  tests/modules/mosdepth/main.nf
  tests/modules/mosdepth/nextflow.config
  tests/modules/mosdepth/test.yml
Labels: Ready for Review

#1620 Add module kat hist
  modules/kat/hist/main.nf
  modules/kat/hist/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/kat/hist/main.nf
  tests/modules/kat/hist/nextflow.config
  tests/modules/kat/hist/test.yml
Labels: Ready for Review

#1696 adding upzip to gamma/gamma
  modules/gamma/gamma/main.nf
  modules/gamma/gamma/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/gamma/gamma/main.nf
  tests/modules/gamma/gamma/nextflow.config
  tests/modules/gamma/gamma/test.yml
  tests/modules/gamma/main.nf
  tests/modules/gamma/test.yml
Labels: update module, Ready for Review

#1698 Patch mash screen
  modules/mash/screen/main.nf
  modules/mash/screen/meta.yml
  tests/modules/mash/screen/main.nf
  tests/modules/mash/screen/test.yml
Labels: Ready for Review

#1701 Mosdepth: add all remaining outputs
  modules/mosdepth/main.nf
  modules/mosdepth/meta.yml
  tests/modules/mosdepth/main.nf
  tests/modules/mosdepth/nextflow.config
  tests/modules/mosdepth/test.yml
Labels: Ready for Review

#1708 👌 IMPROVE: Remove last TODO
  modules/bamtools/convert/meta.yml
Labels: Ready for Review
