Repository nf-core/modules, pull requests merged in 2022-12, with the labels that each got.

#2601 Update whamg again
  modules/nf-core/whamg/main.nf
  modules/nf-core/whamg/meta.yml
  tests/modules/nf-core/whamg/test.yml
Labels: update module, Ready for Review

#2469 Update LAST to latest version and refresh test YAML files - take 2
  modules/nf-core/last/dotplot/main.nf
  modules/nf-core/last/lastal/main.nf
  modules/nf-core/last/lastdb/main.nf
  modules/nf-core/last/mafconvert/main.nf
  modules/nf-core/last/mafswap/main.nf
  modules/nf-core/last/postmask/main.nf
  modules/nf-core/last/split/main.nf
  modules/nf-core/last/train/main.nf
  tests/modules/nf-core/last/lastal/test.yml
  tests/modules/nf-core/last/lastdb/test.yml
  tests/modules/nf-core/last/mafconvert/test.yml
  tests/modules/nf-core/last/mafswap/test.yml
  tests/modules/nf-core/last/postmask/test.yml
  tests/modules/nf-core/last/split/test.yml
  tests/modules/nf-core/last/train/test.yml
Labels: update module, Ready for Review

#2592 New module: picard/bedtointervallist
  modules/nf-core/picard/bedtointervallist/main.nf
  modules/nf-core/picard/bedtointervallist/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/picard/bedtointervallist/main.nf
  tests/modules/nf-core/picard/bedtointervallist/nextflow.config
  tests/modules/nf-core/picard/bedtointervallist/test.yml
Labels: new module, Ready for Review

#2605 Update: DeepBGC replace output directory with prefix
  modules/nf-core/deepbgc/pipeline/main.nf
  tests/modules/nf-core/deepbgc/pipeline/test.yml
Labels: Ready for Review

#2591 Update BAKTA: restructure to allow subcommands and add BAKTA/BAKTADBDOWNLOAD
  modules/nf-core/bakta/bakta/main.nf
  modules/nf-core/bakta/bakta/meta.yml
  modules/nf-core/bakta/baktadbdownload/main.nf
  modules/nf-core/bakta/baktadbdownload/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bakta/bakta/main.nf
  tests/modules/nf-core/bakta/bakta/nextflow.config
  tests/modules/nf-core/bakta/bakta/test.yml
  tests/modules/nf-core/bakta/baktadbdownload/main.nf
  tests/modules/nf-core/bakta/baktadbdownload/nextflow.config
  tests/modules/nf-core/bakta/baktadbdownload/test.yml
Labels: Ready for Review

#2626 Fixed the layout of the dictionary
  tests/config/test_data.config
Labels: Ready for Review

#2603 Add tabular to GCT module for GSEA
  modules/nf-core/custom/tabulartogseagct/main.nf
  modules/nf-core/custom/tabulartogseagct/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/custom/tabulartogseagct/main.nf
  tests/modules/nf-core/custom/tabulartogseagct/nextflow.config
  tests/modules/nf-core/custom/tabulartogseagct/test.yml
Labels: Ready for Review

#2600 New module mmseqs tsv2exprofiledb
  modules/nf-core/mmseqs/tsv2exprofiledb/main.nf
  modules/nf-core/mmseqs/tsv2exprofiledb/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/mmseqs/tsv2exprofiledb/main.nf
  tests/modules/nf-core/mmseqs/tsv2exprofiledb/nextflow.config
  tests/modules/nf-core/mmseqs/tsv2exprofiledb/test.yml
Labels: new module

#2606 Add custom/tabulartogseacls
  modules/nf-core/custom/tabulartogseacls/main.nf
  modules/nf-core/custom/tabulartogseacls/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/custom/tabulartogseacls/main.nf
  tests/modules/nf-core/custom/tabulartogseacls/nextflow.config
  tests/modules/nf-core/custom/tabulartogseacls/test.yml
Labels: Ready for Review

#2617 Add GSEA module
  modules/nf-core/gsea/gsea/main.nf
  modules/nf-core/gsea/gsea/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/gsea/gsea/main.nf
  tests/modules/nf-core/gsea/gsea/nextflow.config
  tests/modules/nf-core/gsea/gsea/test.yml
Labels: Ready for Review

#2625 Newmodule salsa2
  modules/nf-core/salsa2/main.nf
  modules/nf-core/salsa2/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/salsa2/main.nf
  tests/modules/nf-core/salsa2/nextflow.config
  tests/modules/nf-core/salsa2/test.yml
Labels: new module, Ready for Review

#2638 new subworkflow vcf_stats_somalier
  subworkflows/nf-core/vcf_extract_relate_somalier/main.nf
  subworkflows/nf-core/vcf_extract_relate_somalier/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/vcf_extract_relate_somalier/main.nf
  tests/subworkflows/nf-core/vcf_extract_relate_somalier/nextflow.config
  tests/subworkflows/nf-core/vcf_extract_relate_somalier/test.yml
Labels: Ready for Review, new subworkflow

#2642 update vcf_extract_relate_somalier
  subworkflows/nf-core/vcf_extract_relate_somalier/main.nf
  tests/subworkflows/nf-core/vcf_extract_relate_somalier/main.nf
  tests/subworkflows/nf-core/vcf_extract_relate_somalier/test.yml
Labels: Ready for Review, update subworkflow

#2643 add stubs to some modules
  modules/nf-core/bcftools/convert/main.nf
  modules/nf-core/bcftools/filter/main.nf
  modules/nf-core/bcftools/sort/main.nf
  modules/nf-core/bcftools/stats/main.nf
  modules/nf-core/gatk4/calibratedragstrmodel/main.nf
  modules/nf-core/gatk4/composestrtablefile/main.nf
  modules/nf-core/gatk4/createsequencedictionary/main.nf
  modules/nf-core/gatk4/genomicsdbimport/main.nf
  modules/nf-core/gatk4/genotypegvcfs/main.nf
  modules/nf-core/gatk4/haplotypecaller/main.nf
  modules/nf-core/gatk4/reblockgvcf/main.nf
  modules/nf-core/gawk/main.nf
  modules/nf-core/somalier/extract/main.nf
  modules/nf-core/somalier/relate/main.nf
  modules/nf-core/tabix/bgzip/main.nf
  modules/nf-core/vcf2db/main.nf
Labels: update module, Ready for Review

#2543 New module: smncopynumbercaller
  modules/nf-core/smncopynumbercaller/main.nf
  modules/nf-core/smncopynumbercaller/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/smncopynumbercaller/main.nf
  tests/modules/nf-core/smncopynumbercaller/nextflow.config
  tests/modules/nf-core/smncopynumbercaller/test.yml
Labels: new module, Ready for Review

#2624 Add Trinity module
  modules/nf-core/trinity/main.nf
  modules/nf-core/trinity/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/trinity/main.nf
  tests/modules/nf-core/trinity/nextflow.config
  tests/modules/nf-core/trinity/test.yml
Labels: new module

#2644 Fix stub for gatk4/reblockgvcf and gatk4/genomicsdbimport
  modules/nf-core/gatk4/genomicsdbimport/main.nf
  modules/nf-core/gatk4/reblockgvcf/main.nf
Labels: update module, Ready for Review

#2539 Add stubs for nf-core/raredisease modules
  modules/nf-core/gatk4/annotateintervals/main.nf
  modules/nf-core/gatk4/collectreadcounts/main.nf
  modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
  tests/modules/nf-core/gatk4/annotateintervals/test.yml
  tests/modules/nf-core/gatk4/collectreadcounts/test.yml
  tests/modules/nf-core/gatk4/determinegermlinecontigploidy/test.yml
Labels: enhancement, update module, Ready for Review

#2673 samtools_fastq update
  modules/nf-core/samtools/fastq/main.nf
  modules/nf-core/samtools/fastq/meta.yml
  tests/modules/nf-core/samtools/fastq/main.nf
  tests/modules/nf-core/samtools/fastq/test.yml
Labels: update module, Ready for Review

#2672 samtools_fasta update
  modules/nf-core/samtools/fasta/main.nf
  modules/nf-core/samtools/fasta/meta.yml
  tests/modules/nf-core/samtools/fasta/main.nf
  tests/modules/nf-core/samtools/fasta/test.yml
Labels: update module, Ready for Review

#2682 update bcftools reheader
  modules/nf-core/bcftools/reheader/main.nf
  modules/nf-core/bcftools/reheader/meta.yml
  tests/modules/nf-core/bcftools/reheader/main.nf
Labels: update module, Ready for Review

#2681 Add Subsample to Infer strandedness
  subworkflows/nf-core/fastq_subsample_fq_salmon/main.nf
  subworkflows/nf-core/fastq_subsample_fq_salmon/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/fastq_subsample_fq_salmon/main.nf
  tests/subworkflows/nf-core/fastq_subsample_fq_salmon/nextflow.config
  tests/subworkflows/nf-core/fastq_subsample_fq_salmon/test.yml
Labels: new subworkflow

#2688 Update ANTISMASH to 6.1.1 and enable_conda replacement
  modules/nf-core/antismash/antismashlite/main.nf
  modules/nf-core/antismash/antismashlitedownloaddatabases/main.nf
  modules/nf-core/antismash/antismashlitedownloaddatabases/meta.yml
  tests/modules/nf-core/antismash/antismashlite/main.nf
  tests/modules/nf-core/antismash/antismashlite/test.yml
  tests/modules/nf-core/antismash/antismashlitedownloaddatabases/main.nf
  tests/modules/nf-core/antismash/antismashlitedownloaddatabases/test.yml
Labels: update module

#2677 add module picard/collectrnaseqmetrics
  modules/nf-core/picard/collectrnaseqmetrics/main.nf
  modules/nf-core/picard/collectrnaseqmetrics/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/picard/collectrnaseqmetrics/main.nf
  tests/modules/nf-core/picard/collectrnaseqmetrics/nextflow.config
  tests/modules/nf-core/picard/collectrnaseqmetrics/test.yml
Labels: new module

#2690 set jasmine label to process_single
  modules/nf-core/jasminesv/main.nf
Labels: update module, Ready for Review
