Repository nf-core/modules, pull requests merged in 2022-11, with the labels that each got.

#2402 Adding module sourmash/compare
  modules/nf-core/sourmash/compare/main.nf
  modules/nf-core/sourmash/compare/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/sourmash/compare/main.nf
  tests/modules/nf-core/sourmash/compare/nextflow.config
  tests/modules/nf-core/sourmash/compare/test.yml
Labels: new module, Ready for Review

#2438 Change porechop to porechop/porechop
  modules/nf-core/porechop/porechop/main.nf
  modules/nf-core/porechop/porechop/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/porechop/porechop/main.nf
  tests/modules/nf-core/porechop/porechop/nextflow.config
  tests/modules/nf-core/porechop/porechop/test.yml
  tests/modules/nf-core/porechop/test.yml
Labels: Ready for Review

#1036 Bismark: Add back multi-core usage
  modules/nf-core/bismark/align/main.nf
  modules/nf-core/bismark/methylationextractor/main.nf
  tests/modules/nf-core/bismark/align/test.yml
Labels: update module

#2443 Change label for BEDTOOLS_BAMTOBED
  modules/nf-core/bedtools/bamtobed/main.nf
Labels: Ready for Review

#2260 Add AMPcombi module
  modules/nf-core/ampcombi/main.nf
  modules/nf-core/ampcombi/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/ampcombi/main.nf
  tests/modules/nf-core/ampcombi/nextflow.config
  tests/modules/nf-core/ampcombi/test.yml
Labels: new module, Ready for Review

#1931 Picard/ADDORREPLACEREADGROUPS: making args conform to other packages; adding optional index output
  modules/nf-core/picard/addorreplacereadgroups/main.nf
  modules/nf-core/picard/addorreplacereadgroups/meta.yml
  tests/modules/nf-core/picard/addorreplacereadgroups/nextflow.config
  tests/modules/nf-core/picard/addorreplacereadgroups/test.yml
Labels: update module, Ready for Review

#2467 Ampcombi update module to v.0.1.7
  modules/nf-core/ampcombi/main.nf
  modules/nf-core/ampcombi/meta.yml
  tests/modules/nf-core/ampcombi/main.nf
Labels: update module, Ready for Review

#2458 new module gawk
  modules/nf-core/gawk/main.nf
  modules/nf-core/gawk/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gawk/main.nf
  tests/modules/nf-core/gawk/nextflow.config
  tests/modules/nf-core/gawk/test.yml
Labels: new module, Ready for Review

#2399 Shinyngs/staticdifferential
  modules/nf-core/shinyngs/staticdifferential/main.nf
  modules/nf-core/shinyngs/staticdifferential/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/shinyngs/staticdifferential/main.nf
  tests/modules/nf-core/shinyngs/staticdifferential/nextflow.config
  tests/modules/nf-core/shinyngs/staticdifferential/test.yml
Labels: new module, Ready for Review

#2481 Add stub to bcftools concat
  modules/nf-core/bcftools/concat/main.nf
  tests/modules/nf-core/bcftools/concat/test.yml
Labels: Ready for Review

#2425 new module gatk4/determinegermlinecontigploidy
  modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
  modules/nf-core/gatk4/determinegermlinecontigploidy/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
  tests/modules/nf-core/gatk4/determinegermlinecontigploidy/nextflow.config
  tests/modules/nf-core/gatk4/determinegermlinecontigploidy/test.yml
Labels: new module, Ready for Review

#2490 new module gatk4/annotateintervals
  modules/nf-core/gatk4/annotateintervals/main.nf
  modules/nf-core/gatk4/annotateintervals/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/annotateintervals/main.nf
  tests/modules/nf-core/gatk4/annotateintervals/nextflow.config
  tests/modules/nf-core/gatk4/annotateintervals/test.yml
Labels: new module, Ready for Review

#2441 Add porechop_abi module
  modules/nf-core/porechop/abi/main.nf
  modules/nf-core/porechop/abi/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/porechop/abi/main.nf
  tests/modules/nf-core/porechop/abi/nextflow.config
  tests/modules/nf-core/porechop/abi/test.yml
Labels: new module, Ready for Review

#2401 New modules: agat/spstatistics and agat/sqstatbasic Issue #2257
  modules/nf-core/agat/spstatistics/main.nf
  modules/nf-core/agat/spstatistics/meta.yml
  modules/nf-core/agat/sqstatbasic/main.nf
  modules/nf-core/agat/sqstatbasic/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/agat/spstatistics/main.nf
  tests/modules/nf-core/agat/spstatistics/nextflow.config
  tests/modules/nf-core/agat/spstatistics/test.yml
  tests/modules/nf-core/agat/sqstatbasic/main.nf
  tests/modules/nf-core/agat/sqstatbasic/nextflow.config
  tests/modules/nf-core/agat/sqstatbasic/test.yml
Labels: new module, Ready for Review

#2459 New module: arcashla/extract
  modules/nf-core/arcashla/extract/main.nf
  modules/nf-core/arcashla/extract/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/arcashla/extract/main.nf
  tests/modules/nf-core/arcashla/extract/nextflow.config
  tests/modules/nf-core/arcashla/extract/test.yml
Labels: new module

#2222 Added smoove module
  modules/nf-core/smoove/main.nf
  modules/nf-core/smoove/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/smoove/main.nf
  tests/modules/nf-core/smoove/nextflow.config
  tests/modules/nf-core/smoove/test.yml
Labels: new module

#2519 Enforce numeric on formatted tabular outputs from DESeq2
  modules/nf-core/deseq2/differential/templates/deseq_de.R
  tests/modules/nf-core/deseq2/differential/test.yml
Labels: Ready for Review

#2523 add module for shigeifinder
  modules/nf-core/shigeifinder/main.nf
  modules/nf-core/shigeifinder/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/shigeifinder/main.nf
  tests/modules/nf-core/shigeifinder/nextflow.config
  tests/modules/nf-core/shigeifinder/test.yml
Labels: new module

#2549 Two new modules: agat convertspgxf2gxf and convertspgff2gtf. Issue #2527
  modules/nf-core/agat/convertspgff2gtf/main.nf
  modules/nf-core/agat/convertspgff2gtf/meta.yml
  modules/nf-core/agat/convertspgxf2gxf/main.nf
  modules/nf-core/agat/convertspgxf2gxf/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/agat/convertspgff2gtf/main.nf
  tests/modules/nf-core/agat/convertspgff2gtf/nextflow.config
  tests/modules/nf-core/agat/convertspgff2gtf/test.yml
  tests/modules/nf-core/agat/convertspgxf2gxf/main.nf
  tests/modules/nf-core/agat/convertspgxf2gxf/nextflow.config
  tests/modules/nf-core/agat/convertspgxf2gxf/test.yml
Labels: new module, Ready for Review

#2463 Collectwgsmetrics interval
  modules/nf-core/picard/collectwgsmetrics/main.nf
  modules/nf-core/picard/collectwgsmetrics/meta.yml
  subworkflows/nf-core/bam_qc_picard/main.nf
  tests/modules/nf-core/picard/collectwgsmetrics/main.nf
  tests/modules/nf-core/picard/collectwgsmetrics/test.yml
Labels: Ready for Review

#2554 Sync versions on bbmap including mulled containers
  modules/nf-core/bbmap/align/main.nf
  modules/nf-core/bbmap/bbduk/main.nf
  modules/nf-core/bbmap/bbsplit/main.nf
  modules/nf-core/bbmap/clumpify/main.nf
  modules/nf-core/bbmap/index/main.nf
  modules/nf-core/bbmap/pileup/main.nf
  tests/modules/nf-core/bbmap/align/test.yml
  tests/modules/nf-core/bbmap/bbduk/test.yml
  tests/modules/nf-core/bbmap/bbsplit/test.yml
  tests/modules/nf-core/bbmap/pileup/test.yml
Labels: WIP

#2561 2558 new module cnvkitgenemetrics
  modules/nf-core/cnvkit/genemetrics/main.nf
  modules/nf-core/cnvkit/genemetrics/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/cnvkit/genemetrics/main.nf
  tests/modules/nf-core/cnvkit/genemetrics/nextflow.config
  tests/modules/nf-core/cnvkit/genemetrics/test.yml
Labels: Ready for Review

#2560 update vcfanno
  modules/nf-core/vcfanno/main.nf
  modules/nf-core/vcfanno/meta.yml
  tests/modules/nf-core/vcfanno/main.nf
  tests/modules/nf-core/vcfanno/test.yml
Labels: Ready for Review

#2530 Add matrixfilter module
  modules/nf-core/custom/matrixfilter/main.nf
  modules/nf-core/custom/matrixfilter/meta.yml
  modules/nf-core/custom/matrixfilter/templates/matrixfilter.R
  tests/config/pytest_modules.yml
  tests/modules/nf-core/custom/matrixfilter/main.nf
  tests/modules/nf-core/custom/matrixfilter/nextflow.config
  tests/modules/nf-core/custom/matrixfilter/test.yml
Labels: Ready for Review

#2252 fix a few tests after restructure
  modules/nf-core/amrfinderplus/run/main.nf
  modules/nf-core/amrfinderplus/update/main.nf
  tests/modules/nf-core/pirate/test.yml
  tests/modules/nf-core/shovill/test.yml
Labels: tests

#1277 sortmerna: add suffix to output fq, add test.yml, add `--fastx`
  modules/nf-core/sortmerna/main.nf
  modules/nf-core/sortmerna/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/sortmerna/main.nf
  tests/modules/nf-core/sortmerna/nextflow.config
  tests/modules/nf-core/sortmerna/test.yml
Labels: update module, Ready for Review

#2585 Misc. fixes in pytest_modules.yml
  tests/config/pytest_modules.yml
Labels: bug, tests, Ready for Review

#2588 Update picard/collect*metrics
  modules/nf-core/picard/collecthsmetrics/main.nf
  modules/nf-core/picard/collecthsmetrics/meta.yml
  modules/nf-core/picard/collectmultiplemetrics/main.nf
  modules/nf-core/picard/collectmultiplemetrics/meta.yml
  modules/nf-core/picard/collectwgsmetrics/main.nf
  modules/nf-core/picard/collectwgsmetrics/meta.yml
  subworkflows/nf-core/bam_qc_picard/main.nf
  subworkflows/nf-core/bam_qc_picard/meta.yml
  tests/modules/nf-core/picard/collecthsmetrics/main.nf
  tests/modules/nf-core/picard/collecthsmetrics/test.yml
  tests/modules/nf-core/picard/collectmultiplemetrics/main.nf
  tests/modules/nf-core/picard/collectmultiplemetrics/test.yml
  tests/modules/nf-core/picard/collectwgsmetrics/main.nf
  tests/modules/nf-core/picard/collectwgsmetrics/test.yml
  tests/subworkflows/nf-core/bam_qc_picard/main.nf
  tests/subworkflows/nf-core/bam_qc_picard/test.yml
Labels: Ready for Review

#2544 new subworkflow: bed_scatter_bedtools
  subworkflows/nf-core/bed_scatter_bedtools/main.nf
  subworkflows/nf-core/bed_scatter_bedtools/meta.yml
  subworkflows/nf-core/bed_scatter_bedtools/nextflow.config
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/bed_scatter_bedtools/main.nf
  tests/subworkflows/nf-core/bed_scatter_bedtools/nextflow.config
  tests/subworkflows/nf-core/bed_scatter_bedtools/test.yml
Labels: Ready for Review, new subworkflow

#2595 Add FASTA index to Whamg
  modules/nf-core/whamg/main.nf
  modules/nf-core/whamg/meta.yml
  tests/modules/nf-core/whamg/main.nf
Labels: update module, Ready for Review

#2593 Update somalier
  modules/nf-core/somalier/extract/main.nf
  modules/nf-core/somalier/extract/meta.yml
  modules/nf-core/somalier/relate/main.nf
  modules/nf-core/somalier/relate/meta.yml
  tests/modules/nf-core/somalier/extract/main.nf
  tests/modules/nf-core/somalier/extract/test.yml
  tests/modules/nf-core/somalier/relate/main.nf
  tests/modules/nf-core/somalier/relate/nextflow.config
  tests/modules/nf-core/somalier/relate/test.yml
Labels: update module, Ready for Review
