Repository nf-core/modules, pull requests merged in 2022-10, with the labels that each got.

#1901 New module: EMBOSS_SEQRET
  modules/emboss/seqret/main.nf
  modules/emboss/seqret/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/emboss/seqret/main.nf
  tests/modules/emboss/seqret/nextflow.config
  tests/modules/emboss/seqret/test.yml
Labels: new module

#1615 shasta module added
  modules/shasta/main.nf
  modules/shasta/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/shasta/main.nf
  tests/modules/shasta/nextflow.config
  tests/modules/shasta/test.yml
Labels: new module

#2144 update to gatk4/printsvevidence
  modules/nf-core/gatk4/printsvevidence/main.nf
  modules/nf-core/gatk4/printsvevidence/meta.yml
  tests/modules/nf-core/gatk4/printsvevidence/main.nf
  tests/modules/nf-core/gatk4/printsvevidence/nextflow.config
  tests/modules/nf-core/gatk4/printsvevidence/test.yml
Labels: Ready for Review

#2164 Update yara index and yara mapper
  modules/nf-core/yara/index/main.nf
  modules/nf-core/yara/mapper/main.nf
  tests/modules/nf-core/yara/index/main.nf
  tests/modules/nf-core/yara/index/test.yml
  tests/modules/nf-core/yara/mapper/main.nf
  tests/modules/nf-core/yara/mapper/test.yml
Labels: update module

#2181 Picard rename sample in vcf
  modules/nf-core/picard/renamesampleinvcf/main.nf
  modules/nf-core/picard/renamesampleinvcf/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/picard/renamesampleinvcf/main.nf
  tests/modules/nf-core/picard/renamesampleinvcf/nextflow.config
  tests/modules/nf-core/picard/renamesampleinvcf/test.yml
Labels: new module, Ready for Review

#2201 add subworkflow: fastq_align
  subworkflows/nf-core/fastq_align_dna/main.nf
  subworkflows/nf-core/fastq_align_dna/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/fastq_align_dna/main.nf
  tests/subworkflows/nf-core/fastq_align_dna/nextflow.config
  tests/subworkflows/nf-core/fastq_align_dna/test.yml
Labels: Ready for Review

#2074 fix(bases2fastq): Remove stray ls
  modules/nf-core/bases2fastq/main.nf
Labels: update module

#2236 chore: Remove addParams
  subworkflows/nf-core/align_bowtie2/main.nf
  subworkflows/nf-core/gatk_create_som_pon/main.nf
  subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/main.nf
  subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/main.nf
  tests/modules/nf-core/amplify/predict/main.nf
  tests/modules/nf-core/maxquant/lfq/main.nf
  tests/subworkflows/nf-core/align_bowtie2/main.nf
  tests/subworkflows/nf-core/bam_qc_picard/main.nf
  tests/subworkflows/nf-core/gatk_create_som_pon/main.nf
  tests/subworkflows/nf-core/gatk_tumor_normal_somatic_variant_calling/main.nf
  tests/subworkflows/nf-core/gatk_tumor_only_somatic_variant_calling/main.nf
Labels: update subworkflow

#2240 Adding module fgbio/zipperbams
  modules/nf-core/fgbio/zipperbams/main.nf
  modules/nf-core/fgbio/zipperbams/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/fgbio/zipperbams/main.nf
  tests/modules/nf-core/fgbio/zipperbams/nextflow.config
  tests/modules/nf-core/fgbio/zipperbams/test.yml
Labels: enhancement, Ready for Review, subworkflows

#2247 New subworkflow bam_dedup_stats_samtools_umitools
  subworkflows/nf-core/bam_dedup_stats_samtools_umitools/main.nf
  subworkflows/nf-core/bam_dedup_stats_samtools_umitools/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/bam_dedup_stats_samtools_umitools/main.nf
  tests/subworkflows/nf-core/bam_dedup_stats_samtools_umitools/nextflow.config
  tests/subworkflows/nf-core/bam_dedup_stats_samtools_umitools/test.yml
Labels: new subworkflow, subworkflows

#2219 Fix subset of tests
  tests/modules/nf-core/cooler/cload/nextflow.config
  tests/modules/nf-core/gatk4/applybqsr/test.yml
Labels: tests, Ready for Review

#2265 update bowtie2_align to fastq_align_bowtie2 and test
  subworkflows/nf-core/align_bowtie2/nextflow.config
  subworkflows/nf-core/fastq_align_bowtie2/main.nf
  subworkflows/nf-core/fastq_align_bowtie2/meta.yml
  subworkflows/nf-core/fastq_align_bowtie2/nextflow.config
  tests/subworkflows/nf-core/align_bowtie2/main.nf
  tests/subworkflows/nf-core/fastq_align_bowtie2/main.nf
  tests/subworkflows/nf-core/fastq_align_bowtie2/nextflow.config
  tests/subworkflows/nf-core/fastq_align_bowtie2/test.yml
Labels: update subworkflow, subworkflows

#2256 Markduplicates
  modules/nf-core/picard/markduplicates/main.nf
  modules/nf-core/picard/markduplicates/meta.yml
  tests/modules/nf-core/picard/markduplicates/main.nf
  tests/modules/nf-core/picard/markduplicates/nextflow.config
  tests/modules/nf-core/picard/markduplicates/test.yml
Labels: Ready for Review, subworkflows

#2270 Fastq align hisat2
  subworkflows/nf-core/fastq_align_hisat2/main.nf
  subworkflows/nf-core/fastq_align_hisat2/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/fastq_align_hisat2/main.nf
  tests/subworkflows/nf-core/fastq_align_hisat2/nextflow.config
  tests/subworkflows/nf-core/fastq_align_hisat2/test.yml
Labels: subworkflows

#2229 add subworkflow bam_markduplicates_picard
  subworkflows/nf-core/bam_markduplicates_picard/main.nf
  subworkflows/nf-core/bam_markduplicates_picard/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/bam_markduplicates_picard/main.nf
  tests/subworkflows/nf-core/bam_markduplicates_picard/nextflow.config
  tests/subworkflows/nf-core/bam_markduplicates_picard/test.yml
Labels: Ready for Review, subworkflows

#2275 chore: Add a "New subworkflow" issue template
  .github/ISSUE_TEMPLATE/new_subworkflow.yml
Labels: subworkflows

#2243 Adding module fgbio/callduplexconsensusreads
  modules/nf-core/fgbio/callduplexconsensusreads/main.nf
  modules/nf-core/fgbio/callduplexconsensusreads/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/fgbio/callduplexconsensusreads/main.nf
  tests/modules/nf-core/fgbio/callduplexconsensusreads/nextflow.config
  tests/modules/nf-core/fgbio/callduplexconsensusreads/test.yml
Labels: enhancement, Ready for Review, subworkflows

#2286 feat added args2 to samtools view
  modules/nf-core/samtools/view/main.nf
Labels: enhancement, Ready for Review

#2296 add meta to bowtie2 index
  modules/nf-core/bowtie2/align/main.nf
  modules/nf-core/bowtie2/align/meta.yml
  modules/nf-core/bowtie2/build/main.nf
  modules/nf-core/bowtie2/build/meta.yml
  subworkflows/nf-core/fastq_align_dna/README.md
  tests/modules/nf-core/bowtie2/align/main.nf
  tests/modules/nf-core/bowtie2/align/nextflow.config
  tests/modules/nf-core/bowtie2/align/test.yml
  tests/modules/nf-core/bowtie2/build_test/main.nf
  tests/modules/nf-core/bowtie2/build_test/test.yml
  tests/subworkflows/nf-core/fastq_align_bowtie2/main.nf
  tests/subworkflows/nf-core/fastq_align_bowtie2/nextflow.config
  tests/subworkflows/nf-core/fastq_align_bowtie2/test.yml
  tests/subworkflows/nf-core/fastq_align_dna/main.nf
Labels: enhancement, Ready for Review

#2248 Adding module fgbio/filterconsensusreads
  modules/nf-core/fgbio/filterconsensusreads/main.nf
  modules/nf-core/fgbio/filterconsensusreads/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/fgbio/filterconsensusreads/main.nf
  tests/modules/nf-core/fgbio/filterconsensusreads/nextflow.config
  tests/modules/nf-core/fgbio/filterconsensusreads/test.yml
Labels: enhancement, Ready for Review, subworkflows

#2306 set conda.enabled=true to fix Conda testing
  tests/config/nextflow.config
Labels: Ready for Review

#2303 new module gatk4/sitedepthtobaf
  modules/nf-core/gatk4/collectsvevidence/main.nf
  modules/nf-core/gatk4/collectsvevidence/meta.yml
  modules/nf-core/gatk4/sitedepthtobaf/main.nf
  modules/nf-core/gatk4/sitedepthtobaf/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/collectsvevidence/test.yml
  tests/modules/nf-core/gatk4/sitedepthtobaf/main.nf
  tests/modules/nf-core/gatk4/sitedepthtobaf/nextflow.config
  tests/modules/nf-core/gatk4/sitedepthtobaf/test.yml
Labels: new module, Ready for Review

#2311 New Segemehl module
  modules/nf-core/segemehl/align/main.nf
  modules/nf-core/segemehl/align/meta.yml
  modules/nf-core/segemehl/index/main.nf
  modules/nf-core/segemehl/index/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/segemehl/align/main.nf
  tests/modules/nf-core/segemehl/align/nextflow.config
  tests/modules/nf-core/segemehl/align/test.yml
  tests/modules/nf-core/segemehl/index/main.nf
  tests/modules/nf-core/segemehl/index/nextflow.config
  tests/modules/nf-core/segemehl/index/test.yml
Labels: new module, Ready for Review

#2263 fix(bedtools): Add checks for matching inputs and outputs
  modules/nf-core/bedtools/complement/main.nf
  modules/nf-core/bedtools/intersect/main.nf
  modules/nf-core/bedtools/merge/main.nf
  modules/nf-core/bedtools/slop/main.nf
  modules/nf-core/bedtools/sort/main.nf
  modules/nf-core/bedtools/subtract/main.nf
Labels: update module

#2298 new module circexplorer2/parse, annotate
  modules/nf-core/circexplorer2/annotate/main.nf
  modules/nf-core/circexplorer2/annotate/meta.yml
  modules/nf-core/circexplorer2/parse/main.nf
  modules/nf-core/circexplorer2/parse/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/circexplorer2/annotate/main.nf
  tests/modules/nf-core/circexplorer2/annotate/nextflow.config
  tests/modules/nf-core/circexplorer2/annotate/test.yml
  tests/modules/nf-core/circexplorer2/parse/main.nf
  tests/modules/nf-core/circexplorer2/parse/nextflow.config
  tests/modules/nf-core/circexplorer2/parse/test.yml
Labels: new module, Ready for Review

#2310 new miRanda module
  modules/nf-core/miranda/main.nf
  modules/nf-core/miranda/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/miranda/main.nf
  tests/modules/nf-core/miranda/nextflow.config
  tests/modules/nf-core/miranda/test.yml
Labels: new module, Ready for Review

#2326 subworkflow: fasta_align_index
  subworkflows/nf-core/fasta_index_dna/main.nf
  subworkflows/nf-core/fasta_index_dna/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/fasta_index_dna/main.nf
  tests/subworkflows/nf-core/fasta_index_dna/nextflow.config
  tests/subworkflows/nf-core/fasta_index_dna/test.yml
Labels: Ready for Review, new subworkflow, subworkflows

#1874 New module: vsearch/cluster
  modules/nf-core/vsearch/cluster/main.nf
  modules/nf-core/vsearch/cluster/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/vsearch/cluster/main.nf
  tests/modules/nf-core/vsearch/cluster/nextflow.config
  tests/modules/nf-core/vsearch/cluster/test.yml
Labels: new module

#2328 Addition of new module: kofamscan. Issue #2189
  modules/nf-core/kofamscan/main.nf
  modules/nf-core/kofamscan/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/kofamscan/main.nf
  tests/modules/nf-core/kofamscan/nextflow.config
  tests/modules/nf-core/kofamscan/test.yml
Labels: new module, Ready for Review

#2336 new module gatk4/condensedepthevidence
  modules/nf-core/gatk4/condensedepthevidence/main.nf
  modules/nf-core/gatk4/condensedepthevidence/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/condensedepthevidence/main.nf
  tests/modules/nf-core/gatk4/condensedepthevidence/nextflow.config
  tests/modules/nf-core/gatk4/condensedepthevidence/test.yml
Labels: new module, Ready for Review

#2345 new module svtk/vcf2bed
  modules/nf-core/svtk/vcf2bed/main.nf
  modules/nf-core/svtk/vcf2bed/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/svtk/vcf2bed/main.nf
  tests/modules/nf-core/svtk/vcf2bed/nextflow.config
  tests/modules/nf-core/svtk/vcf2bed/test.yml
Labels: new module, Ready for Review

#2334 subworkflow bcl_demultiplex: allow tarred inputs
  subworkflows/nf-core/bcl_demultiplex/main.nf
  subworkflows/nf-core/bcl_demultiplex/meta.yml
  tests/subworkflows/nf-core/bcl_demultiplex/main.nf
Labels: update subworkflow

#2348 new module bedtools/closest
  modules/nf-core/bedtools/closest/main.nf
  modules/nf-core/bedtools/closest/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bedtools/closest/main.nf
  tests/modules/nf-core/bedtools/closest/nextflow.config
  tests/modules/nf-core/bedtools/closest/test.yml
Labels: new module, Ready for Review

#2356 new module gatk4/svannotate
  modules/nf-core/gatk4/svannotate/main.nf
  modules/nf-core/gatk4/svannotate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/svannotate/main.nf
  tests/modules/nf-core/gatk4/svannotate/nextflow.config
  tests/modules/nf-core/gatk4/svannotate/test.yml
Labels: new module, Ready for Review

#2321 Add gtf2featureannotation module
  modules/nf-core/atlasgeneannotationmanipulation/gtf2featureannotation/main.nf
  modules/nf-core/atlasgeneannotationmanipulation/gtf2featureannotation/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/atlasgeneannotationmanipulation/gtf2featureannotation/main.nf
  tests/modules/nf-core/atlasgeneannotationmanipulation/gtf2featureannotation/nextflow.config
  tests/modules/nf-core/atlasgeneannotationmanipulation/gtf2featureannotation/test.yml
Labels: new module, Ready for Review

#2167 Add starting deseq2 differential module
  modules/nf-core/deseq2/differential/main.nf
  modules/nf-core/deseq2/differential/meta.yml
  modules/nf-core/deseq2/differential/templates/deseq_de.R
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/deseq2/differential/main.nf
  tests/modules/nf-core/deseq2/differential/nextflow.config
  tests/modules/nf-core/deseq2/differential/test.yml
Labels: Ready for Review

#2234 add module for biohansel
  modules/nf-core/biohansel/main.nf
  modules/nf-core/biohansel/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/biohansel/main.nf
  tests/modules/nf-core/biohansel/nextflow.config
  tests/modules/nf-core/biohansel/test.yml
Labels: new module, Ready for Review

#2364 Shinyngs/staticexploratory
  modules/nf-core/shinyngs/staticexploratory/main.nf
  modules/nf-core/shinyngs/staticexploratory/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/shinyngs/staticexploratory/main.nf
  tests/modules/nf-core/shinyngs/staticexploratory/nextflow.config
  tests/modules/nf-core/shinyngs/staticexploratory/test.yml
Labels: new module, Ready for Review

#2375 new module svtk/baftest
  modules/nf-core/svtk/baftest/main.nf
  modules/nf-core/svtk/baftest/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/svtk/baftest/main.nf
  tests/modules/nf-core/svtk/baftest/nextflow.config
  tests/modules/nf-core/svtk/baftest/test.yml
Labels: new module, Ready for Review

#2282 drop endedness check for fastqc, add tests
  modules/nf-core/fastqc/main.nf
  tests/modules/nf-core/fastqc/main.nf
  tests/modules/nf-core/fastqc/test.yml
  tests/subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/test.yml
Labels: Ready for Review

#1965 New module mageck/count
  modules/nf-core/mageck/count/main.nf
  modules/nf-core/mageck/count/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/mageck/count/main.nf
  tests/modules/nf-core/mageck/count/nextflow.config
  tests/modules/nf-core/mageck/count/test.yml
Labels: new module

#2377 new module svtk/rdtest2vcf
  modules/nf-core/svtk/rdtest2vcf/main.nf
  modules/nf-core/svtk/rdtest2vcf/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/svtk/rdtest2vcf/main.nf
  tests/modules/nf-core/svtk/rdtest2vcf/nextflow.config
  tests/modules/nf-core/svtk/rdtest2vcf/test.yml
Labels: new module, Ready for Review

#2384 new module svtk/countsvtypes
  modules/nf-core/svtk/countsvtypes/main.nf
  modules/nf-core/svtk/countsvtypes/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/svtk/countsvtypes/main.nf
  tests/modules/nf-core/svtk/countsvtypes/nextflow.config
  tests/modules/nf-core/svtk/countsvtypes/test.yml
Labels: new module, Ready for Review

#2285 New module: bedtools coverage
  modules/nf-core/bedtools/coverage/main.nf
  modules/nf-core/bedtools/coverage/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bedtools/coverage/main.nf
  tests/modules/nf-core/bedtools/coverage/nextflow.config
  tests/modules/nf-core/bedtools/coverage/test.yml
Labels: new module, Ready for Review

#2351 Add calder2 module
  modules/nf-core/calder2/main.nf
  modules/nf-core/calder2/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/calder2/main.nf
  tests/modules/nf-core/calder2/nextflow.config
  tests/modules/nf-core/calder2/test.yml
Labels: new module, Ready for Review

#2323 UCSC: gtfToGenePred
  modules/nf-core/ucsc/gtftogenepred/main.nf
  modules/nf-core/ucsc/gtftogenepred/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/ucsc/gtftogenepred/main.nf
  tests/modules/nf-core/ucsc/gtftogenepred/nextflow.config
  tests/modules/nf-core/ucsc/gtftogenepred/test.yml
Labels: new module, Ready for Review

#2368 add module gatk4/shiftfasta
  modules/nf-core/gatk4/shiftfasta/main.nf
  modules/nf-core/gatk4/shiftfasta/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/shiftfasta/main.nf
  tests/modules/nf-core/gatk4/shiftfasta/nextflow.config
  tests/modules/nf-core/gatk4/shiftfasta/test.yml
Labels: new module, Ready for Review

#2391 New module subcommand : mageck mle
  modules/nf-core/mageck/mle/main.nf
  modules/nf-core/mageck/mle/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/mageck/mle/main.nf
  tests/modules/nf-core/mageck/mle/nextflow.config
  tests/modules/nf-core/mageck/mle/test.yml
Labels: new module

#1152 Adding new module vg/deconstruct
  modules/nf-core/vg/deconstruct/main.nf
  modules/nf-core/vg/deconstruct/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/vg/deconstruct/main.nf
  tests/modules/nf-core/vg/deconstruct/nextflow.config
  tests/modules/nf-core/vg/deconstruct/test.yml
Labels: new module

#2387 new module gangstr
  modules/nf-core/gangstr/main.nf
  modules/nf-core/gangstr/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gangstr/main.nf
  tests/modules/nf-core/gangstr/nextflow.config
  tests/modules/nf-core/gangstr/test.yml
Labels: new module, Ready for Review

#2409 FASTQ_ALIGN_STAR Subworkflow
  subworkflows/nf-core/fastq_align_star/main.nf
  subworkflows/nf-core/fastq_align_star/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/fastq_align_star/main.nf
  tests/subworkflows/nf-core/fastq_align_star/nextflow.config
  tests/subworkflows/nf-core/fastq_align_star/test.yml
Labels: Ready for Review, new subworkflow

#2432 DESeq2: Version doesn't need a meta
  modules/nf-core/deseq2/differential/main.nf
Labels: Ready for Review

#2433 shinyngs/staticexploratory: minor module fixes
  modules/nf-core/shinyngs/staticexploratory/main.nf
  modules/nf-core/shinyngs/staticexploratory/meta.yml
Labels: Ready for Review

#2392 shinyngs feature/observation matrix validation module
  modules/nf-core/shinyngs/validatefomcomponents/main.nf
  modules/nf-core/shinyngs/validatefomcomponents/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/shinyngs/validatefomcomponents/main.nf
  tests/modules/nf-core/shinyngs/validatefomcomponents/nextflow.config
  tests/modules/nf-core/shinyngs/validatefomcomponents/test.yml
Labels: Ready for Review
