Repository nf-core/modules, pull requests merged in 2023-03, with the labels that each got.

#2948 Shapeit5 switch
  modules/nf-core/shapeit5/switch/main.nf
  modules/nf-core/shapeit5/switch/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/shapeit5/switch/main.nf
  tests/modules/nf-core/shapeit5/switch/nextflow.config
  tests/modules/nf-core/shapeit5/switch/test.yml
Labels: new module, Ready for Review

#2959 Glimpse2 splitref
  modules/nf-core/glimpse2/splitreference/main.nf
  modules/nf-core/glimpse2/splitreference/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/glimpse2/splitreference/main.nf
  tests/modules/nf-core/glimpse2/splitreference/nextflow.config
  tests/modules/nf-core/glimpse2/splitreference/test.yml
Labels: new module, Ready for Review

#2962 Updating missing description outputfiles from quast module
  modules/nf-core/quast/meta.yml
Labels: documentation

#2932 Fix tiara/tiara
  modules/nf-core/tiara/tiara/main.nf
  modules/nf-core/tiara/tiara/meta.yml
  tests/modules/nf-core/tiara/tiara/test.yml
Labels: Ready for Review

#2854 New module: graphtyper/vcf_concatenate
  modules/nf-core/graphtyper/vcfconcatenate/main.nf
  modules/nf-core/graphtyper/vcfconcatenate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/graphtyper/vcfconcatenate/main.nf
  tests/modules/nf-core/graphtyper/vcfconcatenate/nextflow.config
  tests/modules/nf-core/graphtyper/vcfconcatenate/test.yml
Labels: new module, Ready for Review

#2217 bam_variant_calling_freebayes
  subworkflows/nf-core/bam_variant_calling_freebayes/main.nf
  subworkflows/nf-core/bam_variant_calling_freebayes/meta.yml
  subworkflows/nf-core/bam_variant_calling_freebayes/readme.md
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/bam_variant_calling_freebayes/main.nf
  tests/subworkflows/nf-core/bam_variant_calling_freebayes/nextflow.config
  tests/subworkflows/nf-core/bam_variant_calling_freebayes/test.yml
Labels: new subworkflow, subworkflows

#2927 Glimpse2 chunk
  modules/nf-core/glimpse2/chunk/main.nf
  modules/nf-core/glimpse2/chunk/meta.yml
  modules/nf-core/shapeit5/phaserare/main.nf
  tests/config/pytest_modules.yml
  tests/modules/nf-core/glimpse2/chunk/main.nf
  tests/modules/nf-core/glimpse2/chunk/nextflow.config
  tests/modules/nf-core/glimpse2/chunk/test.yml
Labels: help wanted, new module, Ready for Review

#2844 New module: kallisto/quant
  modules/nf-core/kallisto/quant/main.nf
  modules/nf-core/kallisto/quant/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/kallisto/quant/main.nf
  tests/modules/nf-core/kallisto/quant/nextflow.config
  tests/modules/nf-core/kallisto/quant/test.yml
Labels: new module, Ready for Review

#2964 Glimpse phase input management
  modules/nf-core/glimpse/phase/main.nf
  modules/nf-core/glimpse/phase/meta.yml
  subworkflows/nf-core/vcf_impute_glimpse/main.nf
  tests/modules/nf-core/glimpse/concordance/main.nf
  tests/modules/nf-core/glimpse/concordance/nextflow.config
  tests/modules/nf-core/glimpse/concordance/test.yml
  tests/modules/nf-core/glimpse/ligate/main.nf
  tests/modules/nf-core/glimpse/ligate/nextflow.config
  tests/modules/nf-core/glimpse/ligate/test.yml
  tests/modules/nf-core/glimpse/phase/main.nf
  tests/modules/nf-core/glimpse/phase/nextflow.config
  tests/modules/nf-core/glimpse/phase/test.yml
  tests/modules/nf-core/glimpse/sample/main.nf
  tests/modules/nf-core/glimpse/sample/nextflow.config
  tests/modules/nf-core/glimpse/sample/test.yml
  tests/subworkflows/nf-core/vcf_impute_glimpse/main.nf
  tests/subworkflows/nf-core/vcf_impute_glimpse/nextflow.config
  tests/subworkflows/nf-core/vcf_impute_glimpse/test.yml
Labels: enhancement, update module, Ready for Review, update subworkflow

#2985 update vcf_annotate_snpeff to guidelines
  subworkflows/nf-core/vcf_annotate_snpeff/main.nf
  subworkflows/nf-core/vcf_annotate_snpeff/meta.yml
Labels: Ready for Review, subworkflows

#3005 update crumble
  modules/nf-core/crumble/main.nf
  modules/nf-core/crumble/meta.yml
  tests/modules/nf-core/crumble/main.nf
  tests/modules/nf-core/crumble/test.yml
Labels: enhancement, Ready for Review

#2986 update bam markduplicates subwf to guidelines
  subworkflows/nf-core/bam_markduplicates_picard/main.nf
  subworkflows/nf-core/bam_markduplicates_picard/meta.yml
  tests/subworkflows/nf-core/bam_markduplicates_picard/test.yml
Labels: Ready for Review, subworkflows

#2987 update bam stats samtools to guidelines
  subworkflows/nf-core/bam_stats_samtools/main.nf
  subworkflows/nf-core/bam_stats_samtools/meta.yml
Labels: Ready for Review, subworkflows

#2995 update vcf extract relate somalier to guidelines
  subworkflows/nf-core/vcf_extract_relate_somalier/main.nf
  subworkflows/nf-core/vcf_extract_relate_somalier/meta.yml
  tests/subworkflows/nf-core/vcf_extract_relate_somalier/main.nf
Labels: Ready for Review, subworkflows

#3007 Glimpse2 concordance
  modules/nf-core/glimpse/concordance/meta.yml
  modules/nf-core/glimpse2/concordance/main.nf
  modules/nf-core/glimpse2/concordance/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/glimpse2/concordance/main.nf
  tests/modules/nf-core/glimpse2/concordance/nextflow.config
  tests/modules/nf-core/glimpse2/concordance/test.yml
Labels: new module, Ready for Review

#2990 update fastq align bwaaln to guidelines
  subworkflows/nf-core/fastq_align_bwaaln/main.nf
  subworkflows/nf-core/fastq_align_bwaaln/meta.yml
Labels: Ready for Review, subworkflows

#2979 Update subworkflow to adhere to the guidelines
  subworkflows/nf-core/bam_create_som_pon_gatk/main.nf
  subworkflows/nf-core/bam_create_som_pon_gatk/meta.yml
  subworkflows/nf-core/bam_create_som_pon_gatk/nextflow.config
  subworkflows/nf-core/bam_dedup_stats_samtools_umitools/main.nf
  subworkflows/nf-core/bam_dedup_stats_samtools_umitools/meta.yml
  subworkflows/nf-core/bam_split_by_region/main.nf
  subworkflows/nf-core/bam_split_by_region/meta.yml
  subworkflows/nf-core/bed_scatter_bedtools/main.nf
  subworkflows/nf-core/bed_scatter_bedtools/meta.yml
  subworkflows/nf-core/fastq_align_bwa/main.nf
  subworkflows/nf-core/fastq_align_bwa/meta.yml
  subworkflows/nf-core/fastq_align_star/main.nf
  subworkflows/nf-core/fastq_align_star/meta.yml
  subworkflows/nf-core/gatk_create_som_pon/main.nf
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/bam_create_som_pon_gatk/main.nf
  tests/subworkflows/nf-core/bam_create_som_pon_gatk/test.yml
  tests/subworkflows/nf-core/gatk_create_som_pon/main.nf
Labels: Ready for Review, subworkflows

#3024 Bump software versions for modules used in nf-core/viralrecon
  modules/nf-core/blast/blastn/main.nf
  modules/nf-core/blast/makeblastdb/main.nf
  modules/nf-core/blast/tblastn/main.nf
  modules/nf-core/custom/dumpsoftwareversions/main.nf
  modules/nf-core/ivar/consensus/main.nf
  modules/nf-core/ivar/trim/main.nf
  modules/nf-core/ivar/variants/main.nf
  modules/nf-core/nextclade/datasetget/main.nf
  modules/nf-core/nextclade/run/main.nf
  modules/nf-core/pangolin/main.nf
  modules/nf-core/spades/main.nf
  tests/modules/nf-core/blast/tblastn/test.yml
  tests/modules/nf-core/ivar/consensus/test.yml
  tests/modules/nf-core/ivar/trim/test.yml
  tests/modules/nf-core/ivar/variants/test.yml
  tests/modules/nf-core/nextclade/run/test.yml
  tests/modules/nf-core/pangolin/test.yml
Labels: Ready for Review

#3038 fix: redirect kraken2 output to /dev/null
  modules/nf-core/kraken2/kraken2/main.nf
Labels: bug, Ready for Review

#3037 Add tbi creation to delly
  modules/nf-core/delly/call/main.nf
  tests/modules/nf-core/delly/call/test.yml
Labels: update module, Ready for Review

#3042 adding gffcompare
  modules/nf-core/gffcompare/main.nf
  modules/nf-core/gffcompare/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gffcompare/main.nf
  tests/modules/nf-core/gffcompare/nextflow.config
  tests/modules/nf-core/gffcompare/test.yml
Labels: new module

#3050 Add new samtools coverage
  modules/nf-core/samtools/coverage/main.nf
  modules/nf-core/samtools/coverage/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/samtools/coverage/main.nf
  tests/modules/nf-core/samtools/coverage/nextflow.config
  tests/modules/nf-core/samtools/coverage/test.yml
Labels: new module, Ready for Review

#3052 New module bcftools call
  modules/nf-core/bcftools/call/main.nf
  modules/nf-core/bcftools/call/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bcftools/call/main.nf
  tests/modules/nf-core/bcftools/call/nextflow.config
  tests/modules/nf-core/bcftools/call/test.yml
Labels: new module

#3063 New fastq_fastqc_umitools_fastp subworkflow
  subworkflows/nf-core/fastq_fastqc_umitools_fastp/main.nf
  subworkflows/nf-core/fastq_fastqc_umitools_fastp/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/fastq_fastqc_umitools_fastp/main.nf
  tests/subworkflows/nf-core/fastq_fastqc_umitools_fastp/nextflow.config
  tests/subworkflows/nf-core/fastq_fastqc_umitools_fastp/test.yml
Labels: Ready for Review, new subworkflow

#3068 Moved the bed input of mosdepth
  modules/nf-core/mosdepth/main.nf
  tests/modules/nf-core/mosdepth/main.nf
Labels: update module, Ready for Review

#3066 New Module: Windowmasker
  modules/nf-core/windowmasker/mk_counts/main.nf
  modules/nf-core/windowmasker/mk_counts/meta.yml
  modules/nf-core/windowmasker/ustat/main.nf
  modules/nf-core/windowmasker/ustat/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/windowmasker/mk_counts/main.nf
  tests/modules/nf-core/windowmasker/mk_counts/nextflow.config
  tests/modules/nf-core/windowmasker/mk_counts/test.yml
  tests/modules/nf-core/windowmasker/ustat/main.nf
  tests/modules/nf-core/windowmasker/ustat/nextflow.config
  tests/modules/nf-core/windowmasker/ustat/test.yml
Labels: new module

#3080 Bump shinyngs in associated modules
  modules/nf-core/shinyngs/staticdifferential/main.nf
  modules/nf-core/shinyngs/staticexploratory/main.nf
  modules/nf-core/shinyngs/validatefomcomponents/main.nf
Labels: Ready for Review

#2961 started adding AuthentiCT module
  modules/nf-core/authentict/deam2cont/main.nf
  modules/nf-core/authentict/deam2cont/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/authentict/deam2cont/main.nf
  tests/modules/nf-core/authentict/deam2cont/nextflow.config
  tests/modules/nf-core/authentict/deam2cont/test.yml
Labels: new subworkflow, update subworkflow, sarek, subworkflows

#2875 New module Ilastik/pixelclassification
  .github/workflows/pytest-workflow.yml
  modules/nf-core/ilastik/pixelclassification/main.nf
  modules/nf-core/ilastik/pixelclassification/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/ilastik/pixelclassification/main.nf
  tests/modules/nf-core/ilastik/pixelclassification/nextflow.config
  tests/modules/nf-core/ilastik/pixelclassification/test.yml
Labels: imaging

#2894 New module Ilastik/multicut
  .github/workflows/pytest-workflow.yml
  modules/nf-core/ilastik/multicut/main.nf
  modules/nf-core/ilastik/multicut/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/ilastik/multicut/main.nf
  tests/modules/nf-core/ilastik/multicut/nextflow.config
  tests/modules/nf-core/ilastik/multicut/test.yml
Labels: imaging

#2984 PEDDY: added prefix to the name of outputs
  modules/nf-core/peddy/main.nf
  tests/modules/nf-core/peddy/test.yml
Labels: Ready for Review

#3104 update UMI subworkflow with duplex and best practices
  subworkflows/nf-core/fastq_create_umi_consensus_fgbio/main.nf
  subworkflows/nf-core/fastq_create_umi_consensus_fgbio/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/fastq_create_umi_consensus_fgbio/main.nf
  tests/subworkflows/nf-core/fastq_create_umi_consensus_fgbio/nextflow.config
  tests/subworkflows/nf-core/fastq_create_umi_consensus_fgbio/test.yml
Labels: hackathon2023

#3136 Zip prodigal outputs (closes #922)
  modules/nf-core/prodigal/main.nf
  tests/modules/nf-core/prodigal/test.yml
Labels: enhancement, good first issue, update module, Ready for Review, hackathon2023

#3159 Version update for sourmash modules
  modules/nf-core/sourmash/compare/main.nf
  modules/nf-core/sourmash/gather/main.nf
  modules/nf-core/sourmash/sketch/main.nf
Labels: Ready for Review

#3150 new module: indeppairwise
  modules/nf-core/plink/indeppairwise/main.nf
  modules/nf-core/plink/indeppairwise/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/plink/indeppairwise/main.nf
  tests/modules/nf-core/plink/indeppairwise/nextflow.config
  tests/modules/nf-core/plink/indeppairwise/test.yml
Labels: new module, hackathon2023

#3168 Addition of new module: Issue #3113 Survivor/filter
  modules/nf-core/survivor/filter/main.nf
  modules/nf-core/survivor/filter/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/survivor/filter/main.nf
  tests/modules/nf-core/survivor/filter/nextflow.config
  tests/modules/nf-core/survivor/filter/test.yml
Labels: new module, Ready for Review, hackathon2023

#3215 update appropriate label for freyja boot
  modules/nf-core/freyja/boot/main.nf
Labels: enhancement

#3212 new module wisecondorx/newref
  modules/nf-core/wisecondorx/newref/main.nf
  modules/nf-core/wisecondorx/newref/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/wisecondorx/newref/main.nf
  tests/modules/nf-core/wisecondorx/newref/nextflow.config
  tests/modules/nf-core/wisecondorx/newref/test.yml
Labels: new module, Ready for Review

#3139 Mcmicro/Scimap
  .github/workflows/pytest-workflow.yml
  modules/nf-core/scimap/mcmicro/main.nf
  modules/nf-core/scimap/mcmicro/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/scimap/mcmicro/main.nf
  tests/modules/nf-core/scimap/mcmicro/nextflow.config
  tests/modules/nf-core/scimap/mcmicro/test.yml
Labels: Ready for Review, imaging

#3219 umi-tools: Choose different process labels
  modules/nf-core/umitools/dedup/main.nf
  modules/nf-core/umitools/extract/main.nf
Labels: Ready for Review, rnaseq

#3214 Cellpose nfcore
  .github/workflows/pytest-workflow.yml
  modules/nf-core/cellpose/main.nf
  modules/nf-core/cellpose/meta.yml
  modules/nf-core/faqcs/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/cellpose/main.nf
  tests/modules/nf-core/cellpose/nextflow.config
  tests/modules/nf-core/cellpose/test.yml
Labels: new module, Ready for Review

#3187 Deepcell - Mesmer segmentation for tissues
  .github/workflows/pytest-workflow.yml
  modules/nf-core/deepcell/mesmer/main.nf
  modules/nf-core/deepcell/mesmer/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/deepcell/mesmer/main.nf
  tests/modules/nf-core/deepcell/mesmer/nextflow.config
  tests/modules/nf-core/deepcell/mesmer/test.yml
Labels: new module, Ready for Review

#3220 New Module: paftools/sam2paf
  modules/nf-core/paftools/sam2paf/main.nf
  modules/nf-core/paftools/sam2paf/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/paftools/sam2paf/main.nf
  tests/modules/nf-core/paftools/sam2paf/nextflow.config
  tests/modules/nf-core/paftools/sam2paf/test.yml
Labels: new module, Ready for Review, hackathon2023

#3171 add module: nanocomp
  modules/nf-core/nanocomp/main.nf
  modules/nf-core/nanocomp/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/nanocomp/main.nf
  tests/modules/nf-core/nanocomp/nextflow.config
  tests/modules/nf-core/nanocomp/test.yml
Labels: Ready for Review, hackathon2023

#3238 Windowmasker version fix
  modules/nf-core/windowmasker/mk_counts/main.nf
  modules/nf-core/windowmasker/ustat/main.nf
Labels: bug

#3227 Bump shinyngs versions, add minor fixes to shinyngs/app module
  modules/nf-core/shinyngs/app/main.nf
  modules/nf-core/shinyngs/staticdifferential/main.nf
  modules/nf-core/shinyngs/validatefomcomponents/main.nf
  tests/modules/nf-core/shinyngs/app/main.nf
  tests/modules/nf-core/shinyngs/app/test.yml
Labels: Ready for Review
