Repository nf-core/modules, pull requests merged in 2023-01, with the labels that each got.

#2698 Let GAPPA_EXAMINEASSIGN take all arguments in one structure
  modules/nf-core/gappa/examineassign/main.nf
  tests/modules/nf-core/gappa/examineassign/main.nf
Labels: Ready for Review

#2697 Let EPANG_PLACE take all mandatory arguments in one structure
  modules/nf-core/epang/place/main.nf
  tests/modules/nf-core/epang/place/main.nf
Labels: Ready for Review

#2706 fix: correct pon if statement, rm collect, set tumor_out to empty string
  modules/nf-core/cnvkit/batch/main.nf
Labels: bug

#2717 update label of genomicsdbimport
  modules/nf-core/gatk4/genomicsdbimport/main.nf
Labels: update module, Ready for Review

#2712 Simplify GSEA outputs, remove nasty symlinking, alow file-level prefixes
  modules/nf-core/gsea/gsea/main.nf
  tests/modules/nf-core/gsea/gsea/nextflow.config
  tests/modules/nf-core/gsea/gsea/test.yml
Labels: Ready for Review

#2721 Implementation of the nf-core YaHS module
  modules/nf-core/yahs/main.nf
  modules/nf-core/yahs/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/yahs/main.nf
  tests/modules/nf-core/yahs/nextflow.config
  tests/modules/nf-core/yahs/test.yml
Labels: new module, Ready for Review

#2726 Quote command line arguments in shinyngs modules
  modules/nf-core/shinyngs/staticdifferential/main.nf
  modules/nf-core/shinyngs/staticexploratory/main.nf
  modules/nf-core/shinyngs/validatefomcomponents/main.nf
Labels: Ready for Review

#2724 DESeq2: Allow for spaces in sample metadata columns
  modules/nf-core/deseq2/differential/templates/deseq_de.R
Labels: Ready for Review

#2731 update happy/happy
  modules/nf-core/happy/happy/main.nf
  modules/nf-core/happy/happy/meta.yml
  tests/modules/nf-core/happy/happy/main.nf
  tests/modules/nf-core/happy/happy/test.yml
Labels: update module, Ready for Review

#2734 Update rtgtools/vcfeval
  modules/nf-core/rtgtools/vcfeval/main.nf
  modules/nf-core/rtgtools/vcfeval/meta.yml
  tests/modules/nf-core/rtgtools/vcfeval/main.nf
  tests/modules/nf-core/rtgtools/vcfeval/test.yml
Labels: update module, Ready for Review

#2735 bump snap version
  modules/nf-core/snapaligner/align/main.nf
  modules/nf-core/snapaligner/index/main.nf
  tests/modules/nf-core/snapaligner/align/test.yml
  tests/subworkflows/nf-core/fastq_align_dna/test.yml
Labels: Ready for Review

#2737 Update jupyternotebook
  modules/nf-core/jupyternotebook/main.nf
Labels: Ready for Review

#2733 Update happy
  modules/nf-core/happy/happy/main.nf
  modules/nf-core/happy/happy/meta.yml
  tests/modules/nf-core/happy/happy/main.nf
Labels: update module, Ready for Review

#2744 new module rtgtools/rocplot
  modules/nf-core/rtgtools/rocplot/main.nf
  modules/nf-core/rtgtools/rocplot/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/rtgtools/rocplot/main.nf
  tests/modules/nf-core/rtgtools/rocplot/nextflow.config
  tests/modules/nf-core/rtgtools/rocplot/test.yml
Labels: new module, Ready for Review

#2750 add stub to bedtools intersect
  modules/nf-core/bedtools/intersect/main.nf
Labels: update module, Ready for Review

#2646 migrate changes to Cell Ranger module tests from UniverSC PR
  tests/modules/nf-core/cellranger/count/nextflow.config
  tests/modules/nf-core/cellranger/count/test.yml
  tests/modules/nf-core/cellranger/mkgtf/test.yml
  tests/modules/nf-core/cellranger/mkref/test.yml
Labels: update module, Ready for Review

#2422 Adding module `sourmash taxonomy annotate`
  modules/nf-core/sourmash/taxannotate/main.nf
  modules/nf-core/sourmash/taxannotate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/sourmash/taxannotate/main.nf
  tests/modules/nf-core/sourmash/taxannotate/nextflow.config
  tests/modules/nf-core/sourmash/taxannotate/test.yml
Labels: new module

#2761 fix(dragmap): Rollback to 1.2.1
  modules/nf-core/dragmap/align/main.nf
  tests/subworkflows/nf-core/fastq_align_dna/test.yml
Labels: bug

#2748 [FEATURE] update trimmomatic to emit summary output
  modules/nf-core/trimmomatic/main.nf
  modules/nf-core/trimmomatic/meta.yml
  tests/modules/nf-core/trimmomatic/main.nf
  tests/modules/nf-core/trimmomatic/test.yml
Labels: enhancement

#2772 untar: need a gnu grep to use -P, also use a consistent tar
  modules/nf-core/untar/main.nf
Labels: Ready for Review

#1150 Adding new module smoothxg
  modules/nf-core/smoothxg/main.nf
  modules/nf-core/smoothxg/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/smoothxg/main.nf
  tests/modules/nf-core/smoothxg/nextflow.config
  tests/modules/nf-core/smoothxg/test.yml
Labels: new module, WIP

#2531 Shinyngs/validator: Make feature file optional
  modules/nf-core/shinyngs/validatefomcomponents/main.nf
  modules/nf-core/shinyngs/validatefomcomponents/meta.yml
  tests/modules/nf-core/shinyngs/validatefomcomponents/main.nf
  tests/modules/nf-core/shinyngs/validatefomcomponents/test.yml
Labels: enhancement

#2779 New module: glimpse ligate
  modules/nf-core/glimpse/ligate/main.nf
  modules/nf-core/glimpse/ligate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/glimpse/ligate/main.nf
  tests/modules/nf-core/glimpse/ligate/nextflow.config
  tests/modules/nf-core/glimpse/ligate/test.yml
Labels: new module, Ready for Review

#2727 New module: Graphtyper/genotype
  modules/nf-core/graphtyper/genotype/main.nf
  modules/nf-core/graphtyper/genotype/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/graphtyper/genotype/main.nf
  tests/modules/nf-core/graphtyper/genotype/nextflow.config
  tests/modules/nf-core/graphtyper/genotype/test.yml
Labels: Ready for Review

#2796 Make untar work for non-gzipped tars
  modules/nf-core/untar/main.nf
  tests/subworkflows/nf-core/fastq_contam_seqtk_kraken/nextflow.config
Labels: Ready for Review

#2790 Add affy/justrma module
  modules/nf-core/affy/justrma/main.nf
  modules/nf-core/affy/justrma/meta.yml
  modules/nf-core/affy/justrma/templates/affy_justrma.R
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/affy/justrma/main.nf
  tests/modules/nf-core/affy/justrma/nextflow.config
  tests/modules/nf-core/affy/justrma/test.yml
Labels: Ready for Review
