Repository nf-core/modules, pull requests merged in 2023-07, with the labels that each got.

#3588 Ucsc update
  modules/nf-core/ucsc/bedgraphtobigwig/main.nf
  modules/nf-core/ucsc/bedtobigbed/main.nf
  modules/nf-core/ucsc/bigwigaverageoverbed/main.nf
  modules/nf-core/ucsc/bigwigaverageoverbed/meta.yml
  modules/nf-core/ucsc/gtftogenepred/main.nf
  modules/nf-core/ucsc/liftover/meta.yml
  modules/nf-core/ucsc/wigtobigwig/main.nf
  modules/nf-core/ucsc/wigtobigwig/meta.yml
  tests/modules/nf-core/ucsc/bedclip/test.yml
  tests/modules/nf-core/ucsc/bedgraphtobigwig/test.yml
  tests/modules/nf-core/ucsc/bedtobigbed/test.yml
  tests/modules/nf-core/ucsc/bigwigaverageoverbed/test.yml
  tests/modules/nf-core/ucsc/gtftogenepred/test.yml
  tests/modules/nf-core/ucsc/wigtobigwig/test.yml
Labels: enhancement, Ready for Review

#3587 Windowmasker update
  modules/nf-core/windowmasker/mkcounts/main.nf
  modules/nf-core/windowmasker/mkcounts/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/windowmasker/mkcounts/main.nf
  tests/modules/nf-core/windowmasker/mkcounts/nextflow.config
  tests/modules/nf-core/windowmasker/mkcounts/test.yml
  tests/modules/nf-core/windowmasker/ustat/main.nf
Labels: enhancement, Ready for Review

#3593 Use `gzip -cd` because `gunzip` preserves the group ownership
  modules/nf-core/gunzip/main.nf
Labels: Ready for Review

#3601 new module: mmseqs2/createdb
  modules/nf-core/mmseqs/createdb/main.nf
  modules/nf-core/mmseqs/createdb/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/mmseqs/createdb/main.nf
  tests/modules/nf-core/mmseqs/createdb/nextflow.config
  tests/modules/nf-core/mmseqs/createdb/test.yml
Labels: new module

#3402 add peka module
  modules/nf-core/peka/main.nf
  modules/nf-core/peka/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/peka/main.nf
  tests/modules/nf-core/peka/nextflow.config
  tests/modules/nf-core/peka/test.yml
Labels: new module

#3438 salmon/quant update to handle multiple pairs of fastqs
  modules/nf-core/salmon/quant/main.nf
  modules/nf-core/salmon/quant/meta.yml
  tests/modules/nf-core/salmon/quant/main.nf
  tests/modules/nf-core/salmon/quant/test.yml
Labels: Ready for Review

#3605 Update bcftools query
  modules/nf-core/bcftools/query/main.nf
  modules/nf-core/bcftools/query/meta.yml
  tests/modules/nf-core/bcftools/query/test.yml
Labels: update module, Ready for Review

#3595 New module: mmseqs/search
  modules/nf-core/mmseqs/search/main.nf
  modules/nf-core/mmseqs/search/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/mmseqs/search/main.nf
  tests/modules/nf-core/mmseqs/search/nextflow.config
  tests/modules/nf-core/mmseqs/search/test.yml
Labels: new module, Ready for Review

#3600 New module: mmseqs/cluster
  modules/nf-core/mmseqs/cluster/main.nf
  modules/nf-core/mmseqs/cluster/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/mmseqs/cluster/main.nf
  tests/modules/nf-core/mmseqs/cluster/nextflow.config
  tests/modules/nf-core/mmseqs/cluster/test.yml
Labels: new module, Ready for Review

#3603 New module: mmseqs/createtsv
  modules/nf-core/mmseqs/createtsv/main.nf
  modules/nf-core/mmseqs/createtsv/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/mmseqs/createtsv/main.nf
  tests/modules/nf-core/mmseqs/createtsv/nextflow.config
  tests/modules/nf-core/mmseqs/createtsv/test.yml
Labels: new module, Ready for Review

#3606 bam_markduplicates_samtools
  subworkflows/nf-core/bam_markduplicates_samtools/main.nf
  subworkflows/nf-core/bam_markduplicates_samtools/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/bam_markduplicates_samtools/main.nf
  tests/subworkflows/nf-core/bam_markduplicates_samtools/nextflow.config
  tests/subworkflows/nf-core/bam_markduplicates_samtools/test.yml
Labels: new subworkflow

#3612 add new module iCount-mini/metagene
  modules/nf-core/icountmini/metagene/main.nf
  modules/nf-core/icountmini/metagene/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/icountmini/metagene/main.nf
  tests/modules/nf-core/icountmini/metagene/nextflow.config
  tests/modules/nf-core/icountmini/metagene/test.yml
Labels: new module, Ready for Review

#3624 NEW MODULE: PURECLIP
  modules/nf-core/pureclip/main.nf
  modules/nf-core/pureclip/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/pureclip/main.nf
  tests/modules/nf-core/pureclip/nextflow.config
  tests/modules/nf-core/pureclip/test.yml
Labels: new module, Ready for Review

#3140 Purecn/run
  modules/nf-core/purecn/run/main.nf
  modules/nf-core/purecn/run/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/purecn/run/main.nf
  tests/modules/nf-core/purecn/run/nextflow.config
  tests/modules/nf-core/purecn/run/test.yml
Labels: new module, hackathon2023

#2933 Hicexplorer hicpca
  modules/nf-core/hicexplorer/hicpca/main.nf
  modules/nf-core/hicexplorer/hicpca/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/hicexplorer/hicpca/main.nf
  tests/modules/nf-core/hicexplorer/hicpca/nextflow.config
  tests/modules/nf-core/hicexplorer/hicpca/test.yml
Labels: Ready for Review

#3623 New module: instrain/compare
  modules/nf-core/instrain/compare/main.nf
  modules/nf-core/instrain/compare/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/instrain/compare/main.nf
  tests/modules/nf-core/instrain/compare/nextflow.config
  tests/modules/nf-core/instrain/compare/test.yml
Labels: new module, Ready for Review

#3665 Update stubs for samtools idxstats
  modules/nf-core/samtools/idxstats/main.nf
  tests/modules/nf-core/samtools/idxstats/main.nf
  tests/modules/nf-core/samtools/idxstats/test.yml
Labels: Ready for Review

#3658 Bump ensembl-vep modules to 110.0
  .github/workflows/pytest-workflow.yml
  modules/nf-core/ensemblvep/download/main.nf
  modules/nf-core/ensemblvep/vep/main.nf
  tests/modules/nf-core/ensemblvep/download/main.nf
  tests/modules/nf-core/ensemblvep/download/test.yml
  tests/modules/nf-core/ensemblvep/vep/main.nf
  tests/modules/nf-core/ensemblvep/vep/nextflow.config
  tests/subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
  tests/subworkflows/nf-core/vcf_annotate_ensemblvep/nextflow.config
  tests/subworkflows/nf-core/vcf_annotate_ensemblvep_snpeff/main.nf
  tests/subworkflows/nf-core/vcf_annotate_ensemblvep_snpeff/nextflow.config
Labels: Do not merge yet

#3671 Update stubs for bwa mem
  modules/nf-core/bwa/mem/main.nf
  tests/modules/nf-core/bwa/mem/main.nf
  tests/modules/nf-core/bwa/mem/test.yml
Labels: Ready for Review

#3667 Additional optional output to homer/annotatepeaks
  modules/nf-core/homer/annotatepeaks/main.nf
  modules/nf-core/homer/annotatepeaks/meta.yml
  tests/modules/nf-core/homer/annotatepeaks/nextflow.config
  tests/modules/nf-core/homer/annotatepeaks/test.yml
Labels: enhancement

#3655 Update: bamtools, gstama, ultra
  modules/nf-core/bamtools/convert/main.nf
  modules/nf-core/bamtools/split/main.nf
  modules/nf-core/bamtools/stats/main.nf
  modules/nf-core/gstama/merge/main.nf
  modules/nf-core/ultra/align/main.nf
  modules/nf-core/ultra/index/main.nf
  modules/nf-core/ultra/pipeline/main.nf
  modules/nf-core/ultra/pipeline/meta.yml
  tests/modules/nf-core/bamtools/convert/test.yml
  tests/modules/nf-core/bamtools/stats/test.yml
  tests/modules/nf-core/ultra/align/main.nf
  tests/modules/nf-core/ultra/align/nextflow.config
  tests/modules/nf-core/ultra/align/test.yml
  tests/modules/nf-core/ultra/index/main.nf
  tests/modules/nf-core/ultra/index/nextflow.config
  tests/modules/nf-core/ultra/index/test.yml
  tests/modules/nf-core/ultra/pipeline/main.nf
  tests/modules/nf-core/ultra/pipeline/nextflow.config
  tests/modules/nf-core/ultra/pipeline/test.yml
Labels: Ready for Review
