Repository nf-core/modules, pull requests merged in 2023-09, with the labels that each got.

#3289 BUSCO: additional outputs
  modules/nf-core/busco/main.nf
  modules/nf-core/busco/meta.yml
Labels: update module

#3573 Add mitohifi/mitohifi module
  .github/workflows/test.yml
  modules/nf-core/mitohifi/mitohifi/main.nf
  modules/nf-core/mitohifi/mitohifi/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/mitohifi/mitohifi/main.nf
  tests/modules/nf-core/mitohifi/mitohifi/nextflow.config
  tests/modules/nf-core/mitohifi/mitohifi/test.yml
Labels: Ready for Review

#3706 Added new module csvtk/join
  modules/nf-core/csvtk/join/main.nf
  modules/nf-core/csvtk/join/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/csvtk/join/main.nf
  tests/modules/nf-core/csvtk/join/nextflow.config
  tests/modules/nf-core/csvtk/join/test.yml
Labels: new module, Ready for Review

#3813 update GATK's annotateintervals and filterintervals, and CNVkit's batch with extra meta fields
  modules/nf-core/cnvkit/batch/main.nf
  modules/nf-core/cnvkit/batch/meta.yml
  modules/nf-core/gatk4/annotateintervals/main.nf
  modules/nf-core/gatk4/annotateintervals/meta.yml
  modules/nf-core/gatk4/filterintervals/main.nf
  modules/nf-core/gatk4/filterintervals/meta.yml
  tests/modules/nf-core/cnvkit/batch/main.nf
  tests/modules/nf-core/gatk4/annotateintervals/main.nf
  tests/modules/nf-core/gatk4/filterintervals/main.nf
Labels: Ready for Review

#3825 add kalign
  modules/nf-core/kalign/align/main.nf
  modules/nf-core/kalign/align/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/kalign/align/main.nf
  tests/modules/nf-core/kalign/align/nextflow.config
  tests/modules/nf-core/kalign/align/test.yml
Labels: Ready for Review

#3763 add new module for conifer
  modules/nf-core/conifer/main.nf
  modules/nf-core/conifer/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/conifer/main.nf
  tests/modules/nf-core/conifer/nextflow.config
  tests/modules/nf-core/conifer/test.yml
Labels: new module, ready to merge

#3804 New module: quilt/quilt
  modules/nf-core/quilt/quilt/main.nf
  modules/nf-core/quilt/quilt/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/quilt/quilt/main.nf
  tests/modules/nf-core/quilt/quilt/nextflow.config
  tests/modules/nf-core/quilt/quilt/test.yml
Labels: new module, ready to merge

#3876 Update main.nf to include stub
  modules/nf-core/seqkit/sliding/main.nf
Labels: ready to merge
