Repository nf-core/modules, pull requests merged in 2023-08, with the labels that each got.

#3680 Update kmcp modules
  modules/nf-core/kmcp/profile/main.nf
  modules/nf-core/kmcp/profile/meta.yml
  modules/nf-core/kmcp/search/main.nf
  modules/nf-core/kmcp/search/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/kmcp/compute/main.nf
  tests/modules/nf-core/kmcp/compute/test.yml
  tests/modules/nf-core/kmcp/profile/main.nf
  tests/modules/nf-core/kmcp/profile/nextflow.config
  tests/modules/nf-core/kmcp/profile/test.yml
  tests/modules/nf-core/kmcp/search/nextflow.config
  tests/modules/nf-core/kmcp/search/test.yml
Labels: update module

#3666 New module: galah
  modules/nf-core/galah/main.nf
  modules/nf-core/galah/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/galah/main.nf
  tests/modules/nf-core/galah/nextflow.config
  tests/modules/nf-core/galah/test.yml
Labels: new module, Ready for Review

#3707 Update shinyngs, remove na.omit() from proteus
  modules/nf-core/proteus/readproteingroups/templates/proteus_readproteingroups.R
  modules/nf-core/shinyngs/app/main.nf
  modules/nf-core/shinyngs/staticdifferential/main.nf
  modules/nf-core/shinyngs/staticexploratory/main.nf
  modules/nf-core/shinyngs/validatefomcomponents/main.nf
  tests/modules/nf-core/proteus/readproteingroups/test.yml
  tests/modules/nf-core/shinyngs/app/test.yml
  tests/modules/nf-core/shinyngs/staticdifferential/test.yml
  tests/modules/nf-core/shinyngs/staticexploratory/main.nf
  tests/modules/nf-core/shinyngs/staticexploratory/nextflow.config
  tests/modules/nf-core/shinyngs/staticexploratory/test.yml
Labels: Ready for Review

#3697 Add module famsa_align
  modules/nf-core/famsa/align/main.nf
  modules/nf-core/famsa/align/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/famsa/align/main.nf
  tests/modules/nf-core/famsa/align/nextflow.config
  tests/modules/nf-core/famsa/align/test.yml
Labels: new module, Ready for Review

#3669 Update CONCOCT_CONCOCT process label
  modules/nf-core/concoct/concoct/main.nf
Labels: update module, Ready for Review

#3719 Update other concoct containers
  modules/nf-core/concoct/concoctcoveragetable/main.nf
  modules/nf-core/concoct/cutupfasta/main.nf
  modules/nf-core/concoct/extractfastabins/main.nf
  modules/nf-core/concoct/mergecutupclustering/main.nf
Labels: Ready for Review

#3730 Add module: Clustalo guidetree
  modules/nf-core/clustalo/guidetree/main.nf
  modules/nf-core/clustalo/guidetree/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/clustalo/guidetree/main.nf
  tests/modules/nf-core/clustalo/guidetree/nextflow.config
  tests/modules/nf-core/clustalo/guidetree/test.yml
Labels: new module, Ready for Review

#3734 Add module: Clustalo align
  modules/nf-core/clustalo/align/main.nf
  modules/nf-core/clustalo/align/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/clustalo/align/main.nf
  tests/modules/nf-core/clustalo/align/nextflow.config
  tests/modules/nf-core/clustalo/align/test.yml
Labels: new module, Ready for Review

#3551 Ashlar
  modules/nf-core/ashlar/main.nf
  modules/nf-core/ashlar/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/ashlar/main.nf
  tests/modules/nf-core/ashlar/nextflow.config
  tests/modules/nf-core/ashlar/test.yml
Labels: Ready for Review, imaging

#3745 Mafft version update
  modules/nf-core/mafft/main.nf
  modules/nf-core/mafft/meta.yml
  tests/modules/nf-core/mafft/test.yml
  tests/subworkflows/nf-core/fasta_newick_epang_gappa/test.yml
Labels: update module

#3751 add bedtools groupby
  modules/nf-core/bedtools/groupby/main.nf
  modules/nf-core/bedtools/groupby/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bedtools/groupby/main.nf
  tests/modules/nf-core/bedtools/groupby/nextflow.config
  tests/modules/nf-core/bedtools/groupby/test.yml
Labels: Ready for Review

#3753 Module quast update to meet guidelines again
  modules/nf-core/quast/main.nf
  modules/nf-core/quast/meta.yml
  tests/modules/nf-core/quast/main.nf
  tests/modules/nf-core/quast/test.yml
Labels: enhancement, Ready for Review

#3760 Add sentieon tnscope
  .github/workflows/test.yml
  modules/nf-core/sentieon/tnscope/main.nf
  modules/nf-core/sentieon/tnscope/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/sentieon/tnscope/main.nf
  tests/modules/nf-core/sentieon/tnscope/nextflow.config
  tests/modules/nf-core/sentieon/tnscope/test.yml
Labels: Ready for Review

#3631 new module: Pairtools stats
  modules/nf-core/pairtools/stats/main.nf
  modules/nf-core/pairtools/stats/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/pairtools/stats/main.nf
  tests/modules/nf-core/pairtools/stats/nextflow.config
  tests/modules/nf-core/pairtools/stats/test.yml
Labels: new module, Ready for Review

#3777 kallisto: add meta information for references
  modules/nf-core/kallisto/index/main.nf
  modules/nf-core/kallisto/index/meta.yml
  tests/modules/nf-core/kallisto/index/main.nf
  tests/modules/nf-core/kallisto/index/test.yml
Labels: update module, Ready for Review

#3766 Stitch
  modules/nf-core/stitch/main.nf
  modules/nf-core/stitch/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/stitch/main.nf
  tests/modules/nf-core/stitch/nextflow.config
  tests/modules/nf-core/stitch/test.yml
Labels: new module, Ready for Review

#3771 STAR: update
  modules/nf-core/star/align/main.nf
  modules/nf-core/star/align/meta.yml
  modules/nf-core/star/genomegenerate/main.nf
  modules/nf-core/star/genomegenerate/meta.yml
  tests/modules/nf-core/star/align/main.nf
  tests/modules/nf-core/star/genomegenerate/main.nf
  tests/subworkflows/nf-core/fastq_align_star/main.nf
Labels: update module, Ready for Review

#3772 New module: star/starsolo
  modules/nf-core/star/starsolo/main.nf
  modules/nf-core/star/starsolo/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/star/starsolo/main.nf
  tests/modules/nf-core/star/starsolo/nextflow.config
  tests/modules/nf-core/star/starsolo/test.yml
Labels: new module

#3765 New module: umitools/group
  modules/nf-core/umitools/group/main.nf
  modules/nf-core/umitools/group/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/umitools/group/main.nf
  tests/modules/nf-core/umitools/group/nextflow.config
  tests/modules/nf-core/umitools/group/test.yml
Labels: new module, Ready for Review
