Repository nf-core/modules, pull requests merged in 2023-04, with the labels that each got.

#3249 update bcftools/annotate
  modules/nf-core/bcftools/annotate/main.nf
  modules/nf-core/bcftools/annotate/meta.yml
  tests/modules/nf-core/bcftools/annotate/main.nf
  tests/modules/nf-core/bcftools/annotate/nextflow.config
  tests/modules/nf-core/bcftools/annotate/test.yml
Labels: Ready for Review

#3243 entrezdirect/esearch test fix
  tests/modules/nf-core/entrezdirect/esearch/main.nf
Labels: bug, tests, Ready for Review

#3252 Added args to main.nf
  modules/nf-core/mcquant/main.nf
  tests/modules/nf-core/mcquant/nextflow.config
Labels: imaging

#3216 Add cadd module
  modules/nf-core/cadd/main.nf
  modules/nf-core/cadd/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/cadd/main.nf
  tests/modules/nf-core/cadd/nextflow.config
  tests/modules/nf-core/cadd/test.yml
Labels: Ready for Review

#3246 Added the MD5 checksums for the delly/call tests
  tests/modules/nf-core/delly/call/test.yml
Labels: tests, Ready for Review

#3152 Windowmasker/convert
  modules/nf-core/windowmasker/convert/main.nf
  modules/nf-core/windowmasker/convert/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/windowmasker/convert/main.nf
  tests/modules/nf-core/windowmasker/convert/nextflow.config
  tests/modules/nf-core/windowmasker/convert/test.yml
Labels: enhancement, Ready for Review, hackathon2023

#3245 Fixed the `bamcmp`module tests
  tests/modules/nf-core/bamcmp/main.nf
  tests/modules/nf-core/bamcmp/test.yml
Labels: bug, tests, Ready for Review

#3242 Cannot use MD5 checksums because the files contain the date of the day
  tests/config/pytest_modules.yml
  tests/modules/nf-core/freebayes/test.yml
  tests/subworkflows/nf-core/bam_variant_calling_sort_freebayes_bcftools/main.nf
  tests/subworkflows/nf-core/bam_variant_calling_sort_freebayes_bcftools/nextflow.config
  tests/subworkflows/nf-core/bam_variant_calling_sort_freebayes_bcftools/test.yml
Labels: bug, tests, Ready for Review

#3248 Updated the MD5 checksums of all controlfreec tests
  tests/modules/nf-core/controlfreec/assesssignificance/test.yml
  tests/modules/nf-core/controlfreec/freec2bed/test.yml
  tests/modules/nf-core/controlfreec/freec2circos/test.yml
  tests/modules/nf-core/controlfreec/makegraph/test.yml
Labels: tests, Ready for Review

#3135 New mitohifi/findmitoreference module
  .github/workflows/pytest-workflow.yml
  modules/nf-core/mitohifi/findmitoreference/main.nf
  modules/nf-core/mitohifi/findmitoreference/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/mitohifi/findmitoreference/main.nf
  tests/modules/nf-core/mitohifi/findmitoreference/nextflow.config
  tests/modules/nf-core/mitohifi/findmitoreference/test.yml
Labels: new module, Ready for Review, hackathon2023

#3244 Fixed the `amps` test
  modules/nf-core/malt/build/meta.yml
  modules/nf-core/malt/run/meta.yml
  modules/nf-core/megan/daa2info/meta.yml
  modules/nf-core/megan/rma2info/meta.yml
  tests/modules/nf-core/amps/main.nf
  tests/modules/nf-core/amps/nextflow.config
Labels: tests, Ready for Review

#3270 Delete logg
  logg
Labels: bug, Ready for Review

#3239 New Module: Seqtk cutN
  modules/nf-core/seqtk/cutn/main.nf
  modules/nf-core/seqtk/cutn/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/seqtk/cutn/main.nf
  tests/modules/nf-core/seqtk/cutn/nextflow.config
  tests/modules/nf-core/seqtk/cutn/test.yml
Labels: new module, Ready for Review

#3262 add custom extra files to vep
  modules/nf-core/ensemblvep/vep/main.nf
  modules/nf-core/ensemblvep/vep/meta.yml
  subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
  subworkflows/nf-core/vcf_annotate_ensemblvep/meta.yml
  tests/modules/nf-core/ensemblvep/vep/main.nf
  tests/subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
Labels: update module, Ready for Review, update subworkflow

#2538 Add gatk4 germlinecnvcaller
  modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
  modules/nf-core/gatk4/germlinecnvcaller/main.nf
  modules/nf-core/gatk4/germlinecnvcaller/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/germlinecnvcaller/main.nf
  tests/modules/nf-core/gatk4/germlinecnvcaller/nextflow.config
  tests/modules/nf-core/gatk4/germlinecnvcaller/test.yml
Labels: bug, help wanted, tests, new module, WIP, DSL2 v2.0, draft

#3240 DEEPVARIANT: add a gzi input field to avoid the problem for compressed fasta file
  modules/nf-core/deepvariant/main.nf
  modules/nf-core/deepvariant/meta.yml
  tests/config/test_data.config
  tests/modules/nf-core/deepvariant/main.nf
  tests/modules/nf-core/deepvariant/test.yml
Labels: update module, Ready for Review

#3180 Addition of new module: interproscan. Issue #3103
  modules/nf-core/interproscan/main.nf
  modules/nf-core/interproscan/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/interproscan/main.nf
  tests/modules/nf-core/interproscan/nextflow.config
  tests/modules/nf-core/interproscan/test.yml
Labels: new module, Ready for Review, hackathon2023

#3258 new module AnnotSV
  .github/workflows/nf-test.yml
  .github/workflows/pytest-workflow.yml
  modules/nf-core/annotsv/annotsv/main.nf
  modules/nf-core/annotsv/annotsv/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/annotsv/annotsv/main.nf
  tests/modules/nf-core/annotsv/annotsv/nextflow.config
  tests/modules/nf-core/annotsv/annotsv/test.yml
Labels: new module, Ready for Review

#3296 Add sample specific resources to VCFanno
  modules/nf-core/vcfanno/main.nf
  modules/nf-core/vcfanno/meta.yml
  tests/modules/nf-core/vcfanno/main.nf
Labels: update module, Ready for Review

#3297 ADD MODULE: gnu/sort
  modules/nf-core/gnu/sort/main.nf
  modules/nf-core/gnu/sort/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/gnu/sort/main.nf
  tests/modules/nf-core/gnu/sort/nextflow.config
  tests/modules/nf-core/gnu/sort/test.yml
Labels: new module, Ready for Review

#3301 feat added gatk4/asereadcounter
  modules/nf-core/gatk4/asereadcounter/main.nf
  modules/nf-core/gatk4/asereadcounter/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/asereadcounter/main.nf
  tests/modules/nf-core/gatk4/asereadcounter/nextflow.config
  tests/modules/nf-core/gatk4/asereadcounter/test.yml
Labels: Ready for Review

#3304 update stub of tabix/bgziptabix
  modules/nf-core/tabix/bgziptabix/main.nf
Labels: update module, Ready for Review

#3305 move around the input of annotsv
  modules/nf-core/annotsv/annotsv/main.nf
  modules/nf-core/annotsv/annotsv/meta.yml
  tests/modules/nf-core/annotsv/annotsv/main.nf
Labels: update module, Ready for Review

#3166 Kmcp compute
  modules/nf-core/kmcp/compute/main.nf
  modules/nf-core/kmcp/compute/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/kmcp/compute/main.nf
  tests/modules/nf-core/kmcp/compute/nextflow.config
  tests/modules/nf-core/kmcp/compute/test.yml
Labels: new module, hackathon2023

#3322 SnpSift Annotation module: Issue #3321
  modules/nf-core/snpsift/annotate/main.nf
  modules/nf-core/snpsift/annotate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/snpsift/annotate/main.nf
  tests/modules/nf-core/snpsift/annotate/nextflow.config
  tests/modules/nf-core/snpsift/annotate/test.yml
Labels: Ready for Review

#3127 Purecn/intervalfile
  modules/nf-core/purecn/intervalfile/main.nf
  modules/nf-core/purecn/intervalfile/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/purecn/intervalfile/main.nf
  tests/modules/nf-core/purecn/intervalfile/nextflow.config
  tests/modules/nf-core/purecn/intervalfile/test.yml
Labels: new module, Ready for Review, hackathon2023

#3325 feat added option of outputing wiggle and bedgraph
  modules/nf-core/star/align/main.nf
  modules/nf-core/star/align/meta.yml
  tests/modules/nf-core/star/align/test.yml
Labels: enhancement, Ready for Review

#3333 new module wisecondorx/gender
  modules/nf-core/wisecondorx/gender/main.nf
  modules/nf-core/wisecondorx/gender/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/wisecondorx/gender/main.nf
  tests/modules/nf-core/wisecondorx/gender/nextflow.config
  tests/modules/nf-core/wisecondorx/gender/test.yml
Labels: new module, Ready for Review

#3298 New module MetaPhlAn4
  modules/nf-core/metaphlan/metaphlan/main.nf
  modules/nf-core/metaphlan/metaphlan/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/metaphlan/metaphlan/main.nf
  tests/modules/nf-core/metaphlan/metaphlan/nextflow.config
  tests/modules/nf-core/metaphlan/metaphlan/test.yml
Labels: Ready for Review
