Repository nf-core/modules, pull requests merged in 2023-06, with the labels that each got.

#3477 Created fcs subworkflow
  .github/workflows/pytest-workflow.yml
  modules/nf-core/fcs/fcsadaptor/main.nf
  subworkflows/nf-core/fasta_clean_fcs/main.nf
  subworkflows/nf-core/fasta_clean_fcs/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/fasta_clean_fcs/main.nf
  tests/subworkflows/nf-core/fasta_clean_fcs/nextflow.config
  tests/subworkflows/nf-core/fasta_clean_fcs/test.yml
Labels: Ready for Review, new subworkflow, subworkflows

#3482 New module: BACPHLIP
  modules/nf-core/bacphlip/main.nf
  modules/nf-core/bacphlip/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bacphlip/main.nf
  tests/modules/nf-core/bacphlip/nextflow.config
  tests/modules/nf-core/bacphlip/test.yml
Labels: new module, Ready for Review

#3486 fix tests for kallistobustools, universc
  modules/nf-core/kallistobustools/count/meta.yml
  tests/modules/nf-core/kallistobustools/count/main.nf
  tests/modules/nf-core/kallistobustools/count/test.yml
  tests/modules/nf-core/universc/main.nf
  tests/modules/nf-core/universc/test.yml
Labels: bug, tests

#3488 Bcftools filter update
  modules/nf-core/bcftools/filter/main.nf
  tests/modules/nf-core/bcftools/filter/main.nf
  tests/modules/nf-core/bcftools/filter/nextflow.config
  tests/modules/nf-core/bcftools/filter/test.yml
Labels: update module, Ready for Review

#3500 adding seqkit grep
  modules/nf-core/seqkit/grep/main.nf
  modules/nf-core/seqkit/grep/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/seqkit/grep/main.nf
  tests/modules/nf-core/seqkit/grep/nextflow.config
  tests/modules/nf-core/seqkit/grep/test.yml
Labels: new module

#3503 NEW module for predicting bacterial host of phages: iPHoP
  modules/nf-core/iphop/download/main.nf
  modules/nf-core/iphop/download/meta.yml
  modules/nf-core/iphop/predict/main.nf
  modules/nf-core/iphop/predict/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/iphop/download/main.nf
  tests/modules/nf-core/iphop/download/nextflow.config
  tests/modules/nf-core/iphop/download/test.yml
  tests/modules/nf-core/iphop/predict/main.nf
  tests/modules/nf-core/iphop/predict/nextflow.config
  tests/modules/nf-core/iphop/predict/test.yml
Labels: new module, Ready for Review

#3501 New module: mmseqs_databases
  modules/nf-core/mmseqs/databases/main.nf
  modules/nf-core/mmseqs/databases/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/mmseqs/databases/main.nf
  tests/modules/nf-core/mmseqs/databases/nextflow.config
  tests/modules/nf-core/mmseqs/databases/test.yml
Labels: new module, Ready for Review

#3509 add args and memory for cdhit
  modules/nf-core/cdhit/cdhit/main.nf
Labels: bug, enhancement

#3512 Add test for stub for kmcp index module
  tests/modules/nf-core/kmcp/index/test.yml
Labels: Ready for Review

#3511 New module: MetaEuk easypredict
  modules/nf-core/metaeuk/easypredict/main.nf
  modules/nf-core/metaeuk/easypredict/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/metaeuk/easypredict/main.nf
  tests/modules/nf-core/metaeuk/easypredict/nextflow.config
  tests/modules/nf-core/metaeuk/easypredict/test.yml
Labels: new module, Ready for Review

#3472 Add spaceranger
  .github/workflows/pytest-workflow.yml
  modules/nf-core/spaceranger/.gitignore
  modules/nf-core/spaceranger/Dockerfile
  modules/nf-core/spaceranger/README.md
  modules/nf-core/spaceranger/count/main.nf
  modules/nf-core/spaceranger/count/meta.yml
  modules/nf-core/spaceranger/mkgtf/main.nf
  modules/nf-core/spaceranger/mkgtf/meta.yml
  modules/nf-core/spaceranger/mkref/main.nf
  modules/nf-core/spaceranger/mkref/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/spaceranger/count/main.nf
  tests/modules/nf-core/spaceranger/count/nextflow.config
  tests/modules/nf-core/spaceranger/count/test.yml
  tests/modules/nf-core/spaceranger/mkgtf/main.nf
  tests/modules/nf-core/spaceranger/mkgtf/nextflow.config
  tests/modules/nf-core/spaceranger/mkgtf/test.yml
  tests/modules/nf-core/spaceranger/mkref/main.nf
  tests/modules/nf-core/spaceranger/mkref/nextflow.config
  tests/modules/nf-core/spaceranger/mkref/test.yml
Labels: Ready for Review

#3522 Adding upd
  modules/nf-core/upd/main.nf
  modules/nf-core/upd/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/upd/main.nf
  tests/modules/nf-core/upd/nextflow.config
  tests/modules/nf-core/upd/test.yml
Labels: draft

#3534 Update wisecondorx predict
  modules/nf-core/wisecondorx/predict/main.nf
  modules/nf-core/wisecondorx/predict/meta.yml
  tests/modules/nf-core/wisecondorx/predict/test.yml
Labels: update module, Ready for Review

#3526 Umitools/dedup adding log and bug workaround
  modules/nf-core/umitools/dedup/main.nf
  modules/nf-core/umitools/dedup/meta.yml
  tests/modules/nf-core/umitools/dedup/test.yml
Labels: Ready for Review

#3536 eklipse module
  modules/nf-core/eklipse/main.nf
  modules/nf-core/eklipse/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/eklipse/main.nf
  tests/modules/nf-core/eklipse/nextflow.config
  tests/modules/nf-core/eklipse/test.yml
Labels: new module, Ready for Review

#3542 Bcftools merge update
  modules/nf-core/bcftools/merge/main.nf
  tests/modules/nf-core/bcftools/merge/main.nf
Labels: Ready for Review

#3549 New module cdhit/cdhitest
  modules/nf-core/cdhit/cdhitest/main.nf
  modules/nf-core/cdhit/cdhitest/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/cdhit/cdhitest/main.nf
  tests/modules/nf-core/cdhit/cdhitest/nextflow.config
  tests/modules/nf-core/cdhit/cdhitest/test.yml
Labels: new module, Ready for Review

#3552 Update upd
  modules/nf-core/upd/main.nf
  tests/modules/nf-core/upd/test.yml
Labels: Ready for Review

#3557 Added a new module: vRhyme (binning of viral assemblies)
  modules/nf-core/vrhyme/extractunbinned/main.nf
  modules/nf-core/vrhyme/extractunbinned/meta.yml
  modules/nf-core/vrhyme/linkbins/main.nf
  modules/nf-core/vrhyme/linkbins/meta.yml
  modules/nf-core/vrhyme/vrhyme/main.nf
  modules/nf-core/vrhyme/vrhyme/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/vrhyme/extractunbinned/main.nf
  tests/modules/nf-core/vrhyme/extractunbinned/nextflow.config
  tests/modules/nf-core/vrhyme/extractunbinned/test.yml
  tests/modules/nf-core/vrhyme/linkbins/main.nf
  tests/modules/nf-core/vrhyme/linkbins/nextflow.config
  tests/modules/nf-core/vrhyme/linkbins/test.yml
  tests/modules/nf-core/vrhyme/vrhyme/main.nf
  tests/modules/nf-core/vrhyme/vrhyme/nextflow.config
  tests/modules/nf-core/vrhyme/vrhyme/test.yml
Labels: new module, Ready for Review

#3554 Adding stubs to frequently used modules
  modules/nf-core/bedtools/bamtobed/main.nf
  modules/nf-core/bedtools/bamtobed/meta.yml
  modules/nf-core/bedtools/genomecov/main.nf
  modules/nf-core/bedtools/genomecov/meta.yml
  modules/nf-core/bedtools/merge/main.nf
  modules/nf-core/bedtools/merge/meta.yml
  modules/nf-core/bedtools/multiinter/main.nf
  modules/nf-core/bedtools/multiinter/meta.yml
  modules/nf-core/bedtools/shift/main.nf
  modules/nf-core/bedtools/slop/main.nf
  modules/nf-core/bedtools/slop/meta.yml
  modules/nf-core/bedtools/sort/main.nf
  modules/nf-core/bedtools/sort/meta.yml
  modules/nf-core/bedtools/subtract/main.nf
  modules/nf-core/bedtools/unionbedg/main.nf
  modules/nf-core/bedtools/unionbedg/meta.yml
  modules/nf-core/cooler/balance/main.nf
  modules/nf-core/cooler/balance/meta.yml
  modules/nf-core/cooler/cload/main.nf
  modules/nf-core/cooler/cload/meta.yml
  modules/nf-core/cooler/digest/main.nf
  modules/nf-core/cooler/digest/meta.yml
  modules/nf-core/cooler/dump/main.nf
  modules/nf-core/cooler/dump/meta.yml
  modules/nf-core/cooler/makebins/main.nf
  modules/nf-core/cooler/makebins/meta.yml
  modules/nf-core/cooler/merge/main.nf
  modules/nf-core/cooler/merge/meta.yml
  modules/nf-core/cooler/zoomify/main.nf
  modules/nf-core/cooler/zoomify/meta.yml
  modules/nf-core/gfastats/main.nf
  modules/nf-core/gfastats/meta.yml
  modules/nf-core/miniprot/align/main.nf
  modules/nf-core/miniprot/index/main.nf
  modules/nf-core/mummer/main.nf
  modules/nf-core/pretextmap/main.nf
  modules/nf-core/samtools/calmd/main.nf
  modules/nf-core/samtools/markdup/main.nf
  modules/nf-core/samtools/markdup/meta.yml
  modules/nf-core/ucsc/bedgraphtobigwig/main.nf
  modules/nf-core/ucsc/bedgraphtobigwig/meta.yml
  modules/nf-core/ucsc/bedtobigbed/main.nf
  modules/nf-core/ucsc/bedtobigbed/meta.yml
  modules/nf-core/yahs/main.nf
  modules/nf-core/yahs/meta.yml
  tests/modules/nf-core/cooler/balance/test.yml
Labels: enhancement

#3561 update modules in GATK's gcnvcaller pipeline
  modules/nf-core/gatk4/collectreadcounts/main.nf
  modules/nf-core/gatk4/collectreadcounts/meta.yml
  modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
  modules/nf-core/gatk4/determinegermlinecontigploidy/meta.yml
  modules/nf-core/gatk4/germlinecnvcaller/main.nf
  modules/nf-core/gatk4/germlinecnvcaller/meta.yml
  modules/nf-core/gatk4/postprocessgermlinecnvcalls/main.nf
  modules/nf-core/gatk4/postprocessgermlinecnvcalls/meta.yml
  tests/modules/nf-core/gatk4/collectreadcounts/main.nf
  tests/modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
  tests/modules/nf-core/gatk4/determinegermlinecontigploidy/test.yml
  tests/modules/nf-core/gatk4/germlinecnvcaller/main.nf
  tests/modules/nf-core/gatk4/germlinecnvcaller/test.yml
  tests/modules/nf-core/gatk4/postprocessgermlinecnvcalls/main.nf
  tests/modules/nf-core/gatk4/postprocessgermlinecnvcalls/nextflow.config
  tests/modules/nf-core/gatk4/postprocessgermlinecnvcalls/test.yml
Labels: Ready for Review

#3569 Gem2/gem indexer
  modules/nf-core/gem2/gemindexer/main.nf
  modules/nf-core/gem2/gemindexer/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gem2/gemindexer/main.nf
  tests/modules/nf-core/gem2/gemindexer/nextflow.config
  tests/modules/nf-core/gem2/gemindexer/test.yml
Labels: new module, Ready for Review

#3570 Gem2/gemmappability
  modules/nf-core/gem2/gemmappability/main.nf
  modules/nf-core/gem2/gemmappability/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gem2/gemmappability/main.nf
  tests/modules/nf-core/gem2/gemmappability/nextflow.config
  tests/modules/nf-core/gem2/gemmappability/test.yml
Labels: update module, Ready for Review

#3572 Gem2/gem2bedmappability
  modules/nf-core/gem2/gem2bedmappability/main.nf
  modules/nf-core/gem2/gem2bedmappability/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gem2/gem2bedmappability/main.nf
  tests/modules/nf-core/gem2/gem2bedmappability/nextflow.config
  tests/modules/nf-core/gem2/gem2bedmappability/test.yml
Labels: new module, Ready for Review
