Repository nf-core/modules, pull requests merged in 2023-02, with the labels that each got.

#2816 New module: Admixture
  modules/nf-core/admixture/main.nf
  modules/nf-core/admixture/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/admixture/main.nf
  tests/modules/nf-core/admixture/nextflow.config
  tests/modules/nf-core/admixture/test.yml
Labels: Ready for Review

#2820 Limma
  modules/nf-core/limma/differential/main.nf
  modules/nf-core/limma/differential/meta.yml
  modules/nf-core/limma/differential/templates/limma_de.R
  tests/config/pytest_modules.yml
  tests/modules/nf-core/limma/differential/main.nf
  tests/modules/nf-core/limma/differential/nextflow.config
  tests/modules/nf-core/limma/differential/test.yml
Labels: Ready for Review

#2824 Added Canu module
  modules/nf-core/canu/main.nf
  modules/nf-core/canu/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/canu/main.nf
  tests/modules/nf-core/canu/nextflow.config
  tests/modules/nf-core/canu/test.yml
Labels: Ready for Review

#2862 new module rtgtools/format
  modules/nf-core/rtgtools/format/main.nf
  modules/nf-core/rtgtools/format/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/rtgtools/format/main.nf
  tests/modules/nf-core/rtgtools/format/nextflow.config
  tests/modules/nf-core/rtgtools/format/test.yml
Labels: new module, Ready for Review

#2791 Added new module: bbmap/sendsketch
  modules/nf-core/bbmap/sendsketch/main.nf
  modules/nf-core/bbmap/sendsketch/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bbmap/sendsketch/main.nf
  tests/modules/nf-core/bbmap/sendsketch/nextflow.config
  tests/modules/nf-core/bbmap/sendsketch/test.yml
Labels: new module, Ready for Review

#2858 New subworkflow vcf_impute_glimpse
  subworkflows/nf-core/vcf_impute_glimpse/main.nf
  subworkflows/nf-core/vcf_impute_glimpse/meta.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/vcf_impute_glimpse/main.nf
  tests/subworkflows/nf-core/vcf_impute_glimpse/nextflow.config
  tests/subworkflows/nf-core/vcf_impute_glimpse/test.yml
Labels: help wanted, Ready for Review, new subworkflow, subworkflows

#2872 Fixed the conda syntax because params.enable_conda is deprecated
  modules/nf-core/gatk4/determinegermlinecontigploidy/main.nf
  modules/nf-core/graphtyper/genotype/main.nf
  modules/nf-core/platypus/main.nf
  modules/nf-core/plink/recode/main.nf
  modules/nf-core/smncopynumbercaller/main.nf
  modules/nf-core/trinity/main.nf
  tests/modules/nf-core/graphtyper/genotype/main.nf
  tests/modules/nf-core/platypus/test.yml
Labels: Ready for Review

#2852 New module: vcflib/vcffilter
  modules/nf-core/vcflib/vcffilter/main.nf
  modules/nf-core/vcflib/vcffilter/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/vcflib/vcffilter/main.nf
  tests/modules/nf-core/vcflib/vcffilter/nextflow.config
  tests/modules/nf-core/vcflib/vcffilter/test.yml
Labels: new module, Ready for Review

#2825 derive annotation from .db packages for affy
  modules/nf-core/affy/justrma/main.nf
  modules/nf-core/affy/justrma/meta.yml
  modules/nf-core/affy/justrma/templates/affy_justrma.R
  tests/modules/nf-core/affy/justrma/nextflow.config
  tests/modules/nf-core/affy/justrma/test.yml
Labels: Ready for Review

#1706 Add Universc
  .github/workflows/pytest-workflow.yml
  modules/nf-core/universc/CITATION.cff
  modules/nf-core/universc/CITATION.md
  modules/nf-core/universc/README.md
  modules/nf-core/universc/main.nf
  modules/nf-core/universc/meta.yml
  tests/config/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/universc/main.nf
  tests/modules/nf-core/universc/nextflow.config
  tests/modules/nf-core/universc/test.yml
Labels: new module, Ready for Review, DSL2 v2.0

#2863 Add taxpasta/merge
  modules/nf-core/taxpasta/merge/main.nf
  modules/nf-core/taxpasta/merge/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/taxpasta/merge/main.nf
  tests/modules/nf-core/taxpasta/merge/nextflow.config
  tests/modules/nf-core/taxpasta/merge/test.yml
Labels: new module, Ready for Review

#2873 New module shapeit5 phase common
  modules/nf-core/shapeit5/phasecommon/main.nf
  modules/nf-core/shapeit5/phasecommon/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/shapeit5/phasecommon/main.nf
  tests/modules/nf-core/shapeit5/phasecommon/nextflow.config
  tests/modules/nf-core/shapeit5/phasecommon/test.yml
Labels: new module, Ready for Review

#2882 Add output prefixing for affy/justrma
  modules/nf-core/affy/justrma/main.nf
  modules/nf-core/affy/justrma/templates/affy_justrma.R
  tests/modules/nf-core/affy/justrma/nextflow.config
  tests/modules/nf-core/affy/justrma/test.yml
Labels: Ready for Review

#2883 Minor limma fixes
  modules/nf-core/limma/differential/templates/limma_de.R
  tests/modules/nf-core/limma/differential/main.nf
Labels: Ready for Review

#2884 custom/matrixfilter fixes
  modules/nf-core/custom/matrixfilter/templates/matrixfilter.R
Labels: Ready for Review

#2885 add stub section to SMNcopynumbercaller
  modules/nf-core/smncopynumbercaller/main.nf
Labels: update module, Ready for Review

#2890 affy/justrma and limma/differential minor fixes
  modules/nf-core/affy/justrma/templates/affy_justrma.R
  modules/nf-core/limma/differential/templates/limma_de.R
  tests/modules/nf-core/affy/justrma/test.yml
Labels: Ready for Review

#2891 New module Tiara
  modules/nf-core/tiara/tiara/main.nf
  modules/nf-core/tiara/tiara/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/tiara/tiara/main.nf
  tests/modules/nf-core/tiara/tiara/nextflow.config
  tests/modules/nf-core/tiara/tiara/test.yml
Labels: new module, Ready for Review

#2689 Update vcf relate somalier
  subworkflows/nf-core/vcf_extract_relate_somalier/main.nf
  subworkflows/nf-core/vcf_extract_relate_somalier/meta.yml
  tests/subworkflows/nf-core/vcf_extract_relate_somalier/main.nf
  tests/subworkflows/nf-core/vcf_extract_relate_somalier/test.yml
Labels: Ready for Review, update subworkflow

#2904 new module paragraph/idxdepth
  modules/nf-core/paragraph/idxdepth/main.nf
  modules/nf-core/paragraph/idxdepth/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/paragraph/idxdepth/main.nf
  tests/modules/nf-core/paragraph/idxdepth/nextflow.config
  tests/modules/nf-core/paragraph/idxdepth/test.yml
Labels: new module, Ready for Review

#2916 Add description to gatk4/splitintervals
  modules/nf-core/gatk4/splitintervals/meta.yml
Labels: documentation, Ready for Review

#2909 add VCF output/input to delly/call
  modules/nf-core/delly/call/main.nf
  modules/nf-core/delly/call/meta.yml
  tests/modules/nf-core/delly/call/main.nf
  tests/modules/nf-core/delly/call/nextflow.config
  tests/modules/nf-core/delly/call/test.yml
Labels: update module, Ready for Review

#2898 new module paragraph/multigrmpy
  modules/nf-core/paragraph/multigrmpy/main.nf
  modules/nf-core/paragraph/multigrmpy/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/paragraph/multigrmpy/main.nf
  tests/modules/nf-core/paragraph/multigrmpy/nextflow.config
  tests/modules/nf-core/paragraph/multigrmpy/test.yml
Labels: new module, Ready for Review

#2888 Shapeit5 ligate
  modules/nf-core/shapeit5/ligate/main.nf
  modules/nf-core/shapeit5/ligate/meta.yml
  modules/nf-core/shapeit5/phasecommon/main.nf
  tests/config/pytest_modules.yml
  tests/modules/nf-core/shapeit5/ligate/main.nf
  tests/modules/nf-core/shapeit5/ligate/nextflow.config
  tests/modules/nf-core/shapeit5/ligate/test.yml
  tests/modules/nf-core/shapeit5/phasecommon/test.yml
Labels: new module

#2925 smncopynumbercaller change echo newline character
  modules/nf-core/smncopynumbercaller/main.nf
Labels: bug

#2648 new module survivor/merge
  modules/nf-core/survivor/merge/main.nf
  modules/nf-core/survivor/merge/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/survivor/merge/main.nf
  tests/modules/nf-core/survivor/merge/nextflow.config
  tests/modules/nf-core/survivor/merge/test.yml
Labels: new module, Ready for Review
