Repository nf-core/modules, pull requests merged in 2023-05, with the labels that each got.

#3349 Sbwf impute glimpse2
  modules/nf-core/glimpse/chunk/meta.yml
  modules/nf-core/glimpse/phase/main.nf
  modules/nf-core/glimpse/phase/meta.yml
  modules/nf-core/glimpse2/chunk/main.nf
  modules/nf-core/glimpse2/phase/main.nf
  modules/nf-core/glimpse2/phase/meta.yml
  modules/nf-core/glimpse2/splitreference/main.nf
  subworkflows/nf-core/multiple_impute_glimpse2/main.nf
  subworkflows/nf-core/multiple_impute_glimpse2/meta.yml
  subworkflows/nf-core/vcf_impute_glimpse/main.nf
  subworkflows/nf-core/vcf_impute_glimpse/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/glimpse/chunk/main.nf
  tests/modules/nf-core/glimpse/chunk/test.yml
  tests/modules/nf-core/glimpse/concordance/main.nf
  tests/modules/nf-core/glimpse/ligate/main.nf
  tests/modules/nf-core/glimpse/phase/main.nf
  tests/modules/nf-core/glimpse/sample/main.nf
  tests/modules/nf-core/glimpse2/chunk/main.nf
  tests/modules/nf-core/glimpse2/concordance/main.nf
  tests/modules/nf-core/glimpse2/concordance/test.yml
  tests/modules/nf-core/glimpse2/ligate/main.nf
  tests/modules/nf-core/glimpse2/ligate/test.yml
  tests/modules/nf-core/glimpse2/phase/main.nf
  tests/modules/nf-core/glimpse2/phase/test.yml
  tests/subworkflows/nf-core/multiple_impute_glimpse2/main.nf
  tests/subworkflows/nf-core/multiple_impute_glimpse2/nextflow.config
  tests/subworkflows/nf-core/multiple_impute_glimpse2/test.yml
  tests/subworkflows/nf-core/vcf_impute_glimpse/main.nf
  tests/subworkflows/nf-core/vcf_impute_glimpse/test.yml
Labels: update module, new subworkflow, update subworkflow

#3145 Islandpath
  .github/workflows/pytest-workflow.yml
  modules/nf-core/islandpath/main.nf
  modules/nf-core/islandpath/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/islandpath/main.nf
  tests/modules/nf-core/islandpath/nextflow.config
  tests/modules/nf-core/islandpath/test.yml
Labels: new module, Ready for Review, hackathon2023

#3331 New module : Pilon
  modules/nf-core/pilon/main.nf
  modules/nf-core/pilon/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/pilon/main.nf
  tests/modules/nf-core/pilon/nextflow.config
  tests/modules/nf-core/pilon/test.yml
Labels: new module

#3184 Update panaroo/run version
  modules/nf-core/panaroo/run/main.nf
  tests/modules/nf-core/panaroo/run/test.yml
Labels: update module, Ready for Review, hackathon2023

#3376 add stub to bcftools query
  modules/nf-core/bcftools/query/main.nf
Labels: update module, Ready for Review

#3377 new module bcftools/pluginscatter
  modules/nf-core/bcftools/pluginscatter/main.nf
  modules/nf-core/bcftools/pluginscatter/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bcftools/pluginscatter/main.nf
  tests/modules/nf-core/bcftools/pluginscatter/nextflow.config
  tests/modules/nf-core/bcftools/pluginscatter/test.yml
Labels: new module, Ready for Review

#3375 new module bcftools/pluginsplit
  modules/nf-core/bcftools/pluginsplit/main.nf
  modules/nf-core/bcftools/pluginsplit/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bcftools/pluginsplit/main.nf
  tests/modules/nf-core/bcftools/pluginsplit/nextflow.config
  tests/modules/nf-core/bcftools/pluginsplit/test.yml
Labels: new module, Ready for Review

#3342 Create a new module mergemetaphlantables
  modules/nf-core/metaphlan/mergemetaphlantables/main.nf
  modules/nf-core/metaphlan/mergemetaphlantables/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/metaphlan/mergemetaphlantables/main.nf
  tests/modules/nf-core/metaphlan/mergemetaphlantables/nextflow.config
  tests/modules/nf-core/metaphlan/mergemetaphlantables/test.yml
Labels: new module, Ready for Review

#3366 Newmodule ultraplex
  modules/nf-core/ultraplex/main.nf
  modules/nf-core/ultraplex/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/ultraplex/main.nf
  tests/modules/nf-core/ultraplex/nextflow.config
  tests/modules/nf-core/ultraplex/test.yml
Labels: new module

#3392 update expansionhunter
  modules/nf-core/expansionhunter/main.nf
  modules/nf-core/expansionhunter/meta.yml
  tests/modules/nf-core/expansionhunter/main.nf
  tests/modules/nf-core/expansionhunter/test.yml
Labels: update module, Ready for Review

#3368 add umicollapse
  modules/nf-core/umicollapse/main.nf
  modules/nf-core/umicollapse/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/umicollapse/main.nf
  tests/modules/nf-core/umicollapse/nextflow.config
  tests/modules/nf-core/umicollapse/test.yml
Labels: new module, Ready for Review

#3229 new module: `cellranger multi`
  .github/workflows/pytest-workflow.yml
  modules/nf-core/cellranger/README.md
  modules/nf-core/cellranger/mkfastq/README.md
  modules/nf-core/cellranger/mkref/meta.yml
  modules/nf-core/cellranger/mkvdjref/meta.yml
  modules/nf-core/cellranger/multi/main.nf
  modules/nf-core/cellranger/multi/meta.yml
  tests/config/pytest_modules.yml
  tests/config/test_data.config
  tests/modules/nf-core/cellranger/count/main.nf
  tests/modules/nf-core/cellranger/count/test.yml
  tests/modules/nf-core/cellranger/multi/main.nf
  tests/modules/nf-core/cellranger/multi/nextflow.config
  tests/modules/nf-core/cellranger/multi/test.yml
  tests/modules/nf-core/cellranger/vdj/main.nf
  tests/modules/nf-core/cellranger/vdj/test.yml
Labels: new module, Ready for Review

#3424 Updates for BGZIPTABIX
  modules/nf-core/tabix/bgziptabix/main.nf
  modules/nf-core/tabix/bgziptabix/meta.yml
  tests/modules/nf-core/tabix/bgziptabix/main.nf
  tests/modules/nf-core/tabix/bgziptabix/nextflow.config
  tests/modules/nf-core/tabix/bgziptabix/test.yml
Labels: enhancement

#3385 Update vep subwf
  .github/workflows/pytest-workflow.yml
  modules/nf-core/bcftools/query/main.nf
  subworkflows/nf-core/vcf_annotate_ensemblvep_snpeff/main.nf
  subworkflows/nf-core/vcf_annotate_ensemblvep_snpeff/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bcftools/query/test.yml
  tests/subworkflows/nf-core/vcf_annotate_ensemblvep_snpeff/main.nf
  tests/subworkflows/nf-core/vcf_annotate_ensemblvep_snpeff/nextflow.config
  tests/subworkflows/nf-core/vcf_annotate_ensemblvep_snpeff/test.yml
Labels: Ready for Review, update subworkflow

#3427 feat renamed hmtnote to hmtnote/annotate
  modules/nf-core/hmtnote/annotate/main.nf
  modules/nf-core/hmtnote/annotate/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/hmtnote/annotate/main.nf
  tests/modules/nf-core/hmtnote/annotate/nextflow.config
  tests/modules/nf-core/hmtnote/annotate/test.yml
  tests/modules/nf-core/hmtnote/test.yml
Labels: Ready for Review

#3429 update input params for bcftools
  modules/nf-core/bcftools/convert/main.nf
  modules/nf-core/bcftools/convert/meta.yml
  modules/nf-core/bcftools/merge/main.nf
  modules/nf-core/bcftools/merge/meta.yml
  modules/nf-core/bcftools/norm/main.nf
  modules/nf-core/bcftools/norm/meta.yml
  modules/nf-core/bcftools/reheader/main.nf
  modules/nf-core/bcftools/reheader/meta.yml
  tests/modules/nf-core/bcftools/convert/main.nf
  tests/modules/nf-core/bcftools/merge/main.nf
  tests/modules/nf-core/bcftools/norm/main.nf
  tests/modules/nf-core/bcftools/norm/test.yml
  tests/modules/nf-core/bcftools/reheader/main.nf
  tests/modules/nf-core/bcftools/reheader/test.yml
Labels: Ready for Review

#3430 Update input params for gatk4 modules
  modules/nf-core/gatk4/bedtointervallist/main.nf
  modules/nf-core/gatk4/bedtointervallist/meta.yml
  modules/nf-core/gatk4/createsequencedictionary/main.nf
  modules/nf-core/gatk4/createsequencedictionary/meta.yml
  modules/nf-core/gatk4/createsomaticpanelofnormals/main.nf
  modules/nf-core/gatk4/createsomaticpanelofnormals/meta.yml
  modules/nf-core/gatk4/filtermutectcalls/main.nf
  modules/nf-core/gatk4/filtermutectcalls/meta.yml
  modules/nf-core/gatk4/getpileupsummaries/main.nf
  modules/nf-core/gatk4/getpileupsummaries/meta.yml
  modules/nf-core/gatk4/mergebamalignment/main.nf
  modules/nf-core/gatk4/mergebamalignment/meta.yml
  modules/nf-core/gatk4/mutect2/main.nf
  modules/nf-core/gatk4/mutect2/meta.yml
  modules/nf-core/gatk4/printreads/main.nf
  modules/nf-core/gatk4/printreads/meta.yml
  modules/nf-core/gatk4/splitintervals/main.nf
  modules/nf-core/gatk4/splitintervals/meta.yml
  modules/nf-core/gatk4/variantfiltration/main.nf
  modules/nf-core/gatk4/variantfiltration/meta.yml
  subworkflows/nf-core/bam_create_som_pon_gatk/main.nf
  tests/modules/nf-core/gatk4/bedtointervallist/main.nf
  tests/modules/nf-core/gatk4/createsequencedictionary/main.nf
  tests/modules/nf-core/gatk4/createsomaticpanelofnormals/main.nf
  tests/modules/nf-core/gatk4/filtermutectcalls/main.nf
  tests/modules/nf-core/gatk4/getpileupsummaries/main.nf
  tests/modules/nf-core/gatk4/mergebamalignment/main.nf
  tests/modules/nf-core/gatk4/mutect2/main.nf
  tests/modules/nf-core/gatk4/printreads/main.nf
  tests/modules/nf-core/gatk4/splitintervals/main.nf
  tests/modules/nf-core/gatk4/variantfiltration/main.nf
  tests/subworkflows/nf-core/bam_create_som_pon_gatk/main.nf
  tests/subworkflows/nf-core/bam_tumor_normal_somatic_variant_calling_gatk/main.nf
  tests/subworkflows/nf-core/bam_tumor_only_somatic_variant_calling_gatk/main.nf
Labels: Ready for Review

#3132 Purecn/coverage
  modules/nf-core/purecn/coverage/main.nf
  modules/nf-core/purecn/coverage/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/purecn/coverage/main.nf
  tests/modules/nf-core/purecn/coverage/nextflow.config
  tests/modules/nf-core/purecn/coverage/test.yml
Labels: new module, Ready for Review, hackathon2023

#3445 update input parameters
  modules/nf-core/samtools/view/main.nf
  modules/nf-core/samtools/view/meta.yml
  subworkflows/nf-core/bam_split_by_region/main.nf
  subworkflows/nf-core/fastq_create_umi_consensus_fgbio/main.nf
  tests/modules/nf-core/samtools/view/main.nf
Labels: Ready for Review

#3447 update input parameters for expansionhunter and stranger
  modules/nf-core/expansionhunter/meta.yml
  modules/nf-core/expansionhunterdenovo/merge/main.nf
  modules/nf-core/expansionhunterdenovo/merge/meta.yml
  modules/nf-core/expansionhunterdenovo/profile/main.nf
  modules/nf-core/expansionhunterdenovo/profile/meta.yml
  modules/nf-core/stranger/main.nf
  modules/nf-core/stranger/meta.yml
  tests/modules/nf-core/expansionhunterdenovo/merge/main.nf
  tests/modules/nf-core/expansionhunterdenovo/profile/main.nf
  tests/modules/nf-core/stranger/main.nf
  tests/modules/nf-core/stranger/nextflow.config
  tests/modules/nf-core/stranger/test.yml
Labels: Ready for Review

#3454 update samtools/faidx
  modules/nf-core/samtools/faidx/main.nf
  modules/nf-core/samtools/faidx/meta.yml
  tests/modules/nf-core/samtools/faidx/main.nf
  tests/modules/nf-core/samtools/faidx/nextflow.config
  tests/modules/nf-core/samtools/faidx/test.yml
Labels: Ready for Review

#3453 add module: PhiSpy
  modules/nf-core/phispy/main.nf
  modules/nf-core/phispy/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/phispy/main.nf
  tests/modules/nf-core/phispy/nextflow.config
  tests/modules/nf-core/phispy/test.yml
Labels: new module, Ready for Review

#3461 update stubs for samtools faidx
  modules/nf-core/samtools/faidx/main.nf
  tests/modules/nf-core/samtools/faidx/main.nf
  tests/modules/nf-core/samtools/faidx/nextflow.config
  tests/modules/nf-core/samtools/faidx/test.yml
Labels: Ready for Review

#3129 Purecn/normaldb
  modules/nf-core/purecn/normaldb/main.nf
  modules/nf-core/purecn/normaldb/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/purecn/normaldb/main.nf
  tests/modules/nf-core/purecn/normaldb/nextflow.config
  tests/modules/nf-core/purecn/normaldb/test.yml
Labels: new module, Ready for Review, hackathon2023

#3451 Added genomad/download and genomad/endtoend modules
  modules/nf-core/genomad/download/main.nf
  modules/nf-core/genomad/download/meta.yml
  modules/nf-core/genomad/endtoend/main.nf
  modules/nf-core/genomad/endtoend/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/genomad/download/main.nf
  tests/modules/nf-core/genomad/download/nextflow.config
  tests/modules/nf-core/genomad/download/test.yml
  tests/modules/nf-core/genomad/endtoend/main.nf
  tests/modules/nf-core/genomad/endtoend/nextflow.config
  tests/modules/nf-core/genomad/endtoend/test.yml
Labels: new module, Ready for Review

#3465 Add purecn/normaldb test data to config and fix paths in tests
  tests/config/test_data.config
  tests/modules/nf-core/purecn/normaldb/main.nf
Labels: Ready for Review
