Repository nf-core/modules, pull requests merged in 2024-06, with the labels that each got.

#3628 new modules: Pairtools split
  modules/nf-core/pairtools/split/environment.yml
  modules/nf-core/pairtools/split/main.nf
  modules/nf-core/pairtools/split/meta.yml
  modules/nf-core/pairtools/split/tests/main.nf.test
  modules/nf-core/pairtools/split/tests/main.nf.test.snap
  modules/nf-core/pairtools/split/tests/tags.yml
Labels: new module

#4509 4445 bbmap pytest to nf test
  modules/nf-core/bbmap/bbduk/environment.yml
  modules/nf-core/bbmap/bbduk/main.nf
  modules/nf-core/bbmap/bbduk/tests/main.nf.test
  modules/nf-core/bbmap/bbduk/tests/main.nf.test.snap
  modules/nf-core/bbmap/bbduk/tests/nextflow.config
  modules/nf-core/bbmap/bbduk/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bbmap/bbduk/main.nf
  tests/modules/nf-core/bbmap/bbduk/test.yml
Labels: nf-test, mismatched hashes

#5775 Update KMCP/PROFILE: add's nf-test, bumps versions, removes non-manadatory input channel
  modules/nf-core/kmcp/profile/environment.yml
  modules/nf-core/kmcp/profile/main.nf
  modules/nf-core/kmcp/profile/meta.yml
  modules/nf-core/kmcp/profile/tests/main.nf.test
  modules/nf-core/kmcp/profile/tests/main.nf.test.snap
  modules/nf-core/kmcp/profile/tests/nextflow.config
  modules/nf-core/kmcp/profile/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/kmcp/profile/main.nf
  tests/modules/nf-core/kmcp/profile/nextflow.config
  tests/modules/nf-core/kmcp/profile/test.yml
Labels: Ready for Review

#5778 Bumped up blast to 2.15.0
  modules/nf-core/blast/blastn/environment.yml
  modules/nf-core/blast/blastn/main.nf
  modules/nf-core/blast/blastn/tests/main.nf.test.snap
  modules/nf-core/blast/blastp/environment.yml
  modules/nf-core/blast/blastp/main.nf
  modules/nf-core/blast/blastp/meta.yml
  modules/nf-core/blast/blastp/tests/main.nf.test
  modules/nf-core/blast/blastp/tests/main.nf.test.snap
  modules/nf-core/blast/tblastn/environment.yml
  modules/nf-core/blast/tblastn/main.nf
  modules/nf-core/blast/tblastn/tests/main.nf.test
  modules/nf-core/blast/tblastn/tests/main.nf.test.snap
Labels: Ready for Review

#5790 Update dsh-bio to 2.4
  modules/nf-core/dshbio/exportsegments/environment.yml
  modules/nf-core/dshbio/exportsegments/main.nf
  modules/nf-core/dshbio/filterbed/environment.yml
  modules/nf-core/dshbio/filterbed/main.nf
  modules/nf-core/dshbio/filtergff3/environment.yml
  modules/nf-core/dshbio/filtergff3/main.nf
  modules/nf-core/dshbio/splitbed/environment.yml
  modules/nf-core/dshbio/splitbed/main.nf
  modules/nf-core/dshbio/splitgff3/environment.yml
  modules/nf-core/dshbio/splitgff3/main.nf
Labels: Ready for Review

#4466 Create nf-test for biscuit/biscuitblaster
  modules/nf-core/biscuit/biscuitblaster/main.nf
  modules/nf-core/biscuit/biscuitblaster/tests/main.nf.test
  modules/nf-core/biscuit/biscuitblaster/tests/main.nf.test.snap
  modules/nf-core/biscuit/biscuitblaster/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/biscuit/biscuitblaster/main.nf
  tests/modules/nf-core/biscuit/biscuitblaster/nextflow.config
  tests/modules/nf-core/biscuit/biscuitblaster/test.yml
Labels: nf-test

#2703 enhancement: add parameter for fastp to make writing of trimmed fastqs optional
  modules/nf-core/fastp/main.nf
  modules/nf-core/fastp/meta.yml
  modules/nf-core/fastp/tests/main.nf.test
  modules/nf-core/fastp/tests/main.nf.test.snap
  modules/nf-core/humid/tests/main.nf.test
  modules/nf-core/humid/tests/main.nf.test.snap
  subworkflows/nf-core/fastq_fastqc_umitools_fastp/main.nf
  subworkflows/nf-core/fastq_fastqc_umitools_fastp/tests/main.nf.test.snap
Labels: enhancement, Ready for Review

#4475 Replace pytest with nf-test for biscuit/mergecg
  modules/nf-core/biscuit/mergecg/main.nf
  modules/nf-core/biscuit/mergecg/tests/main.nf.test
  modules/nf-core/biscuit/mergecg/tests/main.nf.test.snap
  modules/nf-core/biscuit/mergecg/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/biscuit/mergecg/main.nf
  tests/modules/nf-core/biscuit/mergecg/nextflow.config
  tests/modules/nf-core/biscuit/mergecg/test.yml
Labels: nf-test

#5225 nf-test for shovill
  modules/nf-core/shovill/tests/main.nf.test
  modules/nf-core/shovill/tests/main.nf.test.snap
  modules/nf-core/shovill/tests/nextflow.megahit.config
  modules/nf-core/shovill/tests/nextflow.skesa.config
  modules/nf-core/shovill/tests/nextflow.spades.config
  modules/nf-core/shovill/tests/nextflow.velvet.config
  modules/nf-core/shovill/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/shovill/main.nf
  tests/modules/nf-core/shovill/nextflow.config
  tests/modules/nf-core/shovill/test.yml
Labels: Ready for Review

#4668 sourmash/index stub, nf-test, snap
  modules/nf-core/sourmash/index/main.nf
  modules/nf-core/sourmash/index/meta.yml
  modules/nf-core/sourmash/index/tests/main.nf.test
  modules/nf-core/sourmash/index/tests/main.nf.test.snap
  modules/nf-core/sourmash/index/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/sourmash/index/main.nf
  tests/modules/nf-core/sourmash/index/nextflow.config
  tests/modules/nf-core/sourmash/index/test.yml
Labels: help wanted, nf-test

#2206 Bbmap filterbyname
  .gitignore
  modules/nf-core/bbmap/filterbyname/environment.yml
  modules/nf-core/bbmap/filterbyname/main.nf
  modules/nf-core/bbmap/filterbyname/meta.yml
  modules/nf-core/bbmap/filterbyname/tests/main.nf.test
  modules/nf-core/bbmap/filterbyname/tests/main.nf.test.snap
  modules/nf-core/bbmap/filterbyname/tests/tags.yml
Labels: Ready for Review

#5544 Unicycler nftest
  modules/nf-core/unicycler/environment.yml
  modules/nf-core/unicycler/main.nf
  modules/nf-core/unicycler/tests/main.nf.test
  modules/nf-core/unicycler/tests/main.nf.test.snap
  modules/nf-core/unicycler/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/unicycler/main.nf
  tests/modules/nf-core/unicycler/nextflow.config
  tests/modules/nf-core/unicycler/test.yml
Labels: Ready for Review

#2674 `--output-unselected` option in `samtools view`
  modules/nf-core/samtools/view/main.nf
  modules/nf-core/samtools/view/meta.yml
  modules/nf-core/samtools/view/tests/main.nf.test
  modules/nf-core/samtools/view/tests/main.nf.test.snap
Labels: update module, Ready for Review

#5284 nf-test for snpsites
  modules/nf-core/snpsites/main.nf
  modules/nf-core/snpsites/meta.yml
  modules/nf-core/snpsites/tests/main.nf.test
  modules/nf-core/snpsites/tests/main.nf.test.snap
  modules/nf-core/snpsites/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/snpsites/main.nf
  tests/modules/nf-core/snpsites/nextflow.config
  tests/modules/nf-core/snpsites/test.yml
Labels: nf-test

#5293 nf-test for pilon
  modules/nf-core/pilon/main.nf
  modules/nf-core/pilon/meta.yml
  modules/nf-core/pilon/tests/main.nf.test
  modules/nf-core/pilon/tests/main.nf.test.snap
  modules/nf-core/pilon/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/pilon/main.nf
  tests/modules/nf-core/pilon/nextflow.config
  tests/modules/nf-core/pilon/test.yml
Labels: nf-test
