Repository nf-core/modules, pull requests merged in 2024-10, with the labels that each got.

#6720 pypgx/createinputvcf
  modules/nf-core/pypgx/createinputvcf/environment.yml
  modules/nf-core/pypgx/createinputvcf/main.nf
  modules/nf-core/pypgx/createinputvcf/meta.yml
  modules/nf-core/pypgx/createinputvcf/tests/main.nf.test
  modules/nf-core/pypgx/createinputvcf/tests/main.nf.test.snap
  modules/nf-core/pypgx/createinputvcf/tests/tags.yml
Labels: new module

#6718 Add bcftools/pluginsetgt
  modules/nf-core/bcftools/pluginsetgt/environment.yml
  modules/nf-core/bcftools/pluginsetgt/main.nf
  modules/nf-core/bcftools/pluginsetgt/meta.yml
  modules/nf-core/bcftools/pluginsetgt/tests/main.nf.test
  modules/nf-core/bcftools/pluginsetgt/tests/main.nf.test.snap
  modules/nf-core/bcftools/pluginsetgt/tests/nextflow.config
  modules/nf-core/bcftools/pluginsetgt/tests/vcf_gz_index.config
  modules/nf-core/bcftools/pluginsetgt/tests/vcf_gz_index_csi.config
  modules/nf-core/bcftools/pluginsetgt/tests/vcf_gz_index_tbi.config
Labels: Ready for Review

#6706 Add seqkit translate
  modules/nf-core/seqkit/translate/environment.yml
  modules/nf-core/seqkit/translate/main.nf
  modules/nf-core/seqkit/translate/meta.yml
  modules/nf-core/seqkit/translate/tests/main.nf.test
  modules/nf-core/seqkit/translate/tests/main.nf.test.snap
Labels: new module

#6754 Bump openms tools to version 3.2.0
  modules/nf-core/openms/decoydatabase/environment.yml
  modules/nf-core/openms/decoydatabase/main.nf
  modules/nf-core/openms/decoydatabase/tests/main.nf.test.snap
  modules/nf-core/openms/idfilter/environment.yml
  modules/nf-core/openms/idfilter/main.nf
  modules/nf-core/openms/idfilter/tests/main.nf.test.snap
  modules/nf-core/openms/idmassaccuracy/environment.yml
  modules/nf-core/openms/idmassaccuracy/main.nf
  modules/nf-core/openms/idmassaccuracy/tests/main.nf.test.snap
  modules/nf-core/openms/idmerger/environment.yml
  modules/nf-core/openms/idmerger/main.nf
  modules/nf-core/openms/idmerger/tests/main.nf.test.snap
  modules/nf-core/openms/idripper/environment.yml
  modules/nf-core/openms/idripper/main.nf
  modules/nf-core/openms/idripper/tests/main.nf.test.snap
  modules/nf-core/openms/idscoreswitcher/environment.yml
  modules/nf-core/openms/idscoreswitcher/main.nf
  modules/nf-core/openms/idscoreswitcher/tests/main.nf.test.snap
  modules/nf-core/openms/peakpickerhires/environment.yml
  modules/nf-core/openms/peakpickerhires/main.nf
  modules/nf-core/openms/peakpickerhires/tests/main.nf.test.snap
  modules/nf-core/openms/peptideindexer/environment.yml
  modules/nf-core/openms/peptideindexer/main.nf
  modules/nf-core/openms/peptideindexer/tests/main.nf.test.snap
  modules/nf-core/openmsthirdparty/cometadapter/environment.yml
  modules/nf-core/openmsthirdparty/cometadapter/main.nf
  modules/nf-core/openmsthirdparty/cometadapter/meta.yml
  modules/nf-core/openmsthirdparty/cometadapter/tests/main.nf.test.snap
Labels: Ready for Review

#6729 Pypgx/preparedepthofcoverage
  modules/nf-core/pypgx/preparedepthofcoverage/environment.yml
  modules/nf-core/pypgx/preparedepthofcoverage/main.nf
  modules/nf-core/pypgx/preparedepthofcoverage/meta.yml
  modules/nf-core/pypgx/preparedepthofcoverage/tests/main.nf.test
  modules/nf-core/pypgx/preparedepthofcoverage/tests/main.nf.test.snap
Labels: new module, Ready for Review

#6728 Pypgx/computecontrolstatistics
  modules/nf-core/pypgx/computecontrolstatistics/environment.yml
  modules/nf-core/pypgx/computecontrolstatistics/main.nf
  modules/nf-core/pypgx/computecontrolstatistics/meta.yml
  modules/nf-core/pypgx/computecontrolstatistics/tests/main.nf.test
  modules/nf-core/pypgx/computecontrolstatistics/tests/main.nf.test.snap
Labels: new module, Ready for Review

#6691 Add irescue module
  modules/nf-core/irescue/environment.yml
  modules/nf-core/irescue/main.nf
  modules/nf-core/irescue/meta.yml
  modules/nf-core/irescue/tests/main.nf.test
  modules/nf-core/irescue/tests/main.nf.test.snap
Labels: new module, Ready for Review

#6832 Update stitch
  modules/nf-core/stitch/environment.yml
  modules/nf-core/stitch/main.nf
  modules/nf-core/stitch/meta.yml
  modules/nf-core/stitch/tests/main.nf.test
  modules/nf-core/stitch/tests/main.nf.test.snap
  modules/nf-core/stitch/tests/stitch_generate_input.config
  modules/nf-core/stitch/tests/stitch_impute_only.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/stitch/main.nf
  tests/modules/nf-core/stitch/nextflow.config
  tests/modules/nf-core/stitch/test.yml
Labels: nf-test

#6841 New module Sourcepredict
  modules/nf-core/sourcepredict/environment.yml
  modules/nf-core/sourcepredict/main.nf
  modules/nf-core/sourcepredict/meta.yml
  modules/nf-core/sourcepredict/tests/main.nf.test
  modules/nf-core/sourcepredict/tests/main.nf.test.snap
  modules/nf-core/sourcepredict/tests/nextflow.config
  tests/config/test_data.config
Labels: Ready for Review

#6868 cellbender/removebackgroud: update cellbender version and include container image for gpu usage
  modules/nf-core/cellbender/removebackground/environment.yml
  modules/nf-core/cellbender/removebackground/main.nf
  modules/nf-core/cellbender/removebackground/tests/main.nf.test.snap
Labels: new module, Ready for Review

#6903 pbmm2/align
  modules/nf-core/pbmm2/align/environment.yml
  modules/nf-core/pbmm2/align/main.nf
  modules/nf-core/pbmm2/align/meta.yml
  modules/nf-core/pbmm2/align/tests/main.nf.test
  modules/nf-core/pbmm2/align/tests/main.nf.test.snap
Labels: new module, Ready for Review

#6896 Adding sequali module to nf-core modules
  modules/nf-core/sequali/environment.yml
  modules/nf-core/sequali/main.nf
  modules/nf-core/sequali/meta.yml
  modules/nf-core/sequali/tests/main.nf.test
  modules/nf-core/sequali/tests/main.nf.test.snap
Labels: new module, Ready for Review

#6818 pbsv
  modules/nf-core/pbsv/discover/environment.yml
  modules/nf-core/pbsv/discover/main.nf
  modules/nf-core/pbsv/discover/meta.yml
  modules/nf-core/pbsv/discover/tests/main.nf.test
  modules/nf-core/pbsv/discover/tests/main.nf.test.snap
Labels: new module, Ready for Review
