Repository nf-core/modules, pull requests merged in 2024-08, with the labels that each got.

#6136 Update resource allocations of cellranger mkref
  modules/nf-core/cellranger/mkref/main.nf
  modules/nf-core/cellrangerarc/mkref/main.nf
  modules/nf-core/spaceranger/mkref/main.nf
Labels: Ready for Review

#6173 Add module PoolSNP
  modules/nf-core/poolsnp/environment.yml
  modules/nf-core/poolsnp/main.nf
  modules/nf-core/poolsnp/meta.yml
  modules/nf-core/poolsnp/tests/main.nf.test
  modules/nf-core/poolsnp/tests/main.nf.test.snap
  modules/nf-core/poolsnp/tests/nextflow.config
  modules/nf-core/poolsnp/tests/tags.yml
Labels: new module, Ready for Review

#6156 `Fastqc`: FIX memory over-allocation
  modules/nf-core/fastqc/main.nf
  subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/tests/main.nf.test.snap
Labels: Ready for Review

#6019 New sbwf bam_subsampledepth_samtools
  subworkflows/nf-core/bam_subsampledepth_samtools/main.nf
  subworkflows/nf-core/bam_subsampledepth_samtools/meta.yml
  subworkflows/nf-core/bam_subsampledepth_samtools/tests/main.nf.test
  subworkflows/nf-core/bam_subsampledepth_samtools/tests/main.nf.test.snap
  subworkflows/nf-core/bam_subsampledepth_samtools/tests/nextflow.config
  subworkflows/nf-core/bam_subsampledepth_samtools/tests/tags.yml
Labels: Ready for Review, new subworkflow, nf-test

#6217 Add nfschema plugin subwf
  .github/workflows/test.yml
  subworkflows/nf-core/utils_nfschema_plugin/main.nf
  subworkflows/nf-core/utils_nfschema_plugin/meta.yml
  subworkflows/nf-core/utils_nfschema_plugin/tests/main.nf.test
  subworkflows/nf-core/utils_nfschema_plugin/tests/nextflow.config
  subworkflows/nf-core/utils_nfschema_plugin/tests/nextflow_schema.json
Labels: Ready for Review, ready to merge

#5876 New sections for further module info
  .github/ISSUE_TEMPLATE/new_module.yml
Labels: documentation

#6209 Cafe
  modules/nf-core/cafe/environment.yml
  modules/nf-core/cafe/main.nf
  modules/nf-core/cafe/meta.yml
  modules/nf-core/cafe/tests/main.nf.test
  modules/nf-core/cafe/tests/main.nf.test.snap
Labels: Ready for Review

#6427 Add tbi index as an output to lofreq callparallel
  modules/nf-core/lofreq/callparallel/main.nf
  modules/nf-core/lofreq/callparallel/meta.yml
  modules/nf-core/lofreq/callparallel/tests/main.nf.test
  modules/nf-core/lofreq/callparallel/tests/main.nf.test.snap
Labels: update module

#6429 Update lofreq callparallel
  modules/nf-core/lofreq/callparallel/tests/main.nf.test
  modules/nf-core/lofreq/callparallel/tests/main.nf.test.snap
Labels: update module

#6281 Added nf-test for purecn/normaldb
  modules/nf-core/purecn/normaldb/environment.yml
  modules/nf-core/purecn/normaldb/main.nf
  modules/nf-core/purecn/normaldb/meta.yml
  modules/nf-core/purecn/normaldb/tests/main.nf.test
  modules/nf-core/purecn/normaldb/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/purecn/normaldb/main.nf
  tests/modules/nf-core/purecn/normaldb/nextflow.config
  tests/modules/nf-core/purecn/normaldb/test.yml
Labels: Ready for Review

#6270 Added nf-test for ngmaster
  modules/nf-core/ngmaster/environment.yml
  modules/nf-core/ngmaster/main.nf
  modules/nf-core/ngmaster/tests/main.nf.test
  modules/nf-core/ngmaster/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/ngmaster/main.nf
  tests/modules/nf-core/ngmaster/nextflow.config
  tests/modules/nf-core/ngmaster/test.yml
Labels: Ready for Review
