Repository nf-core/modules, pull requests merged in 2024-02, with the labels that each got.

#4131 Feat/bbmap_bbsplit nf-test
  modules/nf-core/bbmap/bbsplit/main.nf
  modules/nf-core/bbmap/bbsplit/tests/main.nf.test
  modules/nf-core/bbmap/bbsplit/tests/main.nf.test.snap
  modules/nf-core/bbmap/bbsplit/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bbmap/bbsplit/main.nf
  tests/modules/nf-core/bbmap/bbsplit/nextflow.config
  tests/modules/nf-core/bbmap/bbsplit/test.yml
Labels: nf-test

#4858 Use `samtools sort` to convert to BAM
  modules/nf-core/minimap2/align/main.nf
Labels: update module

#4851 Update hamronization/abricate
  modules/nf-core/hamronization/abricate/environment.yml
  modules/nf-core/hamronization/abricate/main.nf
  modules/nf-core/hamronization/abricate/meta.yml
  modules/nf-core/hamronization/abricate/tests/main.nf.test
  modules/nf-core/hamronization/abricate/tests/main.nf.test.snap
  modules/nf-core/hamronization/abricate/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/hamronization/abricate/main.nf
  tests/modules/nf-core/hamronization/abricate/nextflow.config
  tests/modules/nf-core/hamronization/abricate/test.yml
Labels: update module, Ready for Review

#4878 Update hamronization submodules to 1.1.4
  modules/nf-core/hamronization/amrfinderplus/environment.yml
  modules/nf-core/hamronization/amrfinderplus/main.nf
  modules/nf-core/hamronization/amrfinderplus/meta.yml
  modules/nf-core/hamronization/amrfinderplus/tests/main.nf.test
  modules/nf-core/hamronization/amrfinderplus/tests/main.nf.test.snap
  modules/nf-core/hamronization/amrfinderplus/tests/tags.yml
  modules/nf-core/hamronization/deeparg/environment.yml
  modules/nf-core/hamronization/deeparg/main.nf
  modules/nf-core/hamronization/deeparg/meta.yml
  modules/nf-core/hamronization/deeparg/tests/main.nf.test
  modules/nf-core/hamronization/deeparg/tests/main.nf.test.snap
  modules/nf-core/hamronization/deeparg/tests/tags.yml
  modules/nf-core/hamronization/fargene/environment.yml
  modules/nf-core/hamronization/fargene/main.nf
  modules/nf-core/hamronization/fargene/meta.yml
  modules/nf-core/hamronization/fargene/tests/main.nf.test
  modules/nf-core/hamronization/fargene/tests/main.nf.test.snap
  modules/nf-core/hamronization/fargene/tests/tags.yml
  modules/nf-core/hamronization/rgi/environment.yml
  modules/nf-core/hamronization/rgi/main.nf
  modules/nf-core/hamronization/rgi/meta.yml
  modules/nf-core/hamronization/rgi/tests/main.nf.test
  modules/nf-core/hamronization/rgi/tests/main.nf.test.snap
  modules/nf-core/hamronization/rgi/tests/tags.yml
  modules/nf-core/hamronization/summarize/environment.yml
  modules/nf-core/hamronization/summarize/main.nf
  modules/nf-core/hamronization/summarize/meta.yml
  modules/nf-core/hamronization/summarize/tests/main.nf.test
  modules/nf-core/hamronization/summarize/tests/main.nf.test.snap
  modules/nf-core/hamronization/summarize/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/hamronization/amrfinderplus/main.nf
  tests/modules/nf-core/hamronization/amrfinderplus/nextflow.config
  tests/modules/nf-core/hamronization/amrfinderplus/test.yml
  tests/modules/nf-core/hamronization/deeparg/main.nf
  tests/modules/nf-core/hamronization/deeparg/nextflow.config
  tests/modules/nf-core/hamronization/deeparg/test.yml
  tests/modules/nf-core/hamronization/fargene/main.nf
  tests/modules/nf-core/hamronization/fargene/nextflow.config
  tests/modules/nf-core/hamronization/fargene/test.yml
  tests/modules/nf-core/hamronization/rgi/main.nf
  tests/modules/nf-core/hamronization/rgi/nextflow.config
  tests/modules/nf-core/hamronization/rgi/test.yml
  tests/modules/nf-core/hamronization/summarize/main.nf
  tests/modules/nf-core/hamronization/summarize/nextflow.config
  tests/modules/nf-core/hamronization/summarize/test.yml
Labels: update module, Ready for Review

#4841 Adding seqkit concat
  modules/nf-core/seqkit/concat/environment.yml
  modules/nf-core/seqkit/concat/main.nf
  modules/nf-core/seqkit/concat/meta.yml
  modules/nf-core/seqkit/concat/tests/main.nf.test
  modules/nf-core/seqkit/concat/tests/main.nf.test.snap
  modules/nf-core/seqkit/concat/tests/nextflow.config
  modules/nf-core/seqkit/concat/tests/tags.yml
Labels: new module, Ready for Review

#4876 Add quartonotebook module
  .github/workflows/test.yml
  modules/nf-core/quartonotebook/Dockerfile
  modules/nf-core/quartonotebook/environment.yml
  modules/nf-core/quartonotebook/main.nf
  modules/nf-core/quartonotebook/meta.yml
  modules/nf-core/quartonotebook/parametrize.nf
  modules/nf-core/quartonotebook/tests/main.nf.test
  modules/nf-core/quartonotebook/tests/main.nf.test.snap
  modules/nf-core/quartonotebook/tests/no-parametrization.config
  modules/nf-core/quartonotebook/tests/tags.yml
  modules/nf-core/quartonotebook/tests/with-parametrization.config
  tests/config/test_data.config
Labels: new module, Ready for Review

#4888 Update antismash/antismashlite to 7.1.0
  modules/nf-core/antismash/antismashlite/environment.yml
  modules/nf-core/antismash/antismashlite/main.nf
  modules/nf-core/antismash/antismashlite/meta.yml
  modules/nf-core/antismash/antismashlite/tests/main.nf.test
  modules/nf-core/antismash/antismashlite/tests/main.nf.test.snap
  modules/nf-core/antismash/antismashlite/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/antismash/antismashlite/main.nf
  tests/modules/nf-core/antismash/antismashlite/nextflow.config
  tests/modules/nf-core/antismash/antismashlite/test.yml
Labels: update module

#4902 Update pyrodigal to 3.3.0
  modules/nf-core/pyrodigal/environment.yml
  modules/nf-core/pyrodigal/main.nf
  modules/nf-core/pyrodigal/tests/main.nf.test.snap
Labels: update module, Ready for Review

#4817 Propr propr
  modules/nf-core/propr/propr/environment.yml
  modules/nf-core/propr/propr/main.nf
  modules/nf-core/propr/propr/meta.yml
  modules/nf-core/propr/propr/templates/propr.R
  modules/nf-core/propr/propr/tests/alr_pcorbshrink.config
  modules/nf-core/propr/propr/tests/clr_pcor.config
  modules/nf-core/propr/propr/tests/clr_pcorbshrink.config
  modules/nf-core/propr/propr/tests/clr_rho.config
  modules/nf-core/propr/propr/tests/clr_rho_alpha.config
  modules/nf-core/propr/propr/tests/main.nf.test
  modules/nf-core/propr/propr/tests/main.nf.test.snap
  modules/nf-core/propr/propr/tests/tags.yml
Labels: ready to merge

#4852 Update seqkit to 2.7.0
  modules/nf-core/seqkit/fx2tab/environment.yml
  modules/nf-core/seqkit/fx2tab/main.nf
  modules/nf-core/seqkit/tab2fx/environment.yml
  modules/nf-core/seqkit/tab2fx/main.nf
Labels: update module, Ready for Review

#4754 Add compression to MSA modules
  modules/nf-core/clustalo/align/environment.yml
  modules/nf-core/clustalo/align/main.nf
  modules/nf-core/clustalo/align/meta.yml
  modules/nf-core/clustalo/align/tests/main.nf.test
  modules/nf-core/clustalo/align/tests/main.nf.test.snap
  modules/nf-core/famsa/align/main.nf
  modules/nf-core/famsa/align/meta.yml
  modules/nf-core/famsa/align/tests/main.nf.test
  modules/nf-core/famsa/align/tests/main.nf.test.snap
  modules/nf-core/mafft/environment.yml
  modules/nf-core/mafft/main.nf
  modules/nf-core/mafft/meta.yml
  modules/nf-core/mafft/tests/main.nf.test
  modules/nf-core/mafft/tests/main.nf.test.snap
  modules/nf-core/mtmalign/align/environment.yml
  modules/nf-core/mtmalign/align/main.nf
  modules/nf-core/mtmalign/align/meta.yml
  modules/nf-core/mtmalign/align/tests/main.nf.test
  modules/nf-core/mtmalign/align/tests/main.nf.test.snap
  modules/nf-core/muscle5/super5/environment.yml
  modules/nf-core/muscle5/super5/main.nf
  modules/nf-core/muscle5/super5/meta.yml
  modules/nf-core/muscle5/super5/tests/main.nf.test
  modules/nf-core/muscle5/super5/tests/main.nf.test.snap
  modules/nf-core/muscle5/super5/tests/nextflow.config
  modules/nf-core/muscle5/super5/tests/perm_all.config
  modules/nf-core/tcoffee/align/environment.yml
  modules/nf-core/tcoffee/align/main.nf
  modules/nf-core/tcoffee/align/meta.yml
  modules/nf-core/tcoffee/align/tests/main.nf.test
  modules/nf-core/tcoffee/align/tests/main.nf.test.snap
  modules/nf-core/tcoffee/align/tests/structure.config
  modules/nf-core/tcoffee/alncompare/environment.yml
  modules/nf-core/tcoffee/alncompare/main.nf
  modules/nf-core/tcoffee/alncompare/meta.yml
  modules/nf-core/tcoffee/alncompare/tests/main.nf.test.snap
  modules/nf-core/tcoffee/irmsd/environment.yml
  modules/nf-core/tcoffee/irmsd/main.nf
  modules/nf-core/tcoffee/irmsd/meta.yml
  modules/nf-core/tcoffee/irmsd/tests/main.nf.test
Labels: Ready for Review

#4924 Dp24 windowmasker
  modules/nf-core/windowmasker/convert/environment.yml
  modules/nf-core/windowmasker/convert/main.nf
  modules/nf-core/windowmasker/convert/tests/convert_binary.config
  modules/nf-core/windowmasker/convert/tests/convert_oascii.config
  modules/nf-core/windowmasker/convert/tests/convert_obinary.config
  modules/nf-core/windowmasker/convert/tests/main.nf.test
  modules/nf-core/windowmasker/convert/tests/main.nf.test.snap
  modules/nf-core/windowmasker/convert/tests/tags.yml
  modules/nf-core/windowmasker/mkcounts/environment.yml
  modules/nf-core/windowmasker/mkcounts/main.nf
  modules/nf-core/windowmasker/mkcounts/tests/main.nf.test
  modules/nf-core/windowmasker/mkcounts/tests/main.nf.test.snap
  modules/nf-core/windowmasker/mkcounts/tests/nextflow.config
  modules/nf-core/windowmasker/mkcounts/tests/tags.yml
  modules/nf-core/windowmasker/ustat/environment.yml
  modules/nf-core/windowmasker/ustat/main.nf
  modules/nf-core/windowmasker/ustat/tests/main.nf.test
  modules/nf-core/windowmasker/ustat/tests/main.nf.test.snap
  modules/nf-core/windowmasker/ustat/tests/nextflow.config
  modules/nf-core/windowmasker/ustat/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/windowmasker/convert/main.nf
  tests/modules/nf-core/windowmasker/convert/nextflow.config
  tests/modules/nf-core/windowmasker/convert/test.yml
  tests/modules/nf-core/windowmasker/mkcounts/main.nf
  tests/modules/nf-core/windowmasker/mkcounts/nextflow.config
  tests/modules/nf-core/windowmasker/mkcounts/test.yml
  tests/modules/nf-core/windowmasker/ustat/main.nf
  tests/modules/nf-core/windowmasker/ustat/nextflow.config
  tests/modules/nf-core/windowmasker/ustat/test.yml
Labels: update module, Ready for Review, nf-test

#4802 cellranger multi: Convert module in python template to add an automatic renaming step
  modules/nf-core/cellranger/multi/main.nf
  modules/nf-core/cellranger/multi/templates/cellranger_multi.py
  tests/modules/nf-core/cellranger/multi/main.nf
  tests/modules/nf-core/cellranger/multi/test.yml
Labels: update module, Do not merge yet

#4972 fix tiny bug in gawk module
  modules/nf-core/gawk/main.nf
  modules/nf-core/gawk/meta.yml
Labels: bug

#4703 Kraken2/add module
  modules/nf-core/kraken2/add/environment.yml
  modules/nf-core/kraken2/add/main.nf
  modules/nf-core/kraken2/add/meta.yml
  modules/nf-core/kraken2/add/tests/main.nf.test
  modules/nf-core/kraken2/add/tests/main.nf.test.snap
  modules/nf-core/kraken2/add/tests/tags.yml
Labels: new module, nf-test

#4950 Updates to gnu sort module to include nf-test
  modules/nf-core/gnu/sort/environment.yml
  modules/nf-core/gnu/sort/main.nf
  modules/nf-core/gnu/sort/meta.yml
  modules/nf-core/gnu/sort/tests/main.nf.test
  modules/nf-core/gnu/sort/tests/main.nf.test.snap
  modules/nf-core/gnu/sort/tests/sort_complex.config
  modules/nf-core/gnu/sort/tests/sort_simple_bed.config
  modules/nf-core/gnu/sort/tests/sort_simple_genome.config
  modules/nf-core/gnu/sort/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gnu/sort/main.nf
  tests/modules/nf-core/gnu/sort/nextflow.config
  tests/modules/nf-core/gnu/sort/test.yml
Labels: update module, Ready for Review, nf-test

#4971 Update gfaffix to 0.1.5b
  modules/nf-core/gfaffix/main.nf
Labels: update module, Ready for Review
