Repository nf-core/modules, pull requests merged in 2024-03, with the labels that each got.

#4937 Dp24 tabix update
  modules/nf-core/tabix/bgzip/environment.yml
  modules/nf-core/tabix/bgzip/main.nf
  modules/nf-core/tabix/bgzip/tests/bgzip_compress.config
  modules/nf-core/tabix/bgzip/tests/main.nf.test
  modules/nf-core/tabix/bgzip/tests/main.nf.test.snap
  modules/nf-core/tabix/bgzip/tests/tags.yml
  modules/nf-core/tabix/bgzip/tests/vcf_none.config
  modules/nf-core/tabix/bgziptabix/environment.yml
  modules/nf-core/tabix/bgziptabix/main.nf
  modules/nf-core/tabix/bgziptabix/tests/main.nf.test
  modules/nf-core/tabix/bgziptabix/tests/main.nf.test.snap
  modules/nf-core/tabix/bgziptabix/tests/tabix_csi.config
  modules/nf-core/tabix/bgziptabix/tests/tabix_tbi.config
  modules/nf-core/tabix/bgziptabix/tests/tags.yml
  modules/nf-core/tabix/tabix/environment.yml
  modules/nf-core/tabix/tabix/main.nf
  modules/nf-core/tabix/tabix/tests/main.nf.test
  modules/nf-core/tabix/tabix/tests/main.nf.test.snap
  modules/nf-core/tabix/tabix/tests/tabix_bed.config
  modules/nf-core/tabix/tabix/tests/tabix_gff.config
  modules/nf-core/tabix/tabix/tests/tabix_vcf_csi.config
  modules/nf-core/tabix/tabix/tests/tabix_vcf_tbi.config
  modules/nf-core/tabix/tabix/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/tabix/bgzip/main.nf
  tests/modules/nf-core/tabix/bgzip/nextflow.config
  tests/modules/nf-core/tabix/bgzip/test.yml
  tests/modules/nf-core/tabix/bgziptabix/main.nf
  tests/modules/nf-core/tabix/bgziptabix/nextflow.config
  tests/modules/nf-core/tabix/bgziptabix/test.yml
  tests/modules/nf-core/tabix/tabix/main.nf
  tests/modules/nf-core/tabix/tabix/nextflow.config
  tests/modules/nf-core/tabix/tabix/test.yml
Labels: update module, Ready for Review, nf-test

#4964 Updates for Seqtk
  modules/nf-core/seqtk/cutn/tests/main.nf.test
  modules/nf-core/seqtk/cutn/tests/main.nf.test.snap
  modules/nf-core/seqtk/cutn/tests/tags.yml
  modules/nf-core/seqtk/mergepe/environment.yml
  modules/nf-core/seqtk/mergepe/main.nf
  modules/nf-core/seqtk/mergepe/meta.yml
  modules/nf-core/seqtk/mergepe/tests/main.nf.test
  modules/nf-core/seqtk/mergepe/tests/main.nf.test.snap
  modules/nf-core/seqtk/mergepe/tests/tags.yml
  modules/nf-core/seqtk/rename/environment.yml
  modules/nf-core/seqtk/rename/main.nf
  modules/nf-core/seqtk/rename/meta.yml
  modules/nf-core/seqtk/rename/tests/main.nf.test
  modules/nf-core/seqtk/rename/tests/main.nf.test.snap
  modules/nf-core/seqtk/rename/tests/tags.yml
  modules/nf-core/seqtk/sample/environment.yml
  modules/nf-core/seqtk/sample/main.nf
  modules/nf-core/seqtk/sample/meta.yml
  modules/nf-core/seqtk/sample/tests/main.nf.test
  modules/nf-core/seqtk/sample/tests/main.nf.test.snap
  modules/nf-core/seqtk/sample/tests/standard.config
  modules/nf-core/seqtk/sample/tests/tags.yml
  modules/nf-core/seqtk/seq/main.nf
  modules/nf-core/seqtk/seq/tests/main.nf.test
  modules/nf-core/seqtk/seq/tests/main.nf.test.snap
  modules/nf-core/seqtk/seq/tests/standard.config
  modules/nf-core/seqtk/seq/tests/tags.yml
  modules/nf-core/seqtk/subseq/environment.yml
  modules/nf-core/seqtk/subseq/main.nf
  modules/nf-core/seqtk/subseq/meta.yml
  modules/nf-core/seqtk/subseq/tests/main.nf.test
  modules/nf-core/seqtk/subseq/tests/main.nf.test.snap
  modules/nf-core/seqtk/subseq/tests/standard.config
  modules/nf-core/seqtk/subseq/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/seqtk/cutn/main.nf
  tests/modules/nf-core/seqtk/cutn/nextflow.config
  tests/modules/nf-core/seqtk/cutn/test.yml
  tests/modules/nf-core/seqtk/mergepe/main.nf
  tests/modules/nf-core/seqtk/mergepe/nextflow.config
  tests/modules/nf-core/seqtk/mergepe/test.yml
  tests/modules/nf-core/seqtk/rename/main.nf
  tests/modules/nf-core/seqtk/rename/nextflow.config
  tests/modules/nf-core/seqtk/rename/test.yml
  tests/modules/nf-core/seqtk/sample/main.nf
  tests/modules/nf-core/seqtk/sample/test.yml
  tests/modules/nf-core/seqtk/seq/main.nf
  tests/modules/nf-core/seqtk/seq/nextflow.config
  tests/modules/nf-core/seqtk/seq/test.yml
  tests/modules/nf-core/seqtk/subseq/main.nf
  tests/modules/nf-core/seqtk/subseq/nextflow.config
  tests/modules/nf-core/seqtk/subseq/test.yml
Labels: update module, Ready for Review, nf-test

#4981 Bump kallistobustools to 0.28.2
  modules/nf-core/kallistobustools/count/environment.yml
  modules/nf-core/kallistobustools/count/main.nf
  modules/nf-core/kallistobustools/count/meta.yml
  modules/nf-core/kallistobustools/count/tests/main.nf.test
  modules/nf-core/kallistobustools/count/tests/main.nf.test.snap
  modules/nf-core/kallistobustools/count/tests/nextflow.config
  modules/nf-core/kallistobustools/count/tests/tags.yml
  modules/nf-core/kallistobustools/ref/environment.yml
  modules/nf-core/kallistobustools/ref/main.nf
  modules/nf-core/kallistobustools/ref/meta.yml
  modules/nf-core/kallistobustools/ref/tests/main.nf.test
  modules/nf-core/kallistobustools/ref/tests/main.nf.test.snap
  modules/nf-core/kallistobustools/ref/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/kallistobustools/count/main.nf
  tests/modules/nf-core/kallistobustools/count/nextflow.config
  tests/modules/nf-core/kallistobustools/count/test.yml
  tests/modules/nf-core/kallistobustools/ref/main.nf
  tests/modules/nf-core/kallistobustools/ref/nextflow.config
  tests/modules/nf-core/kallistobustools/ref/test.yml
Labels: nf-test

#4470 Adding TRUST4 module
  modules/nf-core/trust4/environment.yml
  modules/nf-core/trust4/main.nf
  modules/nf-core/trust4/meta.yml
  modules/nf-core/trust4/tests/main.nf.test
  modules/nf-core/trust4/tests/main.nf.test.snap
  modules/nf-core/trust4/tests/tags.yml
  tests/config/pytest_modules.yml
Labels: Ready for Review, nf-test

#5096 Fix mmseqs/createtsv and add nf-test
  modules/nf-core/mmseqs/createtsv/main.nf
  modules/nf-core/mmseqs/createtsv/tests/cluster.nextflow.config
  modules/nf-core/mmseqs/createtsv/tests/main.nf.test
  modules/nf-core/mmseqs/createtsv/tests/main.nf.test.snap
  modules/nf-core/mmseqs/createtsv/tests/tags.yml
  modules/nf-core/mmseqs/createtsv/tests/taxonomy.nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/mmseqs/createtsv/main.nf
  tests/modules/nf-core/mmseqs/createtsv/nextflow.config
  tests/modules/nf-core/mmseqs/createtsv/test.yml
Labels: Ready for Review, nf-test

#5108 add paths in output directive in cellranger cout module
  modules/nf-core/cellranger/count/main.nf
  modules/nf-core/cellranger/count/meta.yml
  modules/nf-core/cellranger/count/tests/main.nf.test.snap
Labels: Ready for Review

#5110 update kallistobustools count output list
  modules/nf-core/kallistobustools/count/main.nf
  modules/nf-core/kallistobustools/count/meta.yml
  modules/nf-core/kallistobustools/count/tests/main.nf.test.snap
Labels: Ready for Review

#5133 Module PLINK/HWE and proposed template for PLINK modules
  modules/nf-core/plink/hwe/environment.yml
  modules/nf-core/plink/hwe/main.nf
  modules/nf-core/plink/hwe/meta.yml
  modules/nf-core/plink/hwe/tests/main.nf.test
  modules/nf-core/plink/hwe/tests/main.nf.test.snap
  modules/nf-core/plink/hwe/tests/tags.yml
  tests/config/test_data.config
Labels: new module, Ready for Review

#5182 Migrate openms/idfilter from pytest to nf-test
  modules/nf-core/openms/idfilter/environment.yml
  modules/nf-core/openms/idfilter/main.nf
  modules/nf-core/openms/idfilter/meta.yml
  modules/nf-core/openms/idfilter/tests/main.nf.test
  modules/nf-core/openms/idfilter/tests/main.nf.test.snap
  modules/nf-core/openms/idfilter/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/openms/idfilter/main.nf
  tests/modules/nf-core/openms/idfilter/nextflow.config
  tests/modules/nf-core/openms/idfilter/test.yml
Labels: Ready for Review, nf-test

#5130 Prodigal: fix bug and add nf-test
  modules/nf-core/prodigal/main.nf
  modules/nf-core/prodigal/tests/main.nf.test
  modules/nf-core/prodigal/tests/main.nf.test.snap
  modules/nf-core/prodigal/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/prodigal/main.nf
  tests/modules/nf-core/prodigal/nextflow.config
  tests/modules/nf-core/prodigal/test.yml
Labels: Ready for Review, nf-test

#5134 update pyrodigal arguments to v 3.3.0
  modules/nf-core/pyrodigal/environment.yml
  modules/nf-core/pyrodigal/main.nf
  modules/nf-core/pyrodigal/meta.yml
  modules/nf-core/pyrodigal/tests/main.nf.test
  modules/nf-core/pyrodigal/tests/main.nf.test.snap
Labels: Ready for Review

#5195 DEEPCELL/MESMER: Updated container and fixed configs
  modules/nf-core/deepcell/mesmer/main.nf
  modules/nf-core/deepcell/mesmer/tests/main.nf.test.snap
  modules/nf-core/deepcell/mesmer/tests/nextflow.config
Labels: imaging

#5203 add nf-test to bedtools/merge - #3936
  modules/nf-core/bedtools/merge/tests/main.nf.test
  modules/nf-core/bedtools/merge/tests/main.nf.test.snap
  modules/nf-core/bedtools/merge/tests/nextflow.config
  modules/nf-core/bedtools/merge/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bedtools/merge/main.nf
  tests/modules/nf-core/bedtools/merge/nextflow.config
  tests/modules/nf-core/bedtools/merge/test.yml
Labels: nf-test

#5224 splitncigarreads added meta for references
  modules/nf-core/gatk4/splitncigarreads/main.nf
  modules/nf-core/gatk4/splitncigarreads/meta.yml
  modules/nf-core/gatk4/splitncigarreads/tests/main.nf.test
Labels: Ready for Review

#5175 Glimpse2 ligate nftest
  modules/nf-core/glimpse2/ligate/meta.yml
  modules/nf-core/glimpse2/ligate/tests/main.nf.test
  modules/nf-core/glimpse2/ligate/tests/main.nf.test.snap
  modules/nf-core/glimpse2/ligate/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/glimpse2/ligate/main.nf
  tests/modules/nf-core/glimpse2/ligate/nextflow.config
  tests/modules/nf-core/glimpse2/ligate/test.yml
  tests/modules/nf-core/glimpse2/phase/main.nf
  tests/modules/nf-core/glimpse2/phase/nextflow.config
  tests/modules/nf-core/glimpse2/phase/test.yml
Labels: nf-test

#5226 port openms/peakpickerhires to nf-test hackathon march 2023
  modules/nf-core/openms/peakpickerhires/environment.yml
  modules/nf-core/openms/peakpickerhires/main.nf
  modules/nf-core/openms/peakpickerhires/meta.yml
  modules/nf-core/openms/peakpickerhires/tests/main.nf.test
  modules/nf-core/openms/peakpickerhires/tests/main.nf.test.snap
  modules/nf-core/openms/peakpickerhires/tests/nextflow.config
  modules/nf-core/openms/peakpickerhires/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/openms/peakpickerhires/main.nf
  tests/modules/nf-core/openms/peakpickerhires/nextflow.config
  tests/modules/nf-core/openms/peakpickerhires/test.yml
Labels: hackathon2023, nf-test

#5244 Maltextract: Add Meta-map and convert to nf-test
  modules/nf-core/maltextract/main.nf
  modules/nf-core/maltextract/meta.yml
  modules/nf-core/maltextract/tests/main.nf.test
  modules/nf-core/maltextract/tests/main.nf.test.snap
  modules/nf-core/maltextract/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/maltextract/main.nf
  tests/modules/nf-core/maltextract/nextflow.config
  tests/modules/nf-core/maltextract/test.yml
Labels: update module, nf-test

#5250 add module: Add fastx/collapser
  modules/nf-core/fastx/collapser/environment.yml
  modules/nf-core/fastx/collapser/main.nf
  modules/nf-core/fastx/collapser/meta.yml
  modules/nf-core/fastx/collapser/tests/main.nf.test
  modules/nf-core/fastx/collapser/tests/main.nf.test.snap
  modules/nf-core/fastx/collapser/tests/tags.yml
Labels: new module, Ready for Review

#5251 add nf-test to gatk4/bedtointervallist - #3936
  modules/nf-core/gatk4/bedtointervallist/tests/main.nf.test
  modules/nf-core/gatk4/bedtointervallist/tests/main.nf.test.snap
  modules/nf-core/gatk4/bedtointervallist/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/bedtointervallist/main.nf
  tests/modules/nf-core/gatk4/bedtointervallist/nextflow.config
  tests/modules/nf-core/gatk4/bedtointervallist/test.yml
Labels: Ready for Review, nf-test

#5221 add nf-test to bedtools/sort - #3936
  modules/nf-core/bedtools/sort/tests/main.nf.test
  modules/nf-core/bedtools/sort/tests/main.nf.test.snap
  modules/nf-core/bedtools/sort/tests/nextflow.config
  modules/nf-core/bedtools/sort/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bedtools/sort/main.nf
  tests/modules/nf-core/bedtools/sort/nextflow.config
  tests/modules/nf-core/bedtools/sort/test.yml
Labels: Ready for Review, nf-test

#4718 Added gt/gff3validator
  modules/nf-core/gt/gff3validator/environment.yml
  modules/nf-core/gt/gff3validator/main.nf
  modules/nf-core/gt/gff3validator/meta.yml
  modules/nf-core/gt/gff3validator/tests/main.nf.test
  modules/nf-core/gt/gff3validator/tests/main.nf.test.snap
  modules/nf-core/gt/gff3validator/tests/nextflow.config
  modules/nf-core/gt/gff3validator/tests/tags.yml
Labels: Ready for Review

#5275 Add module seqfu/stats
  modules/nf-core/seqfu/stats/environment.yml
  modules/nf-core/seqfu/stats/main.nf
  modules/nf-core/seqfu/stats/meta.yml
  modules/nf-core/seqfu/stats/tests/main.nf.test
  modules/nf-core/seqfu/stats/tests/main.nf.test.snap
  modules/nf-core/seqfu/stats/tests/tags.yml
Labels: Ready for Review

#5164 gatk4_asereadcounter add updated meta and nf-tests
  modules/nf-core/gatk4/asereadcounter/main.nf
  modules/nf-core/gatk4/asereadcounter/main.nf.test
  modules/nf-core/gatk4/asereadcounter/main.nf.test.snap
  modules/nf-core/gatk4/asereadcounter/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/asereadcounter/main.nf
  tests/modules/nf-core/gatk4/asereadcounter/nextflow.config
  tests/modules/nf-core/gatk4/asereadcounter/test.yml
Labels: Ready for Review, nf-test

#5171 Add wittyer as module
  .github/workflows/test.yml
  modules/nf-core/wittyer/README.md
  modules/nf-core/wittyer/environment.yml
  modules/nf-core/wittyer/main.nf
  modules/nf-core/wittyer/meta.yml
  modules/nf-core/wittyer/tests/main.nf.test
  modules/nf-core/wittyer/tests/main.nf.test.snap
  modules/nf-core/wittyer/tests/tags.yml
Labels: new module

#5263 Igv reports
  modules/nf-core/igvreports/environment.yml
  modules/nf-core/igvreports/main.nf
  modules/nf-core/igvreports/meta.yml
  modules/nf-core/igvreports/tests/main.nf.test
  modules/nf-core/igvreports/tests/main.nf.test.snap
  modules/nf-core/igvreports/tests/nextflow_genome.config
  modules/nf-core/igvreports/tests/tags.yml
Labels: Ready for Review

#5307 Revert "update kallistobustools count output list"
  modules/nf-core/kallistobustools/count/main.nf
  modules/nf-core/kallistobustools/count/meta.yml
  modules/nf-core/kallistobustools/count/tests/main.nf.test.snap
Labels: Ready for Review

#5323 Idmerger nf test closes #5157
  modules/nf-core/openms/idmerger/meta.yml
  modules/nf-core/openms/idmerger/tests/main.nf.test
  modules/nf-core/openms/idmerger/tests/main.nf.test.snap
Labels: nf-test

#5288 Tcoffee tcs
  modules/nf-core/tcoffee/tcs/environment.yml
  modules/nf-core/tcoffee/tcs/main.nf
  modules/nf-core/tcoffee/tcs/main.nf.test
  modules/nf-core/tcoffee/tcs/meta.yml
  modules/nf-core/tcoffee/tcs/tests/lib.config
  modules/nf-core/tcoffee/tcs/tests/main.nf.test
  modules/nf-core/tcoffee/tcs/tests/main.nf.test.snap
  modules/nf-core/tcoffee/tcs/tests/tags.yml
Labels: enhancement

#5290 Add module nanofilt
  modules/nf-core/nanofilt/environment.yml
  modules/nf-core/nanofilt/main.nf
  modules/nf-core/nanofilt/meta.yml
  modules/nf-core/nanofilt/tests/main.nf.test
  modules/nf-core/nanofilt/tests/main.nf.test.snap
  modules/nf-core/nanofilt/tests/tags.yml
Labels: Ready for Review

#5325 port `strelka-somatic` to nf-test
  modules/nf-core/strelka/somatic/main.nf
  modules/nf-core/strelka/somatic/meta.yml
  modules/nf-core/strelka/somatic/tests/main.nf.test
  modules/nf-core/strelka/somatic/tests/main.nf.test.snap
  modules/nf-core/strelka/somatic/tests/nextflow.config
  modules/nf-core/strelka/somatic/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/strelka/somatic/main.nf
  tests/modules/nf-core/strelka/somatic/nextflow.config
  tests/modules/nf-core/strelka/somatic/test.yml
Labels: Ready for Review

#5339 Update test_data.config
  tests/config/test_data.config
Labels: Ready for Review

#5337 add nf-test for gatk4/combinegvcfs - #3936
  modules/nf-core/gatk4/combinegvcfs/meta.yml
  modules/nf-core/gatk4/combinegvcfs/tests/main.nf.test
  modules/nf-core/gatk4/combinegvcfs/tests/main.nf.test.snap
  modules/nf-core/gatk4/combinegvcfs/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/combinegvcfs/main.nf
  tests/modules/nf-core/gatk4/combinegvcfs/nextflow.config
  tests/modules/nf-core/gatk4/combinegvcfs/test.yml
Labels: nf-test

#5162 metamaps/mapDirectly
  modules/nf-core/metamaps/mapdirectly/environment.yml
  modules/nf-core/metamaps/mapdirectly/main.nf
  modules/nf-core/metamaps/mapdirectly/meta.yml
  modules/nf-core/metamaps/mapdirectly/tests/main.nf.test
  modules/nf-core/metamaps/mapdirectly/tests/main.nf.test.snap
  modules/nf-core/metamaps/mapdirectly/tests/nextflow.config
  modules/nf-core/metamaps/mapdirectly/tests/tags.yml
  tests/config/test_data.config
Labels: new module, Ready for Review

#5321 nf-test: Migrate islandpath tests to nf-test
  .github/workflows/test.yml
  modules/nf-core/islandpath/meta.yml
  modules/nf-core/islandpath/tests/main.nf.test
  modules/nf-core/islandpath/tests/main.nf.test.snap
  modules/nf-core/islandpath/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/islandpath/main.nf
  tests/modules/nf-core/islandpath/nextflow.config
  tests/modules/nf-core/islandpath/test.yml
Labels: nf-test

#5259 update cnvkit/batch and ported to nf-test
  modules/nf-core/cnvkit/batch/environment.yml
  modules/nf-core/cnvkit/batch/main.nf
  modules/nf-core/cnvkit/batch/meta.yml
  modules/nf-core/cnvkit/batch/tests/batch_hybrid.config
  modules/nf-core/cnvkit/batch/tests/batch_pon.config
  modules/nf-core/cnvkit/batch/tests/batch_tumouronly.config
  modules/nf-core/cnvkit/batch/tests/batch_wgs.config
  modules/nf-core/cnvkit/batch/tests/main.nf.test
  modules/nf-core/cnvkit/batch/tests/main.nf.test.snap
  modules/nf-core/cnvkit/batch/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/cnvkit/batch/main.nf
  tests/modules/nf-core/cnvkit/batch/nextflow.config
  tests/modules/nf-core/cnvkit/batch/test.yml
Labels: update module, Ready for Review

#5252 ported idmerger pytest to nf-test #5157
  modules/nf-core/openms/idmerger/meta.yml
  modules/nf-core/openms/idmerger/tests/main.nf.test
  modules/nf-core/openms/idmerger/tests/main.nf.test.snap
  modules/nf-core/openms/idmerger/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/openms/idmerger/main.nf
  tests/modules/nf-core/openms/idmerger/nextflow.config
  tests/modules/nf-core/openms/idmerger/test.yml
Labels: nf-test

#5326 842 new module circularmappercirculargenerator
  modules/nf-core/circularmapper/circulargenerator/environment.yml
  modules/nf-core/circularmapper/circulargenerator/main.nf
  modules/nf-core/circularmapper/circulargenerator/meta.yml
  modules/nf-core/circularmapper/circulargenerator/tests/main.nf.test
  modules/nf-core/circularmapper/circulargenerator/tests/main.nf.test.snap
  modules/nf-core/circularmapper/circulargenerator/tests/tags.yml
Labels: new module, Ready for Review

#5245 Dp24 pretextmap update
  modules/nf-core/pretextmap/main.nf
  modules/nf-core/pretextmap/meta.yml
  modules/nf-core/pretextmap/tests/main.nf.test
  modules/nf-core/pretextmap/tests/main.nf.test.snap
  modules/nf-core/pretextmap/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/pretextmap/main.nf
  tests/modules/nf-core/pretextmap/nextflow.config
  tests/modules/nf-core/pretextmap/test.yml
Labels: update module, Ready for Review, nf-test

#5329 fix optional cram support in modules and migrate to nf-test
  modules/nf-core/gatk4/estimatelibrarycomplexity/main.nf
  modules/nf-core/gatk4/estimatelibrarycomplexity/tests/main.nf.test
  modules/nf-core/gatk4/estimatelibrarycomplexity/tests/main.nf.test.snap
  modules/nf-core/gatk4/estimatelibrarycomplexity/tests/tags.yml
  modules/nf-core/picard/addorreplacereadgroups/main.nf
  modules/nf-core/picard/addorreplacereadgroups/meta.yml
  modules/nf-core/picard/addorreplacereadgroups/tests/bam.config
  modules/nf-core/picard/addorreplacereadgroups/tests/main.nf.test
  modules/nf-core/picard/addorreplacereadgroups/tests/main.nf.test.snap
  modules/nf-core/picard/markduplicates/main.nf
  modules/nf-core/picard/markduplicates/meta.yml
  modules/nf-core/picard/markduplicates/tests/main.nf.test
  modules/nf-core/picard/markduplicates/tests/main.nf.test.snap
  subworkflows/nf-core/bam_markduplicates_picard/main.nf
  subworkflows/nf-core/bam_markduplicates_picard/meta.yml
  subworkflows/nf-core/bam_markduplicates_picard/tests/main.nf.test
  subworkflows/nf-core/bam_markduplicates_picard/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/estimatelibrarycomplexity/main.nf
  tests/modules/nf-core/gatk4/estimatelibrarycomplexity/nextflow.config
  tests/modules/nf-core/gatk4/estimatelibrarycomplexity/test.yml
Labels: Ready for Review

#5317 Decoupler module
  modules/nf-core/decoupler/decoupler/main.nf
  modules/nf-core/decoupler/decoupler/meta.yml
  modules/nf-core/decoupler/decoupler/tests/main.nf.test
  modules/nf-core/decoupler/decoupler/tests/main.nf.test.snap
  modules/nf-core/decoupler/decoupler/tests/nextflow.config
  modules/nf-core/decoupler/decoupler/tests/tags.yml
  tests/config/test_data.config
Labels: new module, Ready for Review

#5276 Update learnmsa module to work with compressed files.
  modules/nf-core/learnmsa/align/environment.yml
  modules/nf-core/learnmsa/align/main.nf
  modules/nf-core/learnmsa/align/meta.yml
  modules/nf-core/learnmsa/align/tests/main.nf.test
  modules/nf-core/learnmsa/align/tests/main.nf.test.snap
Labels: Ready for Review, ready to merge

#5386 new module: Plink epistasis analysis
  modules/nf-core/plink/epistasis/environment.yml
  modules/nf-core/plink/epistasis/main.nf
  modules/nf-core/plink/epistasis/meta.yml
  modules/nf-core/plink/epistasis/tests/main.nf.test
  modules/nf-core/plink/epistasis/tests/main.nf.test.snap
  modules/nf-core/plink/epistasis/tests/nextflow.config
  modules/nf-core/plink/epistasis/tests/pheno_name.config
  modules/nf-core/plink/epistasis/tests/tags.yml
Labels: new module, Ready for Review

#5403 corrected bug in asereadcounter
  modules/nf-core/gatk4/asereadcounter/main.nf
  modules/nf-core/gatk4/asereadcounter/main.nf.test
  modules/nf-core/gatk4/asereadcounter/meta.yml
Labels: bug

#5389 Adding Fast epistasis module
  modules/nf-core/plink/fastepistasis/environment.yml
  modules/nf-core/plink/fastepistasis/main.nf
  modules/nf-core/plink/fastepistasis/meta.yml
  modules/nf-core/plink/fastepistasis/tests/main.nf.test
  modules/nf-core/plink/fastepistasis/tests/main.nf.test.snap
  modules/nf-core/plink/fastepistasis/tests/nextflow.config
  modules/nf-core/plink/fastepistasis/tests/pheno_name.config
  modules/nf-core/plink/fastepistasis/tests/tags.yml
Labels: Ready for Review
