Repository nf-core/modules, pull requests merged in 2024-11, with the labels that each got.

#6913 Update chopper module to take optional fasta file
  modules/nf-core/chopper/environment.yml
  modules/nf-core/chopper/main.nf
  modules/nf-core/chopper/meta.yml
  modules/nf-core/chopper/tests/main.nf.test
  modules/nf-core/chopper/tests/main.nf.test.snap
Labels: update module, ready to merge

#6915 Pbsv/call
  modules/nf-core/pbsv/call/environment.yml
  modules/nf-core/pbsv/call/main.nf
  modules/nf-core/pbsv/call/meta.yml
  modules/nf-core/pbsv/call/tests/main.nf.test
  modules/nf-core/pbsv/call/tests/main.nf.test.snap
Labels: new module, Ready for Review

#6897 New module: doubletdetection
  .github/workflows/test.yml
  modules/nf-core/doubletdetection/main.nf
  modules/nf-core/doubletdetection/meta.yml
  modules/nf-core/doubletdetection/templates/doubletdetection.py
  modules/nf-core/doubletdetection/tests/main.nf.test
  modules/nf-core/doubletdetection/tests/main.nf.test.snap
Labels: new module

#6911 add anndata/barcodes module
  modules/nf-core/anndata/barcodes/environment.yml
  modules/nf-core/anndata/barcodes/main.nf
  modules/nf-core/anndata/barcodes/meta.yml
  modules/nf-core/anndata/barcodes/templates/barcodes.py
  modules/nf-core/anndata/barcodes/tests/main.nf.test
  modules/nf-core/anndata/barcodes/tests/main.nf.test.snap
  modules/nf-core/anndata/barcodes/tests/tags.yml
Labels: new module, Ready for Review

#6826 5127 new module xenium ranger
  .github/workflows/test.yml
  modules/nf-core/xeniumranger/.gitignore
  modules/nf-core/xeniumranger/Dockerfile
  modules/nf-core/xeniumranger/README.md
  modules/nf-core/xeniumranger/import-segmentation/main.nf
  modules/nf-core/xeniumranger/import-segmentation/meta.yml
  modules/nf-core/xeniumranger/import-segmentation/tests/main.nf.test
  modules/nf-core/xeniumranger/import-segmentation/tests/main.nf.test.snap
  modules/nf-core/xeniumranger/import-segmentation/tests/nextflow.config
  modules/nf-core/xeniumranger/import-segmentation/tests/tags.yml
  modules/nf-core/xeniumranger/relabel/main.nf
  modules/nf-core/xeniumranger/relabel/meta.yml
  modules/nf-core/xeniumranger/relabel/tests/main.nf.test
  modules/nf-core/xeniumranger/relabel/tests/main.nf.test.snap
  modules/nf-core/xeniumranger/relabel/tests/nextflow.config
  modules/nf-core/xeniumranger/relabel/tests/tags.yml
  modules/nf-core/xeniumranger/rename/main.nf
  modules/nf-core/xeniumranger/rename/meta.yml
  modules/nf-core/xeniumranger/rename/tests/main.nf.test
  modules/nf-core/xeniumranger/rename/tests/main.nf.test.snap
  modules/nf-core/xeniumranger/rename/tests/nextflow.config
  modules/nf-core/xeniumranger/rename/tests/tags.yml
  modules/nf-core/xeniumranger/resegment/main.nf
  modules/nf-core/xeniumranger/resegment/meta.yml
  modules/nf-core/xeniumranger/resegment/tests/main.nf.test
  modules/nf-core/xeniumranger/resegment/tests/main.nf.test.snap
  modules/nf-core/xeniumranger/resegment/tests/nextflow.config
  modules/nf-core/xeniumranger/resegment/tests/tags.yml
Labels: new module, Ready for Review, ready to merge

#6854 Hiphase - new module
  modules/nf-core/hiphase/environment.yml
  modules/nf-core/hiphase/main.nf
  modules/nf-core/hiphase/meta.yml
  modules/nf-core/hiphase/tests/main.nf.test
  modules/nf-core/hiphase/tests/main.nf.test.snap
  modules/nf-core/pbsv/call/tests/main.nf.test.snap
Labels: new module, Ready for Review

#6962 Remove pytest remainings
  tests/modules/nf-core/checkm/qa/main.nf
  tests/modules/nf-core/checkm/qa/nextflow.config
  tests/modules/nf-core/checkm/qa/test.yml
Labels: Ready for Review, delete-pytest

#6925 New module: anndata/getsize module
  modules/nf-core/anndata/getsize/environment.yml
  modules/nf-core/anndata/getsize/main.nf
  modules/nf-core/anndata/getsize/meta.yml
  modules/nf-core/anndata/getsize/templates/getsize.py
  modules/nf-core/anndata/getsize/tests/main.nf.test
  modules/nf-core/anndata/getsize/tests/main.nf.test.snap
Labels: new module, Ready for Review

#6959 Add Coverm contigs module
  modules/nf-core/coverm/contig/environment.yml
  modules/nf-core/coverm/contig/main.nf
  modules/nf-core/coverm/contig/meta.yml
  modules/nf-core/coverm/contig/tests/main.nf.test
  modules/nf-core/coverm/contig/tests/main.nf.test.snap
Labels: Ready for Review

#7002 Added module trgt/genotype
  modules/nf-core/trgt/genotype/environment.yml
  modules/nf-core/trgt/genotype/main.nf
  modules/nf-core/trgt/genotype/meta.yml
  modules/nf-core/trgt/genotype/tests/main.nf.test
  modules/nf-core/trgt/genotype/tests/main.nf.test.snap
Labels: Ready for Review

#6998 Fastq align dedup bismark
  subworkflows/nf-core/fastq_align_dedup_bismark/main.nf
  subworkflows/nf-core/fastq_align_dedup_bismark/meta.yml
  subworkflows/nf-core/fastq_align_dedup_bismark/tests/main.nf.test
  subworkflows/nf-core/fastq_align_dedup_bismark/tests/main.nf.test.snap
  subworkflows/nf-core/fastq_align_dedup_bismark/tests/nextflow.config
Labels: Ready for Review, new subworkflow

#7012 Added module trgt/merge
  modules/nf-core/trgt/merge/environment.yml
  modules/nf-core/trgt/merge/main.nf
  modules/nf-core/trgt/merge/meta.yml
  modules/nf-core/trgt/merge/tests/main.nf.test
  modules/nf-core/trgt/merge/tests/main.nf.test.snap
  modules/nf-core/trgt/merge/tests/nextflow.config
Labels: Ready for Review

#7005 improve workflow logic for `fastq_align_dedup_bismark`
  subworkflows/nf-core/fastq_align_dedup_bismark/main.nf
  subworkflows/nf-core/fastq_align_dedup_bismark/meta.yml
  subworkflows/nf-core/fastq_align_dedup_bismark/tests/main.nf.test
  subworkflows/nf-core/fastq_align_dedup_bismark/tests/main.nf.test.snap
  subworkflows/nf-core/fastq_align_dedup_bismark/tests/nextflow.config
Labels: new subworkflow, ready to merge

#7080 trgt/merge: Made extension of stub test configurable
  modules/nf-core/trgt/merge/main.nf
Labels: Ready for Review

#7081 remove soft-linking of fasta instead stage in dir
  modules/nf-core/bismark/align/main.nf
  modules/nf-core/bismark/coverage2cytosine/main.nf
  modules/nf-core/bismark/deduplicate/main.nf
  modules/nf-core/bismark/genomepreparation/main.nf
  modules/nf-core/bismark/genomepreparation/tests/main.nf.test.snap
  modules/nf-core/bismark/methylationextractor/main.nf
  modules/nf-core/bismark/report/main.nf
Labels: Ready for Review

#7049 `BCFTOOLS_CONVERT` Migration to nf-test
  modules/nf-core/bcftools/convert/main.nf
  modules/nf-core/bcftools/convert/meta.yml
  modules/nf-core/bcftools/convert/tests/main.nf.test
  modules/nf-core/bcftools/convert/tests/main.nf.test.snap
  modules/nf-core/bcftools/convert/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bcftools/convert/main.nf
  tests/modules/nf-core/bcftools/convert/nextflow.config
  tests/modules/nf-core/bcftools/convert/test.yml
Labels: nf-test

#6920 Bump GUNC and add gunc/run test
  modules/nf-core/gunc/downloaddb/environment.yml
  modules/nf-core/gunc/downloaddb/main.nf
  modules/nf-core/gunc/downloaddb/tests/main.nf.test.snap
  modules/nf-core/gunc/mergecheckm/environment.yml
  modules/nf-core/gunc/mergecheckm/main.nf
  modules/nf-core/gunc/mergecheckm/tests/main.nf.test
  modules/nf-core/gunc/mergecheckm/tests/main.nf.test.snap
  modules/nf-core/gunc/mergecheckm/tests/nextflow.config
  modules/nf-core/gunc/mergecheckm/tests/tags.yml
  modules/nf-core/gunc/run/environment.yml
  modules/nf-core/gunc/run/main.nf
  modules/nf-core/gunc/run/meta.yml
  modules/nf-core/gunc/run/tests/main.nf.test
  modules/nf-core/gunc/run/tests/main.nf.test.snap
  modules/nf-core/gunc/run/tests/tags.yml
  tests/config/pytest_modules.yml
Labels: Ready for Review

#7010 Fasta index bismark bwameth
  subworkflows/nf-core/fasta_index_bismark_bwameth/main.nf
  subworkflows/nf-core/fasta_index_bismark_bwameth/meta.yml
  subworkflows/nf-core/fasta_index_bismark_bwameth/tests/main.nf.test
  subworkflows/nf-core/fasta_index_bismark_bwameth/tests/main.nf.test.snap
  subworkflows/nf-core/fasta_index_bismark_bwameth/tests/nextflow.config
Labels: Ready for Review, new subworkflow

#7052 Add module gzrt (#6918)
  modules/nf-core/gzrt/environment.yml
  modules/nf-core/gzrt/main.nf
  modules/nf-core/gzrt/meta.yml
  modules/nf-core/gzrt/tests/main.nf.test
  modules/nf-core/gzrt/tests/main.nf.test.snap
Labels: new module, Ready for Review

#7100 New Module: NACHO_NORMALISE
  modules/nf-core/nacho/normalize/environment.yml
  modules/nf-core/nacho/normalize/main.nf
  modules/nf-core/nacho/normalize/meta.yml
  modules/nf-core/nacho/normalize/resources/usr/bin/nacho_norm.R
  modules/nf-core/nacho/normalize/tests/main.nf.test
  modules/nf-core/nacho/normalize/tests/main.nf.test.snap
  modules/nf-core/nacho/normalize/tests/nextflow.config
Labels: new module

#7108 New Module: NACHO_QC
  modules/nf-core/nacho/qc/environment.yml
  modules/nf-core/nacho/qc/main.nf
  modules/nf-core/nacho/qc/meta.yml
  modules/nf-core/nacho/qc/resources/usr/bin/nacho_qc.R
  modules/nf-core/nacho/qc/tests/main.nf.test
  modules/nf-core/nacho/qc/tests/main.nf.test.snap
  modules/nf-core/nacho/qc/tests/nextflow.config
Labels: enhancement, new module

#7007 Fastq align dedup bwameth
  .github/actions/nf-test-action/action.yml
  .github/workflows/gpu-tests.yml
  .github/workflows/nf-test.yml
  modules/nf-core/gffread/tests/main.nf.test
  subworkflows/nf-core/fastq_align_dedup_bwameth/main.nf
  subworkflows/nf-core/fastq_align_dedup_bwameth/meta.yml
  subworkflows/nf-core/fastq_align_dedup_bwameth/tests/gpu.nf.test
  subworkflows/nf-core/fastq_align_dedup_bwameth/tests/gpu.nf.test.snap
  subworkflows/nf-core/fastq_align_dedup_bwameth/tests/main.nf.test
  subworkflows/nf-core/fastq_align_dedup_bwameth/tests/main.nf.test.snap
  subworkflows/nf-core/fastq_align_dedup_bwameth/tests/nextflow.config
Labels: Ready for Review, new subworkflow
