Repository nf-core/modules, pull requests merged in 2024-04, with the labels that each got.

#5412 New module: velocyto, a library for the analysis of RNA velocity.
  modules/nf-core/velocyto/environment.yml
  modules/nf-core/velocyto/main.nf
  modules/nf-core/velocyto/meta.yml
  modules/nf-core/velocyto/tests/main.nf.test
  modules/nf-core/velocyto/tests/main.nf.test.snap
  modules/nf-core/velocyto/tests/tags.yml
  modules/nf-core/velocyto/tests/test.config
Labels: new module

#5394 Update spaceranger container
  modules/nf-core/spaceranger/Dockerfile
  modules/nf-core/spaceranger/README.md
  modules/nf-core/spaceranger/count/main.nf
  modules/nf-core/spaceranger/count/tests/main.nf.test
  modules/nf-core/spaceranger/count/tests/main.nf.test.snap
  modules/nf-core/spaceranger/count/tests/nextflow.config
  modules/nf-core/spaceranger/mkgtf/main.nf
  modules/nf-core/spaceranger/mkgtf/tests/main.nf.test.snap
  modules/nf-core/spaceranger/mkref/main.nf
  modules/nf-core/spaceranger/mkref/tests/main.nf.test.snap
Labels: Ready for Review

#5370 add module: Add xengsort/index
  modules/nf-core/xengsort/index/environment.yml
  modules/nf-core/xengsort/index/main.nf
  modules/nf-core/xengsort/index/meta.yml
  modules/nf-core/xengsort/index/tests/main.nf.test
  modules/nf-core/xengsort/index/tests/main.nf.test.snap
  modules/nf-core/xengsort/index/tests/tags.yml
Labels: new module, Ready for Review

#5292 nf-test: Migrate phispy tests to nf-test
  modules/nf-core/phispy/environment.yml
  modules/nf-core/phispy/meta.yml
  modules/nf-core/phispy/tests/main.nf.test
  modules/nf-core/phispy/tests/main.nf.test.snap
  modules/nf-core/phispy/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/phispy/main.nf
  tests/modules/nf-core/phispy/nextflow.config
  tests/modules/nf-core/phispy/test.yml
Labels: Ready for Review, nf-test

#5444 UPDATE: added barcoding option to ToulligQC module
  modules/nf-core/toulligqc/main.nf
  modules/nf-core/toulligqc/meta.yml
  modules/nf-core/toulligqc/tests/main.nf.test
  modules/nf-core/toulligqc/tests/main.nf.test.snap
  modules/nf-core/toulligqc/tests/nextflow.config
Labels: update module, Ready for Review

#5344 Migrate `gatk4/mutect2` tests to nf-test
  modules/nf-core/gatk4/mutect2/tests/f1r2.config
  modules/nf-core/gatk4/mutect2/tests/main.nf.test
  modules/nf-core/gatk4/mutect2/tests/main.nf.test.snap
  modules/nf-core/gatk4/mutect2/tests/mito.config
  modules/nf-core/gatk4/mutect2/tests/pair.config
  modules/nf-core/gatk4/mutect2/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gatk4/mutect2/main.nf
  tests/modules/nf-core/gatk4/mutect2/nextflow.config
  tests/modules/nf-core/gatk4/mutect2/test.yml
Labels: Ready for Review

#4657 Feat/agat/convertspgff2tsv nf test
  modules/nf-core/agat/convertspgff2tsv/main.nf
  modules/nf-core/agat/convertspgff2tsv/tests/main.nf.test
  modules/nf-core/agat/convertspgff2tsv/tests/main.nf.test.snap
  modules/nf-core/agat/convertspgff2tsv/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/agat/convertspgff2tsv/main.nf
  tests/modules/nf-core/agat/convertspgff2tsv/nextflow.config
  tests/modules/nf-core/agat/convertspgff2tsv/test.yml
Labels: Ready for Review, nf-test

#5463 Update seqkit to 2.8.1
  modules/nf-core/seqkit/fx2tab/environment.yml
  modules/nf-core/seqkit/fx2tab/main.nf
  modules/nf-core/seqkit/tab2fx/environment.yml
  modules/nf-core/seqkit/tab2fx/main.nf
Labels: update module, Ready for Review

#5476 agat/convertspgxf2gxf: Version bumped to 1.4.0
  modules/nf-core/agat/convertspgxf2gxf/environment.yml
  modules/nf-core/agat/convertspgxf2gxf/main.nf
  modules/nf-core/agat/convertspgxf2gxf/meta.yml
  modules/nf-core/agat/convertspgxf2gxf/tests/main.nf.test.snap
Labels: update module, Ready for Review

#5468 Add bedops convert2bed
  modules/nf-core/bedops/convert2bed/environment.yml
  modules/nf-core/bedops/convert2bed/main.nf
  modules/nf-core/bedops/convert2bed/meta.yml
  modules/nf-core/bedops/convert2bed/tests/main.nf.test
  modules/nf-core/bedops/convert2bed/tests/main.nf.test.snap
  modules/nf-core/bedops/convert2bed/tests/tags.yml
Labels: new module, Ready for Review

#5283 New subworkflow: Bam dedup stats samtools umicollapse
  subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/main.nf
  subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/meta.yml
  subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/tests/main.nf.test
  subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/tests/main.nf.test.snap
  subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/tests/paired-end-umis.config
  subworkflows/nf-core/bam_dedup_stats_samtools_umicollapse/tests/tags.yml
Labels: help wanted, tests, new subworkflow, rnaseq

#5493 New Module: humid
  modules/nf-core/humid/environment.yml
  modules/nf-core/humid/main.nf
  modules/nf-core/humid/meta.yml
  modules/nf-core/humid/tests/main.nf.test
  modules/nf-core/humid/tests/main.nf.test.snap
  modules/nf-core/humid/tests/nextflow.config
  modules/nf-core/humid/tests/tags.yml
Labels: new module, Ready for Review

#5506 bump wisecondorx modules
  modules/nf-core/wisecondorx/convert/main.nf
  modules/nf-core/wisecondorx/convert/tests/main.nf.test.snap
  modules/nf-core/wisecondorx/gender/main.nf
  modules/nf-core/wisecondorx/gender/tests/main.nf.test.snap
  modules/nf-core/wisecondorx/newref/main.nf
  modules/nf-core/wisecondorx/newref/tests/main.nf.test.snap
  modules/nf-core/wisecondorx/predict/main.nf
  modules/nf-core/wisecondorx/predict/tests/main.nf.test.snap
Labels: update module

#5511 fix gawk stubs
  modules/nf-core/gawk/main.nf
Labels: bug

#5459 PEKA module update
  modules/nf-core/peka/main.nf
  modules/nf-core/peka/meta.yml
Labels: ready to merge

#5428 New module: gnu/split
  modules/nf-core/gnu/split/environment.yml
  modules/nf-core/gnu/split/main.nf
  modules/nf-core/gnu/split/meta.yml
  modules/nf-core/gnu/split/tests/main.nf.test
  modules/nf-core/gnu/split/tests/main.nf.test.snap
  modules/nf-core/gnu/split/tests/split_csv.config
  modules/nf-core/gnu/split/tests/split_fastq_gz.config
  modules/nf-core/gnu/split/tests/tags.yml
Labels: new module, Ready for Review, ready to merge

#5416 Added repeatmodeler/builddatabase
  modules/nf-core/repeatmodeler/builddatabase/environment.yml
  modules/nf-core/repeatmodeler/builddatabase/main.nf
  modules/nf-core/repeatmodeler/builddatabase/meta.yml
  modules/nf-core/repeatmodeler/builddatabase/tests/main.nf.test
  modules/nf-core/repeatmodeler/builddatabase/tests/main.nf.test.snap
  modules/nf-core/repeatmodeler/builddatabase/tests/tags.yml
Labels: ready to merge

#5531 Changed tag from single quotes to double quotes
  modules/nf-core/ucsc/gtftogenepred/main.nf
Labels: bug, Ready for Review

#5328 re delete gatk4/bedtointervallist from pytest_modules.yml after it was added again (see #5251)
  tests/config/pytest_modules.yml
Labels: nf-test

#5470 migrating flash to nf-test
  modules/nf-core/flash/main.nf
  modules/nf-core/flash/meta.yml
  modules/nf-core/flash/tests/main.nf.test
  modules/nf-core/flash/tests/main.nf.test.snap
  modules/nf-core/flash/tests/nextflow.config
  modules/nf-core/flash/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/flash/main.nf
  tests/modules/nf-core/flash/nextflow.config
  tests/modules/nf-core/flash/test.yml
Labels: nf-test

#5537 add riboseq transcriptome bam to test config
  tests/config/test_data.config
Labels: Ready for Review

#5482 Blastdbcmd new module
  modules/nf-core/blast/blastdbcmd/environment.yml
  modules/nf-core/blast/blastdbcmd/main.nf
  modules/nf-core/blast/blastdbcmd/meta.yml
  modules/nf-core/blast/blastdbcmd/tests/main.nf.test
  modules/nf-core/blast/blastdbcmd/tests/main.nf.test.snap
  modules/nf-core/blast/blastdbcmd/tests/nextflow.config
  modules/nf-core/blast/blastdbcmd/tests/nextflow.txt.config
  modules/nf-core/blast/blastdbcmd/tests/tags.yml
  tests/config/test_data.config
Labels: new module
