Repository nf-core/modules, pull requests merged in 2024-12, with the labels that each got.

#7119 checkm/qa: Improve input validation
  modules/nf-core/checkm/qa/main.nf
Labels: Ready for Review

#7061 `SHAPEIT5_PHASECOMMON` Migrate to nf-test
  modules/nf-core/shapeit5/phasecommon/environment.yml
  modules/nf-core/shapeit5/phasecommon/main.nf
  modules/nf-core/shapeit5/phasecommon/tests/main.nf.test
  modules/nf-core/shapeit5/phasecommon/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/shapeit5/phasecommon/main.nf
  tests/modules/nf-core/shapeit5/phasecommon/nextflow.config
  tests/modules/nf-core/shapeit5/phasecommon/test.yml
Labels: nf-test

#7031 Cellbender empty droplet removal
  subworkflows/nf-core/h5ad_removebackground_barcodes_cellbender_anndata/main.nf
  subworkflows/nf-core/h5ad_removebackground_barcodes_cellbender_anndata/meta.yml
  subworkflows/nf-core/h5ad_removebackground_barcodes_cellbender_anndata/tests/epochs.config
  subworkflows/nf-core/h5ad_removebackground_barcodes_cellbender_anndata/tests/main.nf.test
  subworkflows/nf-core/h5ad_removebackground_barcodes_cellbender_anndata/tests/main.nf.test.snap
Labels: Ready for Review, new subworkflow

#7060 `SHAPEIT5_LIGATE` Migration to nf-test
  modules/nf-core/shapeit5/ligate/environment.yml
  modules/nf-core/shapeit5/ligate/main.nf
  modules/nf-core/shapeit5/ligate/tests/main.nf.test
  modules/nf-core/shapeit5/ligate/tests/main.nf.test.snap
  modules/nf-core/shapeit5/ligate/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/shapeit5/ligate/main.nf
  tests/modules/nf-core/shapeit5/ligate/nextflow.config
  tests/modules/nf-core/shapeit5/ligate/test.yml
Labels: nf-test

#7066 `SHAPEIT5_SWITCH` Migrate to nf-test
  modules/nf-core/shapeit5/switch/environment.yml
  modules/nf-core/shapeit5/switch/main.nf
  modules/nf-core/shapeit5/switch/tests/main.nf.test
  modules/nf-core/shapeit5/switch/tests/main.nf.test.snap
  modules/nf-core/shapeit5/switch/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/shapeit5/switch/main.nf
  tests/modules/nf-core/shapeit5/switch/nextflow.config
  tests/modules/nf-core/shapeit5/switch/test.yml
Labels: nf-test

#7116 Pyrodigal - add --jobs flag for multi-threaded operation, bump version
  modules/nf-core/pyrodigal/environment.yml
  modules/nf-core/pyrodigal/main.nf
  modules/nf-core/pyrodigal/tests/main.nf.test.snap
Labels: Ready for Review

#6980 port parabricks/genotypegvcf to nf-test
  .github/conda_skip.yml
  modules/nf-core/parabricks/genotypegvcf/main.nf
  modules/nf-core/parabricks/genotypegvcf/tests/main.nf.test
  modules/nf-core/parabricks/genotypegvcf/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/parabricks/genotypegvcf/main.nf
  tests/modules/nf-core/parabricks/genotypegvcf/nextflow.config
  tests/modules/nf-core/parabricks/genotypegvcf/test.yml
  tests/modules/nf-core/parabricks/genotypegvcf/test_GPU_config.txt
  tests/modules/nf-core/parabricks/genotypegvcf/test_GPU_yml.txt
Labels: nf-test, gpu

#7182 new module pangolin/updatedata & patch pangolin/run
  modules/nf-core/pangolin/run/environment.yml
  modules/nf-core/pangolin/run/main.nf
  modules/nf-core/pangolin/run/meta.yml
  modules/nf-core/pangolin/run/tests/main.nf.test
  modules/nf-core/pangolin/run/tests/main.nf.test.snap
  modules/nf-core/pangolin/tests/main.nf.test
  modules/nf-core/pangolin/updatedata/environment.yml
  modules/nf-core/pangolin/updatedata/main.nf
  modules/nf-core/pangolin/updatedata/meta.yml
  modules/nf-core/pangolin/updatedata/tests/main.nf.test
  modules/nf-core/pangolin/updatedata/tests/main.nf.test.snap
Labels: new module, Ready for Review

#6996 port parabricks/indexgvcf to nf-test
  .github/conda_skip.yml
  modules/nf-core/parabricks/indexgvcf/main.nf
  modules/nf-core/parabricks/indexgvcf/meta.yml
  modules/nf-core/parabricks/indexgvcf/tests/main.nf.test
  modules/nf-core/parabricks/indexgvcf/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/parabricks/indexgvcf/main.nf
  tests/modules/nf-core/parabricks/indexgvcf/nextflow.config
  tests/modules/nf-core/parabricks/indexgvcf/test.yml
  tests/modules/nf-core/parabricks/indexgvcf/test_GPU_config.txt
  tests/modules/nf-core/parabricks/indexgvcf/test_GPU_yml.txt
Labels: Ready for Review, nf-test, gpu

#6977 Port `parabricks/dbsnp` to nf-test
  .github/conda_skip.yml
  modules/nf-core/parabricks/dbsnp/main.nf
  modules/nf-core/parabricks/dbsnp/tests/main.nf.test
  modules/nf-core/parabricks/dbsnp/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/parabricks/dbsnp/main.nf
  tests/modules/nf-core/parabricks/dbsnp/nextflow.config
  tests/modules/nf-core/parabricks/dbsnp/test.yml
  tests/modules/nf-core/parabricks/dbsnp/test_GPU_config.txt
  tests/modules/nf-core/parabricks/dbsnp/test_GPU_yml.txt
Labels: Ready for Review, nf-test, gpu

#7163 Modify DAS_Tool input structure, bump version, switch to nf-test
  modules/nf-core/dastool/dastool/environment.yml
  modules/nf-core/dastool/dastool/main.nf
  modules/nf-core/dastool/dastool/meta.yml
  modules/nf-core/dastool/dastool/tests/main.nf.test
  modules/nf-core/dastool/dastool/tests/main.nf.test.snap
  modules/nf-core/dastool/dastool/tests/nextflow.config
  modules/nf-core/dastool/fastatocontig2bin/environment.yml
  modules/nf-core/dastool/fastatocontig2bin/main.nf
  modules/nf-core/dastool/fastatocontig2bin/tests/main.nf.test
  modules/nf-core/dastool/fastatocontig2bin/tests/main.nf.test.snap
  modules/nf-core/dastool/scaffolds2bin/main.nf
  modules/nf-core/dastool/scaffolds2bin/tests/main.nf.test
  modules/nf-core/dastool/scaffolds2bin/tests/main.nf.test.snap
  modules/nf-core/metabat2/metabat2/main.nf
  tests/config/pytest_modules.yml
  tests/modules/nf-core/dastool/dastool/main.nf
  tests/modules/nf-core/dastool/dastool/nextflow.config
  tests/modules/nf-core/dastool/dastool/test.yml
  tests/modules/nf-core/dastool/fastatocontig2bin/main.nf
  tests/modules/nf-core/dastool/fastatocontig2bin/test.yml
  tests/modules/nf-core/dastool/scaffolds2bin/main.nf
  tests/modules/nf-core/dastool/scaffolds2bin/nextflow.config
  tests/modules/nf-core/dastool/scaffolds2bin/test.yml
Labels: Ready for Review

#7189 update parabricks/applybqsr
  .github/conda_skip.yml
  modules/nf-core/parabricks/applybqsr/main.nf
  modules/nf-core/parabricks/applybqsr/tests/main.nf.test.snap
Labels: Ready for Review, gpu

#7210 Add busco downloads as output
  modules/nf-core/busco/busco/main.nf
  modules/nf-core/busco/busco/meta.yml
  modules/nf-core/busco/busco/tests/main.nf.test
  modules/nf-core/busco/busco/tests/main.nf.test.snap
  modules/nf-core/busco/generateplot/environment.yml
  modules/nf-core/busco/generateplot/main.nf
  modules/nf-core/busco/generateplot/tests/main.nf.test.snap
  subworkflows/nf-core/fasta_gxf_busco_plot/tests/main.nf.test.snap
Labels: ready to merge

#6991 port parabricks/mutectcaller to nf-test
  .github/conda_skip.yml
  modules/nf-core/parabricks/mutectcaller/main.nf
  modules/nf-core/parabricks/mutectcaller/tests/main.nf.test
  modules/nf-core/parabricks/mutectcaller/tests/main.nf.test.snap
  modules/nf-core/parabricks/mutectcaller/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/parabricks/mutectcaller/main.nf
  tests/modules/nf-core/parabricks/mutectcaller/nextflow.config
  tests/modules/nf-core/parabricks/mutectcaller/test.yml
  tests/modules/nf-core/parabricks/mutectcaller/test_GPU_config.txt
  tests/modules/nf-core/parabricks/mutectcaller/test_GPU_yml.txt
Labels: nf-test, gpu

#7225 Update gzrt
  modules/nf-core/gzrt/main.nf
  modules/nf-core/gzrt/tests/main.nf.test
  modules/nf-core/gzrt/tests/main.nf.test.snap
Labels: update module

#7227 update parabricks/fq2bam
  modules/nf-core/parabricks/fq2bam/main.nf
  modules/nf-core/parabricks/fq2bam/meta.yml
  modules/nf-core/parabricks/fq2bam/tests/main.nf.test
  modules/nf-core/parabricks/fq2bam/tests/main.nf.test.snap
  modules/nf-core/parabricks/fq2bam/tests/nextflow.config
Labels: Ready for Review

#7202 Update vcf2maf and add stub tests
  modules/nf-core/vcf2maf/environment.yml
  modules/nf-core/vcf2maf/main.nf
  modules/nf-core/vcf2maf/tests/main.nf.test
  modules/nf-core/vcf2maf/tests/main.nf.test.snap
  modules/nf-core/vcf2maf/tests/nextflow.config
  modules/nf-core/vcf2maf/tests/nextflow.withVEP.config
  modules/nf-core/vcf2maf/tests/tags.yml
Labels: Ready for Review

#7220 Add propd to abundance_differential_filter subworkflow
  subworkflows/nf-core/abundance_differential_filter/main.nf
  subworkflows/nf-core/abundance_differential_filter/meta.yml
  subworkflows/nf-core/abundance_differential_filter/tests/deseq2_limmavoom_propd_basic.config
  subworkflows/nf-core/abundance_differential_filter/tests/main.nf.test
  subworkflows/nf-core/abundance_differential_filter/tests/main.nf.test.snap
  subworkflows/nf-core/abundance_differential_filter/tests/propd_basic.config
Labels: ready to merge

#7218 Add module custom_tabulargseatochip
  modules/nf-core/custom/tabulartogseachip/environment.yml
  modules/nf-core/custom/tabulartogseachip/main.nf
  modules/nf-core/custom/tabulartogseachip/meta.yml
  modules/nf-core/custom/tabulartogseachip/tests/main.nf.test
  modules/nf-core/custom/tabulartogseachip/tests/main.nf.test.snap
Labels: ready to merge

#7229 Nf-test migration `CNVKIT/EXPORT`
  modules/nf-core/cnvkit/call/tests/main.nf.test
  modules/nf-core/cnvkit/call/tests/main.nf.test.snap
  modules/nf-core/cnvkit/export/main.nf
  modules/nf-core/cnvkit/export/meta.yml
  modules/nf-core/cnvkit/export/tests/main.nf.test
  modules/nf-core/cnvkit/export/tests/main.nf.test.snap
  modules/nf-core/cnvkit/export/tests/nextflow.config
  modules/nf-core/cnvkit/genemetrics/tests/main.nf.test
  modules/nf-core/cnvkit/genemetrics/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/cnvkit/export/main.nf
  tests/modules/nf-core/cnvkit/export/nextflow.config
  tests/modules/nf-core/cnvkit/export/test.yml
Labels: nf-test

#7252 Change flye oras container
  modules/nf-core/flye/main.nf
Labels: container-issue

#7230 Allow Metabat2 to take uncompressed depths file and bump version
  modules/nf-core/metabat2/metabat2/environment.yml
  modules/nf-core/metabat2/metabat2/main.nf
  modules/nf-core/metabat2/metabat2/tests/main.nf.test
  modules/nf-core/metabat2/metabat2/tests/main.nf.test.snap
Labels: Ready for Review

#7236 initial commit of kma_index
  modules/nf-core/kma/index/environment.yml
  modules/nf-core/kma/index/main.nf
  modules/nf-core/kma/index/meta.yml
  modules/nf-core/kma/index/tests/main.nf.test
  modules/nf-core/kma/index/tests/main.nf.test.snap
  modules/nf-core/kma/index/tests/tags.yml
Labels: new module, Ready for Review

#7259 CheckM2 module updates
  modules/nf-core/checkm2/databasedownload/main.nf
  modules/nf-core/checkm2/predict/main.nf
  modules/nf-core/checkm2/predict/meta.yml
  modules/nf-core/checkm2/predict/tests/main.nf.test
  modules/nf-core/checkm2/predict/tests/main.nf.test.snap
Labels: Ready for Review
