Repository nf-core/modules, pull requests merged in 2024-07, with the labels that each got.

#3610 Update md5sum module to be able to take multiple files
  modules/nf-core/md5sum/main.nf
  modules/nf-core/md5sum/meta.yml
  modules/nf-core/md5sum/tests/main.nf.test
  modules/nf-core/md5sum/tests/main.nf.test.snap
Labels: Ready for Review

#5801 build: Bump deepvariant to 1.6.1
  modules/nf-core/deepvariant/README.md
  modules/nf-core/deepvariant/main.nf
  modules/nf-core/deepvariant/tests/main.nf.test.snap
Labels: quay.io

#4665 sourmash/compare stub, nf-test, snapshot
  modules/nf-core/sourmash/compare/main.nf
  modules/nf-core/sourmash/compare/meta.yml
  modules/nf-core/sourmash/compare/tests/main.nf.test
  modules/nf-core/sourmash/compare/tests/main.nf.test.snap
  modules/nf-core/sourmash/compare/tests/nextflow.config
  modules/nf-core/sourmash/compare/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/sourmash/compare/main.nf
  tests/modules/nf-core/sourmash/compare/nextflow.config
  tests/modules/nf-core/sourmash/compare/test.yml
Labels: Ready for Review, nf-test, mismatched hashes

#4512 adding chewbbaca/createschema module
  modules/nf-core/chewbbaca/createschema/environment.yml
  modules/nf-core/chewbbaca/createschema/main.nf
  modules/nf-core/chewbbaca/createschema/meta.yml
  modules/nf-core/chewbbaca/createschema/tests/main.nf.test
  modules/nf-core/chewbbaca/createschema/tests/main.nf.test.snap
  modules/nf-core/chewbbaca/createschema/tests/tags.yml
Labels: new module, Ready for Review

#4651 affy/justrma add stub, nf-test and snapshot
  modules/nf-core/affy/justrma/environment.yml
  modules/nf-core/affy/justrma/main.nf
  modules/nf-core/affy/justrma/templates/affy_justrma.R
  modules/nf-core/affy/justrma/tests/main.nf.test
  modules/nf-core/affy/justrma/tests/main.nf.test.snap
  modules/nf-core/affy/justrma/tests/nextflow.config
  modules/nf-core/affy/justrma/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/affy/justrma/main.nf
  tests/modules/nf-core/affy/justrma/nextflow.config
  tests/modules/nf-core/affy/justrma/test.yml
Labels: nf-test, mismatched hashes

#5624 Bump fgbio versions and swap to nftest
  modules/nf-core/fgbio/callduplexconsensusreads/environment.yml
  modules/nf-core/fgbio/callduplexconsensusreads/main.nf
  modules/nf-core/fgbio/callduplexconsensusreads/meta.yml
  modules/nf-core/fgbio/callduplexconsensusreads/tests/main.nf.test
  modules/nf-core/fgbio/callduplexconsensusreads/tests/main.nf.test.snap
  modules/nf-core/fgbio/callduplexconsensusreads/tests/tags.yml
  modules/nf-core/fgbio/callmolecularconsensusreads/environment.yml
  modules/nf-core/fgbio/callmolecularconsensusreads/main.nf
  modules/nf-core/fgbio/callmolecularconsensusreads/meta.yml
  modules/nf-core/fgbio/callmolecularconsensusreads/tests/main.nf.test
  modules/nf-core/fgbio/callmolecularconsensusreads/tests/main.nf.test.snap
  modules/nf-core/fgbio/callmolecularconsensusreads/tests/sort.config
  modules/nf-core/fgbio/callmolecularconsensusreads/tests/tags.yml
  modules/nf-core/fgbio/fastqtobam/environment.yml
  modules/nf-core/fgbio/fastqtobam/main.nf
  modules/nf-core/fgbio/fastqtobam/tests/main.nf.test
  modules/nf-core/fgbio/fastqtobam/tests/main.nf.test.snap
  modules/nf-core/fgbio/filterconsensusreads/environment.yml
  modules/nf-core/fgbio/filterconsensusreads/main.nf
  modules/nf-core/fgbio/filterconsensusreads/meta.yml
  modules/nf-core/fgbio/filterconsensusreads/tests/main.nf.test
  modules/nf-core/fgbio/filterconsensusreads/tests/main.nf.test.snap
  modules/nf-core/fgbio/filterconsensusreads/tests/tags.yml
  modules/nf-core/fgbio/groupreadsbyumi/environment.yml
  modules/nf-core/fgbio/groupreadsbyumi/main.nf
  modules/nf-core/fgbio/groupreadsbyumi/meta.yml
  modules/nf-core/fgbio/groupreadsbyumi/tests/main.nf.test
  modules/nf-core/fgbio/groupreadsbyumi/tests/main.nf.test.snap
  modules/nf-core/fgbio/groupreadsbyumi/tests/tags.yml
  modules/nf-core/fgbio/sortbam/environment.yml
  modules/nf-core/fgbio/sortbam/main.nf
  modules/nf-core/fgbio/sortbam/tests/main.nf.test
  modules/nf-core/fgbio/sortbam/tests/main.nf.test.snap
  modules/nf-core/fgbio/sortbam/tests/tags.yml
  modules/nf-core/fgbio/zipperbams/environment.yml
  modules/nf-core/fgbio/zipperbams/main.nf
  modules/nf-core/fgbio/zipperbams/meta.yml
  modules/nf-core/fgbio/zipperbams/tests/main.nf.test
  modules/nf-core/fgbio/zipperbams/tests/main.nf.test.snap
  modules/nf-core/fgbio/zipperbams/tests/nextflow.config
  modules/nf-core/fgbio/zipperbams/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/fgbio/callduplexconsensusreads/main.nf
  tests/modules/nf-core/fgbio/callduplexconsensusreads/nextflow.config
  tests/modules/nf-core/fgbio/callduplexconsensusreads/test.yml
  tests/modules/nf-core/fgbio/callmolecularconsensusreads/main.nf
  tests/modules/nf-core/fgbio/callmolecularconsensusreads/nextflow.config
  tests/modules/nf-core/fgbio/callmolecularconsensusreads/test.yml
  tests/modules/nf-core/fgbio/filterconsensusreads/main.nf
  tests/modules/nf-core/fgbio/filterconsensusreads/nextflow.config
  tests/modules/nf-core/fgbio/filterconsensusreads/test.yml
  tests/modules/nf-core/fgbio/groupreadsbyumi/main.nf
  tests/modules/nf-core/fgbio/groupreadsbyumi/nextflow.config
  tests/modules/nf-core/fgbio/groupreadsbyumi/test.yml
  tests/modules/nf-core/fgbio/sortbam/main.nf
  tests/modules/nf-core/fgbio/sortbam/nextflow.config
  tests/modules/nf-core/fgbio/sortbam/test.yml
  tests/modules/nf-core/fgbio/zipperbams/main.nf
  tests/modules/nf-core/fgbio/zipperbams/nextflow.config
  tests/modules/nf-core/fgbio/zipperbams/test.yml
Labels: Ready for Review

#5931 Update lofreq somatic and callparallel
  modules/nf-core/lofreq/callparallel/main.nf
  modules/nf-core/lofreq/callparallel/meta.yml
  modules/nf-core/lofreq/callparallel/tests/main.nf.test
  modules/nf-core/lofreq/callparallel/tests/main.nf.test.snap
  modules/nf-core/lofreq/callparallel/tests/tags.yml
  modules/nf-core/lofreq/somatic/main.nf
  modules/nf-core/lofreq/somatic/meta.yml
  modules/nf-core/lofreq/somatic/tests/main.nf.test
  modules/nf-core/lofreq/somatic/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/lofreq/callparallel/main.nf
  tests/modules/nf-core/lofreq/callparallel/nextflow.config
  tests/modules/nf-core/lofreq/callparallel/test.yml
  tests/modules/nf-core/lofreq/somatic/main.nf
  tests/modules/nf-core/lofreq/somatic/nextflow.config
  tests/modules/nf-core/lofreq/somatic/test.yml
Labels: update module

#5720 Handle empty files
  subworkflows/nf-core/bcl_demultiplex/main.nf
  subworkflows/nf-core/bcl_demultiplex/tests/main.nf.test
  subworkflows/nf-core/bcl_demultiplex/tests/main.nf.test.snap
  subworkflows/nf-core/bcl_demultiplex/tests/nextflow.config
  tests/config/nf-test.config
Labels: ready to merge

#5989 [Upgrade] Normalize input of lofreq-viterbi to match other lofreq modules
  modules/nf-core/lofreq/viterbi/main.nf
  modules/nf-core/lofreq/viterbi/meta.yml
  modules/nf-core/lofreq/viterbi/tests/main.nf.test
  modules/nf-core/lofreq/viterbi/tests/main.nf.test.snap
Labels: update module

#5960 Add module fgbio/collectduplexseqmetrics
  modules/nf-core/fgbio/collectduplexseqmetrics/environment.yml
  modules/nf-core/fgbio/collectduplexseqmetrics/main.nf
  modules/nf-core/fgbio/collectduplexseqmetrics/meta.yml
  modules/nf-core/fgbio/collectduplexseqmetrics/tests/main.nf.test
  modules/nf-core/fgbio/collectduplexseqmetrics/tests/main.nf.test.snap
  modules/nf-core/fgbio/collectduplexseqmetrics/tests/tags.yml
Labels: new module, Ready for Review

#5958 Add Seqfu/derep
  modules/nf-core/seqfu/derep/environment.yml
  modules/nf-core/seqfu/derep/main.nf
  modules/nf-core/seqfu/derep/meta.yml
  modules/nf-core/seqfu/derep/tests/main.nf.test
  modules/nf-core/seqfu/derep/tests/main.nf.test.snap
  modules/nf-core/seqfu/derep/tests/tags.yml
Labels: new module, Ready for Review

#5941 Add stub and test to lofreq/indelqual
  modules/nf-core/lofreq/indelqual/main.nf
  modules/nf-core/lofreq/indelqual/meta.yml
  modules/nf-core/lofreq/indelqual/tests/main.nf.test
  modules/nf-core/lofreq/indelqual/tests/main.nf.test.snap
  modules/nf-core/lofreq/indelqual/tests/nextflow.config
  modules/nf-core/lofreq/indelqual/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/lofreq/indelqual/main.nf
  tests/modules/nf-core/lofreq/indelqual/test.yml
Labels: enhancement, update module, Ready for Review

#6035 Megahit: nf-test & move
  modules/nf-core/megahit/environment.yml
  modules/nf-core/megahit/main.nf
  modules/nf-core/megahit/tests/main.nf.test
  modules/nf-core/megahit/tests/main.nf.test.snap
  modules/nf-core/megahit/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/megahit/main.nf
  tests/modules/nf-core/megahit/nextflow.config
  tests/modules/nf-core/megahit/test.yml
Labels: Ready for Review, nf-test

#6030 added stub command and tests
  modules/nf-core/lofreq/filter/main.nf
  modules/nf-core/lofreq/filter/tests/main.nf.test
  modules/nf-core/lofreq/filter/tests/main.nf.test.snap
  modules/nf-core/lofreq/filter/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/lofreq/filter/main.nf
  tests/modules/nf-core/lofreq/filter/nextflow.config
  tests/modules/nf-core/lofreq/filter/test.yml
Labels: tests, update module, Ready for Review, nf-test

#6051 Update checkqc to 4.0.3
  modules/nf-core/checkqc/environment.yml
  modules/nf-core/checkqc/main.nf
  modules/nf-core/checkqc/meta.yml
  modules/nf-core/checkqc/tests/main.nf.test
  modules/nf-core/checkqc/tests/main.nf.test.snap
Labels: update module, Ready for Review
