Repository nf-core/modules, pull requests merged in 2024-05, with the labels that each got.

#5542 add updates in nf-core/cellrangermulti module script
  modules/nf-core/cellranger/multi/main.nf
  modules/nf-core/cellranger/multi/tests/main.nf.test
Labels: bug, enhancement, Ready for Review

#4507 Add nf tests for the picard bam qc subworkflow
  subworkflows/nf-core/bam_qc_picard/tests/main.nf.test
  subworkflows/nf-core/bam_qc_picard/tests/main.nf.test.snap
  subworkflows/nf-core/bam_qc_picard/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/bam_qc_picard/main.nf
  tests/subworkflows/nf-core/bam_qc_picard/nextflow.config
  tests/subworkflows/nf-core/bam_qc_picard/test.yml
Labels: ready to merge, nf-test

#5549 new module: riboWaltz
  modules/nf-core/ribowaltz/environment.yml
  modules/nf-core/ribowaltz/main.nf
  modules/nf-core/ribowaltz/meta.yml
  modules/nf-core/ribowaltz/templates/ribowaltz.r
  modules/nf-core/ribowaltz/tests/main.nf.test
  modules/nf-core/ribowaltz/tests/main.nf.test.snap
  modules/nf-core/ribowaltz/tests/tags.yml
Labels: new module

#5555 Subworkflow bam_variants_demix_boot_freyja allow optional bootstrap skipping
  modules/nf-core/freyja/boot/environment.yml
  modules/nf-core/freyja/boot/main.nf
  modules/nf-core/freyja/boot/tests/main.nf.test
  modules/nf-core/freyja/boot/tests/main.nf.test.snap
  modules/nf-core/freyja/demix/environment.yml
  modules/nf-core/freyja/demix/main.nf
  modules/nf-core/freyja/demix/tests/main.nf.test
  modules/nf-core/freyja/demix/tests/main.nf.test.snap
  modules/nf-core/freyja/update/environment.yml
  modules/nf-core/freyja/update/main.nf
  modules/nf-core/freyja/update/tests/main.nf.test.snap
  modules/nf-core/freyja/variants/environment.yml
  modules/nf-core/freyja/variants/main.nf
  modules/nf-core/freyja/variants/tests/main.nf.test.snap
  subworkflows/nf-core/bam_variant_demix_boot_freyja/main.nf
  subworkflows/nf-core/bam_variant_demix_boot_freyja/tests/main.nf.test
  subworkflows/nf-core/bam_variant_demix_boot_freyja/tests/main.nf.test.snap
  subworkflows/nf-core/bam_variant_demix_boot_freyja/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/bam_variant_demix_boot_freyja/main.nf
  tests/subworkflows/nf-core/bam_variant_demix_boot_freyja/nextflow.config
  tests/subworkflows/nf-core/bam_variant_demix_boot_freyja/test.yml
Labels: nf-test

#4493 Add nf-test for biscuit/bsconv
  modules/nf-core/biscuit/bsconv/main.nf
  modules/nf-core/biscuit/bsconv/meta.yml
  modules/nf-core/biscuit/bsconv/tests/main.nf.test
  modules/nf-core/biscuit/bsconv/tests/main.nf.test.snap
  modules/nf-core/biscuit/bsconv/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/biscuit/bsconv/main.nf
  tests/modules/nf-core/biscuit/bsconv/nextflow.config
  tests/modules/nf-core/biscuit/bsconv/test.yml
Labels: nf-test

#3984 New module: GEM3/gem3mapper
  modules/nf-core/gem3/gem3indexer/meta.yml
  modules/nf-core/gem3/gem3indexer/tests/main.nf.test
  modules/nf-core/gem3/gem3indexer/tests/main.nf.test.snap
  modules/nf-core/gem3/gem3indexer/tests/tags.yml
  modules/nf-core/gem3/gem3mapper/environment.yml
  modules/nf-core/gem3/gem3mapper/main.nf
  modules/nf-core/gem3/gem3mapper/meta.yml
  modules/nf-core/gem3/gem3mapper/tests/main.nf.test
  modules/nf-core/gem3/gem3mapper/tests/main.nf.test.snap
  modules/nf-core/gem3/gem3mapper/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gem3/gem3indexer/main.nf
  tests/modules/nf-core/gem3/gem3indexer/nextflow.config
  tests/modules/nf-core/gem3/gem3indexer/test.yml
Labels: new module

#5510 Updateblastdb new module
  modules/nf-core/blast/updateblastdb/environment.yml
  modules/nf-core/blast/updateblastdb/main.nf
  modules/nf-core/blast/updateblastdb/meta.yml
  modules/nf-core/blast/updateblastdb/tests/main.nf.test
  modules/nf-core/blast/updateblastdb/tests/main.nf.test.snap
  modules/nf-core/blast/updateblastdb/tests/nextflow.decompress.config
  modules/nf-core/blast/updateblastdb/tests/tags.yml
Labels: new module

#4464 Port miniasm pytest to nf-test #4452
  modules/nf-core/miniasm/main.nf
  modules/nf-core/miniasm/tests/main.nf.test
  modules/nf-core/miniasm/tests/main.nf.test.snap
  modules/nf-core/miniasm/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/miniasm/main.nf
  tests/modules/nf-core/miniasm/nextflow.config
  tests/modules/nf-core/miniasm/test.yml
Labels: nf-test

#4166 new module: clame
  modules/nf-core/clame/environment.yml
  modules/nf-core/clame/main.nf
  modules/nf-core/clame/meta.yml
  modules/nf-core/clame/tests/main.nf.test
  modules/nf-core/clame/tests/main.nf.test.snap
  modules/nf-core/clame/tests/nextflow.config
  modules/nf-core/clame/tests/tags.yml
Labels: new module, hackathon2023

#4053 New module: seqtk/trim
  modules/nf-core/seqtk/trim/environment.yml
  modules/nf-core/seqtk/trim/main.nf
  modules/nf-core/seqtk/trim/meta.yml
  modules/nf-core/seqtk/trim/tests/main.nf.test
  modules/nf-core/seqtk/trim/tests/main.nf.test.snap
  modules/nf-core/seqtk/trim/tests/tags.yml
Labels: new module, nf-test

#4753 Update isoseq modules and migrate to nf-test
  modules/nf-core/isoseq/cluster/environment.yml
  modules/nf-core/isoseq/cluster/main.nf
  modules/nf-core/isoseq/cluster/meta.yml
  modules/nf-core/isoseq/cluster/tests/main.nf.test
  modules/nf-core/isoseq/cluster/tests/main.nf.test.snap
  modules/nf-core/isoseq/cluster/tests/nextflow.config
  modules/nf-core/isoseq/cluster/tests/tags.yml
  modules/nf-core/isoseq/refine/environment.yml
  modules/nf-core/isoseq/refine/main.nf
  modules/nf-core/isoseq/refine/meta.yml
  modules/nf-core/isoseq/refine/tests/main.nf.test
  modules/nf-core/isoseq/refine/tests/main.nf.test.snap
  modules/nf-core/isoseq/refine/tests/nextflow.config
  modules/nf-core/isoseq/refine/tests/tags.yml
  modules/nf-core/isoseq3/refine/main.nf
  modules/nf-core/lima/environment.yml
  modules/nf-core/lima/main.nf
  modules/nf-core/lima/meta.yml
  modules/nf-core/lima/tests/main.nf.test
  modules/nf-core/lima/tests/main.nf.test.snap
  modules/nf-core/lima/tests/nextflow.config
  modules/nf-core/lima/tests/tags.yml
  modules/nf-core/pbccs/main.nf
  modules/nf-core/pbccs/tests/main.nf.test
  modules/nf-core/pbccs/tests/main.nf.test.snap
  modules/nf-core/pbccs/tests/nextflow.config
  modules/nf-core/pbccs/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/isoseq3/cluster/main.nf
  tests/modules/nf-core/isoseq3/cluster/test.yml
  tests/modules/nf-core/isoseq3/refine/main.nf
  tests/modules/nf-core/isoseq3/refine/test.yml
  tests/modules/nf-core/lima/main.nf
  tests/modules/nf-core/lima/nextflow.config
  tests/modules/nf-core/lima/test.yml
  tests/modules/nf-core/pbccs/main.nf
  tests/modules/nf-core/pbccs/test.yml
Labels: Ready for Review, nf-test

#4472 Staramr/search
  modules/nf-core/staramr/search/environment.yml
  modules/nf-core/staramr/search/main.nf
  modules/nf-core/staramr/search/meta.yml
  modules/nf-core/staramr/search/tests/main.nf.test
  modules/nf-core/staramr/search/tests/main.nf.test.snap
  modules/nf-core/staramr/search/tests/tags.yml
Labels: new module, ready to merge, nf-test

#5623 basicpy version bump
  modules/nf-core/basicpy/main.nf
  modules/nf-core/basicpy/meta.yml
  tests/modules/nf-core/basicpy/nextflow.config
Labels: update module

#5524 Add SubWorkflow: mmseqs_contig_taxonomy
  subworkflows/nf-core/mmseqs_contig_taxonomy/main.nf
  subworkflows/nf-core/mmseqs_contig_taxonomy/meta.yml
  subworkflows/nf-core/mmseqs_contig_taxonomy/tests/main.nf.test
  subworkflows/nf-core/mmseqs_contig_taxonomy/tests/main.nf.test.snap
  subworkflows/nf-core/mmseqs_contig_taxonomy/tests/nextflow.config
  subworkflows/nf-core/mmseqs_contig_taxonomy/tests/tags.yml
Labels: Ready for Review

#5479 Add util for extracting ribosomal transcripts
  modules/nf-core/rrnatranscripts/environment.yml
  modules/nf-core/rrnatranscripts/main.nf
  modules/nf-core/rrnatranscripts/meta.yml
  modules/nf-core/rrnatranscripts/templates/get_rrna_transcripts.py
  modules/nf-core/rrnatranscripts/tests/main.nf.test
  modules/nf-core/rrnatranscripts/tests/main.nf.test.snap
  modules/nf-core/rrnatranscripts/tests/tags.yml
Labels: new module

#5648 5643 new module viennarnarnafold
  modules/nf-core/viennarna/rnafold/environment.yml
  modules/nf-core/viennarna/rnafold/main.nf
  modules/nf-core/viennarna/rnafold/meta.yml
  modules/nf-core/viennarna/rnafold/tests/main.nf.test
  modules/nf-core/viennarna/rnafold/tests/main.nf.test.snap
  modules/nf-core/viennarna/rnafold/tests/nf-test.config
  modules/nf-core/viennarna/rnafold/tests/tags.yml
Labels: new module

#4460 biscuit/align nf-test and snapshot
  modules/nf-core/biscuit/align/tests/main.nf.test
  modules/nf-core/biscuit/align/tests/main.nf.test.snap
  modules/nf-core/biscuit/align/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/biscuit/align/main.nf
  tests/modules/nf-core/biscuit/align/nextflow.config
  tests/modules/nf-core/biscuit/align/test.yml
Labels: nf-test

#5652 Add checkm/lineagewf nf tests.
  modules/nf-core/checkm/lineagewf/tests/main.nf.test
  modules/nf-core/checkm/lineagewf/tests/main.nf.test.snap
  modules/nf-core/checkm/lineagewf/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/checkm/lineagewf/main.nf
  tests/modules/nf-core/checkm/lineagewf/nextflow.config
  tests/modules/nf-core/checkm/lineagewf/test.yml
Labels: nf-test

#5320 Add RTNI_TNI module
  modules/nf-core/rtn/tni/environment.yml
  modules/nf-core/rtn/tni/main.nf
  modules/nf-core/rtn/tni/meta.yml
  modules/nf-core/rtn/tni/templates/rtn_tni.r
  modules/nf-core/rtn/tni/tests/main.nf.test
  modules/nf-core/rtn/tni/tests/main.nf.test.snap
  modules/nf-core/rtn/tni/tests/nextflow.config
  modules/nf-core/rtn/tni/tests/nextflow.config2
  modules/nf-core/rtn/tni/tests/nextflow.config3
  modules/nf-core/rtn/tni/tests/tags.yml
Labels: new module
