Repository nf-core/modules, pull requests merged in 2024-09, with the labels that each got.

#6507 Add `mirTrace` module
  modules/nf-core/mirtrace/qc/environment.yml
  modules/nf-core/mirtrace/qc/main.nf
  modules/nf-core/mirtrace/qc/meta.yml
  modules/nf-core/mirtrace/qc/tests/main.nf.test
  modules/nf-core/mirtrace/qc/tests/main.nf.test.snap
Labels: Ready for Review

#6547 Add bcftools/plugintag2tag
  modules/nf-core/bcftools/plugintag2tag/environment.yml
  modules/nf-core/bcftools/plugintag2tag/main.nf
  modules/nf-core/bcftools/plugintag2tag/meta.yml
  modules/nf-core/bcftools/plugintag2tag/tests/main.nf.test
  modules/nf-core/bcftools/plugintag2tag/tests/main.nf.test.snap
  modules/nf-core/bcftools/plugintag2tag/tests/nextflow.config
  modules/nf-core/bcftools/plugintag2tag/tests/tags.yml
  modules/nf-core/bcftools/plugintag2tag/tests/vcf_gz_index.config
  modules/nf-core/bcftools/plugintag2tag/tests/vcf_gz_index_csi.config
  modules/nf-core/bcftools/plugintag2tag/tests/vcf_gz_index_tbi.config
Labels: Ready for Review

#6593 update mirtrace
  modules/nf-core/mirtrace/qc/main.nf
  modules/nf-core/mirtrace/qc/tests/main.nf.test
  modules/nf-core/mirtrace/qc/tests/main.nf.test.snap
Labels: Ready for Review

#6288 Orthofinder
  modules/nf-core/orthofinder/environment.yml
  modules/nf-core/orthofinder/main.nf
  modules/nf-core/orthofinder/meta.yml
  modules/nf-core/orthofinder/tests/main.nf.test
  modules/nf-core/orthofinder/tests/main.nf.test.snap
Labels: enhancement

#6587 Add module and subworkflow mirtop
  modules/nf-core/mirtop/counts/environment.yml
  modules/nf-core/mirtop/counts/main.nf
  modules/nf-core/mirtop/counts/meta.yml
  modules/nf-core/mirtop/counts/tests/main.nf.test
  modules/nf-core/mirtop/counts/tests/main.nf.test.snap
  modules/nf-core/mirtop/counts/tests/nextflow.config
  modules/nf-core/mirtop/export/environment.yml
  modules/nf-core/mirtop/export/main.nf
  modules/nf-core/mirtop/export/meta.yml
  modules/nf-core/mirtop/export/tests/main.nf.test
  modules/nf-core/mirtop/export/tests/main.nf.test.snap
  modules/nf-core/mirtop/gff/environment.yml
  modules/nf-core/mirtop/gff/main.nf
  modules/nf-core/mirtop/gff/meta.yml
  modules/nf-core/mirtop/gff/tests/main.nf.test
  modules/nf-core/mirtop/gff/tests/main.nf.test.snap
  modules/nf-core/mirtop/stats/environment.yml
  modules/nf-core/mirtop/stats/main.nf
  modules/nf-core/mirtop/stats/meta.yml
  modules/nf-core/mirtop/stats/tests/main.nf.test
  modules/nf-core/mirtop/stats/tests/main.nf.test.snap
  subworkflows/nf-core/bam_stats_mirna_mirtop/main.nf
  subworkflows/nf-core/bam_stats_mirna_mirtop/meta.yml
  subworkflows/nf-core/bam_stats_mirna_mirtop/tests/main.nf.test
  subworkflows/nf-core/bam_stats_mirna_mirtop/tests/main.nf.test.snap
  subworkflows/nf-core/bam_stats_mirna_mirtop/tests/nextflow.config
Labels: Ready for Review

#6610 Fix fq/generate
  modules/nf-core/fq/generate/main.nf
  modules/nf-core/fq/generate/tests/main.nf.test
  modules/nf-core/fq/generate/tests/main.nf.test.snap
  modules/nf-core/fq/generate/tests/nextflow.config
Labels: Ready for Review

#6616 Fix `seqcluster`
  modules/nf-core/seqcluster/collapse/main.nf
  modules/nf-core/seqcluster/collapse/tests/main.nf.test
  modules/nf-core/seqcluster/collapse/tests/main.nf.test.snap
Labels: Ready for Review

#6624 Add bcftools/pluginimputeinfo
  modules/nf-core/bcftools/pluginimputeinfo/environment.yml
  modules/nf-core/bcftools/pluginimputeinfo/main.nf
  modules/nf-core/bcftools/pluginimputeinfo/meta.yml
  modules/nf-core/bcftools/pluginimputeinfo/tests/main.nf.test
  modules/nf-core/bcftools/pluginimputeinfo/tests/main.nf.test.snap
  modules/nf-core/bcftools/pluginimputeinfo/tests/nextflow.config
  modules/nf-core/bcftools/pluginimputeinfo/tests/vcf_gz_index.config
  modules/nf-core/bcftools/pluginimputeinfo/tests/vcf_gz_index_csi.config
  modules/nf-core/bcftools/pluginimputeinfo/tests/vcf_gz_index_tbi.config
Labels: Ready for Review

#6627 Add openmsthirdparty/cometadapter
  modules/nf-core/openmsthirdparty/cometadapter/environment.yml
  modules/nf-core/openmsthirdparty/cometadapter/main.nf
  modules/nf-core/openmsthirdparty/cometadapter/meta.yml
  modules/nf-core/openmsthirdparty/cometadapter/tests/main.nf.test
  modules/nf-core/openmsthirdparty/cometadapter/tests/main.nf.test.snap
  modules/nf-core/openmsthirdparty/cometadapter/tests/nextflow.config
  modules/nf-core/openmsthirdparty/cometadapter/tests/tags.yml
  tests/config/test_data.config
Labels: new module, Ready for Review, nf-test

#6613 flye: fix nf-test, update module
  modules/nf-core/flye/environment.yml
  modules/nf-core/flye/main.nf
  modules/nf-core/flye/tests/main.nf.test
  modules/nf-core/flye/tests/main.nf.test.snap
  modules/nf-core/flye/tests/nextflow.config
Labels: help wanted

#6658 Added nf-test for bedtools/intersect
  modules/nf-core/bedtools/intersect/tests/main.nf.test
  modules/nf-core/bedtools/intersect/tests/main.nf.test.snap
  modules/nf-core/bedtools/intersect/tests/nextflow.config
  modules/nf-core/bedtools/intersect/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bedtools/intersect/main.nf
  tests/modules/nf-core/bedtools/intersect/nextflow.config
  tests/modules/nf-core/bedtools/intersect/test.yml
Labels: Ready for Review, nf-test

#6665 Added nf-test for bedtools/unionbedg
  modules/nf-core/bedtools/unionbedg/tests/main.nf.test
  modules/nf-core/bedtools/unionbedg/tests/main.nf.test.snap
  modules/nf-core/bedtools/unionbedg/tests/nextflow.config
  modules/nf-core/bedtools/unionbedg/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bedtools/unionbedg/main.nf
  tests/modules/nf-core/bedtools/unionbedg/nextflow.config
  tests/modules/nf-core/bedtools/unionbedg/test.yml
Labels: Ready for Review, nf-test

#6663 Update mirtop version
  modules/nf-core/mirtop/counts/environment.yml
  modules/nf-core/mirtop/counts/main.nf
  modules/nf-core/mirtop/counts/tests/main.nf.test
  modules/nf-core/mirtop/counts/tests/main.nf.test.snap
  modules/nf-core/mirtop/export/environment.yml
  modules/nf-core/mirtop/export/main.nf
  modules/nf-core/mirtop/export/tests/main.nf.test.snap
  modules/nf-core/mirtop/gff/environment.yml
  modules/nf-core/mirtop/gff/main.nf
  modules/nf-core/mirtop/gff/tests/main.nf.test
  modules/nf-core/mirtop/gff/tests/main.nf.test.snap
  modules/nf-core/mirtop/stats/environment.yml
  modules/nf-core/mirtop/stats/main.nf
  modules/nf-core/mirtop/stats/tests/main.nf.test.snap
  subworkflows/nf-core/bam_stats_mirna_mirtop/tests/main.nf.test.snap
Labels: Ready for Review

#6662 Add nf-core module and subworkflow `mirdeep2`
  modules/nf-core/mirdeep2/mapper/environment.yml
  modules/nf-core/mirdeep2/mapper/main.nf
  modules/nf-core/mirdeep2/mapper/meta.yml
  modules/nf-core/mirdeep2/mapper/tests/main.nf.test
  modules/nf-core/mirdeep2/mapper/tests/main.nf.test.snap
  modules/nf-core/mirdeep2/mapper/tests/nextflow.config
  modules/nf-core/mirdeep2/mirdeep2/environment.yml
  modules/nf-core/mirdeep2/mirdeep2/main.nf
  modules/nf-core/mirdeep2/mirdeep2/meta.yml
  modules/nf-core/mirdeep2/mirdeep2/tests/main.nf.test
  modules/nf-core/mirdeep2/mirdeep2/tests/main.nf.test.snap
  modules/nf-core/mirdeep2/mirdeep2/tests/nextflow.config
  subworkflows/nf-core/fastq_find_mirna_mirdeep2/main.nf
  subworkflows/nf-core/fastq_find_mirna_mirdeep2/meta.yml
  subworkflows/nf-core/fastq_find_mirna_mirdeep2/tests/main.nf.test
  subworkflows/nf-core/fastq_find_mirna_mirdeep2/tests/main.nf.test.snap
  subworkflows/nf-core/fastq_find_mirna_mirdeep2/tests/nextflow.config
Labels: help wanted

#6693 add alignmentSieve
  modules/nf-core/deeptools/alignmentsieve/environment.yml
  modules/nf-core/deeptools/alignmentsieve/main.nf
  modules/nf-core/deeptools/alignmentsieve/meta.yml
  modules/nf-core/deeptools/alignmentsieve/tests/main.nf.test
  modules/nf-core/deeptools/alignmentsieve/tests/main.nf.test.snap
  modules/nf-core/deeptools/alignmentsieve/tests/tags.yml
Labels: update module, Ready for Review, new subworkflow
