Repository nf-core/modules, pull requests merged in 2025-04, with the labels that each got.

#8176 update cutadapt module to latest version
  modules/nf-core/cutadapt/environment.yml
  modules/nf-core/cutadapt/main.nf
  modules/nf-core/cutadapt/tests/main.nf.test.snap
Labels: Ready for Review

#8180 Change FastQC memory parameter from float to int
  modules/nf-core/fastqc/main.nf
Labels: Ready for Review

#8184 update freyja module to latest version
  modules/nf-core/freyja/boot/environment.yml
  modules/nf-core/freyja/boot/main.nf
  modules/nf-core/freyja/boot/tests/main.nf.test.snap
  modules/nf-core/freyja/demix/environment.yml
  modules/nf-core/freyja/demix/main.nf
  modules/nf-core/freyja/demix/tests/main.nf.test.snap
  modules/nf-core/freyja/update/environment.yml
  modules/nf-core/freyja/update/main.nf
  modules/nf-core/freyja/update/meta.yml
  modules/nf-core/freyja/update/tests/main.nf.test.snap
  modules/nf-core/freyja/variants/environment.yml
  modules/nf-core/freyja/variants/main.nf
  modules/nf-core/freyja/variants/tests/main.nf.test.snap
  subworkflows/nf-core/bam_variant_demix_boot_freyja/tests/main.nf.test.snap
Labels: Ready for Review

#8186 updated artic to latest version
  modules/nf-core/artic/guppyplex/environment.yml
  modules/nf-core/artic/guppyplex/main.nf
  modules/nf-core/artic/guppyplex/tests/main.nf.test.snap
  modules/nf-core/artic/minion/environment.yml
  modules/nf-core/artic/minion/main.nf
  modules/nf-core/artic/minion/tests/main.nf.test.snap
Labels: Ready for Review

#8131 add module integronfinder
  modules/nf-core/integronfinder/environment.yml
  modules/nf-core/integronfinder/main.nf
  modules/nf-core/integronfinder/meta.yml
  modules/nf-core/integronfinder/tests/main.nf.test
  modules/nf-core/integronfinder/tests/main.nf.test.snap
Labels: Ready for Review

#8200 Mindagap stub and test updates
  modules/nf-core/mindagap/duplicatefinder/environment.yml
  modules/nf-core/mindagap/duplicatefinder/main.nf
  modules/nf-core/mindagap/duplicatefinder/tests/main.nf.test
  modules/nf-core/mindagap/duplicatefinder/tests/main.nf.test.snap
  modules/nf-core/mindagap/mindagap/main.nf
  modules/nf-core/mindagap/mindagap/tests/main.nf.test
  modules/nf-core/mindagap/mindagap/tests/main.nf.test.snap
Labels: Ready for Review

#8196 fixed bug in bandage/image module, wrong versions.yml outputted
  modules/nf-core/bandage/image/main.nf
  modules/nf-core/bandage/image/tests/main.nf.test.snap
Labels: Ready for Review

#8145 Metaspace download
  modules/nf-core/metaspace/download/environment.yml
  modules/nf-core/metaspace/download/main.nf
  modules/nf-core/metaspace/download/meta.yml
  modules/nf-core/metaspace/download/templates/metaspace_download.py
  modules/nf-core/metaspace/download/tests/main.nf.test
  modules/nf-core/metaspace/download/tests/main.nf.test.snap
Labels: Ready for Review

#8227 Plink2 hwe
  modules/nf-core/plink2/hwe/environment.yml
  modules/nf-core/plink2/hwe/main.nf
  modules/nf-core/plink2/hwe/meta.yml
  modules/nf-core/plink2/hwe/tests/main.nf.test
  modules/nf-core/plink2/hwe/tests/main.nf.test.snap
Labels: Ready for Review

#8229 migrate nf-test: survivor-filter
  modules/nf-core/survivor/filter/tests/main.nf.test
  modules/nf-core/survivor/filter/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/survivor/filter/main.nf
  tests/modules/nf-core/survivor/filter/nextflow.config
  tests/modules/nf-core/survivor/filter/test.yml
Labels: nf-test

#8243 Stecfinder nftest
  modules/nf-core/stecfinder/environment.yml
  modules/nf-core/stecfinder/main.nf
  modules/nf-core/stecfinder/tests/main.nf.test
  modules/nf-core/stecfinder/tests/main.nf.test.snap
  modules/nf-core/stecfinder/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/stecfinder/main.nf
  tests/modules/nf-core/stecfinder/nextflow.config
  tests/modules/nf-core/stecfinder/test.yml
Labels: Ready for Review, nf-test

#8245 Swap shigeifinder to nf-test
  modules/nf-core/shigeifinder/environment.yml
  modules/nf-core/shigeifinder/main.nf
  modules/nf-core/shigeifinder/tests/main.nf.test
  modules/nf-core/shigeifinder/tests/main.nf.test.snap
  modules/nf-core/shigeifinder/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/shigeifinder/main.nf
  tests/modules/nf-core/shigeifinder/nextflow.config
  tests/modules/nf-core/shigeifinder/test.yml
Labels: Ready for Review

#8219 Migrate `cellrangerarc/mkref`to nf-test
  .github/skip_nf_test.json
  .github/workflows/pytest-workflow.yml
  modules/nf-core/cellrangerarc/mkref/main.nf
  modules/nf-core/cellrangerarc/mkref/tests/main.nf.test
  modules/nf-core/cellrangerarc/mkref/tests/main.nf.test.snap
  modules/nf-core/cellrangerarc/mkref/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/cellrangerarc/mkref/main.nf
  tests/modules/nf-core/cellrangerarc/mkref/nextflow.config
  tests/modules/nf-core/cellrangerarc/mkref/test.yml
Labels: nf-test

#8234 Add gatk4/modelsegments
  modules/nf-core/gatk4/modelsegments/environment.yml
  modules/nf-core/gatk4/modelsegments/main.nf
  modules/nf-core/gatk4/modelsegments/meta.yml
  modules/nf-core/gatk4/modelsegments/tests/main.nf.test
  modules/nf-core/gatk4/modelsegments/tests/main.nf.test.snap
  modules/nf-core/gatk4/modelsegments/tests/nextflow.config
Labels: Ready for Review, ready to merge

#8265 Migrate `GENOTYPHI_PARSE` to nf-test
  modules/nf-core/genotyphi/parse/main.nf
  modules/nf-core/genotyphi/parse/tests/main.nf.test
  modules/nf-core/genotyphi/parse/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/genotyphi/parse/main.nf
  tests/modules/nf-core/genotyphi/parse/nextflow.config
  tests/modules/nf-core/genotyphi/parse/test.yml
Labels: nf-test

#8269 Deprecate `FCS_FCSGX`
  modules/nf-core/fcs/fcsgx/main.nf
  modules/nf-core/fcs/fcsgx/tests/main.nf.test
  tests/config/pytest_modules.yml
  tests/modules/nf-core/fcs/fcsgx/main.nf
  tests/modules/nf-core/fcs/fcsgx/nextflow.config
  tests/modules/nf-core/fcs/fcsgx/test.yml
Labels: nf-test

#8275 Migrate `gem2/gem2bedmappability` to nf-test
  modules/nf-core/gem2/gem2bedmappability/main.nf
  modules/nf-core/gem2/gem2bedmappability/tests/main.nf.test
  modules/nf-core/gem2/gem2bedmappability/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gem2/gem2bedmappability/main.nf
  tests/modules/nf-core/gem2/gem2bedmappability/nextflow.config
  tests/modules/nf-core/gem2/gem2bedmappability/test.yml
Labels: nf-test

#8280 remove plink2 hwe
  modules/nf-core/plink2/hwe/environment.yml
  modules/nf-core/plink2/hwe/main.nf
  modules/nf-core/plink2/hwe/meta.yml
  modules/nf-core/plink2/hwe/tests/main.nf.test
  modules/nf-core/plink2/hwe/tests/main.nf.test.snap
Labels: Ready for Review

#8279 Migrate `genmap/map` to nf-test
  modules/nf-core/genmap/map/main.nf
  modules/nf-core/genmap/map/tests/main.nf.test
  modules/nf-core/genmap/map/tests/main.nf.test.snap
  modules/nf-core/genmap/map/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/genmap/map/main.nf
  tests/modules/nf-core/genmap/map/nextflow.config
  tests/modules/nf-core/genmap/map/test.yml
Labels: nf-test

#8273 update makeblastdb -out
  modules/nf-core/blast/makeblastdb/main.nf
  modules/nf-core/blast/makeblastdb/meta.yml
  modules/nf-core/blast/makeblastdb/tests/main.nf.test
  modules/nf-core/blast/makeblastdb/tests/main.nf.test.snap
Labels: update module, Ready for Review

#8297 Migrate to `ICOUNTMINI_METAGENE` nf-test
  modules/nf-core/icountmini/metagene/main.nf
  modules/nf-core/icountmini/metagene/tests/main.nf.test
  modules/nf-core/icountmini/metagene/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/icountmini/metagene/main.nf
  tests/modules/nf-core/icountmini/metagene/nextflow.config
  tests/modules/nf-core/icountmini/metagene/test.yml
Labels: nf-test

#8296 Migrate `ICOUNTMINI_PEAKS` to nf-test
  modules/nf-core/icountmini/peaks/main.nf
  modules/nf-core/icountmini/peaks/tests/main.nf.test
  modules/nf-core/icountmini/peaks/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/icountmini/peaks/main.nf
  tests/modules/nf-core/icountmini/peaks/nextflow.config
  tests/modules/nf-core/icountmini/peaks/test.yml
Labels: nf-test

#8298 Migrate `ICOUNTMINI_SIGXLS` to nf-test
  modules/nf-core/icountmini/sigxls/main.nf
  modules/nf-core/icountmini/sigxls/tests/main.nf.test
  modules/nf-core/icountmini/sigxls/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/icountmini/sigxls/main.nf
  tests/modules/nf-core/icountmini/sigxls/nextflow.config
  tests/modules/nf-core/icountmini/sigxls/test.yml
Labels: nf-test

#8293 Migrate `HMMER_ESLALIMASK` to nf-test
  modules/nf-core/hmmer/eslalimask/main.nf
  modules/nf-core/hmmer/eslalimask/tests/main.nf.test
  modules/nf-core/hmmer/eslalimask/tests/main.nf.test.snap
  modules/nf-core/hmmer/eslalimask/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/hmmer/eslalimask/main.nf
  tests/modules/nf-core/hmmer/eslalimask/nextflow.config
  tests/modules/nf-core/hmmer/eslalimask/test.yml
Labels: nf-test

#8004 Metaspace converter
  modules/nf-core/metaspace/converter/environment.yml
  modules/nf-core/metaspace/converter/main.nf
  modules/nf-core/metaspace/converter/meta.yml
  modules/nf-core/metaspace/converter/templates/run_metaspace_converter.py
  modules/nf-core/metaspace/converter/tests/main.nf.test
  modules/nf-core/metaspace/converter/tests/main.nf.test.snap
Labels: Ready for Review, ready to merge

#8294 Migrate `GRAPHMAP2_ALIGN` to nf-test
  modules/nf-core/graphmap2/align/main.nf
  modules/nf-core/graphmap2/align/tests/main.nf.test
  modules/nf-core/graphmap2/align/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/graphmap2/align/main.nf
  tests/modules/nf-core/graphmap2/align/nextflow.config
  tests/modules/nf-core/graphmap2/align/test.yml
Labels: nf-test

#8272 Bump PureCN for all relevant modules (#8264)
  modules/nf-core/purecn/coverage/environment.yml
  modules/nf-core/purecn/coverage/main.nf
  modules/nf-core/purecn/coverage/tests/main.nf.test.snap
  modules/nf-core/purecn/intervalfile/environment.yml
  modules/nf-core/purecn/intervalfile/main.nf
  modules/nf-core/purecn/intervalfile/tests/main.nf.test.snap
  modules/nf-core/purecn/normaldb/environment.yml
  modules/nf-core/purecn/normaldb/main.nf
  modules/nf-core/purecn/normaldb/tests/main.nf.test.snap
  modules/nf-core/purecn/run/environment.yml
  modules/nf-core/purecn/run/main.nf
  modules/nf-core/purecn/run/meta.yml
Labels: Ready for Review

#8333 Update vsearch/usearchglobal to strict syntax
  modules/nf-core/vsearch/usearchglobal/main.nf
Labels: update module

#8339 Migrate `iphop/predict` to nf-test
  modules/nf-core/iphop/predict/main.nf
  modules/nf-core/iphop/predict/tests/main.nf.test
  modules/nf-core/iphop/predict/tests/main.nf.test.snap
  modules/nf-core/iphop/predict/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/iphop/predict/main.nf
  tests/modules/nf-core/iphop/predict/nextflow.config
  tests/modules/nf-core/iphop/predict/test.yml
Labels: nf-test

#8190 ✨ Add VueGen module files
  modules/nf-core/vuegen/environment.yml
  modules/nf-core/vuegen/main.nf
  modules/nf-core/vuegen/meta.yml
  modules/nf-core/vuegen/tests/main.nf.test
  modules/nf-core/vuegen/tests/main.nf.test.snap
Labels: Ready for Review

#8351 Deprecate `kat/hist` and migrate it to nf-test
  modules/nf-core/kat/hist/main.nf
  modules/nf-core/kat/hist/tests/main.nf.test
  modules/nf-core/kat/hist/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/kat/hist/main.nf
  tests/modules/nf-core/kat/hist/nextflow.config
  tests/modules/nf-core/kat/hist/test.yml
Labels: nf-test

#8352 Migrate `cellrangeratac/mkref` to nf-test
  .github/skip_nf_test.json
  .github/workflows/pytest-workflow.yml
  modules/nf-core/cellrangeratac/mkref/main.nf
  modules/nf-core/cellrangeratac/mkref/tests/main.nf.test
  modules/nf-core/cellrangeratac/mkref/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/cellrangeratac/mkref/main.nf
  tests/modules/nf-core/cellrangeratac/mkref/nextflow.config
  tests/modules/nf-core/cellrangeratac/mkref/test.yml
Labels: nf-test

#8363 Migrate `khmer/uniquekmers` to nf-test
  modules/nf-core/khmer/uniquekmers/main.nf
  modules/nf-core/khmer/uniquekmers/meta.yml
  modules/nf-core/khmer/uniquekmers/tests/main.nf.test
  modules/nf-core/khmer/uniquekmers/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/khmer/uniquekmers/main.nf
  tests/modules/nf-core/khmer/uniquekmers/nextflow.config
  tests/modules/nf-core/khmer/uniquekmers/test.yml
Labels: nf-test

#8364 Migrate `kmcp/merge` to nf-test
  modules/nf-core/kmcp/merge/environment.yml
  modules/nf-core/kmcp/merge/main.nf
  modules/nf-core/kmcp/merge/tests/main.nf.test
  modules/nf-core/kmcp/merge/tests/main.nf.test.snap
  modules/nf-core/kmcp/merge/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/kmcp/merge/main.nf
  tests/modules/nf-core/kmcp/merge/nextflow.config
  tests/modules/nf-core/kmcp/merge/test.yml
Labels: nf-test

#8377 Pypgx small batch update
  modules/nf-core/pypgx/computecontrolstatistics/main.nf
  modules/nf-core/pypgx/computecontrolstatistics/meta.yml
  modules/nf-core/pypgx/computecontrolstatistics/tests/config.nextflow
  modules/nf-core/pypgx/computecontrolstatistics/tests/main.nf.test
  modules/nf-core/pypgx/createinputvcf/main.nf
  modules/nf-core/pypgx/createinputvcf/meta.yml
  modules/nf-core/pypgx/createinputvcf/tests/main.nf.test
  modules/nf-core/pypgx/createinputvcf/tests/main.nf.test.snap
  modules/nf-core/pypgx/createinputvcf/tests/nextflow.config
  modules/nf-core/pypgx/preparedepthofcoverage/main.nf
  modules/nf-core/pypgx/preparedepthofcoverage/meta.yml
  modules/nf-core/pypgx/preparedepthofcoverage/tests/main.nf.test
  modules/nf-core/pypgx/preparedepthofcoverage/tests/main.nf.test.snap
  modules/nf-core/pypgx/preparedepthofcoverage/tests/nextflow.config
  modules/nf-core/pypgx/runngspipeline/main.nf
  modules/nf-core/pypgx/runngspipeline/meta.yml
  modules/nf-core/pypgx/runngspipeline/tests/main.nf.test
  modules/nf-core/pypgx/runngspipeline/tests/nextflow.config
Labels: Ready for Review

#8370 Add stub and stub test to snpsift/split module
  modules/nf-core/snpsift/split/main.nf
  modules/nf-core/snpsift/split/tests/main.nf.test
  modules/nf-core/snpsift/split/tests/main.nf.test.snap
Labels: update module
