Repository nf-core/modules, pull requests merged in 2025-01, with the labels that each got.

#7249 Added BBMAP/REPAIR submodule
  modules/nf-core/bbmap/repair/environment.yml
  modules/nf-core/bbmap/repair/main.nf
  modules/nf-core/bbmap/repair/meta.yml
  modules/nf-core/bbmap/repair/tests/main.nf.test
  modules/nf-core/bbmap/repair/tests/main.nf.test.snap
  modules/nf-core/bbmap/repair/tests/nextflow.config
  modules/nf-core/bbmap/repair/tests/tags.yml
Labels: update module, ready to merge, container-issue

#7241 Update gzrt to v0.9.1
  modules/nf-core/gzrt/environment.yml
  modules/nf-core/gzrt/main.nf
  modules/nf-core/gzrt/meta.yml
  modules/nf-core/gzrt/tests/main.nf.test
  modules/nf-core/gzrt/tests/main.nf.test.snap
Labels: update module, ready to merge, container-issue

#7267 Bump csvtk and change stageIn pattern of csvtk/concat
  modules/nf-core/csvtk/concat/environment.yml
  modules/nf-core/csvtk/concat/main.nf
  modules/nf-core/csvtk/concat/tests/main.nf.test
  modules/nf-core/csvtk/concat/tests/main.nf.test.snap
  modules/nf-core/csvtk/join/environment.yml
  modules/nf-core/csvtk/join/main.nf
  modules/nf-core/csvtk/join/tests/main.nf.test.snap
  modules/nf-core/csvtk/split/environment.yml
  modules/nf-core/csvtk/split/main.nf
  modules/nf-core/csvtk/split/tests/main.nf.test.snap
Labels: Ready for Review

#7250 Update Prokka to take compressed input && tidy module script
  modules/nf-core/prokka/environment.yml
  modules/nf-core/prokka/main.nf
  modules/nf-core/prokka/tests/main.nf.test
  modules/nf-core/prokka/tests/main.nf.test.snap
Labels: ready to merge

#7260 Fix singularity oras images
  modules/nf-core/annotsv/annotsv/main.nf
  modules/nf-core/annotsv/installannotations/main.nf
  modules/nf-core/dysgu/environment.yml
  modules/nf-core/dysgu/main.nf
  modules/nf-core/eido/convert/environment.yml
  modules/nf-core/eido/convert/main.nf
  modules/nf-core/foldmason/easymsa/main.nf
  modules/nf-core/purecn/intervalfile/main.nf
  modules/nf-core/purecn/normaldb/main.nf
  modules/nf-core/samshee/main.nf
  modules/nf-core/scvitools/scar/environment.yml
  modules/nf-core/scvitools/scar/main.nf
  modules/nf-core/scvitools/solo/environment.yml
  modules/nf-core/scvitools/solo/main.nf
  modules/nf-core/sequali/main.nf
  modules/nf-core/tcoffee/consensus/main.nf
  modules/nf-core/untarfiles/main.nf
  modules/nf-core/upp/align/main.nf
Labels: container-issue

#6907 Add scds module
  modules/nf-core/scds/environment.yml
  modules/nf-core/scds/main.nf
  modules/nf-core/scds/meta.yml
  modules/nf-core/scds/templates/scds.R
  modules/nf-core/scds/tests/main.nf.test
  modules/nf-core/scds/tests/main.nf.test.snap
Labels: Ready for Review

#6823 pypgx/runngspipeline
  modules/nf-core/pypgx/runngspipeline/environment.yml
  modules/nf-core/pypgx/runngspipeline/main.nf
  modules/nf-core/pypgx/runngspipeline/meta.yml
  modules/nf-core/pypgx/runngspipeline/tests/main.nf.test
  modules/nf-core/pypgx/runngspipeline/tests/main.nf.test.snap
Labels: new module

#7291 Update Galah & add nf-tests
  modules/nf-core/galah/environment.yml
  modules/nf-core/galah/main.nf
  modules/nf-core/galah/meta.yml
  modules/nf-core/galah/tests/main.nf.test
  modules/nf-core/galah/tests/main.nf.test.snap
  modules/nf-core/galah/tests/nextflow.config
  modules/nf-core/galah/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/galah/main.nf
  tests/modules/nf-core/galah/nextflow.config
  tests/modules/nf-core/galah/test.yml
Labels: Ready for Review

#7300 Update WIPERTOOLS
  modules/nf-core/wipertools/fastqgather/main.nf
  modules/nf-core/wipertools/fastqgather/meta.yml
  modules/nf-core/wipertools/fastqgather/tests/main.nf.test
  modules/nf-core/wipertools/fastqgather/tests/main.nf.test.snap
  modules/nf-core/wipertools/fastqscatter/main.nf
  modules/nf-core/wipertools/fastqscatter/meta.yml
  modules/nf-core/wipertools/fastqscatter/tests/main.nf.test.snap
  modules/nf-core/wipertools/fastqwiper/main.nf
  modules/nf-core/wipertools/fastqwiper/meta.yml
  modules/nf-core/wipertools/fastqwiper/tests/main.nf.test
  modules/nf-core/wipertools/fastqwiper/tests/main.nf.test.snap
  modules/nf-core/wipertools/reportgather/main.nf
  modules/nf-core/wipertools/reportgather/meta.yml
  modules/nf-core/wipertools/reportgather/tests/main.nf.test
  modules/nf-core/wipertools/reportgather/tests/main.nf.test.snap
Labels: update module, Ready for Review

#7305 Bumped agat modules
  modules/nf-core/agat/convertspgff2gtf/environment.yml
  modules/nf-core/agat/convertspgff2gtf/main.nf
  modules/nf-core/agat/convertspgff2gtf/tests/main.nf.test.snap
  modules/nf-core/agat/convertspgff2tsv/environment.yml
  modules/nf-core/agat/convertspgff2tsv/main.nf
  modules/nf-core/agat/convertspgff2tsv/tests/main.nf.test.snap
  modules/nf-core/agat/convertspgxf2gxf/environment.yml
  modules/nf-core/agat/convertspgxf2gxf/main.nf
  modules/nf-core/agat/convertspgxf2gxf/tests/main.nf.test.snap
  modules/nf-core/agat/spaddintrons/environment.yml
  modules/nf-core/agat/spaddintrons/main.nf
  modules/nf-core/agat/spaddintrons/tests/main.nf.test.snap
  modules/nf-core/agat/spfilterfeaturefromkilllist/environment.yml
  modules/nf-core/agat/spfilterfeaturefromkilllist/main.nf
  modules/nf-core/agat/spfilterfeaturefromkilllist/tests/main.nf.test
  modules/nf-core/agat/spfilterfeaturefromkilllist/tests/main.nf.test.snap
  modules/nf-core/agat/spmergeannotations/environment.yml
  modules/nf-core/agat/spmergeannotations/main.nf
  modules/nf-core/agat/spmergeannotations/tests/main.nf.test
  modules/nf-core/agat/spmergeannotations/tests/main.nf.test.snap
  modules/nf-core/agat/spstatistics/environment.yml
  modules/nf-core/agat/spstatistics/main.nf
  modules/nf-core/agat/spstatistics/tests/main.nf.test.snap
  modules/nf-core/agat/sqstatbasic/environment.yml
  modules/nf-core/agat/sqstatbasic/main.nf
  modules/nf-core/agat/sqstatbasic/tests/main.nf.test.snap
Labels: Ready for Review

#7301 Bump rundeepvariant and vcfstatsreport
  .github/skip_nf_test.json
  modules/nf-core/deepvariant/rundeepvariant/main.nf
  modules/nf-core/deepvariant/rundeepvariant/tests/main.nf.test.snap
  modules/nf-core/deepvariant/vcfstatsreport/main.nf
  modules/nf-core/deepvariant/vcfstatsreport/tests/main.nf.test.snap
Labels: Ready for Review

#7315 Update seqkit to version 2.9.0
  modules/nf-core/seqkit/concat/environment.yml
  modules/nf-core/seqkit/concat/main.nf
  modules/nf-core/seqkit/concat/tests/main.nf.test.snap
  modules/nf-core/seqkit/fq2fa/environment.yml
  modules/nf-core/seqkit/fq2fa/main.nf
  modules/nf-core/seqkit/fq2fa/tests/main.nf.test.snap
  modules/nf-core/seqkit/grep/environment.yml
  modules/nf-core/seqkit/grep/main.nf
  modules/nf-core/seqkit/grep/tests/main.nf.test.snap
  modules/nf-core/seqkit/pair/environment.yml
  modules/nf-core/seqkit/pair/main.nf
  modules/nf-core/seqkit/pair/tests/main.nf.test.snap
  modules/nf-core/seqkit/replace/environment.yml
  modules/nf-core/seqkit/replace/main.nf
  modules/nf-core/seqkit/replace/tests/main.nf.test.snap
  modules/nf-core/seqkit/rmdup/environment.yml
  modules/nf-core/seqkit/rmdup/main.nf
  modules/nf-core/seqkit/rmdup/tests/main.nf.test.snap
  modules/nf-core/seqkit/seq/environment.yml
  modules/nf-core/seqkit/seq/main.nf
  modules/nf-core/seqkit/seq/tests/main.nf.test.snap
  modules/nf-core/seqkit/sliding/environment.yml
  modules/nf-core/seqkit/sliding/main.nf
  modules/nf-core/seqkit/sliding/tests/main.nf.test.snap
  modules/nf-core/seqkit/sort/environment.yml
  modules/nf-core/seqkit/sort/main.nf
  modules/nf-core/seqkit/sort/tests/main.nf.test.snap
  modules/nf-core/seqkit/split2/environment.yml
  modules/nf-core/seqkit/split2/main.nf
  modules/nf-core/seqkit/split2/meta.yml
  modules/nf-core/seqkit/split2/tests/main.nf.test.snap
  modules/nf-core/seqkit/stats/environment.yml
  modules/nf-core/seqkit/stats/main.nf
  modules/nf-core/seqkit/stats/meta.yml
  modules/nf-core/seqkit/stats/tests/main.nf.test.snap
  modules/nf-core/seqkit/translate/environment.yml
  modules/nf-core/seqkit/translate/main.nf
  modules/nf-core/seqkit/translate/tests/main.nf.test.snap
  subworkflows/nf-core/fasta_explore_search_plot_tidk/tests/main.nf.test.snap
  subworkflows/nf-core/fastq_find_mirna_mirdeep2/tests/main.nf.test.snap
Labels: Ready for Review

#7328 Bump wipertools to 1.1.4
  modules/nf-core/wipertools/fastqgather/environment.yml
  modules/nf-core/wipertools/fastqgather/main.nf
  modules/nf-core/wipertools/fastqgather/tests/main.nf.test.snap
  modules/nf-core/wipertools/fastqscatter/environment.yml
  modules/nf-core/wipertools/fastqscatter/main.nf
  modules/nf-core/wipertools/fastqscatter/tests/main.nf.test
  modules/nf-core/wipertools/fastqscatter/tests/main.nf.test.snap
  modules/nf-core/wipertools/fastqwiper/environment.yml
  modules/nf-core/wipertools/fastqwiper/main.nf
  modules/nf-core/wipertools/fastqwiper/tests/main.nf.test.snap
  modules/nf-core/wipertools/reportgather/environment.yml
  modules/nf-core/wipertools/reportgather/main.nf
  modules/nf-core/wipertools/reportgather/tests/main.nf.test.snap
Labels: update module

#6995 port parabricks/deepvariant to nf-test
  modules/nf-core/parabricks/applybqsr/meta.yml
  modules/nf-core/parabricks/dbsnp/meta.yml
  modules/nf-core/parabricks/deepvariant/main.nf
  modules/nf-core/parabricks/deepvariant/meta.yml
  modules/nf-core/parabricks/deepvariant/tests/main.nf.test
  modules/nf-core/parabricks/deepvariant/tests/main.nf.test.snap
  modules/nf-core/parabricks/deepvariant/tests/nextflow.config
  modules/nf-core/parabricks/genotypegvcf/meta.yml
  modules/nf-core/parabricks/indexgvcf/meta.yml
  modules/nf-core/parabricks/mutectcaller/meta.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/parabricks/deepvariant/main.nf
  tests/modules/nf-core/parabricks/deepvariant/nextflow.config
  tests/modules/nf-core/parabricks/deepvariant/test.yml
  tests/modules/nf-core/parabricks/deepvariant/test_GPU_config.txt
  tests/modules/nf-core/parabricks/deepvariant/test_GPU_yml.txt
Labels: Ready for Review, nf-test, gpu

#7284 Dynamic sharding
  .github/actions/get-shards/action.yml
  .github/workflows/lint.yml
  .github/workflows/nf-test-gpu.yml
  .github/workflows/nf-test.yml
  .github/workflows/pytest-workflow.yml
Labels: WIP

#7344 Use the correct syntax for devcontainer features
  .devcontainer/devcontainer.json
Labels: bug, Ready for Review

#7313 Update odgi to version 0.9.0
  modules/nf-core/odgi/build/environment.yml
  modules/nf-core/odgi/build/main.nf
  modules/nf-core/odgi/build/tests/main.nf.test
  modules/nf-core/odgi/build/tests/main.nf.test.snap
  modules/nf-core/odgi/draw/environment.yml
  modules/nf-core/odgi/draw/main.nf
  modules/nf-core/odgi/draw/tests/main.nf.test
  modules/nf-core/odgi/draw/tests/main.nf.test.snap
  modules/nf-core/odgi/layout/environment.yml
  modules/nf-core/odgi/layout/main.nf
  modules/nf-core/odgi/layout/tests/main.nf.test
  modules/nf-core/odgi/layout/tests/main.nf.test.snap
  modules/nf-core/odgi/sort/environment.yml
  modules/nf-core/odgi/sort/main.nf
  modules/nf-core/odgi/sort/tests/main.nf.test.snap
  modules/nf-core/odgi/squeeze/environment.yml
  modules/nf-core/odgi/squeeze/main.nf
  modules/nf-core/odgi/squeeze/tests/main.nf.test.snap
  modules/nf-core/odgi/stats/environment.yml
  modules/nf-core/odgi/stats/main.nf
  modules/nf-core/odgi/stats/tests/main.nf.test.snap
  modules/nf-core/odgi/unchop/environment.yml
  modules/nf-core/odgi/unchop/main.nf
  modules/nf-core/odgi/unchop/tests/main.nf.test.snap
  modules/nf-core/odgi/view/environment.yml
  modules/nf-core/odgi/view/main.nf
  modules/nf-core/odgi/view/tests/main.nf.test.snap
  modules/nf-core/odgi/viz/environment.yml
  modules/nf-core/odgi/viz/main.nf
  modules/nf-core/odgi/viz/tests/main.nf.test.snap
Labels: Ready for Review

#7345 Bump Severus to 1.3
  modules/nf-core/severus/environment.yml
  modules/nf-core/severus/main.nf
  modules/nf-core/severus/tests/main.nf.test
  modules/nf-core/severus/tests/main.nf.test.snap
  modules/nf-core/severus/tests/nextflow.config
Labels: Ready for Review

#7346 Bump TRGT to 1.5.0
  modules/nf-core/trgt/genotype/environment.yml
  modules/nf-core/trgt/genotype/main.nf
  modules/nf-core/trgt/genotype/tests/main.nf.test.snap
  modules/nf-core/trgt/merge/environment.yml
  modules/nf-core/trgt/merge/main.nf
  modules/nf-core/trgt/merge/tests/main.nf.test.snap
  modules/nf-core/trgt/plot/environment.yml
  modules/nf-core/trgt/plot/main.nf
  modules/nf-core/trgt/plot/tests/main.nf.test.snap
Labels: Ready for Review

#7318 Added 2FAST2Q module
  modules/nf-core/fast2q/environment.yml
  modules/nf-core/fast2q/main.nf
  modules/nf-core/fast2q/meta.yml
  modules/nf-core/fast2q/tests/main.nf.test
  modules/nf-core/fast2q/tests/main.nf.test.snap
  modules/nf-core/fast2q/tests/nextflow.config
  modules/nf-core/fast2q/tests/tags.yml
  modules/yaml-schema.json
Labels: Ready for Review
