Repository nf-core/modules, pull requests merged in 2025-08, with the labels that each got.

#8885 Fix CheckM2 database download
  modules/nf-core/checkm2/databasedownload/main.nf
  modules/nf-core/galah/tests/nextflow.config
Labels: Ready for Review

#8781 BUSCO 6 update
  modules/nf-core/busco/busco/environment.yml
  modules/nf-core/busco/busco/main.nf
  modules/nf-core/busco/busco/tests/main.nf.test
  modules/nf-core/busco/busco/tests/main.nf.test.snap
  subworkflows/nf-core/fasta_gxf_busco_plot/tests/main.nf.test.snap
Labels: help wanted, update module

#8849 Add new subworkflow: tiff_segmentation_vpt
  subworkflows/nf-core/tiff_segmentation_vpt/main.nf
  subworkflows/nf-core/tiff_segmentation_vpt/meta.yml
  subworkflows/nf-core/tiff_segmentation_vpt/tests/main.nf.test
  subworkflows/nf-core/tiff_segmentation_vpt/tests/main.nf.test.snap
  subworkflows/nf-core/tiff_segmentation_vpt/tests/nextflow.config
Labels: Ready for Review, new subworkflow
