Repository nf-core/modules, pull requests merged in 2025-09, with the labels that each got.

#8965 New module: modkit/bedmethyltobigwig
  modules/nf-core/modkit/bedmethyltobigwig/environment.yml
  modules/nf-core/modkit/bedmethyltobigwig/main.nf
  modules/nf-core/modkit/bedmethyltobigwig/meta.yml
  modules/nf-core/modkit/bedmethyltobigwig/tests/main.nf.test
  modules/nf-core/modkit/bedmethyltobigwig/tests/main.nf.test.snap
  modules/nf-core/modkit/bedmethyltobigwig/tests/tags.yml
Labels: new module, Ready for Review

#9015 Update multiqc to 1.31
  modules/nf-core/multiqc/environment.yml
  modules/nf-core/multiqc/main.nf
  modules/nf-core/multiqc/tests/main.nf.test.snap
Labels: update module, container-issue

#9083 Update module tinc
  modules/nf-core/tinc/meta.yml
  modules/nf-core/tinc/templates/main_script.R
Labels: update module

#9113 Update to Beagle 5.5
  modules/nf-core/beagle5/beagle/environment.yml
  modules/nf-core/beagle5/beagle/main.nf
  modules/nf-core/beagle5/beagle/meta.yml
  modules/nf-core/beagle5/beagle/tests/main.nf.test.snap
Labels: Ready for Review

#9102 new module: fibertools-rs
  modules/nf-core/fibertoolsrs/addnucleosomes/environment.yml
  modules/nf-core/fibertoolsrs/addnucleosomes/main.nf
  modules/nf-core/fibertoolsrs/addnucleosomes/meta.yml
  modules/nf-core/fibertoolsrs/addnucleosomes/tests/main.nf.test
  modules/nf-core/fibertoolsrs/addnucleosomes/tests/main.nf.test.snap
  modules/nf-core/fibertoolsrs/extract/environment.yml
  modules/nf-core/fibertoolsrs/extract/main.nf
  modules/nf-core/fibertoolsrs/extract/meta.yml
  modules/nf-core/fibertoolsrs/extract/tests/main.nf.test
  modules/nf-core/fibertoolsrs/extract/tests/main.nf.test.snap
  modules/nf-core/fibertoolsrs/predictm6a/environment.yml
  modules/nf-core/fibertoolsrs/predictm6a/main.nf
  modules/nf-core/fibertoolsrs/predictm6a/meta.yml
  modules/nf-core/fibertoolsrs/predictm6a/tests/main.nf.test
  modules/nf-core/fibertoolsrs/predictm6a/tests/main.nf.test.snap
Labels: new module

#9147 Add module csvtk/sort
  modules/nf-core/csvtk/sort/environment.yml
  modules/nf-core/csvtk/sort/main.nf
  modules/nf-core/csvtk/sort/meta.yml
  modules/nf-core/csvtk/sort/tests/main.nf.test
  modules/nf-core/csvtk/sort/tests/main.nf.test.snap
Labels: new module

#8241 fix: nf-test in strelka
  modules/nf-core/strelka/germline/environment.yml
  modules/nf-core/strelka/germline/main.nf
  modules/nf-core/strelka/germline/tests/main.nf.test
  modules/nf-core/strelka/germline/tests/main.nf.test.snap
  modules/nf-core/strelka/germline/tests/nextflow.config
  modules/nf-core/strelka/somatic/environment.yml
  modules/nf-core/strelka/somatic/main.nf
  modules/nf-core/strelka/somatic/tests/main.nf.test
  modules/nf-core/strelka/somatic/tests/main.nf.test.snap
  modules/nf-core/strelka/somatic/tests/nextflow.config
Labels: Ready for Review
