Repository nf-core/modules, pull requests merged in 2025-03, with the labels that each got.

#7725 Migrate `ARTIC/GUPPYPLEX` to nf-test
  modules/nf-core/artic/guppyplex/main.nf
  modules/nf-core/artic/guppyplex/tests/main.nf.test
  modules/nf-core/artic/guppyplex/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/artic/guppyplex/main.nf
  tests/modules/nf-core/artic/guppyplex/nextflow.config
  tests/modules/nf-core/artic/guppyplex/test.yml
Labels: nf-test

#7724 Fix `VCF_IMPUTE_GLIMPSE` nf-test
  subworkflows/nf-core/vcf_impute_glimpse/tests/main.nf.test
  subworkflows/nf-core/vcf_impute_glimpse/tests/main.nf.test.snap
Labels: nf-test

#7726 `ARTIC_MINION` migration to nf-test
  modules/nf-core/artic/minion/environment.yml
  modules/nf-core/artic/minion/main.nf
  modules/nf-core/artic/minion/meta.yml
  modules/nf-core/artic/minion/tests/main.nf.test
  modules/nf-core/artic/minion/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/artic/minion/main.nf
  tests/modules/nf-core/artic/minion/nextflow.config
  tests/modules/nf-core/artic/minion/test.yml
Labels: nf-test

#7742 Pin bcftools in ngscheckmate conda YAML to same version as biocontainer
  modules/nf-core/ngscheckmate/fastq/environment.yml
  modules/nf-core/ngscheckmate/fastq/main.nf
  modules/nf-core/ngscheckmate/ncm/environment.yml
  modules/nf-core/ngscheckmate/ncm/main.nf
  modules/nf-core/ngscheckmate/ncm/tests/main.nf.test.snap
  modules/nf-core/ngscheckmate/patterngenerator/environment.yml
  modules/nf-core/ngscheckmate/patterngenerator/main.nf
  modules/nf-core/ngscheckmate/vafncm/environment.yml
  modules/nf-core/ngscheckmate/vafncm/main.nf
  modules/nf-core/ngscheckmate/vafncm/tests/main.nf.test.snap
Labels: Ready for Review

#7745 GAWK: Fix output specification
  modules/nf-core/gawk/main.nf
  modules/nf-core/gawk/meta.yml
Labels: Ready for Review

#7718 Fix fastq_create_umi_consensus_fgbio and swap to nf-test
  subworkflows/nf-core/fastq_create_umi_consensus_fgbio/main.nf
  subworkflows/nf-core/fastq_create_umi_consensus_fgbio/tests/duplex.config
  subworkflows/nf-core/fastq_create_umi_consensus_fgbio/tests/main.nf.test
  subworkflows/nf-core/fastq_create_umi_consensus_fgbio/tests/main.nf.test.snap
  subworkflows/nf-core/fastq_create_umi_consensus_fgbio/tests/single.config
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/fastq_create_umi_consensus_fgbio/main.nf
  tests/subworkflows/nf-core/fastq_create_umi_consensus_fgbio/nextflow.config
  tests/subworkflows/nf-core/fastq_create_umi_consensus_fgbio/test.yml
Labels: Ready for Review

#7728 nf-test for bam_ngscheckmate
  modules/nf-core/ngscheckmate/ncm/tests/main.nf.test
  modules/nf-core/ngscheckmate/ncm/tests/main.nf.test.snap
  subworkflows/nf-core/bam_ngscheckmate/main.nf
  subworkflows/nf-core/bam_ngscheckmate/nextflow.config
  subworkflows/nf-core/bam_ngscheckmate/tests/main.nf.test
  subworkflows/nf-core/bam_ngscheckmate/tests/main.nf.test.snap
  subworkflows/nf-core/bam_ngscheckmate/tests/nextflow.config
  test.bed
  test.genome.vcf.bed
  test.genome.vcf.bed.1
  test_snp.bed
  tests/config/pytest_modules.yml
  tests/subworkflows/nf-core/bam_ngscheckmate/main.nf
  tests/subworkflows/nf-core/bam_ngscheckmate/test.yml
Labels: Ready for Review

#7481 Add index format to samtools view
  modules/nf-core/samtools/view/main.nf
  modules/nf-core/samtools/view/meta.yml
  modules/nf-core/samtools/view/tests/cram_index.config
  modules/nf-core/samtools/view/tests/main.nf.test
  modules/nf-core/samtools/view/tests/main.nf.test.snap
  modules/nf-core/yahs/tests/main.nf.test
  subworkflows/nf-core/bam_split_by_region/README.md
  subworkflows/nf-core/bam_split_by_region/main.nf
  subworkflows/nf-core/bam_split_by_region/tests/main.nf.test
  subworkflows/nf-core/bam_split_by_region/tests/main.nf.test.snap
  subworkflows/nf-core/bam_split_by_region/tests/nextflow.config
  subworkflows/nf-core/bam_subsampledepth_samtools/main.nf
  tests/config/pytest_modules.yml
  tests/modules/nf-core/endorspy/main.nf
  tests/modules/nf-core/leehom/main.nf
  tests/modules/nf-core/metaphlan3/metaphlan3/main.nf
  tests/subworkflows/nf-core/bam_split_by_region/main.nf
  tests/subworkflows/nf-core/bam_split_by_region/nextflow.config
  tests/subworkflows/nf-core/bam_split_by_region/test.yml
Labels: Ready for Review

#7727 `ASCAT` migration to nf-test
  modules/nf-core/ascat/environment.yml
  modules/nf-core/ascat/main.nf
  modules/nf-core/ascat/tests/main.nf.test
  modules/nf-core/ascat/tests/main.nf.test.snap
  modules/nf-core/ascat/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/ascat/main.nf
  tests/modules/nf-core/ascat/nextflow.config
  tests/modules/nf-core/ascat/test.yml
Labels: nf-test

#7723 Committing new module Portcullis
  modules/nf-core/portcullis/full/environment.yml
  modules/nf-core/portcullis/full/main.nf
  modules/nf-core/portcullis/full/meta.yml
  modules/nf-core/portcullis/full/tests/main.nf.test
  modules/nf-core/portcullis/full/tests/main.nf.test.snap
Labels: Ready for Review

#7755 Swap sexdeterrmine to nf-test
  modules/nf-core/sexdeterrmine/main.nf
  modules/nf-core/sexdeterrmine/tests/main.nf.test
  modules/nf-core/sexdeterrmine/tests/main.nf.test.snap
  modules/nf-core/sexdeterrmine/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/sexdeterrmine/main.nf
  tests/modules/nf-core/sexdeterrmine/nextflow.config
  tests/modules/nf-core/sexdeterrmine/test.yml
Labels: Ready for Review

#7794 Update CheckM2, add stub tests
  modules/nf-core/checkm2/databasedownload/environment.yml
  modules/nf-core/checkm2/databasedownload/main.nf
  modules/nf-core/checkm2/databasedownload/tests/main.nf.test
  modules/nf-core/checkm2/databasedownload/tests/main.nf.test.snap
  modules/nf-core/checkm2/predict/environment.yml
  modules/nf-core/checkm2/predict/main.nf
  modules/nf-core/checkm2/predict/tests/main.nf.test
  modules/nf-core/checkm2/predict/tests/main.nf.test.snap
  modules/nf-core/checkm2/predict/tests/nextflow.config
Labels: Ready for Review

#7812 Added coreograph nf-test
  .github/skip_nf_test.json
  .github/workflows/pytest-workflow.yml
  modules/nf-core/coreograph/main.nf
  modules/nf-core/coreograph/meta.yml
  modules/nf-core/coreograph/tests/main.nf.test
  modules/nf-core/coreograph/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/coreograph/main.nf
  tests/modules/nf-core/coreograph/nextflow.config
  tests/modules/nf-core/coreograph/test.yml
Labels: Ready for Review

#7811 Added ilastik/multicut nftest
  .github/workflows/pytest-workflow.yml
  modules/nf-core/ilastik/multicut/main.nf
  modules/nf-core/ilastik/multicut/meta.yml
  modules/nf-core/ilastik/multicut/tests/main.nf.test
  modules/nf-core/ilastik/multicut/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/ilastik/multicut/main.nf
  tests/modules/nf-core/ilastik/multicut/nextflow.config
  tests/modules/nf-core/ilastik/multicut/test.yml
Labels: Ready for Review

#7805 Update `graphtyper/vcfconcatenate`: Add batching to avoid long command line error
  modules/nf-core/graphtyper/vcfconcatenate/environment.yml
  modules/nf-core/graphtyper/vcfconcatenate/main.nf
  modules/nf-core/graphtyper/vcfconcatenate/meta.yml
  modules/nf-core/graphtyper/vcfconcatenate/tests/main.nf.test
  modules/nf-core/graphtyper/vcfconcatenate/tests/main.nf.test.snap
Labels: Ready for Review

#7807 New module: `seqkit/head`
  modules/nf-core/seqkit/head/environment.yml
  modules/nf-core/seqkit/head/main.nf
  modules/nf-core/seqkit/head/meta.yml
  modules/nf-core/seqkit/head/tests/main.nf.test
  modules/nf-core/seqkit/head/tests/main.nf.test.snap
Labels: Ready for Review

#7808 Update `sourmash/compare`: Name output by prefix and update conda/docker
  modules/nf-core/sourmash/compare/environment.yml
  modules/nf-core/sourmash/compare/main.nf
  modules/nf-core/sourmash/compare/tests/main.nf.test.snap
  modules/nf-core/sourmash/gather/environment.yml
  modules/nf-core/sourmash/gather/main.nf
  modules/nf-core/sourmash/gather/tests/main.nf.test
  modules/nf-core/sourmash/gather/tests/main.nf.test.snap
  modules/nf-core/sourmash/gather/tests/nextflow.config
  modules/nf-core/sourmash/gather/tests/tags.yml
  modules/nf-core/sourmash/index/environment.yml
  modules/nf-core/sourmash/index/main.nf
  modules/nf-core/sourmash/index/tests/main.nf.test.snap
  modules/nf-core/sourmash/sketch/environment.yml
  modules/nf-core/sourmash/sketch/main.nf
  modules/nf-core/sourmash/sketch/tests/main.nf.test
  modules/nf-core/sourmash/sketch/tests/main.nf.test.snap
  modules/nf-core/sourmash/taxannotate/environment.yml
  modules/nf-core/sourmash/taxannotate/main.nf
  modules/nf-core/sourmash/taxannotate/tests/main.nf.test
  modules/nf-core/sourmash/taxannotate/tests/main.nf.test.snap
  modules/nf-core/sourmash/taxannotate/tests/nextflow.config
  modules/nf-core/sourmash/taxannotate/tests/tags.yml
  tests/config/pytest_modules.yml
  tests/modules/nf-core/sourmash/gather/main.nf
  tests/modules/nf-core/sourmash/gather/nextflow.config
  tests/modules/nf-core/sourmash/gather/test.yml
  tests/modules/nf-core/sourmash/taxannotate/main.nf
  tests/modules/nf-core/sourmash/taxannotate/nextflow.config
  tests/modules/nf-core/sourmash/taxannotate/test.yml
Labels: Ready for Review

#7788 New module: `busco/download`
  modules/nf-core/busco/download/environment.yml
  modules/nf-core/busco/download/main.nf
  modules/nf-core/busco/download/meta.yml
  modules/nf-core/busco/download/tests/main.nf.test
  modules/nf-core/busco/download/tests/main.nf.test.snap
  modules/nf-core/busco/download/tests/tags.yml
Labels: Ready for Review

#7844 Update dsh-bio to 3.0
  modules/nf-core/dshbio/exportsegments/environment.yml
  modules/nf-core/dshbio/exportsegments/main.nf
  modules/nf-core/dshbio/exportsegments/tests/main.nf.test.snap
  modules/nf-core/dshbio/filterbed/environment.yml
  modules/nf-core/dshbio/filterbed/main.nf
  modules/nf-core/dshbio/filterbed/tests/main.nf.test
  modules/nf-core/dshbio/filterbed/tests/main.nf.test.snap
  modules/nf-core/dshbio/filterbed/tests/nextflow.config
  modules/nf-core/dshbio/filtergff3/environment.yml
  modules/nf-core/dshbio/filtergff3/main.nf
  modules/nf-core/dshbio/filtergff3/tests/main.nf.test.snap
  modules/nf-core/dshbio/splitbed/environment.yml
  modules/nf-core/dshbio/splitbed/main.nf
  modules/nf-core/dshbio/splitbed/tests/main.nf.test
  modules/nf-core/dshbio/splitbed/tests/main.nf.test.snap
  modules/nf-core/dshbio/splitgff3/environment.yml
  modules/nf-core/dshbio/splitgff3/main.nf
  modules/nf-core/dshbio/splitgff3/tests/main.nf.test.snap
Labels: update module, Ready for Review

#7800 Swap bamtools/split to nf-test
  modules/nf-core/bamtools/split/main.nf
  modules/nf-core/bamtools/split/tests/main.nf.test
  modules/nf-core/bamtools/split/tests/main.nf.test.snap
  modules/nf-core/bamtools/split/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bamtools/split/main.nf
  tests/modules/nf-core/bamtools/split/nextflow.config
  tests/modules/nf-core/bamtools/split/test.yml
Labels: Ready for Review

#7820 Added cram output to samtools/fixmate
  modules/nf-core/samtools/fixmate/main.nf
  modules/nf-core/samtools/fixmate/meta.yml
  modules/nf-core/samtools/fixmate/tests/main.nf.test
  modules/nf-core/samtools/fixmate/tests/main.nf.test.snap
  modules/nf-core/samtools/fixmate/tests/nextflow.config
  modules/nf-core/samtools/fixmate/tests/tags.yml
  modules/nf-core/samtools/markdup/tests/main.nf.test
  modules/yaml-schema.json
Labels: Ready for Review

#7893 Migrate `ATAQV/MKARV` to nf-test
  modules/nf-core/ataqv/mkarv/main.nf
  modules/nf-core/ataqv/mkarv/tests/main.nf.test
  modules/nf-core/ataqv/mkarv/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/ataqv/mkarv/main.nf
  tests/modules/nf-core/ataqv/mkarv/nextflow.config
  tests/modules/nf-core/ataqv/mkarv/test.yml
Labels: nf-test

#7958 Migrate `BAMTOOLS/CONVERT` to nf-test
  modules/nf-core/bamtools/convert/main.nf
  modules/nf-core/bamtools/convert/tests/main.nf.test
  modules/nf-core/bamtools/convert/tests/main.nf.test.snap
  modules/nf-core/bamtools/convert/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/bamtools/convert/main.nf
  tests/modules/nf-core/bamtools/convert/nextflow.config
  tests/modules/nf-core/bamtools/convert/test.yml
Labels: nf-test

#7263 Add new module `decoupler`
  modules/nf-core/decoupler/decoupler/environment.yml
  modules/nf-core/decoupler/decoupler/main.nf
  modules/nf-core/decoupler/decoupler/meta.yml
  modules/nf-core/decoupler/decoupler/templates/decoupler.py
  modules/nf-core/decoupler/decoupler/tests/main.nf.test
  modules/nf-core/decoupler/decoupler/tests/main.nf.test.snap
  modules/nf-core/decoupler/decoupler/tests/nextflow.config
Labels: Ready for Review

#8011 Migrate `CONIFER` to nf-test
  modules/nf-core/conifer/tests/main.nf.test
  modules/nf-core/conifer/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/conifer/main.nf
  tests/modules/nf-core/conifer/nextflow.config
  tests/modules/nf-core/conifer/test.yml
Labels: nf-test

#8053 Migrate `CUTESV` to nf-test
  modules/nf-core/cutesv/main.nf
  modules/nf-core/cutesv/tests/main.nf.test
  modules/nf-core/cutesv/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/cutesv/main.nf
  tests/modules/nf-core/cutesv/nextflow.config
  tests/modules/nf-core/cutesv/test.yml
Labels: nf-test

#8065 Migrate `DEDUP` to nf-test
  modules/nf-core/dedup/main.nf
  modules/nf-core/dedup/tests/main.nf.test
  modules/nf-core/dedup/tests/main.nf.test.snap
  modules/nf-core/dedup/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/dedup/main.nf
  tests/modules/nf-core/dedup/nextflow.config
  tests/modules/nf-core/dedup/test.yml
Labels: nf-test

#8074 Update to nf-test
  modules/nf-core/ucsc/bedtobigbed/main.nf
  modules/nf-core/ucsc/bedtobigbed/tests/main.nf.test
  modules/nf-core/ucsc/bedtobigbed/tests/main.nf.test.snap
  modules/nf-core/ucsc/bedtobigbed/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/ucsc/bedtobigbed/main.nf
  tests/modules/nf-core/ucsc/bedtobigbed/nextflow.config
  tests/modules/nf-core/ucsc/bedtobigbed/test.yml
Labels: nf-test

#8039 Update vcflib
  modules/nf-core/vcflib/vcfbreakmulti/environment.yml
  modules/nf-core/vcflib/vcfbreakmulti/main.nf
  modules/nf-core/vcflib/vcfbreakmulti/tests/main.nf.test.snap
  modules/nf-core/vcflib/vcffilter/environment.yml
  modules/nf-core/vcflib/vcffilter/main.nf
  modules/nf-core/vcflib/vcffilter/tests/main.nf.test
  modules/nf-core/vcflib/vcffilter/tests/main.nf.test.snap
  modules/nf-core/vcflib/vcffixup/environment.yml
  modules/nf-core/vcflib/vcffixup/main.nf
  modules/nf-core/vcflib/vcffixup/tests/main.nf.test
  modules/nf-core/vcflib/vcffixup/tests/main.nf.test.snap
  modules/nf-core/vcflib/vcfuniq/environment.yml
  modules/nf-core/vcflib/vcfuniq/main.nf
  modules/nf-core/vcflib/vcfuniq/meta.yml
  modules/nf-core/vcflib/vcfuniq/tests/main.nf.test
  modules/nf-core/vcflib/vcfuniq/tests/main.nf.test.snap
Labels: Ready for Review

#7982 Migrate `CANU` to nf-test
  modules/nf-core/canu/environment.yml
  modules/nf-core/canu/main.nf
  modules/nf-core/canu/tests/main.nf.test
  modules/nf-core/canu/tests/main.nf.test.snap
  modules/nf-core/canu/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/canu/main.nf
  tests/modules/nf-core/canu/nextflow.config
  tests/modules/nf-core/canu/test.yml
Labels: nf-test

#8064 Updated unicycler module to latest version
  modules/nf-core/unicycler/environment.yml
  modules/nf-core/unicycler/main.nf
  modules/nf-core/unicycler/tests/main.nf.test.snap
Labels: Ready for Review

#8092 Migrate `ELPREP_MERGE` to nf-test
  modules/nf-core/elprep/merge/environment.yml
  modules/nf-core/elprep/merge/main.nf
  modules/nf-core/elprep/merge/tests/main.nf.test
  modules/nf-core/elprep/merge/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/elprep/merge/main.nf
  tests/modules/nf-core/elprep/merge/nextflow.config
  tests/modules/nf-core/elprep/merge/test.yml
Labels: nf-test

#8088 Migrate `EIGENSTRATSNPCOVERAGE` to nf-test
  modules/nf-core/eigenstratdatabasetools/eigenstratsnpcoverage/main.nf
  modules/nf-core/eigenstratdatabasetools/eigenstratsnpcoverage/tests/main.nf.test
  modules/nf-core/eigenstratdatabasetools/eigenstratsnpcoverage/tests/main.nf.test.snap
  modules/nf-core/eigenstratdatabasetools/eigenstratsnpcoverage/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/eigenstratdatabasetools/eigenstratsnpcoverage/main.nf
  tests/modules/nf-core/eigenstratdatabasetools/eigenstratsnpcoverage/nextflow.config
  tests/modules/nf-core/eigenstratdatabasetools/eigenstratsnpcoverage/test.yml
Labels: nf-test

#8067 Migrate `DEEPTMHMM` to nf-test
  modules/nf-core/deeptmhmm/environment.yml
  modules/nf-core/deeptmhmm/main.nf
  modules/nf-core/deeptmhmm/tests/main.nf.test
  modules/nf-core/deeptmhmm/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/deeptmhmm/main.nf
  tests/modules/nf-core/deeptmhmm/nextflow.config
  tests/modules/nf-core/deeptmhmm/test.yml
Labels: nf-test

#8026 [New module] Infernal cmsearch
  modules/nf-core/infernal/cmsearch/environment.yml
  modules/nf-core/infernal/cmsearch/main.nf
  modules/nf-core/infernal/cmsearch/meta.yml
  modules/nf-core/infernal/cmsearch/tests/main.nf.test
  modules/nf-core/infernal/cmsearch/tests/main.nf.test.snap
Labels: Ready for Review

#8095 Migrate `ENDORSPY` to nf-test
  modules/nf-core/endorspy/main.nf
  modules/nf-core/endorspy/tests/main.nf.test
  modules/nf-core/endorspy/tests/main.nf.test.snap
  modules/nf-core/endorspy/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/endorspy/main.nf
  tests/modules/nf-core/endorspy/nextflow.config
  tests/modules/nf-core/endorspy/test.yml
Labels: nf-test

#8096 Migrate `entrezdirect_xtract` to nf-test
  modules/nf-core/entrezdirect/xtract/main.nf
  modules/nf-core/entrezdirect/xtract/tests/main.nf.test
  modules/nf-core/entrezdirect/xtract/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/entrezdirect/xtract/main.nf
  tests/modules/nf-core/entrezdirect/xtract/nextflow.config
  tests/modules/nf-core/entrezdirect/xtract/test.yml
Labels: nf-test

#7810 Added ilastik/pixelclassification nf-test
  .github/workflows/pytest-workflow.yml
  modules/nf-core/ilastik/pixelclassification/main.nf
  modules/nf-core/ilastik/pixelclassification/meta.yml
  modules/nf-core/ilastik/pixelclassification/tests/main.nf.test
  modules/nf-core/ilastik/pixelclassification/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/ilastik/pixelclassification/main.nf
  tests/modules/nf-core/ilastik/pixelclassification/nextflow.config
  tests/modules/nf-core/ilastik/pixelclassification/test.yml
Labels: Ready for Review

#7959 ultra/pipeline nf-test conversion
  modules/nf-core/ultra/pipeline/main.nf
  modules/nf-core/ultra/pipeline/tests/main.nf.test
  modules/nf-core/ultra/pipeline/tests/main.nf.test.snap
  modules/nf-core/ultra/pipeline/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/ultra/pipeline/main.nf
  tests/modules/nf-core/ultra/pipeline/nextflow.config
  tests/modules/nf-core/ultra/pipeline/test.yml
Labels: Ready for Review

#8080 Migrate `DUPHOLD` to nf-test
  modules/nf-core/duphold/main.nf
  modules/nf-core/duphold/tests/main.nf.test
  modules/nf-core/duphold/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/duphold/main.nf
  tests/modules/nf-core/duphold/nextflow.config
  tests/modules/nf-core/duphold/test.yml
Labels: nf-test

#8100 Migrate `expansionhunterdenovo/merge` to nf-test
  modules/nf-core/expansionhunterdenovo/merge/main.nf
  modules/nf-core/expansionhunterdenovo/merge/tests/main.nf.test
  modules/nf-core/expansionhunterdenovo/merge/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/expansionhunterdenovo/merge/main.nf
  tests/modules/nf-core/expansionhunterdenovo/merge/nextflow.config
  tests/modules/nf-core/expansionhunterdenovo/merge/test.yml
Labels: nf-test

#8098 Migrate `ENTREZDIRECT_ESEARCH` to nf-test
  modules/nf-core/entrezdirect/esearch/main.nf
  modules/nf-core/entrezdirect/esearch/tests/main.nf.test
  modules/nf-core/entrezdirect/esearch/tests/main.nf.test.snap
  modules/nf-core/entrezdirect/esearch/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/entrezdirect/esearch/main.nf
  tests/modules/nf-core/entrezdirect/esearch/nextflow.config
  tests/modules/nf-core/entrezdirect/esearch/test.yml
Labels: nf-test

#8079 add module spkeeplongestisoform - Fix #7892
  modules/nf-core/agat/spkeeplongestisoform/environment.yml
  modules/nf-core/agat/spkeeplongestisoform/main.nf
  modules/nf-core/agat/spkeeplongestisoform/meta.yml
  modules/nf-core/agat/spkeeplongestisoform/tests/main.nf.test
  modules/nf-core/agat/spkeeplongestisoform/tests/main.nf.test.snap
Labels: Ready for Review

#8103 Updated tabix modules to latest version
  modules/nf-core/tabix/bgzip/environment.yml
  modules/nf-core/tabix/bgzip/main.nf
  modules/nf-core/tabix/bgzip/tests/main.nf.test.snap
  modules/nf-core/tabix/bgziptabix/environment.yml
  modules/nf-core/tabix/bgziptabix/main.nf
  modules/nf-core/tabix/bgziptabix/tests/main.nf.test.snap
  modules/nf-core/tabix/tabix/environment.yml
  modules/nf-core/tabix/tabix/main.nf
  modules/nf-core/tabix/tabix/tests/main.nf.test.snap
Labels: Ready for Review

#8114 unify angsd gl configs
  modules/nf-core/angsd/gl/tests/config_gl_2.conf
  modules/nf-core/angsd/gl/tests/config_gl_3.conf
  modules/nf-core/angsd/gl/tests/config_gl_4.conf
  modules/nf-core/angsd/gl/tests/main.nf.test
  modules/nf-core/angsd/gl/tests/nextflow.config
Labels: Ready for Review

#8117 Migrate nf-test for Snapaligner/align
  modules/nf-core/snapaligner/align/main.nf
  modules/nf-core/snapaligner/align/meta.yml
  modules/nf-core/snapaligner/align/tests/main.nf.test
  modules/nf-core/snapaligner/align/tests/main.nf.test.snap
  modules/nf-core/snapaligner/align/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/snapaligner/align/main.nf
  tests/modules/nf-core/snapaligner/align/nextflow.config
  tests/modules/nf-core/snapaligner/align/test.yml
Labels: nf-test

#8128 Migrate `GEM2_GEMINDEXED` to nf-test
  modules/nf-core/gem2/gemindexer/tests/main.nf.test
  modules/nf-core/gem2/gemindexer/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/gem2/gemindexer/main.nf
  tests/modules/nf-core/gem2/gemindexer/nextflow.config
  tests/modules/nf-core/gem2/gemindexer/test.yml
Labels: nf-test

#8132 plink/indep nf-test migration
  modules/nf-core/plink/indep/tests/main.nf.test
  modules/nf-core/plink/indep/tests/main.nf.test.snap
  modules/nf-core/plink/indep/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/plink/indep/main.nf
  tests/modules/nf-core/plink/indep/nextflow.config
  tests/modules/nf-core/plink/indep/test.yml
Labels: nf-test

#8126 nf-test for cnvpytor/histogram process
  modules/nf-core/cnvpytor/histogram/main.nf
  modules/nf-core/cnvpytor/histogram/tests/main.nf.test
  modules/nf-core/cnvpytor/histogram/tests/main.nf.test.snap
  modules/nf-core/cnvpytor/histogram/tests/nextflow.config
  tests/modules/nf-core/cnvpytor/histogram/main.nf
  tests/modules/nf-core/cnvpytor/histogram/nextflow.config
  tests/modules/nf-core/cnvpytor/histogram/test.yml
Labels: nf-test

#8123 Migrate `FQTK` to nf-test
  modules/nf-core/fqtk/main.nf
  modules/nf-core/fqtk/meta.yml
  modules/nf-core/fqtk/tests/main.nf.test
  modules/nf-core/fqtk/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/fqtk/nextflow.config
  tests/modules/nf-core/fqtk/test.yml
Labels: nf-test

#8006 bump bowtie/bowtie2 and dependencies
  modules/nf-core/bowtie/align/environment.yml
  modules/nf-core/bowtie/align/main.nf
  modules/nf-core/bowtie/align/tests/main.nf.test.snap
  modules/nf-core/bowtie/build/environment.yml
  modules/nf-core/bowtie/build/main.nf
  modules/nf-core/bowtie2/align/environment.yml
  modules/nf-core/bowtie2/align/main.nf
  modules/nf-core/bowtie2/align/tests/main.nf.test.snap
  modules/nf-core/bowtie2/build/environment.yml
  modules/nf-core/bowtie2/build/main.nf
  modules/nf-core/bowtie2/build/tests/main.nf.test.snap
  modules/nf-core/fastqscreen/buildfromindex/tests/main.nf.test.snap
  modules/nf-core/fastqscreen/fastqscreen/tests/main.nf.test.snap
  subworkflows/nf-core/fastq_align_bowtie2/tests/main.nf.test.snap
  subworkflows/nf-core/fastq_align_dna/tests/main.nf.test.snap
Labels: Ready for Review

#8111 update quast
  modules/nf-core/quast/environment.yml
  modules/nf-core/quast/main.nf
  modules/nf-core/quast/tests/main.nf.test.snap
Labels: Ready for Review

#8155 update nanoplot to latest available version
  modules/nf-core/nanoplot/environment.yml
  modules/nf-core/nanoplot/main.nf
  modules/nf-core/nanoplot/tests/main.nf.test.snap
Labels: Ready for Review

#7983 Migration `cnvnator/cnvnator` to nf-test
  modules/nf-core/cnvnator/cnvnator/environment.yml
  modules/nf-core/cnvnator/cnvnator/main.nf
  modules/nf-core/cnvnator/cnvnator/tests/main.nf.test
  modules/nf-core/cnvnator/cnvnator/tests/main.nf.test.snap
  modules/nf-core/cnvnator/cnvnator/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/cnvnator/cnvnator/main.nf
  tests/modules/nf-core/cnvnator/cnvnator/nextflow.config
  tests/modules/nf-core/cnvnator/cnvnator/test.yml
Labels: nf-test

#8057 Migrate `cnvnator/convert2vcf` to nf-test
  modules/nf-core/cnvnator/convert2vcf/environment.yml
  modules/nf-core/cnvnator/convert2vcf/main.nf
  modules/nf-core/cnvnator/convert2vcf/tests/main.nf.test
  modules/nf-core/cnvnator/convert2vcf/tests/main.nf.test.snap
  modules/nf-core/cnvnator/convert2vcf/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/cnvnator/convert2vcf/main.nf
  tests/modules/nf-core/cnvnator/convert2vcf/nextflow.config
  tests/modules/nf-core/cnvnator/convert2vcf/test.yml
Labels: nf-test

#8129 Migrate nf-test for Snippy/core
  modules/nf-core/snippy/core/main.nf
  modules/nf-core/snippy/core/meta.yml
  modules/nf-core/snippy/core/tests/main.nf.test
  modules/nf-core/snippy/core/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/snippy/core/main.nf
  tests/modules/nf-core/snippy/core/nextflow.config
  tests/modules/nf-core/snippy/core/test.yml
Labels: nf-test

#8162 Swap seqwish/induce to nf-test
  modules/nf-core/seqwish/induce/environment.yml
  modules/nf-core/seqwish/induce/main.nf
  modules/nf-core/seqwish/induce/tests/main.nf.test
  modules/nf-core/seqwish/induce/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/seqwish/induce/main.nf
  tests/modules/nf-core/seqwish/induce/nextflow.config
  tests/modules/nf-core/seqwish/induce/test.yml
Labels: Ready for Review, nf-test
