Repository nf-core/modules, pull requests merged in 2025-06, with the labels that each got.

#8577 update regex in `FASTQ_FASTQC_UMITOOLS_TRIMGALORE` subworkflow, closes #8576
  subworkflows/nf-core/fastq_fastqc_umitools_trimgalore/main.nf
Labels: bug

#6584 add crabs/dbimport from readsimulator pipeline and rename to crabs/import
  modules/nf-core/crabs/import/environment.yml
  modules/nf-core/crabs/import/main.nf
  modules/nf-core/crabs/import/meta.yml
  modules/nf-core/crabs/import/tests/main.nf.test
  modules/nf-core/crabs/import/tests/main.nf.test.snap
  modules/nf-core/crabs/import/tests/nextflow.config
Labels: Ready for Review

#8596 nanoq: fix output path
  modules/nf-core/nanoq/main.nf
  modules/nf-core/nanoq/meta.yml
Labels: Ready for Review

#8613 Update `ABACAS`
  modules/nf-core/abacas/main.nf
  modules/nf-core/abacas/meta.yml
  modules/nf-core/abacas/tests/main.nf.test
  modules/nf-core/abacas/tests/main.nf.test.snap
Labels: ready to merge

#8575 Add Vizgenpostprocessing/preparesegmentation module
  .github/skip_nf_test.json
  modules/nf-core/vizgenpostprocessing/preparesegmentation/main.nf
  modules/nf-core/vizgenpostprocessing/preparesegmentation/meta.yml
  modules/nf-core/vizgenpostprocessing/preparesegmentation/tests/main.nf.test
  modules/nf-core/vizgenpostprocessing/preparesegmentation/tests/main.nf.test.snap
Labels: awaiting-changes

#8597 emu/abundance: update
  modules/nf-core/emu/abundance/environment.yml
  modules/nf-core/emu/abundance/main.nf
  modules/nf-core/emu/abundance/meta.yml
  modules/nf-core/emu/abundance/tests/main.nf.test
  modules/nf-core/emu/abundance/tests/main.nf.test.snap
  modules/nf-core/emu/abundance/tests/nextflow.config
Labels: ready to merge

#8585 PICARD_BEDTOINTERVALLIST add stub and fix for nf language
  modules/nf-core/picard/bedtointervallist/main.nf
  modules/nf-core/picard/bedtointervallist/meta.yml
  modules/nf-core/picard/bedtointervallist/tests/main.nf.test
  modules/nf-core/picard/bedtointervallist/tests/main.nf.test.snap
Labels: Ready for Review

#8050 Raw2ometiff
  modules/nf-core/raw2ometiff/environment.yml
  modules/nf-core/raw2ometiff/main.nf
  modules/nf-core/raw2ometiff/meta.yml
  modules/nf-core/raw2ometiff/tests/main.nf.test
  modules/nf-core/raw2ometiff/tests/main.nf.test.snap
Labels: Ready for Review

#8649 Add parabricks-minimap2 module
  modules/nf-core/parabricks/minimap2/main.nf
  modules/nf-core/parabricks/minimap2/meta.yml
  modules/nf-core/parabricks/minimap2/tests/main.nf.test
  modules/nf-core/parabricks/minimap2/tests/main.nf.test.snap
  modules/nf-core/parabricks/minimap2/tests/nextflow.config
Labels: new module, gpu

#8635 Add force-tile-extent module
  .github/skip_nf_test.json
  modules/nf-core/force/tileextent/Dockerfile
  modules/nf-core/force/tileextent/main.nf
  modules/nf-core/force/tileextent/meta.yml
  modules/nf-core/force/tileextent/tests/main.nf.test
  modules/nf-core/force/tileextent/tests/main.nf.test.snap
Labels: new module

#8567 Adding nf-core sparsesignatures module
  .github/skip_nf_test.json
  modules/nf-core/sparsesignatures/environment.yml
  modules/nf-core/sparsesignatures/main.nf
  modules/nf-core/sparsesignatures/meta.yml
  modules/nf-core/sparsesignatures/templates/main_script.R
  modules/nf-core/sparsesignatures/tests/main.nf.test
  modules/nf-core/sparsesignatures/tests/main.nf.test.snap
  modules/nf-core/sparsesignatures/tests/nextflow.config
Labels: Ready for Review

#8688 Update hostile modules
  modules/nf-core/hostile/clean/environment.yml
  modules/nf-core/hostile/clean/main.nf
  modules/nf-core/hostile/clean/meta.yml
  modules/nf-core/hostile/clean/tests/main.nf.test
  modules/nf-core/hostile/clean/tests/main.nf.test.snap
  modules/nf-core/hostile/fetch/environment.yml
  modules/nf-core/hostile/fetch/main.nf
  modules/nf-core/hostile/fetch/meta.yml
  modules/nf-core/hostile/fetch/tests/main.nf.test
  modules/nf-core/hostile/fetch/tests/main.nf.test.snap
  modules/nf-core/hostile/fetch/tests/nextflow.config
Labels: Ready for Review

#8719 Add module: STARE
  modules/nf-core/stare/environment.yml
  modules/nf-core/stare/main.nf
  modules/nf-core/stare/meta.yml
  modules/nf-core/stare/tests/main.nf.test
  modules/nf-core/stare/tests/main.nf.test.snap
Labels: new module, Ready for Review

#8668 Add module of TINC tool
  modules/nf-core/tinc/environment.yml
  modules/nf-core/tinc/main.nf
  modules/nf-core/tinc/meta.yml
  modules/nf-core/tinc/templates/main_script.R
  modules/nf-core/tinc/tests/main.nf.test
  modules/nf-core/tinc/tests/main.nf.test.snap
  modules/nf-core/tinc/tests/nextflow.config
Labels: new module, Ready for Review

#8725 Migrate fusionreport/download module
  modules/nf-core/fusionreport/download/environment.yml
  modules/nf-core/fusionreport/download/main.nf
  modules/nf-core/fusionreport/download/meta.yml
  modules/nf-core/fusionreport/download/tests/main.nf.test
  modules/nf-core/fusionreport/download/tests/main.nf.test.snap
  modules/nf-core/fusionreport/download/tests/nextflow.config
Labels: new module
