Repository nf-core/modules, pull requests merged in 2025-07, with the labels that each got.

#8754 Update Cellpose to 3.1.0
  modules/nf-core/cellpose/main.nf
  modules/nf-core/cellpose/tests/main.nf.test.snap
Labels: Ready for Review

#8749 New module Bftools/showinf
  modules/nf-core/bftools/showinf/environment.yml
  modules/nf-core/bftools/showinf/main.nf
  modules/nf-core/bftools/showinf/meta.yml
  modules/nf-core/bftools/showinf/tests/main.nf.test
  modules/nf-core/bftools/showinf/tests/main.nf.test.snap
Labels: new module, Ready for Review

#7506 new module: FASTQDL
  modules/nf-core/fastqdl/environment.yml
  modules/nf-core/fastqdl/main.nf
  modules/nf-core/fastqdl/meta.yml
  modules/nf-core/fastqdl/tests/main.nf.test
  modules/nf-core/fastqdl/tests/main.nf.test.snap
Labels: Ready for Review

#8762 Init Proseg
  modules/nf-core/proseg/proseg/environment.yml
  modules/nf-core/proseg/proseg/main.nf
  modules/nf-core/proseg/proseg/meta.yml
  modules/nf-core/proseg/proseg/tests/main.nf.test
  modules/nf-core/proseg/proseg/tests/main.nf.test.snap
  modules/nf-core/proseg/proseg_to_baysor/environment.yml
  modules/nf-core/proseg/proseg_to_baysor/main.nf
  modules/nf-core/proseg/proseg_to_baysor/meta.yml
  modules/nf-core/proseg/proseg_to_baysor/tests/main.nf.test
  modules/nf-core/proseg/proseg_to_baysor/tests/main.nf.test.snap
Labels: new module, Ready for Review

#8809 Add new module varscan/somatic
  modules/nf-core/varscan/somatic/environment.yml
  modules/nf-core/varscan/somatic/main.nf
  modules/nf-core/varscan/somatic/meta.yml
  modules/nf-core/varscan/somatic/tests/main.nf.test
  modules/nf-core/varscan/somatic/tests/main.nf.test.snap
  modules/nf-core/varscan/somatic/tests/nextflow.config
Labels: new module, Ready for Review

#8810 Add new module varscan/processsomatic
  modules/nf-core/varscan/processsomatic/environment.yml
  modules/nf-core/varscan/processsomatic/main.nf
  modules/nf-core/varscan/processsomatic/meta.yml
  modules/nf-core/varscan/processsomatic/tests/main.nf.test
  modules/nf-core/varscan/processsomatic/tests/main.nf.test.snap
  modules/nf-core/varscan/processsomatic/tests/nextflow.config
Labels: new module

#8816 New module: vamb/bin
  modules/nf-core/coverm/contig/main.nf
  modules/nf-core/coverm/contig/tests/main.nf.test.snap
  modules/nf-core/vamb/bin/environment.yml
  modules/nf-core/vamb/bin/main.nf
  modules/nf-core/vamb/bin/meta.yml
  modules/nf-core/vamb/bin/tests/main.nf.test
  modules/nf-core/vamb/bin/tests/main.nf.test.snap
  modules/nf-core/vamb/bin/tests/nextflow.config
Labels: Ready for Review

#8812 Add new module varscan/fpfilter
  modules/nf-core/varscan/fpfilter/environment.yml
  modules/nf-core/varscan/fpfilter/main.nf
  modules/nf-core/varscan/fpfilter/meta.yml
  modules/nf-core/varscan/fpfilter/tests/main.nf.test
  modules/nf-core/varscan/fpfilter/tests/main.nf.test.snap
  modules/nf-core/varscan/fpfilter/tests/nextflow.config
Labels: new module

#8718 New module: KMA (based on https://github.com/nf-core/modules/pull/7251)
  modules/nf-core/kma/kma/environment.yml
  modules/nf-core/kma/kma/main.nf
  modules/nf-core/kma/kma/meta.yml
  modules/nf-core/kma/kma/tests/main.nf.test
  modules/nf-core/kma/kma/tests/main.nf.test.snap
  modules/nf-core/kma/kma/tests/nextflow.config
Labels: help wanted, new module, container-issue

#8833 Move YaHS inputs to single tuple
  modules/nf-core/yahs/environment.yml
  modules/nf-core/yahs/main.nf
  modules/nf-core/yahs/meta.yml
  modules/nf-core/yahs/tests/main.nf.test
  modules/nf-core/yahs/tests/main.nf.test.snap
  modules/nf-core/yahs/tests/nextflow.config
Labels: Ready for Review
