Repository nf-core/modules, pull requests merged in 2025-02, with the labels that each got.

#7431 Remove switch statement from metamdbg/asm for language server compatibility
  modules/nf-core/metamdbg/asm/main.nf
Labels: Ready for Review

#7472 fix: language server related issue with bcftools
  modules/nf-core/bcftools/call/main.nf
  modules/nf-core/bcftools/mpileup/main.nf
  modules/nf-core/bcftools/pluginimputeinfo/main.nf
  modules/nf-core/bcftools/pluginsetgt/main.nf
  modules/nf-core/bcftools/plugintag2tag/main.nf
  modules/nf-core/bcftools/view/main.nf
Labels: Ready for Review

#7488 Update conda channels priority in csvtk and mafft
  modules/nf-core/csvtk/concat/environment.yml
  modules/nf-core/csvtk/join/environment.yml
  modules/nf-core/csvtk/split/environment.yml
  modules/nf-core/mafft/align/environment.yml
  modules/nf-core/mafft/guidetree/environment.yml
Labels: Ready for Review

#7470 BUSCO: Expose log as output and add parameter to remove intermediate files
  modules/nf-core/busco/busco/main.nf
  modules/nf-core/busco/busco/meta.yml
  modules/nf-core/busco/busco/tests/main.nf.test
  modules/nf-core/busco/busco/tests/main.nf.test.snap
  modules/nf-core/busco/generateplot/tests/main.nf.test
  subworkflows/nf-core/fasta_gxf_busco_plot/main.nf
  subworkflows/nf-core/fasta_gxf_busco_plot/meta.yml
  subworkflows/nf-core/fasta_gxf_busco_plot/tests/main.nf.test
  subworkflows/nf-core/fasta_gxf_busco_plot/tests/main.nf.test.snap
Labels: Ready for Review

#7468 port parabricks/haplotypecaller to nf-test and update
  modules/nf-core/parabricks/haplotypecaller/main.nf
  modules/nf-core/parabricks/haplotypecaller/meta.yml
  modules/nf-core/parabricks/haplotypecaller/tests/main.nf.test
  modules/nf-core/parabricks/haplotypecaller/tests/main.nf.test.snap
  modules/nf-core/parabricks/haplotypecaller/tests/nextflow.config
  tests/config/pytest_modules.yml
  tests/modules/nf-core/parabricks/haplotypecaller/main.nf
  tests/modules/nf-core/parabricks/haplotypecaller/nextflow.config
  tests/modules/nf-core/parabricks/haplotypecaller/test.yml
  tests/modules/nf-core/parabricks/haplotypecaller/test_GPU_config.txt
  tests/modules/nf-core/parabricks/haplotypecaller/test_GPU_yml.txt
Labels: Ready for Review, gpu

#7480 Update fqtk to 0.3.1
  modules/nf-core/fqtk/environment.yml
  modules/nf-core/fqtk/main.nf
Labels: Ready for Review

#7502 Allow cram output for parabricks/fq2bam module and remove fastq_align_parabricks
  modules/nf-core/parabricks/fq2bam/main.nf
  modules/nf-core/parabricks/fq2bam/meta.yml
  modules/nf-core/parabricks/fq2bam/tests/main.nf.test
  modules/nf-core/parabricks/fq2bam/tests/main.nf.test.snap
  subworkflows/nf-core/fastq_align_parabricks/main.nf
  subworkflows/nf-core/fastq_align_parabricks/meta.yml
  subworkflows/nf-core/fastq_align_parabricks/tests/main.nf.test
  subworkflows/nf-core/fastq_align_parabricks/tests/main.nf.test.snap
  subworkflows/nf-core/fastq_align_parabricks/tests/nextflow.config
Labels: gpu

#7296 Swap transdecoder predict to nf-test
  modules/nf-core/transdecoder/longorf/main.nf
  modules/nf-core/transdecoder/predict/environment.yml
  modules/nf-core/transdecoder/predict/main.nf
  modules/nf-core/transdecoder/predict/tests/main.nf.test
  modules/nf-core/transdecoder/predict/tests/main.nf.test.snap
  tests/config/pytest_modules.yml
  tests/modules/nf-core/transdecoder/predict/main.nf
  tests/modules/nf-core/transdecoder/predict/nextflow.config
  tests/modules/nf-core/transdecoder/predict/test.yml
Labels: Ready for Review

#7719 `AMPS` migration to nftest
  modules/nf-core/amps/main.nf
  modules/nf-core/amps/tests/main.nf.test
  modules/nf-core/amps/tests/main.nf.test.snap
  modules/nf-core/amps/tests/nextflow.config
  modules/nf-core/malt/build/main.nf
  tests/config/pytest_modules.yml
  tests/modules/nf-core/amps/main.nf
  tests/modules/nf-core/amps/nextflow.config
  tests/modules/nf-core/amps/test.yml
Labels: nf-test
